/* ════════════════════════════════════════
   questions/cinema.js — Cinéma / Séries — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.cinema = [
  {q:"Qui a réalisé le film Titanic ?",a:["Steven Spielberg","James Cameron","Ridley Scott","Christopher Nolan"],c:1,f:""},
  {q:"Quel acteur joue Jack dans Titanic ?",a:["Brad Pitt","Leonardo DiCaprio","Tom Cruise","Matt Damon"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Walter White ?",a:["Narcos","Breaking Bad","Better Call Saul","Ozark"],c:1,f:""},
  {q:"Qui joue Iron Man dans l'univers Marvel ?",a:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],c:1,f:""},
  {q:"Dans quelle série se déroule la lutte pour le trône de Westeros ?",a:["The Witcher","Game of Thrones","Vikings","House of the Dragon"],c:1,f:""},
  {q:"Quel acteur joue le Joker dans The Dark Knight ?",a:["Joaquin Phoenix","Jared Leto","Heath Ledger","Jack Nicholson"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on les personnages Eleven et Mike ?",a:["Dark","Stranger Things","The Umbrella Academy","The OA"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un parc rempli de dinosaures ?",a:["King Kong","Jurassic Park","Godzilla","Avatar"],c:1,f:""},
  {q:"Qui joue le rôle de Harry Potter au cinéma ?",a:["Rupert Grint","Daniel Radcliffe","Tom Felton","Elijah Wood"],c:1,f:""},
  {q:"Quel acteur incarne Spider-Man dans les films du MCU récents ?",a:["Tobey Maguire","Andrew Garfield","Tom Holland","Timothée Chalamet"],c:2,f:""},
  {q:"Quel acteur joue Neo dans The Matrix ?",a:["Brad Pitt","Keanu Reeves","Tom Cruise","Johnny Depp"],c:1,f:""},
  {q:"Quel film met en scène un naufragé sur une île avec un ballon nommé Wilson ?",a:["Cast Away","Life of Pi","The Martian","The Beach"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un clown terrifiant nommé Pennywise ?",a:["The Conjuring","It","The Nun","Annabelle"],c:1,f:""},
  {q:"Quel acteur joue Wolverine dans les films X-Men ?",a:["Hugh Jackman","Chris Evans","Ryan Reynolds","Chris Pratt"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui revit la même journée sans cesse ?",a:["Groundhog Day","Edge of Tomorrow","Looper","Source Code"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Ragnar Lothbrok ?",a:["Vikings","The Last Kingdom","Game of Thrones","Barbarians"],c:0,f:""},
  {q:"Quel film met en scène un parc virtuel nommé OASIS ?",a:["Tron: Legacy","Ready Player One","Inception","Minority Report"],c:1,f:""},
  {q:"Dans quelle série se déroule un braquage de la Monnaie d'Espagne ?",a:["Narcos","Money Heist","Ozark","Lupin"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un astronaute seul sur Mars ?",a:["Gravity","Interstellar","The Martian","Apollo 13"],c:2,f:""},
  {q:"Dans quelle série suit-on un gentleman cambrioleur inspiré d'Arsène Lupin ?",a:["Lupin","Sherlock","Narcos","Money Heist"],c:0,f:""},
  {q:"Quel acteur joue Batman dans la trilogie de Christopher Nolan ?",a:["Ben Affleck","Christian Bale","Michael Keaton","Val Kilmer"],c:1,f:""},
  {q:"Dans quel film entend-on la phrase 'Je suis ton père' ?",a:["Star Wars IV","Star Wars V","Star Wars VI","Star Wars III"],c:1,f:""},
  {q:"Quel film d'animation raconte l'histoire d'un poisson cherchant son fils ?",a:["Shark Tale","Le Monde de Nemo","Surf's Up","Shark Tale"],c:1,f:""},
  {q:"Dans quelle série joue Bryan Cranston en prof de chimie ?",a:["Dexter","Breaking Bad","The Wire","Ozark"],c:1,f:""},
  {q:"Quel film raconte l'histoire de la construction du mur d'un immeuble de luxe ?",a:["Parasite","Squid Game","Okja","Mother"],c:0,f:""},
  {q:"Quel acteur joue Forrest Gump ?",a:["Tom Hanks","Kevin Costner","Tom Cruise","Mel Gibson"],c:0,f:""},
  {q:"Dans quel film trouve-t-on le personnage de Jack Sparrow ?",a:["Pirates of the Caribbean","Master and Commander","The Bounty","Cutthroat Island"],c:0,f:""},
  {q:"Quel film raconte l'invasion de la Normandie en 1944 ?",a:["Platoon","Full Metal Jacket","Saving Private Ryan","Apocalypse Now"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on Daenerys Targaryen ?",a:["The Witcher","Game of Thrones","House of the Dragon","The Last Kingdom"],c:1,f:""},
  {q:"Quel film met en scène des jouets qui prennent vie quand les humains s'en vont ?",a:["Toy Story","Small Soldiers","The Lego Movie","Antz"],c:0,f:""},
  {q:"Quel acteur joue Tony Montana dans Scarface ?",a:["Robert De Niro","Al Pacino","Jack Nicholson","Dustin Hoffman"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on Sheldon Cooper ?",a:["How I Met Your Mother","Friends","The Big Bang Theory","Two and a Half Men"],c:2,f:""},
  {q:"Quel film raconte l'histoire d'un comptable qui aide un baron de la drogue ?",a:["El Camino","Ozark","The Accountant","Money Monster"],c:2,f:""},
  {q:"Quel acteur joue James Bond dans Casino Royale (2006) ?",a:["Pierce Brosnan","Daniel Craig","Roger Moore","Timothy Dalton"],c:1,f:""},
  {q:"Dans quel film entend-on la réplique 'Tu vas te faire une offre qu'il ne pourra pas refuser' ?",a:["Casino","Goodfellas","The Godfather","Scarface"],c:2,f:""},
  {q:"Quel film d'animation met en scène un robot nommé WALL-E ?",a:["Big Hero 6","Robots","WALL-E","Treasure Planet"],c:2,f:""},
  {q:"Dans quelle série suit-on la famille Soprano ?",a:["The Wire","Boardwalk Empire","The Sopranos","Ozark"],c:2,f:""},
  {q:"Quel acteur joue le rôle principal dans Gladiator ?",a:["Brad Pitt","Russell Crowe","Mel Gibson","Gerard Butler"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui voyage dans le temps pour sauver sa femme ?",a:["About Time","The Time Traveler's Wife","Midnight in Paris","Looper"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Ross et Rachel ?",a:["Seinfeld","Friends","How I Met Your Mother","New Girl"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un nageur devenant champion olympique ?",a:["Rush","The Swimmer","Eddie the Eagle","Chariots of Fire"],c:3,f:""},
  {q:"Quel acteur joue le personnage de Don Draper ?",a:["Jon Hamm","Bryan Cranston","Matthew McConaughey","Kevin Spacey"],c:0,f:""},
  {q:"Dans quel film trouve-t-on la phrase 'Houston, we have a problem' ?",a:["The Right Stuff","First Man","Apollo 13","Gravity"],c:2,f:""},
  {q:"Quelle actrice joue le rôle d'Hermione Granger ?",a:["Emma Watson","Keira Knightley","Natalie Portman","Lily James"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Tyrion Lannister ?",a:["The Witcher","Vikings","Game of Thrones","Marco Polo"],c:2,f:""},
  {q:"Quel film raconte l'histoire d'une marionnette qui veut devenir un vrai garçon ?",a:["Pinocchio","Puppet Master","Small Soldiers","Annabelle"],c:0,f:""},
  {q:"Quel acteur joue le rôle de Hannibal Lecter dans Le Silence des Agneaux ?",a:["Gary Oldman","Anthony Hopkins","Christopher Walken","Ian McKellen"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Dexter Morgan ?",a:["Dexter","Mindhunter","Criminal Minds","The Following"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui découvre que sa vie est un show télévisé ?",a:["The Truman Show","EdTV","The Game","Synecdoche New York"],c:0,f:""},
  {q:"Quel acteur joue le rôle de Jack Torrance dans The Shining ?",a:["Robert De Niro","Jack Nicholson","Al Pacino","Dustin Hoffman"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Frank Underwood ?",a:["Succession","House of Cards","Billions","Designated Survivor"],c:1,f:""},
  {q:"Quel film d'animation Disney met en scène une princesse aux cheveux magiques ?",a:["Frozen","Tangled","Brave","Moana"],c:1,f:""},
  {q:"Quel acteur joue le rôle de Thor dans le MCU ?",a:["Chris Evans","Chris Pratt","Chris Hemsworth","Liam Hemsworth"],c:2,f:""},
  {q:"Dans quel film trouve-t-on la phrase 'I'll be back' ?",a:["RoboCop","Terminator","Predator","Total Recall"],c:1,f:""},
  {q:"Quelle actrice joue Katniss Everdeen dans Hunger Games ?",a:["Shailene Woodley","Jennifer Lawrence","Emma Stone","Lily Collins"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Jesse Pinkman ?",a:["Better Call Saul","Breaking Bad","Ozark","The Wire"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui s'endort 20 ans ?",a:["Groundhog Day","Sleepy Hollow","Rip Van Winkle","Big"],c:0,f:""},
  {q:"Quel acteur joue le rôle de Gandalf dans Le Seigneur des Anneaux ?",a:["Ian McKellen","Patrick Stewart","Anthony Hopkins","Michael Gambon"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Monica et Chandler ?",a:["Seinfeld","Friends","How I Met Your Mother","New Girl"],c:1,f:""},
  {q:"Quel film d'animation met en scène des personnages Pixar dans leur maison ?",a:["Cars","Up","Inside Out","Onward"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Vito Corleone dans Le Parrain ?",a:["Al Pacino","Marlon Brando","Robert De Niro","James Caan"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Mike Ross ?",a:["Suits","The Good Wife","Boston Legal","Better Call Saul"],c:0,f:""},
  {q:"Quel film raconte l'histoire de la construction de Facebook ?",a:["Jobs","The Imitation Game","The Social Network","Pirates of Silicon Valley"],c:2,f:""},
  {q:"Quelle actrice joue le rôle de Wonder Woman ?",a:["Scarlett Johansson","Gal Gadot","Brie Larson","Zoe Saldana"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Negan ?",a:["Fear the Walking Dead","The Walking Dead","Z Nation","The Last of Us"],c:1,f:""},
  {q:"Quel film d'animation met en scène un jeune lion qui devient roi ?",a:["Bambi","Jungle Book","The Lion King","Brother Bear"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Batman dans Batman v Superman ?",a:["Christian Bale","Ben Affleck","Robert Pattinson","Val Kilmer"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Harvey Specter ?",a:["Suits","The Good Wife","Billions","Boston Legal"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un boxeur qui devient champion du monde ?",a:["Rocky","Raging Bull","Ali","Million Dollar Baby"],c:0,f:""},
  {q:"Quelle actrice joue le rôle de Clarice Starling dans Le Silence des Agneaux ?",a:["Sigourney Weaver","Jodie Foster","Meryl Streep","Glenn Close"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Jax Teller ?",a:["Mayans M.C.","Sons of Anarchy","Biker Boyz","Outlaw"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un groupe d'astronautes qui voyagent vers un trou noir ?",a:["Gravity","The Martian","Interstellar","Ad Astra"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Frodo dans Le Seigneur des Anneaux ?",a:["Dominic Monaghan","Billy Boyd","Elijah Wood","Sean Astin"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Nathan et Haley ?",a:["One Tree Hill","Dawson's Creek","The O.C.","Gossip Girl"],c:0,f:""},
  {q:"Quel film d'animation met en scène une petite sirène ?",a:["Sinbad","The Little Mermaid","Atlantis","Moana"],c:1,f:""},
  {q:"Quel acteur joue le rôle de Thanos dans le MCU ?",a:["James Earl Jones","Josh Brolin","Ron Perlman","Vin Diesel"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Don Corleone junior ?",a:["The Sopranos","Boardwalk Empire","Gomorra","Suburra"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui rêve dans les rêves des autres ?",a:["Eternal Sunshine","Inception","Shutter Island","The Cell"],c:1,f:""},
  {q:"Quelle actrice joue le rôle de Black Widow dans le MCU ?",a:["Gal Gadot","Brie Larson","Scarlett Johansson","Zoe Saldana"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Carrie et Mr. Big ?",a:["Desperate Housewives","Sex and the City","Dirty Sexy Money","Gossip Girl"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un comptable qui découvre qu'il est un personnage de roman ?",a:["Adaptation","Stranger Than Fiction","Synecdoche New York","Ruby Sparks"],c:1,f:""},
  {q:"Quel acteur joue le rôle de Joker dans le film Joker (2019) ?",a:["Heath Ledger","Jared Leto","Joaquin Phoenix","Jack Nicholson"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Kendall Roy ?",a:["Billions","Succession","Halt and Catch Fire","Industry"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui découvre qu'il peut arrêter le temps ?",a:["Minority Report","Next","Limitless","Source Code"],c:1,f:""},
  {q:"Quelle actrice joue le rôle de Daenerys dans Game of Thrones ?",a:["Sophie Turner","Maisie Williams","Emilia Clarke","Natalie Dormer"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Walter White junior ?",a:["Breaking Bad","Better Call Saul","Ozark","Bloodline"],c:0,f:""},
  {q:"Quel film d'animation Pixar met en scène des émotions personnifiées ?",a:["Soul","Luca","Inside Out","Turning Red"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Captain America dans le MCU ?",a:["Chris Hemsworth","Chris Pratt","Chris Evans","Liam Neeson"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Cersei Lannister ?",a:["The Witcher","Game of Thrones","Vikings","Barbarians"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui s'endort et se réveille dans le futur ?",a:["Idiocracy","Sleeper","Future Man","Interstellar"],c:0,f:""},
  {q:"Quel acteur joue le rôle de l'agent Smith dans The Matrix ?",a:["Hugo Weaving","Ralph Fiennes","Gary Oldman","Tim Roth"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Sansa Stark ?",a:["The Last Kingdom","Game of Thrones","Vikings","House of the Dragon"],c:1,f:""},
  {q:"Quel film raconte l'histoire de la création d'Apple par Steve Jobs ?",a:["Steve Jobs","Jobs","Pirates of Silicon Valley","The Social Network"],c:0,f:""},
  {q:"Quelle actrice joue le rôle de Catwoman dans The Dark Knight Rises ?",a:["Halle Berry","Michelle Pfeiffer","Anne Hathaway","Margot Robbie"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Littlefinger ?",a:["The Witcher","Game of Thrones","Marco Polo","Knightfall"],c:1,f:""},
  {q:"Quel film d'animation raconte l'histoire d'un dinosaure qui se lie d'amitié avec un humain ?",a:["Ice Age","The Good Dinosaur","Dinosaur","Over the Hedge"],c:1,f:""},
];
