/* ════════════════════════════════════════
   questions/cinema.js — Cinéma / Séries — 200 questions
   ════════════════════════════════════════ */
QUESTIONS.cinema = [
  {q:"Qui a réalisé le film Titanic ?",a:["Steven Spielberg","James Cameron","Ridley Scott","Christopher Nolan"],c:1,f:""},
  {q:"Quel acteur joue Jack dans Titanic ?",a:["Brad Pitt","Leonardo DiCaprio","Tom Cruise","Matt Damon"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Walter White ?",a:["Narcos","Breaking Bad","Better Call Saul","Ozark"],c:1,f:""},
  {q:"Qui joue Iron Man dans l'univers Marvel ?",a:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],c:1,f:""},
  {q:"Dans quelle série se déroule la lutte pour le trône de Westeros ?",a:["The Witcher","Game of Thrones","Vikings","House of the Dragon"],c:1,f:""},
  {q:"Quel acteur joue le Joker dans The Dark Knight ?",a:["Joaquin Phoenix","Jared Leto","Heath Ledger","Jack Nicholson"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on les personnages Eleven et Mike ?",a:["Dark","Stranger Things","The Umbrella Academy","The OA"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un parc rempli de dinosaures ?",a:["King Kong","Jurassic Park","Godzilla","Avatar"],c:1,f:""},
  {q:"Qui joue le rôle de Harry Potter au cinéma ?",a:["Rupert Grint","Daniel Radcliffe","Tom Felton","Elijah Wood"],c:1,f:""},
  {q:"Quel acteur incarne Spider-Man dans les films du MCU récents ?",a:["Tobey Maguire","Andrew Garfield","Tom Holland","Timothée Chalamet"],c:2,f:""},
  {q:"Quel acteur joue Neo dans The Matrix ?",a:["Brad Pitt","Keanu Reeves","Tom Cruise","Johnny Depp"],c:1,f:""},
  {q:"Quel film met en scène un naufragé sur une île avec un ballon nommé Wilson ?",a:["Cast Away","Life of Pi","The Martian","The Beach"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un clown terrifiant nommé Pennywise ?",a:["The Conjuring","It","The Nun","Annabelle"],c:1,f:""},
  {q:"Quel acteur joue Wolverine dans les films X-Men ?",a:["Hugh Jackman","Chris Evans","Ryan Reynolds","Chris Pratt"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui revit la même journée sans cesse ?",a:["Groundhog Day","Edge of Tomorrow","Looper","Source Code"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Ragnar Lothbrok ?",a:["Vikings","The Last Kingdom","Game of Thrones","Barbarians"],c:0,f:""},
  {q:"Quel film met en scène un parc virtuel nommé OASIS ?",a:["Tron: Legacy","Ready Player One","Inception","Minority Report"],c:1,f:""},
  {q:"Dans quelle série se déroule un braquage de la Monnaie d'Espagne ?",a:["Narcos","Money Heist","Ozark","Lupin"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un astronaute seul sur Mars ?",a:["Gravity","Interstellar","The Martian","Apollo 13"],c:2,f:""},
  {q:"Dans quelle série suit-on un gentleman cambrioleur inspiré d'Arsène Lupin ?",a:["Lupin","Sherlock","Narcos","Money Heist"],c:0,f:""},
  {q:"Quel acteur joue Batman dans la trilogie de Christopher Nolan ?",a:["Ben Affleck","Christian Bale","Michael Keaton","Val Kilmer"],c:1,f:""},
  {q:"Dans quel film entend-on la phrase 'Je suis ton père' ?",a:["Star Wars IV","Star Wars V","Star Wars VI","Star Wars III"],c:1,f:""},
  {q:"Quel film d'animation raconte l'histoire d'un poisson cherchant son fils ?",a:["Shark Tale","Le Monde de Nemo","Surf's Up","Shark Tale"],c:1,f:""},
  {q:"Dans quelle série joue Bryan Cranston en prof de chimie ?",a:["Dexter","Breaking Bad","The Wire","Ozark"],c:1,f:""},
  {q:"Quel film raconte l'histoire de la construction du mur d'un immeuble de luxe ?",a:["Parasite","Squid Game","Okja","Mother"],c:0,f:""},
  {q:"Quel acteur joue Forrest Gump ?",a:["Tom Hanks","Kevin Costner","Tom Cruise","Mel Gibson"],c:0,f:""},
  {q:"Dans quel film trouve-t-on le personnage de Jack Sparrow ?",a:["Pirates of the Caribbean","Master and Commander","The Bounty","Cutthroat Island"],c:0,f:""},
  {q:"Quel film raconte l'invasion de la Normandie en 1944 ?",a:["Platoon","Full Metal Jacket","Saving Private Ryan","Apocalypse Now"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on Daenerys Targaryen ?",a:["The Witcher","Game of Thrones","House of the Dragon","The Last Kingdom"],c:1,f:""},
  {q:"Quel film met en scène des jouets qui prennent vie quand les humains s'en vont ?",a:["Toy Story","Small Soldiers","The Lego Movie","Antz"],c:0,f:""},
  {q:"Quel acteur joue Tony Montana dans Scarface ?",a:["Robert De Niro","Al Pacino","Jack Nicholson","Dustin Hoffman"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on Sheldon Cooper ?",a:["How I Met Your Mother","Friends","The Big Bang Theory","Two and a Half Men"],c:2,f:""},
  {q:"Quel film raconte l'histoire d'un comptable qui aide un baron de la drogue ?",a:["El Camino","Ozark","The Accountant","Money Monster"],c:2,f:""},
  {q:"Quel acteur joue James Bond dans Casino Royale (2006) ?",a:["Pierce Brosnan","Daniel Craig","Roger Moore","Timothy Dalton"],c:1,f:""},
  {q:"Dans quel film entend-on la réplique 'Tu vas te faire une offre qu'il ne pourra pas refuser' ?",a:["Casino","Goodfellas","The Godfather","Scarface"],c:2,f:""},
  {q:"Quel film d'animation met en scène un robot nommé WALL-E ?",a:["Big Hero 6","Robots","WALL-E","Treasure Planet"],c:2,f:""},
  {q:"Dans quelle série suit-on la famille Soprano ?",a:["The Wire","Boardwalk Empire","The Sopranos","Ozark"],c:2,f:""},
  {q:"Quel acteur joue le rôle principal dans Gladiator ?",a:["Brad Pitt","Russell Crowe","Mel Gibson","Gerard Butler"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui voyage dans le temps pour sauver sa femme ?",a:["About Time","The Time Traveler's Wife","Midnight in Paris","Looper"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Ross et Rachel ?",a:["Seinfeld","Friends","How I Met Your Mother","New Girl"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un nageur devenant champion olympique ?",a:["Rush","The Swimmer","Eddie the Eagle","Chariots of Fire"],c:3,f:""},
  {q:"Quel acteur joue le personnage de Don Draper ?",a:["Jon Hamm","Bryan Cranston","Matthew McConaughey","Kevin Spacey"],c:0,f:""},
  {q:"Dans quel film trouve-t-on la phrase 'Houston, we have a problem' ?",a:["The Right Stuff","First Man","Apollo 13","Gravity"],c:2,f:""},
  {q:"Quelle actrice joue le rôle d'Hermione Granger ?",a:["Emma Watson","Keira Knightley","Natalie Portman","Lily James"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Tyrion Lannister ?",a:["The Witcher","Vikings","Game of Thrones","Marco Polo"],c:2,f:""},
  {q:"Quel film raconte l'histoire d'une marionnette qui veut devenir un vrai garçon ?",a:["Pinocchio","Puppet Master","Small Soldiers","Annabelle"],c:0,f:""},
  {q:"Quel acteur joue le rôle de Hannibal Lecter dans Le Silence des Agneaux ?",a:["Gary Oldman","Anthony Hopkins","Christopher Walken","Ian McKellen"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Dexter Morgan ?",a:["Dexter","Mindhunter","Criminal Minds","The Following"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui découvre que sa vie est un show télévisé ?",a:["The Truman Show","EdTV","The Game","Synecdoche New York"],c:0,f:""},
  {q:"Quel acteur joue le rôle de Jack Torrance dans The Shining ?",a:["Robert De Niro","Jack Nicholson","Al Pacino","Dustin Hoffman"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Frank Underwood ?",a:["Succession","House of Cards","Billions","Designated Survivor"],c:1,f:""},
  {q:"Quel film d'animation Disney met en scène une princesse aux cheveux magiques ?",a:["Frozen","Tangled","Brave","Moana"],c:1,f:""},
  {q:"Quel acteur joue le rôle de Thor dans le MCU ?",a:["Chris Evans","Chris Pratt","Chris Hemsworth","Liam Hemsworth"],c:2,f:""},
  {q:"Dans quel film trouve-t-on la phrase 'I'll be back' ?",a:["RoboCop","Terminator","Predator","Total Recall"],c:1,f:""},
  {q:"Quelle actrice joue Katniss Everdeen dans Hunger Games ?",a:["Shailene Woodley","Jennifer Lawrence","Emma Stone","Lily Collins"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Jesse Pinkman ?",a:["Better Call Saul","Breaking Bad","Ozark","The Wire"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui s'endort 20 ans ?",a:["Groundhog Day","Sleepy Hollow","Rip Van Winkle","Big"],c:0,f:""},
  {q:"Quel acteur joue le rôle de Gandalf dans Le Seigneur des Anneaux ?",a:["Ian McKellen","Patrick Stewart","Anthony Hopkins","Michael Gambon"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Monica et Chandler ?",a:["Seinfeld","Friends","How I Met Your Mother","New Girl"],c:1,f:""},
  {q:"Quel film d'animation met en scène des personnages Pixar dans leur maison ?",a:["Cars","Up","Inside Out","Onward"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Vito Corleone dans Le Parrain ?",a:["Al Pacino","Marlon Brando","Robert De Niro","James Caan"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Mike Ross ?",a:["Suits","The Good Wife","Boston Legal","Better Call Saul"],c:0,f:""},
  {q:"Quel film raconte l'histoire de la construction de Facebook ?",a:["Jobs","The Imitation Game","The Social Network","Pirates of Silicon Valley"],c:2,f:""},
  {q:"Quelle actrice joue le rôle de Wonder Woman ?",a:["Scarlett Johansson","Gal Gadot","Brie Larson","Zoe Saldana"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Negan ?",a:["Fear the Walking Dead","The Walking Dead","Z Nation","The Last of Us"],c:1,f:""},
  {q:"Quel film d'animation met en scène un jeune lion qui devient roi ?",a:["Bambi","Jungle Book","The Lion King","Brother Bear"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Batman dans Batman v Superman ?",a:["Christian Bale","Ben Affleck","Robert Pattinson","Val Kilmer"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Harvey Specter ?",a:["Suits","The Good Wife","Billions","Boston Legal"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un boxeur qui devient champion du monde ?",a:["Rocky","Raging Bull","Ali","Million Dollar Baby"],c:0,f:""},
  {q:"Quelle actrice joue le rôle de Clarice Starling dans Le Silence des Agneaux ?",a:["Sigourney Weaver","Jodie Foster","Meryl Streep","Glenn Close"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Jax Teller ?",a:["Mayans M.C.","Sons of Anarchy","Biker Boyz","Outlaw"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un groupe d'astronautes qui voyagent vers un trou noir ?",a:["Gravity","The Martian","Interstellar","Ad Astra"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Frodo dans Le Seigneur des Anneaux ?",a:["Dominic Monaghan","Billy Boyd","Elijah Wood","Sean Astin"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Nathan et Haley ?",a:["One Tree Hill","Dawson's Creek","The O.C.","Gossip Girl"],c:0,f:""},
  {q:"Quel film d'animation met en scène une petite sirène ?",a:["Sinbad","The Little Mermaid","Atlantis","Moana"],c:1,f:""},
  {q:"Quel acteur joue le rôle de Thanos dans le MCU ?",a:["James Earl Jones","Josh Brolin","Ron Perlman","Vin Diesel"],c:1,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Don Corleone junior ?",a:["The Sopranos","Boardwalk Empire","Gomorra","Suburra"],c:0,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui rêve dans les rêves des autres ?",a:["Eternal Sunshine","Inception","Shutter Island","The Cell"],c:1,f:""},
  {q:"Quelle actrice joue le rôle de Black Widow dans le MCU ?",a:["Gal Gadot","Brie Larson","Scarlett Johansson","Zoe Saldana"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on les personnages de Carrie et Mr. Big ?",a:["Desperate Housewives","Sex and the City","Dirty Sexy Money","Gossip Girl"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un comptable qui découvre qu'il est un personnage de roman ?",a:["Adaptation","Stranger Than Fiction","Synecdoche New York","Ruby Sparks"],c:1,f:""},
  {q:"Quel acteur joue le rôle de Joker dans le film Joker (2019) ?",a:["Heath Ledger","Jared Leto","Joaquin Phoenix","Jack Nicholson"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Kendall Roy ?",a:["Billions","Succession","Halt and Catch Fire","Industry"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui découvre qu'il peut arrêter le temps ?",a:["Minority Report","Next","Limitless","Source Code"],c:1,f:""},
  {q:"Quelle actrice joue le rôle de Daenerys dans Game of Thrones ?",a:["Sophie Turner","Maisie Williams","Emilia Clarke","Natalie Dormer"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Walter White junior ?",a:["Breaking Bad","Better Call Saul","Ozark","Bloodline"],c:0,f:""},
  {q:"Quel film d'animation Pixar met en scène des émotions personnifiées ?",a:["Soul","Luca","Inside Out","Turning Red"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Captain America dans le MCU ?",a:["Chris Hemsworth","Chris Pratt","Chris Evans","Liam Neeson"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Cersei Lannister ?",a:["The Witcher","Game of Thrones","Vikings","Barbarians"],c:1,f:""},
  {q:"Quel film raconte l'histoire d'un homme qui s'endort et se réveille dans le futur ?",a:["Idiocracy","Sleeper","Future Man","Interstellar"],c:0,f:""},
  {q:"Quel acteur joue le rôle de l'agent Smith dans The Matrix ?",a:["Hugo Weaving","Ralph Fiennes","Gary Oldman","Tim Roth"],c:0,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Sansa Stark ?",a:["The Last Kingdom","Game of Thrones","Vikings","House of the Dragon"],c:1,f:""},
  {q:"Quel film raconte l'histoire de la création d'Apple par Steve Jobs ?",a:["Steve Jobs","Jobs","Pirates of Silicon Valley","The Social Network"],c:0,f:""},
  {q:"Quelle actrice joue le rôle de Catwoman dans The Dark Knight Rises ?",a:["Halle Berry","Michelle Pfeiffer","Anne Hathaway","Margot Robbie"],c:2,f:""},
  {q:"Dans quelle série trouve-t-on le personnage de Littlefinger ?",a:["The Witcher","Game of Thrones","Marco Polo","Knightfall"],c:1,f:""},
  {q:"Quel film d'animation raconte l'histoire d'un dinosaure qui se lie d'amitié avec un humain ?",a:["Ice Age","The Good Dinosaur","Dinosaur","Over the Hedge"],c:1,f:""},

  // ── 101-200 : nouvelles questions ──────────────────────────────────
  {q:"Quel studio d'animation japonais a produit Le Voyage de Chihiro ?",a:["Toei Animation","Studio Ghibli","Madhouse","Sunrise"],c:1,f:""},
  {q:"Quel film de Quentin Tarantino se déroule pendant la Seconde Guerre mondiale ?",a:["Kill Bill","Django Unchained","Inglourious Basterds","The Hateful Eight"],c:2,f:""},
  {q:"Quel film d'animation Pixar met en scène un rat qui rêve de devenir chef cuisinier à Paris ?",a:["Coco","Ratatouille","Up","Luca"],c:1,f:""},
  {q:"Quel réalisateur français a réalisé Le Fabuleux Destin d'Amélie Poulain ?",a:["Luc Besson","Jean-Pierre Jeunet","François Truffaut","Jacques Audiard"],c:1,f:""},
  {q:"Quel film a remporté l'Oscar du meilleur film en 2020 ?",a:["1917","Joker","Parasite","Once Upon a Time in Hollywood"],c:2,f:""},
  {q:"Dans Stranger Things, dans quelle dimension parallèle se retrouve Will Byers ?",a:["Le Néant","L'Upside Down","Le Vortex","La Zone Sombre"],c:1,f:""},
  {q:"Quel réalisateur est connu pour 2001 : L'Odyssée de l'espace et Orange Mécanique ?",a:["Ridley Scott","Stanley Kubrick","David Lynch","Martin Scorsese"],c:1,f:""},
  {q:"Quel film d'horreur met en scène une famille qui emménage dans un hôtel isolé pour l'hiver ?",a:["Psycho","The Shining","The Amityville Horror","Rosemary's Baby"],c:1,f:""},
  {q:"Quel acteur français a joué dans Intouchables aux côtés de François Cluzet ?",a:["Jamel Debbouze","Dany Boon","Omar Sy","Gad Elmaleh"],c:2,f:""},
  {q:"Quel film de Christopher Nolan raconte l'évacuation de soldats britanniques en 1940 ?",a:["Interstellar","Tenet","Dunkirk","The Prestige"],c:2,f:""},
  {q:"Quel film d'animation du Studio Ghibli met en scène deux soeurs et un esprit de la forêt ?",a:["Ponyo","Mon Voisin Totoro","Le Château Ambulant","Princesse Mononoké"],c:1,f:""},
  {q:"Quel film d'horreur de 1973 raconte la possession d'une jeune fille nommée Regan ?",a:["The Omen","Carrie","The Exorcist","Poltergeist"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Django dans Django Unchained ?",a:["Samuel L. Jackson","Will Smith","Jamie Foxx","Idris Elba"],c:2,f:""},
  {q:"Quel film français de Luc Besson met en scène un tueur à gages et une jeune fille ?",a:["Nikita","Le Cinquième Élément","Léon","Subway"],c:2,f:""},
  {q:"Quel film détient le record du plus gros succès au box-office mondial ?",a:["Avengers: Endgame","Titanic","Avatar","Star Wars: The Force Awakens"],c:2,f:""},
  {q:"Dans Breaking Bad, quel est le nom de code de Walter White dans le trafic de drogue ?",a:["The Cook","Blue Sky","Heisenberg","The Chemist"],c:2,f:""},
  {q:"Quel réalisateur a réalisé Schindler's List et E.T. l'extra-terrestre ?",a:["Martin Scorsese","Francis Ford Coppola","Steven Spielberg","George Lucas"],c:2,f:""},
  {q:"Quel film d'animation Disney de 2013 met en scène les soeurs Anna et Elsa ?",a:["Tangled","Moana","Frozen","Encanto"],c:2,f:""},
  {q:"Dans quelle série Netflix un joueur d'échecs prodige se bat contre ses addictions ?",a:["Ozark","The Queen's Gambit","Dark","Mindhunter"],c:1,f:""},
  {q:"Quel acteur incarne le personnage de Tyler Durden dans Fight Club ?",a:["Edward Norton","Jared Leto","Brad Pitt","Matt Damon"],c:2,f:""},
  {q:"Quel film d'horreur de 1996 met en scène un tueur masqué qui appelle ses victimes au téléphone ?",a:["Halloween","Scream","I Know What You Did Last Summer","Urban Legend"],c:1,f:""},
  {q:"Quel réalisateur français a réalisé La Haine en 1995 ?",a:["Mathieu Kassovitz","Cédric Klapisch","Jacques Audiard","Gaspar Noé"],c:0,f:""},
  {q:"Quel film a remporté le plus d'Oscars dans l'histoire avec 11 statuettes ?",a:["Titanic","Le Seigneur des Anneaux : Le Retour du Roi","Ben-Hur","Schindler's List"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Saul Goodman dans Better Call Saul ?",a:["Aaron Paul","Bob Odenkirk","Jonathan Banks","Giancarlo Esposito"],c:1,f:""},
  {q:"Quel film de Stanley Kubrick se déroule pendant la guerre du Vietnam ?",a:["Apocalypse Now","Platoon","Full Metal Jacket","The Deer Hunter"],c:2,f:""},
  {q:"Quel film d'animation Pixar raconte le voyage d'un vieil homme en maison volante ?",a:["Coco","Up","Inside Out","Onward"],c:1,f:""},
  {q:"Quel film d'horreur japonais a inspiré le remake américain The Ring ?",a:["Ju-On","Ringu","Dark Water","Audition"],c:1,f:""},
  {q:"Quelle actrice joue Mia dans le film La La Land ?",a:["Anne Hathaway","Margot Robbie","Emma Stone","Natalie Portman"],c:2,f:""},
  {q:"Quel est le premier long-métrage d'animation de l'histoire du cinéma ?",a:["Fantasia","Blanche-Neige et les Sept Nains","Pinocchio","Bambi"],c:1,f:""},
  {q:"Dans Game of Thrones, qui tue le Night King ?",a:["Jon Snow","Daenerys","Arya Stark","Bran Stark"],c:2,f:""},
  {q:"Quel film de Tarantino raconte l'histoire d'un braquage qui tourne mal ?",a:["Pulp Fiction","Reservoir Dogs","Jackie Brown","Kill Bill"],c:1,f:""},
  {q:"Quel réalisateur français a créé Le Grand Bleu et Le Cinquième Élément ?",a:["Jean-Jacques Annaud","Luc Besson","Cédric Klapisch","Olivier Assayas"],c:1,f:""},
  {q:"Quel film a remporté l'Oscar du meilleur film en 1994 ?",a:["Pulp Fiction","The Shawshank Redemption","Forrest Gump","Schindler's List"],c:2,f:""},
  {q:"Quelle série Netflix raconte la vie de la famille royale britannique ?",a:["Downton Abbey","Bridgerton","The Crown","Victoria"],c:2,f:""},
  {q:"Quel acteur joue le rôle du Colonel Hans Landa dans Inglourious Basterds ?",a:["Michael Fassbender","Daniel Brühl","Christoph Waltz","Til Schweiger"],c:2,f:""},
  {q:"Quel film d'animation du Studio Ghibli se déroule dans un château volant ?",a:["Le Voyage de Chihiro","Mon Voisin Totoro","Le Château Ambulant","Ponyo"],c:2,f:""},
  {q:"Quel film d'horreur de 1978 a lancé la franchise de Michael Myers ?",a:["Friday the 13th","A Nightmare on Elm Street","Halloween","The Texas Chain Saw Massacre"],c:2,f:""},
  {q:"Quel acteur français joue le rôle d'Assane Diop dans la série Lupin ?",a:["Dany Boon","Omar Sy","Tahar Rahim","Romain Duris"],c:1,f:""},
  {q:"Quel film de Nolan joue avec la notion de temps inversé ?",a:["Memento","Inception","Interstellar","Tenet"],c:3,f:""},
  {q:"Quel film d'animation Pixar explore le monde des morts au Mexique ?",a:["Soul","Luca","Coco","Onward"],c:2,f:""},
  {q:"Dans quelle série un professeur de lycée fabrique de la méthamphétamine dans le désert ?",a:["Ozark","Narcos","Better Call Saul","Breaking Bad"],c:3,f:""},
  {q:"Quel réalisateur a créé la saga Indiana Jones ?",a:["James Cameron","George Lucas","Steven Spielberg","Ridley Scott"],c:2,f:""},
  {q:"Quel film français de 1966 met en scène Louis de Funès en gendarme à Saint-Tropez ?",a:["La Grande Vadrouille","Le Gendarme de Saint-Tropez","Le Corniaud","Rabbi Jacob"],c:1,f:""},
  {q:"Quel film d'horreur raconte l'histoire d'une famille traquée par ses propres doubles ?",a:["Get Out","Hereditary","Us","Midsommar"],c:2,f:""},
  {q:"Quel est le premier film de la saga Star Wars sorti en salles ?",a:["La Menace Fantôme","Un Nouvel Espoir","L'Empire Contre-Attaque","Le Retour du Jedi"],c:1,f:""},
  {q:"Quelle actrice joue le rôle de Mathilda dans le film Léon ?",a:["Winona Ryder","Natalie Portman","Christina Ricci","Drew Barrymore"],c:1,f:""},
  {q:"Quel film Netflix sud-coréen met en scène un jeu de survie mortel ?",a:["Parasite","Train to Busan","Squid Game","Oldboy"],c:2,f:""},
  {q:"Quel réalisateur est connu pour ses plans-séquences dans Birdman et The Revenant ?",a:["Alfonso Cuarón","Guillermo del Toro","Alejandro González Iñárritu","Denis Villeneuve"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Vincent Vega dans Pulp Fiction ?",a:["Samuel L. Jackson","Bruce Willis","John Travolta","Tim Roth"],c:2,f:""},
  {q:"Quel film d'animation Disney raconte l'histoire d'une jeune Polynésienne qui traverse l'océan ?",a:["Lilo & Stitch","Frozen","Encanto","Moana"],c:3,f:""},
  {q:"Quel film d'horreur de Jordan Peele traite du racisme à travers un thriller ?",a:["Us","Nope","Get Out","Candyman"],c:2,f:""},
  {q:"Quel film français a remporté la Palme d'Or à Cannes en 2008 avec le récit d'une classe de banlieue ?",a:["La Vie d'Adèle","Dheepan","Entre les Murs","Amour"],c:2,f:""},
  {q:"Quelle série HBO raconte les origines de la Maison Targaryen ?",a:["Game of Thrones","The Witcher","House of the Dragon","Rings of Power"],c:2,f:""},
  {q:"Quel acteur joue le rôle d'Andy Dufresne dans Les Évadés ?",a:["Morgan Freeman","Tim Robbins","Clint Eastwood","Kevin Costner"],c:1,f:""},
  {q:"Quel film de Christopher Nolan met en scène un duel entre deux magiciens ?",a:["Memento","Inception","The Prestige","Insomnia"],c:2,f:""},
  {q:"Quel film d'animation Pixar met en scène des voitures qui parlent ?",a:["Turbo","Cars","Speed Racer","Hot Wheels"],c:1,f:""},
  {q:"Dans Stranger Things, quel acteur joue le rôle du shérif Jim Hopper ?",a:["Winona Ryder","David Harbour","Sean Astin","Joe Keery"],c:1,f:""},
  {q:"Quel film de Kubrick raconte l'histoire d'Alex et de ses droogs dans un futur dystopique ?",a:["Full Metal Jacket","The Shining","Orange Mécanique","2001"],c:2,f:""},
  {q:"Quelle actrice a remporté le plus d'Oscars de la meilleure actrice ?",a:["Meryl Streep","Katharine Hepburn","Cate Blanchett","Frances McDormand"],c:1,f:""},
  {q:"Quel film français de Jacques Audiard met en scène un détenu corse en prison ?",a:["Dheepan","De Rouille et d'Os","Un Prophète","Les Frères Sisters"],c:2,f:""},
  {q:"Dans quelle série Netflix des enfants disparaissent dans une petite ville allemande ?",a:["Stranger Things","The Rain","Dark","Tribes of Europa"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Léon dans le film de Luc Besson ?",a:["Gary Oldman","Jean Reno","Vincent Cassel","Liam Neeson"],c:1,f:""},
  {q:"Quel film de Spielberg raconte le sauvetage de soldats pendant la Seconde Guerre mondiale ?",a:["Schindler's List","Bridge of Spies","Saving Private Ryan","War Horse"],c:2,f:""},
  {q:"Quel film d'animation du Studio Ghibli met en scène une princesse guerrière protégeant la forêt ?",a:["Le Voyage de Chihiro","Princesse Mononoké","Nausicaä","Le Château Ambulant"],c:1,f:""},
  {q:"Quel film d'horreur met en scène une poupée démoniaque nommée Annabelle ?",a:["Chucky","The Conjuring","Annabelle","Dead Silence"],c:2,f:""},
  {q:"Quel réalisateur mexicain a réalisé Le Labyrinthe de Pan ?",a:["Alfonso Cuarón","Alejandro González Iñárritu","Guillermo del Toro","Robert Rodriguez"],c:2,f:""},
  {q:"Quel film a été le premier à dépasser un milliard de dollars au box-office mondial ?",a:["Jurassic Park","Star Wars","Titanic","Le Seigneur des Anneaux"],c:2,f:""},
  {q:"Quelle série raconte l'histoire d'un chimiste génial devenu baron de la drogue au Nouveau-Mexique ?",a:["Narcos","Ozark","Breaking Bad","Weeds"],c:2,f:""},
  {q:"Quel acteur a incarné le Docteur Strange dans le MCU ?",a:["Benedict Cumberbatch","Tom Hiddleston","Mads Mikkelsen","Chiwetel Ejiofor"],c:0,f:""},
  {q:"Quel film de Tarantino met en scène une mariée en quête de vengeance ?",a:["Pulp Fiction","Django Unchained","Kill Bill","Death Proof"],c:2,f:""},
  {q:"Quel film d'animation Disney de 2021 se déroule en Colombie avec une famille aux pouvoirs magiques ?",a:["Moana","Raya and the Last Dragon","Encanto","Luca"],c:2,f:""},
  {q:"Quel film d'horreur d'Ari Aster se déroule lors d'un festival suédois en plein été ?",a:["Hereditary","The Witch","Midsommar","It Follows"],c:2,f:""},
  {q:"Quel acteur français a joué dans Le Grand Bleu de Luc Besson ?",a:["Vincent Cassel","Jean-Marc Barr","Romain Duris","Guillaume Canet"],c:1,f:""},
  {q:"Quel film de Nolan raconte l'histoire d'un homme souffrant d'amnésie antérograde ?",a:["The Prestige","Inception","Insomnia","Memento"],c:3,f:""},
  {q:"Quel personnage de Stranger Things possède des pouvoirs télékinésiques ?",a:["Mike Wheeler","Dustin Henderson","Eleven","Will Byers"],c:2,f:""},
  {q:"Quel film d'animation Pixar met en scène un poisson amnésique nommé Dory ?",a:["Le Monde de Nemo","Le Monde de Dory","Shark Tale","Luca"],c:1,f:""},
  {q:"Quel réalisateur a réalisé les films Alien et Blade Runner ?",a:["James Cameron","David Fincher","Ridley Scott","Denis Villeneuve"],c:2,f:""},
  {q:"Quelle actrice joue le rôle de Furiosa dans Mad Max: Fury Road ?",a:["Scarlett Johansson","Emily Blunt","Charlize Theron","Margot Robbie"],c:2,f:""},
  {q:"Quel film français de 2011 est devenu le plus gros succès du cinéma français à l'étranger ?",a:["Amélie","Le Fabuleux Destin d'Amélie Poulain","Intouchables","La Vie en Rose"],c:2,f:""},
  {q:"Quel film détient le record du plus grand nombre d'entrées en France ?",a:["Intouchables","Bienvenue chez les Ch'tis","Titanic","Astérix et Obélix : Mission Cléopâtre"],c:2,f:""},
  {q:"Quel acteur joue le rôle de Gustavo Fring dans Breaking Bad ?",a:["Jonathan Banks","Bob Odenkirk","Giancarlo Esposito","Dean Norris"],c:2,f:""},
  {q:"Quel film de Spielberg raconte l'histoire d'un extra-terrestre ami d'un enfant ?",a:["Close Encounters","A.I.","E.T. l'extra-terrestre","Super 8"],c:2,f:""},
  {q:"Quel film d'animation du Studio Ghibli raconte l'histoire d'une petite fille dans un monde de bains publics pour esprits ?",a:["Ponyo","Mon Voisin Totoro","Le Voyage de Chihiro","Kiki la Petite Sorcière"],c:2,f:""},
  {q:"Quel film d'horreur de 2017 met en scène une famille hantée après la mort de la grand-mère ?",a:["Midsommar","Get Out","Hereditary","It"],c:2,f:""},
  {q:"Quelle série Netflix originale raconte la vie dans une prison pour femmes ?",a:["Wentworth","Vis a Vis","Orange Is the New Black","The Handmaid's Tale"],c:2,f:""},
  {q:"Quel réalisateur canadien a réalisé Dune (2021) et Arrival ?",a:["Christopher Nolan","Ridley Scott","Denis Villeneuve","David Fincher"],c:2,f:""},
  {q:"Quel acteur joue le personnage de John Wick ?",a:["Jason Statham","Keanu Reeves","Liam Neeson","Denzel Washington"],c:1,f:""},
  {q:"Quel film de Kubrick se déroule entièrement dans une station spatiale et sur la Lune ?",a:["Solaris","Interstellar","2001 : L'Odyssée de l'espace","Gravity"],c:2,f:""},
  {q:"Quelle actrice joue le rôle de la Reine Elizabeth II dans les premières saisons de The Crown ?",a:["Olivia Colman","Helena Bonham Carter","Claire Foy","Imelda Staunton"],c:2,f:""},
  {q:"Quel film français de François Truffaut raconte l'histoire d'un garçon fugueur nommé Antoine Doinel ?",a:["Jules et Jim","La Nuit Américaine","Les 400 Coups","L'Enfant Sauvage"],c:2,f:""},
  {q:"Quel film de Tarantino se déroule dans l'Amérique esclavagiste du Sud ?",a:["The Hateful Eight","Inglourious Basterds","Kill Bill","Django Unchained"],c:3,f:""},
  {q:"Quel film d'animation Disney met en scène un génie bleu dans une lampe ?",a:["Hercule","Aladdin","Le Roi Lion","Le Bossu de Notre-Dame"],c:1,f:""},
  {q:"Quel film d'horreur met en scène un démon invoqué par un livre appelé le Necronomicon ?",a:["Hellraiser","Evil Dead","The Conjuring","Sinister"],c:1,f:""},
  {q:"Quelle série coréenne de Netflix a battu tous les records de visionnage en 2021 ?",a:["Kingdom","All of Us Are Dead","Squid Game","Hellbound"],c:2,f:""},
  {q:"Quel acteur a joué à la fois dans Inception et dans Shutter Island la même année ?",a:["Tom Hardy","Ben Kingsley","Leonardo DiCaprio","Cillian Murphy"],c:2,f:""},
  {q:"Quel film de Nolan raconte la vie de J. Robert Oppenheimer ?",a:["Tenet","Interstellar","Dunkirk","Oppenheimer"],c:3,f:""},
  {q:"Quel film d'animation Pixar explore la vie après la mort et la passion musicale d'un professeur ?",a:["Inside Out","Coco","Soul","Luca"],c:2,f:""},
  {q:"Quel acteur incarne le Roi Léonidas dans le film 300 ?",a:["Russell Crowe","Gerard Butler","Michael Fassbender","Liam Neeson"],c:1,f:""},
  {q:"Quel film de David Fincher raconte la traque d'un tueur en série qui choisit ses victimes selon les sept péchés capitaux ?",a:["Zodiac","Gone Girl","Fight Club","Seven"],c:3,f:""},
  {q:"Quelle actrice française a remporté l'Oscar de la meilleure actrice pour La Môme ?",a:["Juliette Binoche","Isabelle Huppert","Marion Cotillard","Audrey Tautou"],c:2,f:""},
  {q:"Quel film d'animation Disney de 2016 se déroule dans une ville peuplée d'animaux anthropomorphes ?",a:["Encanto","Zootopia","Ralph 2.0","Les Mondes de Ralph"],c:1,f:""},
  {q:"Dans Game of Thrones, quel personnage est surnommé le Limier ?",a:["Gregor Clegane","Bronn","Sandor Clegane","Jorah Mormont"],c:2,f:""},
  {q:"Quel film de Quentin Tarantino met en scène huit personnages bloqués dans un refuge pendant un blizzard ?",a:["Reservoir Dogs","Django Unchained","The Hateful Eight","Inglourious Basterds"],c:2,f:""},
  {q:"Quel réalisateur a réalisé le film Mulholland Drive et la série Twin Peaks ?",a:["David Cronenberg","Stanley Kubrick","David Lynch","Darren Aronofsky"],c:2,f:""},
];
