/* ════════════════════════════════════════
   questions/culture.js — Culture Générale
   100 questions
   { q:"Question ?", a:["A","B","C","D"], c:2, f:"" }
   c = index de la bonne réponse (0=A 1=B 2=C 3=D)
   ════════════════════════════════════════ */
QUESTIONS.culture = [
  {q:"Quel est le plus grand pays du monde par superficie ?",a:["Canada","Chine","Russie","États-Unis"],c:2,f:""},
  {q:"Qui a peint La Nuit étoilée ?",a:["Claude Monet","Vincent van Gogh","Pablo Picasso","Salvador Dalí"],c:1,f:""},
  {q:"Quelle est la capitale du Canada ?",a:["Toronto","Vancouver","Ottawa","Montréal"],c:2,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de football sur le terrain ?",a:["9","10","11","12"],c:2,f:""},
  {q:"Quel est le plus grand désert du monde ?",a:["Sahara","Antarctique","Gobi","Kalahari"],c:1,f:""},
  {q:"Qui a écrit Le Petit Prince ?",a:["Albert Camus","Antoine de Saint-Exupéry","Marcel Proust","Jules Verne"],c:1,f:""},
  {q:"Quelle planète est surnommée « la planète rouge » ?",a:["Mars","Vénus","Jupiter","Saturne"],c:0,f:""},
  {q:"Dans quel pays se trouve la ville de Dubaï ?",a:["Qatar","Arabie saoudite","Émirats arabes unis","Oman"],c:2,f:""},
  {q:"Qui a composé la Symphonie n°9 ?",a:["Johann Sebastian Bach","Wolfgang Amadeus Mozart","Ludwig van Beethoven","Frédéric Chopin"],c:2,f:""},
  {q:"Quel est le plus grand organe du corps humain ?",a:["Foie","Peau","Cerveau","Poumon"],c:1,f:""},
  {q:"Quel est le symbole chimique du fer ?",a:["Fe","Fr","F","Ir"],c:0,f:""},
  {q:"Quel océan borde la côte ouest de l'Europe ?",a:["Océan Pacifique","Océan Atlantique","Océan Indien","Océan Arctique"],c:1,f:""},
  {q:"Qui a réalisé le film Titanic ?",a:["Steven Spielberg","James Cameron","Christopher Nolan","Ridley Scott"],c:1,f:""},
  {q:"Quel est l'animal terrestre le plus rapide ?",a:["Lion","Guépard","Antilope","Tigre"],c:1,f:""},
  {q:"Dans quel pays est née la marque IKEA ?",a:["Finlande","Danemark","Suède","Norvège"],c:2,f:""},
  {q:"Qui a écrit Harry Potter à l'école des sorciers ?",a:["J. R. R. Tolkien","J. K. Rowling","Stephen King","George R. R. Martin"],c:1,f:""},
  {q:"Quelle est la capitale de l'Italie ?",a:["Milan","Venise","Florence","Rome"],c:3,f:""},
  {q:"Combien y a-t-il de côtés dans un hexagone ?",a:["5","6","7","8"],c:1,f:""},
  {q:"Quel gaz les plantes absorbent-elles principalement ?",a:["Oxygène","Azote","Dioxyde de carbone","Hydrogène"],c:2,f:""},
  {q:"Qui était le premier président des États-Unis ?",a:["Abraham Lincoln","George Washington","Thomas Jefferson","John Adams"],c:1,f:""},
  {q:"Quel est le plus haut sommet du monde ?",a:["K2","Mont Blanc","Mont Everest","Kilimandjaro"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Rio de Janeiro ?",a:["Argentine","Brésil","Mexique","Pérou"],c:1,f:""},
  {q:"Quelle est la monnaie officielle du Royaume-Uni ?",a:["Euro","Dollar","Livre sterling","Couronne"],c:2,f:""},
  {q:"Qui a peint Guernica ?",a:["Pablo Picasso","Henri Matisse","Paul Cézanne","Edvard Munch"],c:0,f:""},
  {q:"Quelle est la capitale de l'Espagne ?",a:["Barcelone","Madrid","Valence","Séville"],c:1,f:""},
  {q:"Quel instrument possède généralement 88 touches ?",a:["Violon","Piano","Guitare","Trompette"],c:1,f:""},
  {q:"Quel est le plus grand mammifère du monde ?",a:["Éléphant","Requin blanc","Baleine bleue","Girafe"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Bangkok ?",a:["Vietnam","Thaïlande","Cambodge","Laos"],c:1,f:""},
  {q:"Qui a inventé l'ampoule électrique moderne ?",a:["Nikola Tesla","Thomas Edison","Alexander Graham Bell","Benjamin Franklin"],c:1,f:""},
  {q:"Quel est le symbole chimique de l'or ?",a:["Ag","Au","Go","Or"],c:1,f:""},
  {q:"Quelle est la langue la plus parlée au monde ?",a:["Anglais","Espagnol","Mandarin","Hindi"],c:2,f:""},
  {q:"Quel est le plus petit pays du monde ?",a:["Monaco","Saint-Marin","Liechtenstein","Vatican"],c:3,f:""},
  {q:"Combien de continents y a-t-il sur Terre ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Qui a découvert la pénicilline ?",a:["Louis Pasteur","Alexander Fleming","Marie Curie","Charles Darwin"],c:1,f:""},
  {q:"Quelle est la vitesse de la lumière (environ) ?",a:["100 000 km/s","300 000 km/s","500 000 km/s","1 000 000 km/s"],c:1,f:""},
  {q:"Quel est le roman le plus vendu de l'histoire après la Bible ?",a:["Don Quichotte","Le Seigneur des Anneaux","Harry Potter","Le Petit Prince"],c:0,f:""},
  {q:"Dans quel pays a été inventé le papier ?",a:["Égypte","Inde","Chine","Grèce"],c:2,f:""},
  {q:"Quelle planète est la plus grande du système solaire ?",a:["Saturne","Neptune","Jupiter","Uranus"],c:2,f:""},
  {q:"Qui a composé La Flûte enchantée ?",a:["Beethoven","Mozart","Bach","Schubert"],c:1,f:""},
  {q:"Quel est le fleuve le plus long du monde ?",a:["Amazone","Nil","Yangtsé","Mississippi"],c:1,f:""},
  {q:"Quelle est la formule chimique de l'eau ?",a:["HO","H2O","H3O","OH2"],c:1,f:""},
  {q:"Qui a peint La Joconde ?",a:["Michel-Ange","Raphaël","Léonard de Vinci","Botticelli"],c:2,f:""},
  {q:"Quel pays a remporté le plus de Coupes du Monde de football ?",a:["Allemagne","Argentine","Brésil","France"],c:2,f:""},
  {q:"Quel est l'os le plus long du corps humain ?",a:["Tibia","Humérus","Fémur","Radius"],c:2,f:""},
  {q:"Dans quelle ville se trouve la Tour Eiffel ?",a:["Lyon","Marseille","Bordeaux","Paris"],c:3,f:""},
  {q:"Qui a écrit Les Misérables ?",a:["Émile Zola","Gustave Flaubert","Victor Hugo","Alexandre Dumas"],c:2,f:""},
  {q:"Quel est le métal le plus abondant dans la croûte terrestre ?",a:["Fer","Cuivre","Aluminium","Silicium"],c:2,f:""},
  {q:"En quelle année a eu lieu la Révolution française ?",a:["1776","1789","1804","1815"],c:1,f:""},
  {q:"Quel scientifique a formulé la théorie de la relativité ?",a:["Isaac Newton","Stephen Hawking","Albert Einstein","Niels Bohr"],c:2,f:""},
  {q:"Quel est le plus grand lac du monde ?",a:["Lac Supérieur","Lac Victoria","Mer Caspienne","Lac Baïkal"],c:2,f:""},
  {q:"Dans quel pays est né Napoléon Bonaparte ?",a:["France","Italie","Corse","Sardaigne"],c:2,f:""},
  {q:"Quelle est la capitale de la Chine ?",a:["Shanghai","Hong Kong","Pékin","Canton"],c:2,f:""},
  {q:"Quel est le symbole chimique de l'argent ?",a:["Ar","Ag","Si","Al"],c:1,f:""},
  {q:"Quel artiste a vendu le plus d'albums de tous les temps ?",a:["The Beatles","Michael Jackson","Elvis Presley","Madonna"],c:0,f:""},
  {q:"Combien de dents a un adulte humain (sans les dents de sagesse) ?",a:["28","30","32","34"],c:0,f:""},
  {q:"Quel est le pays le plus peuplé du monde ?",a:["Inde","Chine","États-Unis","Indonésie"],c:0,f:""},
  {q:"Qui a inventé le téléphone ?",a:["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Guglielmo Marconi"],c:2,f:""},
  {q:"Quelle est la monnaie du Japon ?",a:["Yuan","Won","Yen","Ringgit"],c:2,f:""},
  {q:"Quel est le sport le plus pratiqué au monde ?",a:["Basketball","Tennis","Football","Cricket"],c:2,f:""},
  {q:"Dans quelle ville se trouve le Colisée ?",a:["Athènes","Istanbul","Rome","Carthage"],c:2,f:""},
  {q:"Combien d'heures dure une journée sur Mars (environ) ?",a:["20h","24h30","36h","48h"],c:1,f:""},
  {q:"Quel est le nombre de couleurs dans l'arc-en-ciel ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Quelle est la capitale de l'Australie ?",a:["Sydney","Melbourne","Canberra","Perth"],c:2,f:""},
  {q:"Qui a écrit L'Odyssée ?",a:["Sophocle","Homère","Virgile","Platon"],c:1,f:""},
  {q:"Quel pays a construit le premier chemin de fer ?",a:["France","États-Unis","Allemagne","Royaume-Uni"],c:3,f:""},
  {q:"Quelle est la plus longue muraille jamais construite ?",a:["Mur d'Hadrien","Grande Muraille de Chine","Mur de Berlin","Mur d'Antonin"],c:1,f:""},
  {q:"Combien de grammes y a-t-il dans un kilogramme ?",a:["10","100","1000","10000"],c:2,f:""},
  {q:"Quel animal est le symbole de l'Australie ?",a:["Koala","Kangourou","Émeu","Wallaby"],c:1,f:""},
  {q:"Quelle planète possède les anneaux les plus visibles ?",a:["Jupiter","Uranus","Neptune","Saturne"],c:3,f:""},
  {q:"Qui a écrit Crime et Châtiment ?",a:["Léon Tolstoï","Anton Tchekhov","Fiodor Dostoïevski","Ivan Tourgueniev"],c:2,f:""},
  {q:"Dans quel pays se trouve Machu Picchu ?",a:["Mexique","Colombie","Pérou","Bolivie"],c:2,f:""},
  {q:"Quelle est la capitale du Brésil ?",a:["Rio de Janeiro","São Paulo","Brasilia","Salvador"],c:2,f:""},
  {q:"Quel est l'élément chimique dont le symbole est 'O' ?",a:["Or","Osmium","Oxygène","Ozone"],c:2,f:""},
  {q:"Combien de planètes y a-t-il dans le système solaire ?",a:["7","8","9","10"],c:1,f:""},
  {q:"Quel célèbre scientifique a découvert la gravité selon la légende de la pomme ?",a:["Albert Einstein","Galilée","Isaac Newton","Nikola Tesla"],c:2,f:""},
  {q:"Quelle est la capitale de la Russie ?",a:["Saint-Pétersbourg","Moscou","Kiev","Minsk"],c:1,f:""},
  {q:"Quel est le plus grand océan du monde ?",a:["Atlantique","Indien","Arctique","Pacifique"],c:3,f:""},
  {q:"Qui a réalisé la chapelle Sixtine ?",a:["Léonard de Vinci","Raphaël","Michel-Ange","Botticelli"],c:2,f:""},
  {q:"Quelle est la capitale du Mexique ?",a:["Guadalajara","Cancún","Mexico","Monterrey"],c:2,f:""},
  {q:"Combien de secondes y a-t-il dans une heure ?",a:["360","3600","600","6000"],c:1,f:""},
  {q:"Quel est le gaz le plus abondant dans l'atmosphère terrestre ?",a:["Oxygène","Dioxyde de carbone","Azote","Argon"],c:2,f:""},
  {q:"Qui a fondé Microsoft ?",a:["Steve Jobs","Mark Zuckerberg","Bill Gates","Elon Musk"],c:2,f:""},
  {q:"Dans quel pays se trouve le Taj Mahal ?",a:["Pakistan","Bangladesh","Inde","Sri Lanka"],c:2,f:""},
  {q:"Quel est le plus grand reptile du monde ?",a:["Anaconda","Crocodile marin","Varan de Komodo","Python réticulé"],c:1,f:""},
  {q:"Quelle est la monnaie de la Chine ?",a:["Yen","Won","Yuan","Ringgit"],c:2,f:""},
  {q:"Qui a écrit Don Quichotte ?",a:["Lope de Vega","Miguel de Cervantes","Francisco de Quevedo","Tirso de Molina"],c:1,f:""},
  {q:"Quel est le nom du premier satellite artificiel lancé dans l'espace ?",a:["Apollo","Spoutnik","Explorer","Vostok"],c:1,f:""},
  {q:"Dans quel pays se trouve la ville d'Amsterdam ?",a:["Belgique","Allemagne","Pays-Bas","Danemark"],c:2,f:""},
  {q:"Quel écrivain français a écrit Vingt Mille Lieues sous les mers ?",a:["Victor Hugo","Alexandre Dumas","Jules Verne","Guy de Maupassant"],c:2,f:""},
  {q:"Combien de joueurs composent une équipe de basketball sur le terrain ?",a:["4","5","6","7"],c:1,f:""},
  {q:"Quelle est la capitale de l'Argentine ?",a:["Santiago","Lima","Montevideo","Buenos Aires"],c:3,f:""},
  {q:"Quel est le plus grand pays d'Afrique par superficie ?",a:["Congo","Soudan","Algérie","Libye"],c:2,f:""},
  {q:"Qui a fondé Apple ?",a:["Bill Gates","Steve Jobs","Mark Zuckerberg","Jeff Bezos"],c:1,f:""},
  {q:"Quelle est la devise de la France ?",a:["Honneur et Patrie","Liberté Égalité Fraternité","Dieu et Mon Droit","Un pour tous tous pour un"],c:1,f:""},
  {q:"Dans quel pays se trouve la ville de Séoul ?",a:["Chine","Japon","Corée du Nord","Corée du Sud"],c:3,f:""},
  {q:"Combien de côtés a un octogone ?",a:["6","7","8","9"],c:2,f:""},
  {q:"Qui a peint Le Cri ?",a:["Vincent van Gogh","Edvard Munch","Gustav Klimt","Paul Gauguin"],c:1,f:""},
  {q:"Quelle est la capitale de l'Inde ?",a:["Mumbai","Kolkata","Chennai","New Delhi"],c:3,f:""},
  {q:"Quel est le plus petit os du corps humain ?",a:["Péroné","Étrier","Radius","Coccyx"],c:1,f:""},
];
