/* ════════════════════════════════════════
   questions/culture.js — Culture Générale
   Pour ajouter une question, copie ce format :
   { q:"Question ?", a:["A","B","C","D"], c:2, f:"Anecdote" }
   c = index de la bonne réponse (0=A 1=B 2=C 3=D)
   ════════════════════════════════════════ */
QUESTIONS.culture = [
  {q:"Quel est le plus grand pays du monde par superficie ?",a:["Canada","Chine","Russie","États-Unis"],c:2,f:""},
  {q:"Qui a peint La Nuit étoilée ?",a:["Claude Monet","Vincent van Gogh","Pablo Picasso","Salvador Dalí"],c:1,f:""},
  {q:"Quelle est la capitale du Canada ?",a:["Toronto","Vancouver","Ottawa","Montréal"],c:2,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de football sur le terrain ?",a:["9","10","11","12"],c:2,f:""},
  {q:"Quel est le plus grand désert du monde ?",a:["Sahara","Antarctique","Gobi","Kalahari"],c:1,f:""},
  {q:"Qui a écrit Le Petit Prince ?",a:["Albert Camus","Antoine de Saint-Exupéry","Marcel Proust","Jules Verne"],c:1,f:""},
  {q:"Quelle planète est surnommée « la planète rouge » ?",a:["Mars","Vénus","Jupiter","Saturne"],c:0,f:""},
  {q:"Dans quel pays se trouve la ville de Dubaï ?",a:["Qatar","Arabie saoudite","Émirats arabes unis","Oman"],c:2,f:""},
  {q:"Qui a composé la Symphonie n°9 ?",a:["Johann Sebastian Bach","Wolfgang Amadeus Mozart","Ludwig van Beethoven","Frédéric Chopin"],c:2,f:""},
  {q:"Quel est le plus grand organe du corps humain ?",a:["Foie","Peau","Cerveau","Poumon"],c:1,f:""},
  {q:"Quel est le symbole chimique du fer ?",a:["Fe","Fr","F","Ir"],c:0,f:""},
  {q:"Quel océan borde la côte ouest de l'Europe ?",a:["Océan Pacifique","Océan Atlantique","Océan Indien","Océan Arctique"],c:1,f:""},
  {q:"Qui a réalisé le film Titanic ?",a:["Steven Spielberg","James Cameron","Christopher Nolan","Ridley Scott"],c:1,f:""},
  {q:"Quel est l'animal terrestre le plus rapide ?",a:["Lion","Guépard","Antilope","Tigre"],c:1,f:""},
  {q:"Dans quel pays est née la marque IKEA ?",a:["Finlande","Danemark","Suède","Norvège"],c:2,f:""},
  {q:"Qui a écrit Harry Potter à l'école des sorciers ?",a:["J. R. R. Tolkien","J. K. Rowling","Stephen King","George R. R. Martin"],c:1,f:""},
  {q:"Quelle est la capitale de l'Italie ?",a:["Milan","Venise","Florence","Rome"],c:3,f:""},
  {q:"Combien y a-t-il de côtés dans un hexagone ?",a:["5","6","7","8"],c:1,f:""},
  {q:"Quel gaz les plantes absorbent-elles principalement ?",a:["Oxygène","Azote","Dioxyde de carbone","Hydrogène"],c:2,f:""},
  {q:"Qui était le premier président des États-Unis ?",a:["Abraham Lincoln","George Washington","Thomas Jefferson","John Adams"],c:1,f:""},
  {q:"Quel est le plus haut sommet du monde ?",a:["K2","Mont Blanc","Mont Everest","Kilimandjaro"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Rio de Janeiro ?",a:["Argentine","Brésil","Mexique","Pérou"],c:1,f:""},
  {q:"Quelle est la monnaie officielle du Royaume-Uni ?",a:["Euro","Dollar","Livre sterling","Couronne"],c:2,f:""},
  {q:"Qui a peint Guernica ?",a:["Pablo Picasso","Henri Matisse","Paul Cézanne","Edvard Munch"],c:0,f:""},
  {q:"Quelle est la capitale de l'Espagne ?",a:["Barcelone","Madrid","Valence","Séville"],c:1,f:""},
  {q:"Quel instrument possède généralement 88 touches ?",a:["Violon","Piano","Guitare","Trompette"],c:1,f:""},
  {q:"Quel est le plus grand mammifère du monde ?",a:["Éléphant","Requin blanc","Baleine bleue","Girafe"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Bangkok ?",a:["Vietnam","Thaïlande","Cambodge","Laos"],c:1,f:""},
  {q:"Qui a inventé l'ampoule électrique moderne ?",a:["Nikola Tesla","Thomas Edison","Alexander Graham Bell","Benjamin Franklin"],c:1,f:""},
  {q:"Quel est le symbole chimique de l'or ?",a:["Ag","Au","Go","Or"],c:1,f:""},
  {q:"Quelle est la langue la plus parlée au monde ?",a:["Anglais","Espagnol","Mandarin","Hindi"],c:2,f:""},
  {q:"Quel est le plus petit pays du monde ?",a:["Monaco","Saint-Marin","Liechtenstein","Vatican"],c:3,f:""},
  {q:"Combien de continents y a-t-il sur Terre ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Qui a découvert la pénicilline ?",a:["Louis Pasteur","Alexander Fleming","Marie Curie","Charles Darwin"],c:1,f:""},
  {q:"Quelle est la vitesse de la lumière (environ) ?",a:["100 000 km/s","300 000 km/s","500 000 km/s","1 000 000 km/s"],c:1,f:""},
  {q:"Quel est le roman le plus vendu de l'histoire après la Bible ?",a:["Don Quichotte","Le Seigneur des Anneaux","Harry Potter","Le Petit Prince"],c:0,f:""},
  {q:"Dans quel pays a été inventé le papier ?",a:["Égypte","Inde","Chine","Grèce"],c:2,f:""},
  {q:"Quelle planète est la plus grande du système solaire ?",a:["Saturne","Neptune","Jupiter","Uranus"],c:2,f:""},
  {q:"Qui a composé La Flûte enchantée ?",a:["Beethoven","Mozart","Bach","Schubert"],c:1,f:""},
  {q:"Quel est le fleuve le plus long du monde ?",a:["Amazone","Nil","Yangtsé","Mississippi"],c:1,f:""},
  {q:"Quelle est la formule chimique de l'eau ?",a:["HO","H2O","H3O","OH2"],c:1,f:""},
  {q:"Qui a peint La Joconde ?",a:["Michel-Ange","Raphaël","Leonard de Vinci","Botticelli"],c:2,f:""},
  {q:"Quel pays a remporté le plus de Coupes du Monde de football ?",a:["Allemagne","Argentine","Brésil","France"],c:2,f:""},
  {q:"Combien d'heures dure une journée sur Mars (environ) ?",a:["20h","24h30","36h","48h"],c:1,f:""},
  {q:"Quel est l'os le plus long du corps humain ?",a:["Tibia","Humérus","Fémur","Radius"],c:2,f:""},
  {q:"Dans quelle ville se trouve la Tour Eiffel ?",a:["Lyon","Marseille","Bordeaux","Paris"],c:3,f:""},
  {q:"Qui a écrit Les Misérables ?",a:["Émile Zola","Gustave Flaubert","Victor Hugo","Alexandre Dumas"],c:2,f:""},
  {q:"Quel est le métal le plus abondant dans la croûte terrestre ?",a:["Fer","Cuivre","Aluminium","Silicium"],c:2,f:""},
  {q:"En quelle année a eu lieu la Révolution française ?",a:["1776","1789","1804","1815"],c:1,f:""},
  {q:"Quel scientifique a formulé la théorie de la relativité ?",a:["Isaac Newton","Stephen Hawking","Albert Einstein","Niels Bohr"],c:2,f:""},
  {q:"Quel est le plus grand lac du monde ?",a:["Lac Supérieur","Lac Victoria","Mer Caspienne","Lac Baïkal"],c:2,f:""},
  {q:"Dans quel pays est né Napoléon Bonaparte ?",a:["France","Italie","Corse","Sardaigne"],c:2,f:""},
  {q:"Quelle est la capitale de la Chine ?",a:["Shanghai","Hong Kong","Pékin","Canton"],c:2,f:""},
  {q:"Quel est le symbole chimique de l'argent ?",a:["Ar","Ag","Si","Al"],c:1,f:""},
  {q:"Quel artiste a vendu le plus d'albums de tous les temps ?",a:["The Beatles","Michael Jackson","Elvis Presley","Madonna"],c:0,f:""},
  {q:"Combien de dents a un adulte humain (sans les dents de sagesse) ?",a:["28","30","32","34"],c:0,f:""},
  {q:"Quel est le pays le plus peuplé du monde ?",a:["Inde","Chine","États-Unis","Indonésie"],c:0,f:""},
  {q:"Qui a inventé le téléphone ?",a:["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Guglielmo Marconi"],c:2,f:""},
  {q:"Quelle est la monnaie du Japon ?",a:["Yuan","Won","Yen","Ringgit"],c:2,f:""},
  {q:"Quel est le sport le plus pratiqué au monde ?",a:["Basketball","Tennis","Football","Cricket"],c:2,f:""},
  {q:"Dans quelle ville se trouve le Colisée ?",a:["Athènes","Istanbul","Rome","Carthage"],c:2,f:""},
];
