/* ════════════════════════════════════════
   questions/football.js — Football — 200 questions
   ════════════════════════════════════════ */
QUESTIONS.football = [
  {q:"Quel pays a remporté la Coupe du Monde 2018 ?",a:["Brésil","Croatie","France","Allemagne"],c:2,f:""},
  {q:"Combien de joueurs composent une équipe de football sur le terrain ?",a:["9","10","11","12"],c:2,f:""},
  {q:"Quelle est la durée réglementaire d'un match de football ?",a:["80 minutes","90 minutes","100 minutes","120 minutes"],c:1,f:""},
  {q:"Qui a marqué le but de la « Main de Dieu » en 1986 ?",a:["Pelé","Maradona","Zidane","Platini"],c:1,f:""},
  {q:"Quel club a remporté le plus de Ligues des Champions ?",a:["FC Barcelone","AC Milan","Real Madrid","Liverpool"],c:2,f:""},
  {q:"En quelle année la première Coupe du Monde a-t-elle eu lieu ?",a:["1926","1930","1934","1928"],c:1,f:""},
  {q:"Quel pays a remporté la première Coupe du Monde ?",a:["Brésil","Argentine","Uruguay","Italie"],c:2,f:""},
  {q:"Quel joueur détient le record de Ballons d'Or ?",a:["Cristiano Ronaldo","Zinédine Zidane","Lionel Messi","Michel Platini"],c:2,f:""},
  {q:"Quel est le surnom de l'équipe de France ?",a:["Les Bleus","Les Rouges","Les Tricolores","Les Coqs"],c:0,f:""},
  {q:"Que signifie un carton rouge ?",a:["Avertissement","Expulsion","Remplacement","Penalty"],c:1,f:""},
  {q:"Quel joueur français a mis un coup de tête en finale de la Coupe du Monde 2006 ?",a:["Thierry Henry","Patrick Vieira","Zinédine Zidane","David Trezeguet"],c:2,f:""},
  {q:"Combien d'étoiles figurent sur le maillot du Brésil ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Quel pays a remporté le plus de Coupes du Monde ?",a:["Allemagne","Argentine","Italie","Brésil"],c:3,f:""},
  {q:"Quel club anglais est surnommé « The Red Devils » ?",a:["Liverpool","Arsenal","Manchester United","Chelsea"],c:2,f:""},
  {q:"Quel stade accueille les matchs du FC Barcelone ?",a:["Santiago Bernabéu","Camp Nou","San Siro","Anfield"],c:1,f:""},
  {q:"Qui est le meilleur buteur de l'histoire de la Ligue des Champions ?",a:["Lionel Messi","Raúl","Cristiano Ronaldo","Robert Lewandowski"],c:2,f:""},
  {q:"Quel pays a organisé la Coupe du Monde 2022 ?",a:["Russie","Arabie Saoudite","Qatar","Émirats arabes unis"],c:2,f:""},
  {q:"Quel joueur est surnommé « CR7 » ?",a:["Carlos Roa","Cristiano Ronaldo","Clarence Rankin","Cafu Roberto"],c:1,f:""},
  {q:"Quelle équipe a remporté la Coupe du Monde 2022 ?",a:["France","Brésil","Croatie","Argentine"],c:3,f:""},
  {q:"Combien de remplacements sont autorisés en match officiel depuis 2020 ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Quel gardien italien a remporté le Ballon d'Or en 2006 ?",a:["Gianluigi Buffon","Fabien Barthez","Fabio Cannavaro","Paolo Maldini"],c:2,f:""},
  {q:"Quel club français a atteint la finale de la Ligue des Champions en 2020 ?",a:["Olympique de Marseille","AS Monaco","Paris Saint-Germain","Olympique Lyonnais"],c:2,f:""},
  {q:"Quelle est la distance d'un penalty ?",a:["9,15 mètres","11 mètres","12 mètres","10 mètres"],c:1,f:""},
  {q:"Quel pays a remporté l'Euro 2016 ?",a:["France","Allemagne","Portugal","Espagne"],c:2,f:""},
  {q:"Qui est le meilleur buteur de l'histoire de l'équipe de France ?",a:["Zinédine Zidane","Michel Platini","Thierry Henry","Olivier Giroud"],c:3,f:""},
  {q:"Quel club est surnommé « Les Reds » ?",a:["Manchester United","Arsenal","Liverpool","Southampton"],c:2,f:""},
  {q:"En quelle année Zinédine Zidane a-t-il remporté la Coupe du Monde en tant que joueur ?",a:["1994","1998","2002","2006"],c:1,f:""},
  {q:"Quel joueur brésilien est surnommé « O Rei » (Le Roi) ?",a:["Ronaldo","Ronaldinho","Pelé","Neymar"],c:2,f:""},
  {q:"Combien de fois l'Italie a-t-elle remporté la Coupe du Monde ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quel est le plus grand stade de football au monde ?",a:["Wembley","Maracanã","Stade de France","Rungrado May Day"],c:3,f:""},
  {q:"Quel joueur a inscrit un triplé en finale de la Coupe du Monde 2022 ?",a:["Lionel Messi","Kylian Mbappé","Julian Álvarez","Antoine Griezmann"],c:1,f:""},
  {q:"Quel club allemand a remporté la Ligue des Champions en 2013 ?",a:["Bayer Leverkusen","Borussia Dortmund","Bayern Munich","Schalke 04"],c:2,f:""},
  {q:"Quelle règle a été introduite pour la première fois lors de la Coupe du Monde 1970 ?",a:["Le carton rouge","Les remplacements","Le hors-jeu","Le carton jaune"],c:3,f:""},
  {q:"Quel pays africain a atteint les quarts de finale de la Coupe du Monde 2010 ?",a:["Nigeria","Côte d'Ivoire","Ghana","Cameroun"],c:2,f:""},
  {q:"Quel joueur a remporté le Ballon d'Or 2023 ?",a:["Erling Haaland","Kylian Mbappé","Lionel Messi","Vinícius Júnior"],c:2,f:""},
  {q:"Quel est le surnom de l'équipe du Brésil ?",a:["La Celeste","A Seleção","Die Mannschaft","Les Cafeteros"],c:1,f:""},
  {q:"Quel entraîneur a remporté trois Ligues des Champions avec le Real Madrid ?",a:["José Mourinho","Carlo Ancelotti","Zinédine Zidane","Vicente Del Bosque"],c:2,f:""},
  {q:"Quel club italien joue au stade San Siro avec l'AC Milan ?",a:["Juventus","AS Roma","Inter Milan","SSC Napoli"],c:2,f:""},
  {q:"Quel joueur a inscrit le but « Gol del Siglo » (But du siècle) en 1986 ?",a:["Pelé","Zinédine Zidane","Diego Maradona","Lothar Matthäus"],c:2,f:""},
  {q:"Quel pays a remporté le premier Euro en 1960 ?",a:["Allemagne","France","Union soviétique","Espagne"],c:2,f:""},
  {q:"Combien de titres de champion de France le PSG a-t-il remportés avant 2025 ?",a:["8","10","12","7"],c:2,f:""},
  {q:"Quelle compétition européenne est réservée aux clubs non qualifiés pour la Ligue des Champions ?",a:["Conference League","Ligue Europa","Supercoupe","Coupe Intertoto"],c:1,f:""},
  {q:"Quel gardien espagnol est célèbre pour ses arrêts avec le Real Madrid et l'Espagne ?",a:["Víctor Valdés","David de Gea","Iker Casillas","Pepe Reina"],c:2,f:""},
  {q:"Quel club anglais a remporté la Premier League de manière invincible en 2004 ?",a:["Chelsea","Manchester United","Arsenal","Liverpool"],c:2,f:""},
  {q:"Quel joueur est le meilleur buteur de l'histoire de la Liga ?",a:["Cristiano Ronaldo","Raúl","Lionel Messi","Telmo Zarra"],c:2,f:""},
  {q:"Quel pays a remporté la Coupe du Monde 2014 ?",a:["Brésil","Argentine","Pays-Bas","Allemagne"],c:3,f:""},
  {q:"Quelle est la sanction pour une faute de main volontaire dans la surface ?",a:["Coup franc","Corner","Penalty","Carton jaune uniquement"],c:2,f:""},
  {q:"Quel joueur français a remporté la Premier League avec Leicester en 2016 ?",a:["Riyad Mahrez","N'Golo Kanté","Anthony Martial","Moussa Sissoko"],c:1,f:""},
  {q:"Quel est le surnom de la Juventus de Turin ?",a:["La Vecchia Signora","I Rossoneri","I Nerazzurri","Gli Azzurri"],c:0,f:""},
  {q:"Quelle équipe nationale est surnommée « La Roja » ?",a:["Portugal","Mexique","Espagne","Chili"],c:2,f:""},
  {q:"En quelle année le VAR a-t-il été utilisé pour la première fois en Coupe du Monde ?",a:["2014","2016","2018","2020"],c:2,f:""},
  {q:"Quel joueur a marqué le plus de buts en une année civile (91 buts en 2012) ?",a:["Cristiano Ronaldo","Robert Lewandowski","Lionel Messi","Gerd Müller"],c:2,f:""},
  {q:"Quel club a remporté la première édition de la Ligue des Champions (1956) ?",a:["AC Milan","Benfica","Real Madrid","FC Barcelone"],c:2,f:""},
  {q:"Quel pays a accueilli la Coupe du Monde 2006 ?",a:["France","Japon","Afrique du Sud","Allemagne"],c:3,f:""},
  {q:"Quel défenseur italien a remporté le Ballon d'Or en 2006 ?",a:["Paolo Maldini","Alessandro Nesta","Fabio Cannavaro","Lilian Thuram"],c:2,f:""},
  {q:"Quel joueur détient le record de sélections en équipe de France (145 matchs) ?",a:["Thierry Henry","Hugo Lloris","Lilian Thuram","Marcel Desailly"],c:1,f:""},
  {q:"Quel est le nom du trophée remis au meilleur buteur de la Coupe du Monde ?",a:["Ballon d'Or","Soulier d'Or","Gant d'Or","FIFA Fair Play"],c:1,f:""},
  {q:"Quel club espagnol est surnommé « Les Merengues » ?",a:["FC Barcelone","Atlético Madrid","Real Madrid","Valence CF"],c:2,f:""},
  {q:"Quel joueur a marqué le but en or en finale de l'Euro 2000 pour la France ?",a:["Zinédine Zidane","Thierry Henry","David Trezeguet","Sylvain Wiltord"],c:2,f:""},
  {q:"Quelle équipe a réalisé le « sextuplé » en 2009 ?",a:["Real Madrid","Manchester United","FC Barcelone","Bayern Munich"],c:2,f:""},
  {q:"Quel est le nombre maximum de joueurs sur une feuille de match en Ligue 1 ?",a:["16","18","20","23"],c:2,f:""},
  {q:"Quel pays a remporté la Copa América 2021 ?",a:["Brésil","Colombie","Argentine","Uruguay"],c:2,f:""},
  {q:"Quel entraîneur est surnommé « The Special One » ?",a:["Pep Guardiola","Carlo Ancelotti","José Mourinho","Jürgen Klopp"],c:2,f:""},
  {q:"Quel joueur brésilien a remporté le Ballon d'Or en 2007 ?",a:["Ronaldinho","Kaká","Ronaldo","Rivaldo"],c:1,f:""},
  {q:"Quel est le score le plus large en Coupe du Monde (2001, Australie vs Samoa américaines) ?",a:["15-0","21-0","31-0","25-0"],c:2,f:""},
  {q:"Quel club français a remporté la Ligue des Champions en 1993 ?",a:["Paris Saint-Germain","AS Monaco","Olympique de Marseille","Olympique Lyonnais"],c:2,f:""},
  {q:"Quelle position occupe le numéro 9 traditionnellement ?",a:["Gardien","Défenseur central","Milieu de terrain","Avant-centre"],c:3,f:""},
  {q:"Combien de minutes dure la mi-temps ?",a:["10 minutes","15 minutes","20 minutes","25 minutes"],c:1,f:""},
  {q:"Quel joueur nigérian a remporté le Ballon d'Or africain cinq fois ?",a:["Jay-Jay Okocha","Nwankwo Kanu","Samuel Eto'o","Didier Drogba"],c:2,f:""},
  {q:"Quel est le diamètre du rond central sur un terrain de football ?",a:["7,32 mètres","9,15 mètres","18,32 mètres","12 mètres"],c:1,f:""},
  {q:"Quelle sélection nationale est surnommée « Die Mannschaft » ?",a:["Autriche","Suisse","Pays-Bas","Allemagne"],c:3,f:""},
  {q:"Quel joueur a inscrit deux buts en finale de la Coupe du Monde 1998 ?",a:["Thierry Henry","Emmanuel Petit","Zinédine Zidane","Lilian Thuram"],c:2,f:""},
  {q:"Quel club anglais est surnommé « The Gunners » ?",a:["Chelsea","Tottenham","Arsenal","Everton"],c:2,f:""},
  {q:"Quel pays a remporté l'Euro 2020 (joué en 2021) ?",a:["Angleterre","Espagne","Italie","Danemark"],c:2,f:""},
  {q:"Quel gardien a remporté le trophée Yachine en 2023 ?",a:["Thibaut Courtois","Emiliano Martínez","Alisson Becker","Mike Maignan"],c:1,f:""},
  {q:"Quel joueur est le meilleur buteur de l'histoire de la Premier League ?",a:["Wayne Rooney","Thierry Henry","Alan Shearer","Andrew Cole"],c:2,f:""},
  {q:"Quel pays organise traditionnellement le « Calcio Storico » ?",a:["Espagne","Portugal","Italie","Grèce"],c:2,f:""},
  {q:"Quelle est la largeur réglementaire des buts de football ?",a:["6,50 m","7,32 m","8,00 m","7,00 m"],c:1,f:""},
  {q:"Quel joueur a été le premier à atteindre 100 buts en Ligue des Champions ?",a:["Lionel Messi","Raúl","Cristiano Ronaldo","Karim Benzema"],c:2,f:""},
  {q:"Quel pays a remporté la Coupe du Monde féminine en 2019 ?",a:["Allemagne","Pays-Bas","France","États-Unis"],c:3,f:""},
  {q:"Quel joueur argentin est surnommé « El Pibe de Oro » ?",a:["Lionel Messi","Diego Maradona","Gabriel Batistuta","Hernán Crespo"],c:1,f:""},
  {q:"Combien de coupes du monde Pelé a-t-il remportées ?",a:["1","2","3","4"],c:2,f:""},
  {q:"Quel club a remporté la Ligue des Champions en 2023 ?",a:["Inter Milan","Real Madrid","Manchester City","AC Milan"],c:2,f:""},
  {q:"Quelle est la position du numéro 1 dans une équipe ?",a:["Attaquant","Milieu défensif","Défenseur","Gardien de but"],c:3,f:""},
  {q:"Quel joueur français a remporté le Ballon d'Or en 1991 ?",a:["Zinédine Zidane","Michel Platini","Jean-Pierre Papin","Éric Cantona"],c:2,f:""},
  {q:"Quel pays a accueilli la Coupe du Monde 2010 ?",a:["Brésil","Allemagne","Afrique du Sud","Russie"],c:2,f:""},
  {q:"Quel joueur a inscrit le but victorieux de la finale de la Coupe du Monde 2010 ?",a:["David Villa","Xavi Hernández","Andrés Iniesta","Fernando Torres"],c:2,f:""},
  {q:"Quel est le nombre de joueurs minimum pour commencer un match ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Quel club turc a remporté la Coupe UEFA en 2000 ?",a:["Fenerbahçe","Beşiktaş","Trabzonspor","Galatasaray"],c:3,f:""},
  {q:"Quel joueur est surnommé « La Pulga » (La Puce) ?",a:["Neymar","Cristiano Ronaldo","Lionel Messi","Kylian Mbappé"],c:2,f:""},
  {q:"Quelle équipe nationale a remporté la Coupe d'Afrique des Nations le plus de fois ?",a:["Nigeria","Cameroun","Ghana","Égypte"],c:3,f:""},
  {q:"Quel joueur a marqué le but le plus rapide en Coupe du Monde (11 secondes) ?",a:["Miroslav Klose","Hakan Şükür","Ronaldo","Clint Dempsey"],c:1,f:""},
  {q:"Quel est le nom du système de jeu 4-3-3 ?",a:["Catenaccio","Tiki-taka","Faux neuf","Aucun de ces noms"],c:3,f:""},
  {q:"Quel joueur a remporté la Coupe du Monde en tant que joueur et entraîneur ?",a:["Zinédine Zidane","Franz Beckenbauer","Johan Cruyff","Mario Zagallo"],c:3,f:""},
  {q:"Quel est le surnom de l'équipe d'Argentine ?",a:["La Roja","La Albiceleste","La Celeste","La Verde"],c:1,f:""},
  {q:"Quel joueur français a été le meilleur buteur de la Coupe du Monde 2018 ?",a:["Antoine Griezmann","Kylian Mbappé","Olivier Giroud","Paul Pogba"],c:1,f:""},
  {q:"Combien de Ligues des Champions le Liverpool FC a-t-il remportées ?",a:["4","5","6","7"],c:2,f:""},
  {q:"Quel pays a remporté la Coupe du Monde 1966 ?",a:["Brésil","Allemagne de l'Ouest","Angleterre","Portugal"],c:2,f:""},
  {q:"Quel joueur hollandais est surnommé « Le Cygne d'Utrecht » ?",a:["Ruud Gullit","Johan Cruyff","Marco van Basten","Dennis Bergkamp"],c:2,f:""},
  {q:"Quel club a réalisé le triplé (championnat, coupe, Ligue des Champions) en 1999 ?",a:["Bayern Munich","FC Barcelone","Manchester United","Ajax Amsterdam"],c:2,f:""},

  // ── 100 nouvelles questions ──────────────────────────────────────────

  {q:"Quel pays a accueilli la toute première Copa América en 1916 ?",a:["Brésil","Uruguay","Argentine","Chili"],c:2,f:""},
  {q:"Quel club a remporté le plus de titres de Serie A en Italie ?",a:["AC Milan","Inter Milan","Juventus","AS Roma"],c:2,f:""},
  {q:"Quel entraîneur a dirigé Manchester United pendant 26 ans ?",a:["José Mourinho","Arsène Wenger","Alex Ferguson","Bobby Robson"],c:2,f:""},
  {q:"Quel gardien allemand est considéré comme l'un des meilleurs de l'histoire et a joué au Bayern Munich ?",a:["Manuel Neuer","Jens Lehmann","Oliver Kahn","Sepp Maier"],c:2,f:""},
  {q:"Quel pays africain a remporté la CAN 2022 disputée au Cameroun ?",a:["Cameroun","Égypte","Sénégal","Algérie"],c:2,f:""},
  {q:"Combien de Ballons d'Or Michel Platini a-t-il remportés ?",a:["1","2","3","4"],c:2,f:""},
  {q:"Quel stade londonien accueille les matchs de l'équipe d'Angleterre ?",a:["Stamford Bridge","Emirates Stadium","Wembley","Old Trafford"],c:2,f:""},
  {q:"Quelle joueuse américaine détient le record de buts en sélection féminine ?",a:["Mia Hamm","Alex Morgan","Abby Wambach","Carli Lloyd"],c:2,f:""},
  {q:"Quel club allemand a remporté le plus de titres de Bundesliga ?",a:["Borussia Dortmund","Hambourg SV","Bayern Munich","Borussia Mönchengladbach"],c:2,f:""},
  {q:"Quel est le transfert le plus cher de l'histoire (en 2017) ?",a:["Kylian Mbappé au PSG","Cristiano Ronaldo à la Juventus","Neymar au PSG","Paul Pogba à Manchester United"],c:2,f:""},
  {q:"Quel pays a accueilli la Coupe du Monde 1986 ?",a:["Argentine","Colombie","Mexique","Espagne"],c:2,f:""},
  {q:"Quel défenseur italien est considéré comme le meilleur arrière gauche de l'histoire ?",a:["Fabio Cannavaro","Alessandro Nesta","Franco Baresi","Paolo Maldini"],c:3,f:""},
  {q:"Quelle formation tactique est associée au « Catenaccio » italien ?",a:["4-4-2","4-3-3","3-5-2","5-3-2"],c:3,f:""},
  {q:"En quelle année le football a-t-il été codifié par la Football Association en Angleterre ?",a:["1848","1857","1863","1872"],c:2,f:""},
  {q:"Quel entraîneur espagnol est surnommé « Pep » ?",a:["Luis Enrique","Vicente Del Bosque","Pep Guardiola","Rafael Benítez"],c:2,f:""},
  {q:"Quel club de Saint-Étienne a atteint la finale de la Coupe d'Europe en 1976 ?",a:["OGC Nice","AS Saint-Étienne","RC Lens","FC Nantes"],c:1,f:""},
  {q:"Quel pays a remporté la toute première CAN en 1957 ?",a:["Ghana","Cameroun","Égypte","Éthiopie"],c:2,f:""},
  {q:"Quel joueur détient le record de buts en Coupe du Monde (16 buts) ?",a:["Pelé","Gerd Müller","Miroslav Klose","Ronaldo"],c:2,f:""},
  {q:"Quel gardien brésilien a remporté la Coupe du Monde en 2002 ?",a:["Dida","Marcos","Rogério Ceni","Taffarel"],c:1,f:""},
  {q:"Quel stade est surnommé « Le Théâtre des Rêves » ?",a:["Anfield","Camp Nou","Old Trafford","Santiago Bernabéu"],c:2,f:""},
  {q:"Quelle équipe féminine a remporté le plus de Coupes du Monde ?",a:["Allemagne","Brésil","Japon","États-Unis"],c:3,f:""},
  {q:"Quel joueur a remporté le premier Ballon d'Or en 1956 ?",a:["Alfredo Di Stéfano","Raymond Kopa","Stanley Matthews","Lev Yachine"],c:2,f:""},
  {q:"Quel défenseur allemand a remporté le Ballon d'Or en 1990 ?",a:["Jürgen Klinsmann","Karl-Heinz Rummenigge","Franz Beckenbauer","Lothar Matthäus"],c:3,f:""},
  {q:"Quel pays a organisé la Coupe du Monde 1998 ?",a:["Allemagne","Angleterre","France","Espagne"],c:2,f:""},
  {q:"Quel club a remporté la Copa Libertadores le plus de fois ?",a:["Boca Juniors","Santos","Peñarol","Club Atlético Independiente"],c:3,f:""},
  {q:"Quelle est la capacité approximative du stade Maracanã ?",a:["60 000","78 000","100 000","120 000"],c:1,f:""},
  {q:"Quel entraîneur italien a remporté la Ligue des Champions avec deux clubs différents (Milan et Real Madrid) ?",a:["Marcello Lippi","Fabio Capello","Carlo Ancelotti","Giovanni Trapattoni"],c:2,f:""},
  {q:"Quel joueur uruguayen a remporté le Ballon d'Or européen en 1961 ?",a:["Juan Alberto Schiaffino","Enzo Francescoli","Omar Sívori","Luis Suárez Miramontes"],c:2,f:""},
  {q:"Quel pays a remporté la Copa América 2015 ?",a:["Argentine","Brésil","Chili","Paraguay"],c:2,f:""},
  {q:"Quel gardien soviétique est le seul gardien à avoir remporté le Ballon d'Or ?",a:["Rinat Dasaev","Lev Yachine","Dino Zoff","Gordon Banks"],c:1,f:""},
  {q:"Quel est le nombre de CAN remportées par le Cameroun ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Quel joueur a été le plus jeune à marquer en finale de Coupe du Monde (17 ans en 1958) ?",a:["Ronaldo","Maradona","Pelé","Mbappé"],c:2,f:""},
  {q:"Quelle ville accueille le stade Signal Iduna Park ?",a:["Munich","Berlin","Dortmund","Hambourg"],c:2,f:""},
  {q:"Quel club espagnol est surnommé « Los Colchoneros » ?",a:["Real Madrid","FC Barcelone","Atlético Madrid","FC Séville"],c:2,f:""},
  {q:"Quel pays a accueilli la Coupe du Monde en 1994 ?",a:["Mexique","France","États-Unis","Japon"],c:2,f:""},
  {q:"Qui a été le premier joueur africain à remporter le Ballon d'Or (1995) ?",a:["Samuel Eto'o","Didier Drogba","George Weah","Abédi Pelé"],c:2,f:""},
  {q:"Quel club portugais a remporté la Ligue des Champions en 2004 ?",a:["Benfica","Sporting CP","Porto","Braga"],c:2,f:""},
  {q:"Quelle joueuse norvégienne a remporté le premier Ballon d'Or féminin officieux en 1995 ?",a:["Hege Riise","Ada Hegerberg","Birgit Prinz","Mia Hamm"],c:0,f:""},
  {q:"Quel pays organise la Coupe du Monde 2026 avec les États-Unis et le Mexique ?",a:["Colombie","Canada","Angleterre","Australie"],c:1,f:""},
  {q:"Quel entraîneur portugais a remporté la Ligue des Champions avec Porto en 2004 ?",a:["André Villas-Boas","Carlos Queiroz","José Mourinho","Jorge Jesus"],c:2,f:""},
  {q:"Quel joueur détient le record du plus grand nombre de matchs en Ligue des Champions ?",a:["Xavi Hernández","Cristiano Ronaldo","Iker Casillas","Ryan Giggs"],c:1,f:""},
  {q:"Quel est le surnom du Borussia Dortmund ?",a:["Die Fohlen","Die Borussen","Der BVB","Die Schwarzgelben"],c:2,f:""},
  {q:"Quel pays a perdu la finale de la Coupe du Monde en 1974 face à l'Allemagne ?",a:["Brésil","Argentine","Pays-Bas","Pologne"],c:2,f:""},
  {q:"Quel joueur a marqué lors de la fameuse « Nuit de Séville » (demi-finale Coupe du Monde 1982) ?",a:["Michel Platini","Alain Giresse","Patrick Battiston","Karl-Heinz Rummenigge"],c:3,f:""},
  {q:"Quel club a remporté la première édition de la Conference League en 2022 ?",a:["Feyenoord","AS Roma","Nice","Leicester City"],c:1,f:""},
  {q:"Quel joueur ivoirien est le meilleur buteur de l'histoire de Chelsea ?",a:["Salomon Kalou","Didier Drogba","Yaya Touré","Gervinho"],c:1,f:""},
  {q:"Quel pays d'Amérique du Sud a remporté le plus de Copa América ?",a:["Brésil","Argentine","Paraguay","Uruguay"],c:3,f:""},
  {q:"Quelle est la hauteur réglementaire des buts de football ?",a:["2,00 m","2,44 m","2,50 m","2,30 m"],c:1,f:""},
  {q:"Quel gardien a remporté le Mondial 2002 avec le Brésil et est connu pour sa coupe de cheveux atypique ?",a:["Marcos","Dida","Taffarel","Rogério Ceni"],c:0,f:""},
  {q:"Quel joueur est le plus jeune à avoir disputé une finale de Coupe du Monde (17 ans, 1982) ?",a:["Giuseppe Bergomi","Paolo Rossi","Marco Tardelli","Antonio Cabrini"],c:0,f:""},
  {q:"Quel entraîneur a remporté le plus de Ligues des Champions en tant que coach ?",a:["Zinédine Zidane","Bob Paisley","Carlo Ancelotti","Alex Ferguson"],c:2,f:""},
  {q:"Quel pays africain a été le premier à atteindre les quarts de finale d'une Coupe du Monde (1990) ?",a:["Nigeria","Sénégal","Ghana","Cameroun"],c:3,f:""},
  {q:"Quel joueur a inscrit le « but fantôme » controversé lors de la finale de la Coupe du Monde 1966 ?",a:["Bobby Charlton","Geoff Hurst","Gordon Banks","Martin Peters"],c:1,f:""},
  {q:"Quel stade italien est surnommé « La Bombonera d'Europe » ?",a:["San Siro","Stadio Olimpico","Stadio Diego Armando Maradona","Allianz Stadium"],c:2,f:""},
  {q:"En quelle année la Coupe du Monde féminine a-t-elle été créée ?",a:["1987","1989","1991","1995"],c:2,f:""},
  {q:"Quel joueur a remporté le Ballon d'Or 2024 ?",a:["Vinícius Júnior","Jude Bellingham","Rodri","Kylian Mbappé"],c:2,f:""},
  {q:"Quel club de Bundesliga est surnommé « Die Fohlen » (Les Poulains) ?",a:["Bayern Munich","Borussia Dortmund","Borussia Mönchengladbach","RB Leipzig"],c:2,f:""},
  {q:"Quelle équipe a remporté la tséance de tirs au but la plus longue en Coupe du Monde (2006, 1/8) ?",a:["Italie","Allemagne","Argentine","Ukraine"],c:3,f:""},
  {q:"Quel joueur sénégalais a marqué le but contre la France lors de la Coupe du Monde 2002 ?",a:["El Hadji Diouf","Henri Camara","Papa Bouba Diop","Khalilou Fadiga"],c:2,f:""},
  {q:"Quel club anglais est surnommé « The Toffees » ?",a:["West Ham","Aston Villa","Everton","Leicester City"],c:2,f:""},
  {q:"Quel pays a organisé les Coupes du Monde 1970 et 1986 ?",a:["Brésil","Argentine","Italie","Mexique"],c:3,f:""},
  {q:"Quel défenseur brésilien a été élu meilleur joueur de la Coupe du Monde 1994 ?",a:["Cafu","Aldair","Romário","Dunga"],c:2,f:""},
  {q:"Quel gardien danois est célèbre pour ses exploits à l'Euro 1992 ?",a:["Jan Sørensen","Peter Schmeichel","Thomas Sørensen","Kasper Schmeichel"],c:1,f:""},
  {q:"Quel joueur algérien a été élu meilleur joueur de la CAN 2019 ?",a:["Riyad Mahrez","Ismaël Bennacer","Baghdad Bounedjah","Youcef Atal"],c:1,f:""},
  {q:"Quelle formation tactique utilise un « libéro » ?",a:["4-4-2","3-5-2 avec libéro","4-3-3","4-2-3-1"],c:1,f:""},
  {q:"Quel est le record du monde de buts marqués en un seul match international (2001) ?",a:["21-0","25-0","31-0","36-0"],c:2,f:""},
  {q:"Quel club de Serie A est surnommé « I Partenopei » ?",a:["AS Roma","Lazio Rome","SSC Napoli","Fiorentina"],c:2,f:""},
  {q:"Quel pays a remporté la CAN 2019 ?",a:["Sénégal","Nigeria","Algérie","Tunisie"],c:2,f:""},
  {q:"Quel entraîneur allemand est surnommé « Kloppo » ?",a:["Thomas Tuchel","Julian Nagelsmann","Jürgen Klopp","Hansi Flick"],c:2,f:""},
  {q:"Quel joueur a marqué le penalty décisif de la finale de la Coupe du Monde 2006 pour l'Italie ?",a:["Andrea Pirlo","Alessandro Del Piero","Fabio Grosso","Francesco Totti"],c:2,f:""},
  {q:"Quel stade est le domicile du Borussia Dortmund ?",a:["Allianz Arena","Olympiastadion","Signal Iduna Park","Volksparkstadion"],c:2,f:""},
  {q:"Quel club a remporté la Liga espagnole le plus de fois ?",a:["FC Barcelone","Atlético Madrid","Athletic Bilbao","Real Madrid"],c:3,f:""},
  {q:"Quel joueur est le plus vieux à avoir marqué en Coupe du Monde (42 ans, 2022) ?",a:["Cristiano Ronaldo","Roger Milla","Essam El-Hadary","Dani Alves"],c:1,f:""},
  {q:"Quel pays a été le premier hôte asiatique d'une Coupe du Monde (co-organisation 2002) ?",a:["Chine","Corée du Sud et Japon","Inde","Qatar"],c:1,f:""},
  {q:"Quel joueur camerounais est le meilleur buteur de l'histoire du FC Barcelone en Liga africaine ?",a:["Roger Milla","Rigobert Song","Samuel Eto'o","Patrick Mboma"],c:2,f:""},
  {q:"Quel gardien italien a été titulaire lors de la victoire de l'Italie en Coupe du Monde 2006 ?",a:["Gianluigi Donnarumma","Angelo Peruzzi","Gianluigi Buffon","Francesco Toldo"],c:2,f:""},
  {q:"Quel joueur a inscrit quatre buts en un match de Coupe du Monde en 1994 contre le Cameroun ?",a:["Hristo Stoitchkov","Romário","Oleg Salenko","Roberto Baggio"],c:2,f:""},
  {q:"Quel stade accueille la finale de la Coupe d'Angleterre (FA Cup) ?",a:["Old Trafford","Anfield","Wembley","Emirates Stadium"],c:2,f:""},
  {q:"Quel pays a remporté la Coupe du Monde 1990 ?",a:["Argentine","Brésil","Italie","Allemagne de l'Ouest"],c:3,f:""},
  {q:"Quel défenseur français a marqué deux buts en demi-finale de la Coupe du Monde 1998 contre la Croatie ?",a:["Marcel Desailly","Laurent Blanc","Lilian Thuram","Bixente Lizarazu"],c:2,f:""},
  {q:"Quel pays a accueilli le premier match de football international en 1872 ?",a:["Angleterre","France","Écosse","Pays de Galles"],c:2,f:""},
  {q:"Quel joueur espagnol a remporté le Ballon d'Or en 1960 ?",a:["Alfredo Di Stéfano","Luis Suárez Miramontes","Francisco Gento","Amancio"],c:1,f:""},
  {q:"Quel club de Liga est basé à Séville et a remporté six Ligues Europa ?",a:["Real Betis","FC Séville","Cádiz","Villarreal"],c:1,f:""},
  {q:"Quel joueur est devenu le transfert le plus cher d'un défenseur en 2018 ?",a:["Raphaël Varane","Matthijs de Ligt","Virgil van Dijk","Harry Maguire"],c:2,f:""},
  {q:"Quelle équipe féminine a remporté la Coupe du Monde 2023 ?",a:["Angleterre","Espagne","Suède","Japon"],c:1,f:""},
  {q:"Quel joueur a réalisé le premier « hat-trick parfait » en Ligue des Champions (pied droit, pied gauche, tête) ?",a:["Cristiano Ronaldo","Luiz Adriano","Lionel Messi","Robert Lewandowski"],c:1,f:""},
  {q:"Quel pays a perdu trois finales de Copa América consécutives (2014-2016) avant de gagner en 2021 ?",a:["Brésil","Colombie","Argentine","Chili"],c:2,f:""},
  {q:"Quel entraîneur a gagné la Ligue des Champions avec Nottingham Forest (1979, 1980) ?",a:["Bill Shankly","Matt Busby","Brian Clough","Don Revie"],c:2,f:""},
  {q:"Quel joueur a été élu meilleur joueur de l'Euro 2000 ?",a:["Thierry Henry","Zinédine Zidane","Luís Figo","David Trezeguet"],c:1,f:""},
  {q:"Quel pays a remporté la CAN 2021 (jouée en 2022) ?",a:["Cameroun","Égypte","Sénégal","Algérie"],c:2,f:""},
  {q:"Quel stade est le domicile du club de River Plate à Buenos Aires ?",a:["La Bombonera","El Monumental","Estadio Centenario","Estadio Azteca"],c:1,f:""},
  {q:"Quel joueur français a inscrit le dernier penalty contre l'Italie en finale de l'Euro 2000 ?",a:["Zinédine Zidane","Sylvain Wiltord","David Trezeguet","Robert Pirès"],c:2,f:""},
  {q:"Quel gardien paraguayen est célèbre pour avoir arrêté des penalties en Coupe du Monde 2010 ?",a:["Justo Villar","José Luis Chilavert","Aldo Bobadilla","Antolín Alcaraz"],c:0,f:""},
  {q:"Combien de Ballons d'Or Cristiano Ronaldo a-t-il remportés ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Quel est le surnom des supporters de l'OM ?",a:["Les Gones","Les Ultras","Les Aiglons","Les Olympiens"],c:3,f:""},
  {q:"Quelle était la particularité du « WM » inventé par Herbert Chapman ?",a:["3 défenseurs et 2 attaquants","Formation en W en attaque et M en défense","5 milieux de terrain","Tous les joueurs défendent"],c:1,f:""},
  {q:"Quel pays a remporté la Coupe du Monde 1954 en battant la Hongrie en finale ?",a:["Brésil","Uruguay","Allemagne de l'Ouest","Angleterre"],c:2,f:""},
  {q:"Quel joueur nigérian a remporté l'or olympique en football en 1996 ?",a:["Jay-Jay Okocha","Nwankwo Kanu","Taribo West","Daniel Amokachi"],c:1,f:""},
  {q:"Quel club a été le premier à remporter la Ligue des Champions en étant invaincu toute la compétition (2024) ?",a:["Manchester City","Bayern Munich","Real Madrid","Bayer Leverkusen"],c:2,f:""},
  {q:"Quel joueur a inscrit le but le plus tardif en finale de Ligue des Champions (93e minute, 1999) ?",a:["Teddy Sheringham","David Beckham","Ole Gunnar Solskjær","Andy Cole"],c:2,f:""},
];
