/* ════════════════════════════════════════
   questions/football.js — Football — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.football = [
  {q:"Quel pays a remporté la Coupe du Monde 2018 ?",a:["Brésil","Croatie","France","Allemagne"],c:2,f:""},
  {q:"Combien de joueurs composent une équipe de football sur le terrain ?",a:["9","10","11","12"],c:2,f:""},
  {q:"Quelle est la durée réglementaire d'un match de football ?",a:["80 minutes","90 minutes","100 minutes","120 minutes"],c:1,f:""},
  {q:"Qui a marqué le but de la « Main de Dieu » en 1986 ?",a:["Pelé","Maradona","Zidane","Platini"],c:1,f:""},
  {q:"Quel club a remporté le plus de Ligues des Champions ?",a:["FC Barcelone","AC Milan","Real Madrid","Liverpool"],c:2,f:""},
  {q:"En quelle année la première Coupe du Monde a-t-elle eu lieu ?",a:["1926","1930","1934","1928"],c:1,f:""},
  {q:"Quel pays a remporté la première Coupe du Monde ?",a:["Brésil","Argentine","Uruguay","Italie"],c:2,f:""},
  {q:"Quel joueur détient le record de Ballons d'Or ?",a:["Cristiano Ronaldo","Zinédine Zidane","Lionel Messi","Michel Platini"],c:2,f:""},
  {q:"Quel est le surnom de l'équipe de France ?",a:["Les Bleus","Les Rouges","Les Tricolores","Les Coqs"],c:0,f:""},
  {q:"Que signifie un carton rouge ?",a:["Avertissement","Expulsion","Remplacement","Penalty"],c:1,f:""},
  {q:"Quel joueur français a mis un coup de tête en finale de la Coupe du Monde 2006 ?",a:["Thierry Henry","Patrick Vieira","Zinédine Zidane","David Trezeguet"],c:2,f:""},
  {q:"Combien d'étoiles figurent sur le maillot du Brésil ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Quel pays a remporté le plus de Coupes du Monde ?",a:["Allemagne","Argentine","Italie","Brésil"],c:3,f:""},
  {q:"Quel club anglais est surnommé « The Red Devils » ?",a:["Liverpool","Arsenal","Manchester United","Chelsea"],c:2,f:""},
  {q:"Quel stade accueille les matchs du FC Barcelone ?",a:["Santiago Bernabéu","Camp Nou","San Siro","Anfield"],c:1,f:""},
  {q:"Qui est le meilleur buteur de l'histoire de la Ligue des Champions ?",a:["Lionel Messi","Raúl","Cristiano Ronaldo","Robert Lewandowski"],c:2,f:""},
  {q:"Quel pays a organisé la Coupe du Monde 2022 ?",a:["Russie","Arabie Saoudite","Qatar","Émirats arabes unis"],c:2,f:""},
  {q:"Quel joueur est surnommé « CR7 » ?",a:["Carlos Roa","Cristiano Ronaldo","Clarence Rankin","Cafu Roberto"],c:1,f:""},
  {q:"Quelle équipe a remporté la Coupe du Monde 2022 ?",a:["France","Brésil","Croatie","Argentine"],c:3,f:""},
  {q:"Combien de remplacements sont autorisés en match officiel depuis 2020 ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Quel gardien italien a remporté le Ballon d'Or en 2006 ?",a:["Gianluigi Buffon","Fabien Barthez","Fabio Cannavaro","Paolo Maldini"],c:2,f:""},
  {q:"Quel club français a atteint la finale de la Ligue des Champions en 2020 ?",a:["Olympique de Marseille","AS Monaco","Paris Saint-Germain","Olympique Lyonnais"],c:2,f:""},
  {q:"Quelle est la distance d'un penalty ?",a:["9,15 mètres","11 mètres","12 mètres","10 mètres"],c:1,f:""},
  {q:"Quel pays a remporté l'Euro 2016 ?",a:["France","Allemagne","Portugal","Espagne"],c:2,f:""},
  {q:"Qui est le meilleur buteur de l'histoire de l'équipe de France ?",a:["Zinédine Zidane","Michel Platini","Thierry Henry","Olivier Giroud"],c:3,f:""},
  {q:"Quel club est surnommé « Les Reds » ?",a:["Manchester United","Arsenal","Liverpool","Southampton"],c:2,f:""},
  {q:"En quelle année Zinédine Zidane a-t-il remporté la Coupe du Monde en tant que joueur ?",a:["1994","1998","2002","2006"],c:1,f:""},
  {q:"Quel joueur brésilien est surnommé « O Rei » (Le Roi) ?",a:["Ronaldo","Ronaldinho","Pelé","Neymar"],c:2,f:""},
  {q:"Combien de fois l'Italie a-t-elle remporté la Coupe du Monde ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quel est le plus grand stade de football au monde ?",a:["Wembley","Maracanã","Stade de France","Rungrado May Day"],c:3,f:""},
  {q:"Quel joueur a inscrit un triplé en finale de la Coupe du Monde 2022 ?",a:["Lionel Messi","Kylian Mbappé","Julian Álvarez","Antoine Griezmann"],c:1,f:""},
  {q:"Quel club allemand a remporté la Ligue des Champions en 2013 ?",a:["Bayer Leverkusen","Borussia Dortmund","Bayern Munich","Schalke 04"],c:2,f:""},
  {q:"Quelle règle a été introduite pour la première fois lors de la Coupe du Monde 1970 ?",a:["Le carton rouge","Les remplacements","Le hors-jeu","Le carton jaune"],c:3,f:""},
  {q:"Quel pays africain a atteint les quarts de finale de la Coupe du Monde 2010 ?",a:["Nigeria","Côte d'Ivoire","Ghana","Cameroun"],c:2,f:""},
  {q:"Quel joueur a remporté le Ballon d'Or 2023 ?",a:["Erling Haaland","Kylian Mbappé","Lionel Messi","Vinícius Júnior"],c:2,f:""},
  {q:"Quel est le surnom de l'équipe du Brésil ?",a:["La Celeste","A Seleção","Die Mannschaft","Les Cafeteros"],c:1,f:""},
  {q:"Quel entraîneur a remporté trois Ligues des Champions avec le Real Madrid ?",a:["José Mourinho","Carlo Ancelotti","Zinédine Zidane","Vicente Del Bosque"],c:2,f:""},
  {q:"Quel club italien joue au stade San Siro avec l'AC Milan ?",a:["Juventus","AS Roma","Inter Milan","SSC Napoli"],c:2,f:""},
  {q:"Quel joueur a inscrit le but « Gol del Siglo » (But du siècle) en 1986 ?",a:["Pelé","Zinédine Zidane","Diego Maradona","Lothar Matthäus"],c:2,f:""},
  {q:"Quel pays a remporté le premier Euro en 1960 ?",a:["Allemagne","France","Union soviétique","Espagne"],c:2,f:""},
  {q:"Combien de titres de champion de France le PSG a-t-il remportés avant 2025 ?",a:["8","10","12","7"],c:2,f:""},
  {q:"Quelle compétition européenne est réservée aux clubs non qualifiés pour la Ligue des Champions ?",a:["Conference League","Ligue Europa","Supercoupe","Coupe Intertoto"],c:1,f:""},
  {q:"Quel gardien espagnol est célèbre pour ses arrêts avec le Real Madrid et l'Espagne ?",a:["Víctor Valdés","David de Gea","Iker Casillas","Pepe Reina"],c:2,f:""},
  {q:"Quel club anglais a remporté la Premier League de manière invincible en 2004 ?",a:["Chelsea","Manchester United","Arsenal","Liverpool"],c:2,f:""},
  {q:"Quel joueur est le meilleur buteur de l'histoire de la Liga ?",a:["Cristiano Ronaldo","Raúl","Lionel Messi","Telmo Zarra"],c:2,f:""},
  {q:"Quel pays a remporté la Coupe du Monde 2014 ?",a:["Brésil","Argentine","Pays-Bas","Allemagne"],c:3,f:""},
  {q:"Quelle est la sanction pour une faute de main volontaire dans la surface ?",a:["Coup franc","Corner","Penalty","Carton jaune uniquement"],c:2,f:""},
  {q:"Quel joueur français a remporté la Premier League avec Leicester en 2016 ?",a:["Riyad Mahrez","N'Golo Kanté","Anthony Martial","Moussa Sissoko"],c:1,f:""},
  {q:"Quel est le surnom de la Juventus de Turin ?",a:["La Vecchia Signora","I Rossoneri","I Nerazzurri","Gli Azzurri"],c:0,f:""},
  {q:"Quelle équipe nationale est surnommée « La Roja » ?",a:["Portugal","Mexique","Espagne","Chili"],c:2,f:""},
  {q:"En quelle année le VAR a-t-il été utilisé pour la première fois en Coupe du Monde ?",a:["2014","2016","2018","2020"],c:2,f:""},
  {q:"Quel joueur a marqué le plus de buts en une année civile (91 buts en 2012) ?",a:["Cristiano Ronaldo","Robert Lewandowski","Lionel Messi","Gerd Müller"],c:2,f:""},
  {q:"Quel club a remporté la première édition de la Ligue des Champions (1956) ?",a:["AC Milan","Benfica","Real Madrid","FC Barcelone"],c:2,f:""},
  {q:"Quel pays a accueilli la Coupe du Monde 2006 ?",a:["France","Japon","Afrique du Sud","Allemagne"],c:3,f:""},
  {q:"Quel défenseur italien a remporté le Ballon d'Or en 2006 ?",a:["Paolo Maldini","Alessandro Nesta","Fabio Cannavaro","Lilian Thuram"],c:2,f:""},
  {q:"Quel joueur détient le record de sélections en équipe de France (145 matchs) ?",a:["Thierry Henry","Hugo Lloris","Lilian Thuram","Marcel Desailly"],c:1,f:""},
  {q:"Quel est le nom du trophée remis au meilleur buteur de la Coupe du Monde ?",a:["Ballon d'Or","Soulier d'Or","Gant d'Or","FIFA Fair Play"],c:1,f:""},
  {q:"Quel club espagnol est surnommé « Les Merengues » ?",a:["FC Barcelone","Atlético Madrid","Real Madrid","Valence CF"],c:2,f:""},
  {q:"Quel joueur a marqué le but en or en finale de l'Euro 2000 pour la France ?",a:["Zinédine Zidane","Thierry Henry","David Trezeguet","Sylvain Wiltord"],c:2,f:""},
  {q:"Quelle équipe a réalisé le « sextuplé » en 2009 ?",a:["Real Madrid","Manchester United","FC Barcelone","Bayern Munich"],c:2,f:""},
  {q:"Quel est le nombre maximum de joueurs sur une feuille de match en Ligue 1 ?",a:["16","18","20","23"],c:2,f:""},
  {q:"Quel pays a remporté la Copa América 2021 ?",a:["Brésil","Colombie","Argentine","Uruguay"],c:2,f:""},
  {q:"Quel entraîneur est surnommé « The Special One » ?",a:["Pep Guardiola","Carlo Ancelotti","José Mourinho","Jürgen Klopp"],c:2,f:""},
  {q:"Quel joueur brésilien a remporté le Ballon d'Or en 2007 ?",a:["Ronaldinho","Kaká","Ronaldo","Rivaldo"],c:1,f:""},
  {q:"Quel est le score le plus large en Coupe du Monde (2001, Australie vs Samoa américaines) ?",a:["15-0","21-0","31-0","25-0"],c:2,f:""},
  {q:"Quel club français a remporté la Ligue des Champions en 1993 ?",a:["Paris Saint-Germain","AS Monaco","Olympique de Marseille","Olympique Lyonnais"],c:2,f:""},
  {q:"Quelle position occupe le numéro 9 traditionnellement ?",a:["Gardien","Défenseur central","Milieu de terrain","Avant-centre"],c:3,f:""},
  {q:"Combien de minutes dure la mi-temps ?",a:["10 minutes","15 minutes","20 minutes","25 minutes"],c:1,f:""},
  {q:"Quel joueur nigérian a remporté le Ballon d'Or africain cinq fois ?",a:["Jay-Jay Okocha","Nwankwo Kanu","Samuel Eto'o","Didier Drogba"],c:2,f:""},
  {q:"Quel est le diamètre du rond central sur un terrain de football ?",a:["7,32 mètres","9,15 mètres","18,32 mètres","12 mètres"],c:1,f:""},
  {q:"Quelle sélection nationale est surnommée « Die Mannschaft » ?",a:["Autriche","Suisse","Pays-Bas","Allemagne"],c:3,f:""},
  {q:"Quel joueur a inscrit deux buts en finale de la Coupe du Monde 1998 ?",a:["Thierry Henry","Emmanuel Petit","Zinédine Zidane","Lilian Thuram"],c:2,f:""},
  {q:"Quel club anglais est surnommé « The Gunners » ?",a:["Chelsea","Tottenham","Arsenal","Everton"],c:2,f:""},
  {q:"Quel pays a remporté l'Euro 2020 (joué en 2021) ?",a:["Angleterre","Espagne","Italie","Danemark"],c:2,f:""},
  {q:"Quel gardien a remporté le trophée Yachine en 2023 ?",a:["Thibaut Courtois","Emiliano Martínez","Alisson Becker","Mike Maignan"],c:1,f:""},
  {q:"Quel joueur est le meilleur buteur de l'histoire de la Premier League ?",a:["Wayne Rooney","Thierry Henry","Alan Shearer","Andrew Cole"],c:2,f:""},
  {q:"Quel pays organise traditionnellement le « Calcio Storico » ?",a:["Espagne","Portugal","Italie","Grèce"],c:2,f:""},
  {q:"Quelle est la largeur réglementaire des buts de football ?",a:["6,50 m","7,32 m","8,00 m","7,00 m"],c:1,f:""},
  {q:"Quel joueur a été le premier à atteindre 100 buts en Ligue des Champions ?",a:["Lionel Messi","Raúl","Cristiano Ronaldo","Karim Benzema"],c:2,f:""},
  {q:"Quel pays a remporté la Coupe du Monde féminine en 2019 ?",a:["Allemagne","Pays-Bas","France","États-Unis"],c:3,f:""},
  {q:"Quel joueur argentin est surnommé « El Pibe de Oro » ?",a:["Lionel Messi","Diego Maradona","Gabriel Batistuta","Hernán Crespo"],c:1,f:""},
  {q:"Combien de coupes du monde Pelé a-t-il remportées ?",a:["1","2","3","4"],c:2,f:""},
  {q:"Quel club a remporté la Ligue des Champions en 2023 ?",a:["Inter Milan","Real Madrid","Manchester City","AC Milan"],c:2,f:""},
  {q:"Quelle est la position du numéro 1 dans une équipe ?",a:["Attaquant","Milieu défensif","Défenseur","Gardien de but"],c:3,f:""},
  {q:"Quel joueur français a remporté le Ballon d'Or en 1991 ?",a:["Zinédine Zidane","Michel Platini","Jean-Pierre Papin","Éric Cantona"],c:2,f:""},
  {q:"Quel pays a accueilli la Coupe du Monde 2010 ?",a:["Brésil","Allemagne","Afrique du Sud","Russie"],c:2,f:""},
  {q:"Quel joueur a inscrit le but victorieux de la finale de la Coupe du Monde 2010 ?",a:["David Villa","Xavi Hernández","Andrés Iniesta","Fernando Torres"],c:2,f:""},
  {q:"Quel est le nombre de joueurs minimum pour commencer un match ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Quel club turc a remporté la Coupe UEFA en 2000 ?",a:["Fenerbahçe","Beşiktaş","Trabzonspor","Galatasaray"],c:3,f:""},
  {q:"Quel joueur est surnommé « La Pulga » (La Puce) ?",a:["Neymar","Cristiano Ronaldo","Lionel Messi","Kylian Mbappé"],c:2,f:""},
  {q:"Quelle équipe nationale a remporté la Coupe d'Afrique des Nations le plus de fois ?",a:["Nigeria","Cameroun","Ghana","Égypte"],c:3,f:""},
  {q:"Quel joueur a marqué le but le plus rapide en Coupe du Monde (11 secondes) ?",a:["Miroslav Klose","Hakan Şükür","Ronaldo","Clint Dempsey"],c:1,f:""},
  {q:"Quel est le nom du système de jeu 4-3-3 ?",a:["Catenaccio","Tiki-taka","Faux neuf","Aucun de ces noms"],c:3,f:""},
  {q:"Quel joueur a remporté la Coupe du Monde en tant que joueur et entraîneur ?",a:["Zinédine Zidane","Franz Beckenbauer","Johan Cruyff","Mario Zagallo"],c:3,f:""},
  {q:"Quel est le surnom de l'équipe d'Argentine ?",a:["La Roja","La Albiceleste","La Celeste","La Verde"],c:1,f:""},
  {q:"Quel joueur français a été le meilleur buteur de la Coupe du Monde 2018 ?",a:["Antoine Griezmann","Kylian Mbappé","Olivier Giroud","Paul Pogba"],c:1,f:""},
  {q:"Combien de Ligues des Champions le Liverpool FC a-t-il remportées ?",a:["4","5","6","7"],c:2,f:""},
  {q:"Quel pays a remporté la Coupe du Monde 1966 ?",a:["Brésil","Allemagne de l'Ouest","Angleterre","Portugal"],c:2,f:""},
  {q:"Quel joueur hollandais est surnommé « Le Cygne d'Utrecht » ?",a:["Ruud Gullit","Johan Cruyff","Marco van Basten","Dennis Bergkamp"],c:2,f:""},
  {q:"Quel club a réalisé le triplé (championnat, coupe, Ligue des Champions) en 1999 ?",a:["Bayern Munich","FC Barcelone","Manchester United","Ajax Amsterdam"],c:2,f:""},
];
