/* ════════════════════════════════════════
   questions/francaise.js — Culture Française — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.francaise = [
  {q:"Quelle est la capitale de la France ?",a:["Lyon","Marseille","Paris","Bordeaux"],c:2,f:""},
  {q:"Quel monument parisien a été construit pour l'Exposition universelle de 1889 ?",a:["La Tour Eiffel","L'Arc de Triomphe","Le Sacré-Cœur","Le Panthéon"],c:0,f:""},
  {q:"Quel fleuve traverse Paris ?",a:["La Loire","Le Rhône","La Garonne","La Seine"],c:3,f:""},
  {q:"Qui a écrit 'Les Misérables' ?",a:["Émile Zola","Victor Hugo","Gustave Flaubert","Alexandre Dumas"],c:1,f:""},
  {q:"Quel plat français est préparé avec des escargots ?",a:["Bouillabaisse","Escargots de Bourgogne","Ratatouille","Pot-au-feu"],c:1,f:""},
  {q:"En quelle année a eu lieu la Révolution française ?",a:["1776","1815","1789","1804"],c:2,f:""},
  {q:"Quel fromage français est surnommé 'le roi des fromages' ?",a:["Le Comté","Le Roquefort","Le Camembert","Le Brie de Meaux"],c:3,f:""},
  {q:"Qui était surnommé 'le Roi-Soleil' ?",a:["Louis XIV","Louis XVI","François Ier","Napoléon"],c:0,f:""},
  {q:"Dans quelle région française produit-on le champagne ?",a:["Bourgogne","Alsace","Champagne","Loire"],c:2,f:""},
  {q:"Quel est le plus long fleuve de France ?",a:["La Seine","Le Rhône","La Garonne","La Loire"],c:3,f:""},
  {q:"Qui a peint 'La Liberté guidant le peuple' ?",a:["Claude Monet","Eugène Delacroix","Auguste Renoir","Jacques-Louis David"],c:1,f:""},
  {q:"Quelle est la devise de la République française ?",a:["Honneur et Patrie","Liberté, Égalité, Fraternité","Dieu et mon Droit","Union fait la Force"],c:1,f:""},
  {q:"Quel est le nombre de régions métropolitaines en France depuis 2016 ?",a:["18","13","22","15"],c:1,f:""},
  {q:"Quel acteur français est célèbre pour le film 'Le Grand Bleu' ?",a:["Gérard Depardieu","Jean Reno","Jean-Marc Barr","Alain Delon"],c:2,f:""},
  {q:"Quelle ville française est connue pour son festival de cinéma ?",a:["Nice","Cannes","Marseille","Avignon"],c:1,f:""},
  {q:"Quel est le symbole national de la France ?",a:["L'aigle","Le coq","Le lion","L'ours"],c:1,f:""},
  {q:"Quel écrivain a créé le personnage d'Arsène Lupin ?",a:["Gaston Leroux","Maurice Leblanc","Jules Verne","Georges Simenon"],c:1,f:""},
  {q:"Dans quel département se trouve le Mont-Saint-Michel ?",a:["Calvados","Côtes-d'Armor","Manche","Ille-et-Vilaine"],c:2,f:""},
  {q:"Quelle chanteuse française est connue sous le surnom 'La Môme' ?",a:["Dalida","Édith Piaf","Mireille Mathieu","Barbara"],c:1,f:""},
  {q:"Quel roi de France a été guillotiné en 1793 ?",a:["Louis XIV","Louis XV","Louis XVI","Charles X"],c:2,f:""},
  {q:"Quelle spécialité culinaire est originaire de Marseille ?",a:["La choucroute","La bouillabaisse","Le cassoulet","La tartiflette"],c:1,f:""},
  {q:"Quel est le plus haut sommet de France ?",a:["Le Mont Ventoux","Le Pic du Midi","Le Mont Blanc","L'Aiguille du Midi"],c:2,f:""},
  {q:"Que signifie l'expression 'avoir le cafard' ?",a:["Avoir faim","Être en colère","Être triste","Avoir peur"],c:2,f:""},
  {q:"Qui a fondé la Cinquième République française ?",a:["Georges Pompidou","Charles de Gaulle","François Mitterrand","René Coty"],c:1,f:""},
  {q:"Quel peintre français est le chef de file de l'impressionnisme ?",a:["Paul Cézanne","Claude Monet","Edgar Degas","Pierre-Auguste Renoir"],c:1,f:""},
  {q:"Quelle est la plus grande île française de Méditerranée ?",a:["La Réunion","La Martinique","La Guadeloupe","La Corse"],c:3,f:""},
  {q:"Quel est le nom du palais où siège le président de la République ?",a:["Le Louvre","L'Élysée","Matignon","Versailles"],c:1,f:""},
  {q:"En quelle année la France a-t-elle remporté sa première Coupe du monde de football ?",a:["1994","2002","1998","2006"],c:2,f:""},
  {q:"Quel auteur a écrit 'Le Petit Prince' ?",a:["Albert Camus","Antoine de Saint-Exupéry","Jean-Paul Sartre","André Malraux"],c:1,f:""},
  {q:"Quelle région française est célèbre pour ses crêpes ?",a:["La Normandie","La Bretagne","La Picardie","Le Poitou"],c:1,f:""},
  {q:"Quel monument parisien abrite la Joconde ?",a:["Le Musée d'Orsay","Le Centre Pompidou","Le Louvre","Le Grand Palais"],c:2,f:""},
  {q:"Quel général français a dirigé la France Libre pendant la Seconde Guerre mondiale ?",a:["Philippe Pétain","Jean Moulin","Charles de Gaulle","Leclerc"],c:2,f:""},
  {q:"Quelle ville est la préfecture du département du Rhône ?",a:["Saint-Étienne","Grenoble","Lyon","Villeurbanne"],c:2,f:""},
  {q:"Que signifie l'expression 'poser un lapin' ?",a:["Offrir un cadeau","Ne pas venir à un rendez-vous","Faire une surprise","Dire un mensonge"],c:1,f:""},
  {q:"Quel compositeur français a écrit 'Boléro' ?",a:["Claude Debussy","Camille Saint-Saëns","Maurice Ravel","Hector Berlioz"],c:2,f:""},
  {q:"Combien de départements compte la France métropolitaine ?",a:["96","100","101","89"],c:0,f:""},
  {q:"Quel est le plat traditionnel du Nouvel An en France ?",a:["La dinde aux marrons","Le foie gras","La galette des rois","La bûche de Noël"],c:1,f:""},
  {q:"Quelle est la monnaie utilisée en France ?",a:["Le franc","Le dollar","L'euro","La livre"],c:2,f:""},
  {q:"Quel réalisateur français a dirigé 'Amélie Poulain' ?",a:["Luc Besson","Jean-Pierre Jeunet","François Truffaut","Claude Chabrol"],c:1,f:""},
  {q:"Quel scientifique français a découvert la radioactivité ?",a:["Louis Pasteur","Pierre Curie","Antoine Lavoisier","Henri Becquerel"],c:3,f:""},
  {q:"Dans quelle ville se trouve le Pont du Gard ?",a:["Nîmes","Vers-Pont-du-Gard","Avignon","Arles"],c:1,f:""},
  {q:"Quel est le nom de l'hymne national français ?",a:["La Brabançonne","La Marseillaise","Le Chant du Départ","God Save the Queen"],c:1,f:""},
  {q:"Quel philosophe français a dit 'Je pense, donc je suis' ?",a:["Voltaire","Jean-Jacques Rousseau","René Descartes","Blaise Pascal"],c:2,f:""},
  {q:"Quelle fête française se célèbre le 14 juillet ?",a:["La Fête du Travail","L'Armistice","La Fête nationale","La Toussaint"],c:2,f:""},
  {q:"Quel vin est produit dans la région de Bordeaux ?",a:["Le Riesling","Le Muscadet","Le Saint-Émilion","Le Chablis"],c:2,f:""},
  {q:"Quelle actrice française a remporté un Oscar pour 'La Vie en Rose' ?",a:["Juliette Binoche","Isabelle Huppert","Marion Cotillard","Catherine Deneuve"],c:2,f:""},
  {q:"Quel est le nom du train à grande vitesse français ?",a:["Eurostar","Thalys","TGV","ICE"],c:2,f:""},
  {q:"Quel écrivain français a reçu le prix Nobel de littérature en 1957 ?",a:["Jean-Paul Sartre","André Gide","Albert Camus","François Mauriac"],c:2,f:""},
  {q:"Quelle chaîne de montagnes sépare la France de l'Espagne ?",a:["Les Alpes","Le Jura","Le Massif central","Les Pyrénées"],c:3,f:""},
  {q:"Quel est le dessert traditionnel de l'Épiphanie en France ?",a:["La crêpe","La galette des rois","La bûche de Noël","Le Paris-Brest"],c:1,f:""},
  {q:"Quelle bataille napoléonienne de 1805 est considérée comme son chef-d'œuvre tactique ?",a:["Waterloo","Iéna","Austerlitz","Marengo"],c:2,f:""},
  {q:"Quel couturier français a créé le 'New Look' en 1947 ?",a:["Coco Chanel","Yves Saint Laurent","Christian Dior","Pierre Cardin"],c:2,f:""},
  {q:"Dans quelle ville française se trouve la basilique de Fourvière ?",a:["Marseille","Paris","Lyon","Toulouse"],c:2,f:""},
  {q:"Que signifie l'expression 'avoir la pêche' ?",a:["Avoir sommeil","Être en forme","Avoir faim","Être malade"],c:1,f:""},
  {q:"Quel président français a aboli la peine de mort en 1981 ?",a:["Valéry Giscard d'Estaing","Jacques Chirac","François Mitterrand","Georges Pompidou"],c:2,f:""},
  {q:"Quel est le plus grand parc d'attractions de France ?",a:["Le Puy du Fou","Astérix","Disneyland Paris","Le Futuroscope"],c:2,f:""},
  {q:"Quel fromage est fabriqué dans des caves naturelles à Roquefort-sur-Soulzon ?",a:["Le Bleu d'Auvergne","Le Roquefort","Le Munster","Le Reblochon"],c:1,f:""},
  {q:"Quel explorateur français a découvert le Canada ?",a:["Samuel de Champlain","Jacques Cartier","La Pérouse","Cavelier de La Salle"],c:1,f:""},
  {q:"Quelle est la spécialité culinaire de la région Alsace ?",a:["Le cassoulet","La choucroute","La ratatouille","Le gratin dauphinois"],c:1,f:""},
  {q:"Quel écrivain français a créé le personnage du commissaire Maigret ?",a:["Maurice Leblanc","Fred Vargas","Georges Simenon","Émile Gaboriau"],c:2,f:""},
  {q:"Quelle mer borde la Côte d'Azur ?",a:["L'océan Atlantique","La Manche","La mer du Nord","La mer Méditerranée"],c:3,f:""},
  {q:"Quel homme politique français est associé à la construction européenne ?",a:["Charles de Gaulle","Robert Schuman","Léon Blum","Georges Clemenceau"],c:1,f:""},
  {q:"Quel est le numéro du département de Paris ?",a:["69","75","13","33"],c:1,f:""},
  {q:"Quelle cathédrale gothique se trouve à Reims ?",a:["Notre-Dame de Paris","Notre-Dame de Reims","Saint-Denis","Chartres"],c:1,f:""},
  {q:"Quel cinéaste français est associé à la Nouvelle Vague ?",a:["Luc Besson","Jacques Tati","François Truffaut","Marcel Carné"],c:2,f:""},
  {q:"Que signifie l'expression 'tomber dans les pommes' ?",a:["Avoir faim","S'évanouir","Tomber amoureux","Se tromper"],c:1,f:""},
  {q:"Quel pont célèbre se trouve en Avignon ?",a:["Le Pont Neuf","Le Pont des Arts","Le Pont Saint-Bénézet","Le Pont Alexandre III"],c:2,f:""},
  {q:"Quel écrivain a dit 'L'enfer, c'est les autres' ?",a:["Albert Camus","Simone de Beauvoir","Jean-Paul Sartre","André Malraux"],c:2,f:""},
  {q:"Quelle région française est célèbre pour le calisson ?",a:["La Bretagne","La Provence","La Normandie","La Lorraine"],c:1,f:""},
  {q:"Quel roi de France a construit le château de Versailles ?",a:["François Ier","Henri IV","Louis XIII","Louis XIV"],c:3,f:""},
  {q:"Quelle ville française est surnommée 'la Ville Rose' ?",a:["Montpellier","Bordeaux","Toulouse","Lyon"],c:2,f:""},
  {q:"Qui a inventé le vaccin contre la rage ?",a:["Claude Bernard","Louis Pasteur","René Laennec","Ambroise Paré"],c:1,f:""},
  {q:"Quel département français porte le numéro 13 ?",a:["Le Rhône","La Gironde","Les Bouches-du-Rhône","L'Hérault"],c:2,f:""},
  {q:"Quelle est la plus ancienne université de France ?",a:["La Sorbonne","L'Université de Montpellier","L'Université de Toulouse","L'Université de Paris"],c:3,f:""},
  {q:"Quel auteur français a écrit 'Germinal' ?",a:["Victor Hugo","Honoré de Balzac","Émile Zola","Guy de Maupassant"],c:2,f:""},
  {q:"Quel est le plat traditionnel du sud-ouest associé au canard ?",a:["La blanquette","Le confit de canard","La quiche lorraine","Le bœuf bourguignon"],c:1,f:""},
  {q:"Quel peintre post-impressionniste a vécu à Tahiti ?",a:["Paul Cézanne","Henri Matisse","Paul Gauguin","Georges Seurat"],c:2,f:""},
  {q:"Que signifie l'expression 'coûter les yeux de la tête' ?",a:["Être gratuit","Être très cher","Être beau","Être rare"],c:1,f:""},
  {q:"Quel est le nom du résistant français qui a unifié les mouvements de Résistance ?",a:["Pierre Brossolette","Charles de Gaulle","Jean Moulin","Lucie Aubrac"],c:2,f:""},
  {q:"Quelle ville française accueille le Festival d'Avignon ?",a:["Aix-en-Provence","Orange","Avignon","Arles"],c:2,f:""},
  {q:"Quel chanteur français a interprété 'Que je t'aime' ?",a:["Charles Aznavour","Jacques Brel","Serge Gainsbourg","Johnny Hallyday"],c:3,f:""},
  {q:"Combien d'habitants compte approximativement la France métropolitaine ?",a:["50 millions","68 millions","80 millions","45 millions"],c:1,f:""},
  {q:"Quel est le nom de la résidence officielle du Premier ministre ?",a:["L'Élysée","Matignon","Le Quai d'Orsay","Le Palais Bourbon"],c:1,f:""},
  {q:"Quel architecte a conçu la pyramide du Louvre ?",a:["Jean Nouvel","Le Corbusier","Ieoh Ming Pei","Renzo Piano"],c:2,f:""},
  {q:"Dans quelle région se trouve le château de Chambord ?",a:["Île-de-France","Centre-Val de Loire","Pays de la Loire","Nouvelle-Aquitaine"],c:1,f:""},
  {q:"Quel est le fromage emblématique de la Savoie utilisé dans la tartiflette ?",a:["Le Beaufort","Le Reblochon","L'Abondance","Le Comté"],c:1,f:""},
  {q:"Que signifie l'expression 'mettre son grain de sel' ?",a:["Cuisiner","Se mêler de ce qui ne nous regarde pas","Ajouter du piquant","Être discret"],c:1,f:""},
  {q:"Quel est le volcan le plus connu du Massif central ?",a:["Le Puy de Dôme","Le Mont Dore","Le Cantal","Le Plomb du Cantal"],c:0,f:""},
  {q:"Quel écrivain français a écrit 'Les Fleurs du mal' ?",a:["Arthur Rimbaud","Paul Verlaine","Charles Baudelaire","Stéphane Mallarmé"],c:2,f:""},
  {q:"Quelle est la spécialité de la ville de Dijon ?",a:["Le nougat","La moutarde","Le calisson","La navette"],c:1,f:""},
  {q:"Quel personnage de bande dessinée française vit dans un village gaulois ?",a:["Tintin","Lucky Luke","Astérix","Gaston Lagaffe"],c:2,f:""},
  {q:"En quelle année les femmes ont-elles obtenu le droit de vote en France ?",a:["1936","1944","1952","1920"],c:1,f:""},
  {q:"Quel est le nom de la place principale de la ville de Lyon ?",a:["Place de la Concorde","Place Bellecour","Place du Capitole","Place de la Bourse"],c:1,f:""},
  {q:"Quel cinéaste français a réalisé 'Le Cinquième Élément' ?",a:["Jean-Pierre Jeunet","Luc Besson","Mathieu Kassovitz","Jacques Audiard"],c:1,f:""},
  {q:"Quelle bataille de 1916 est devenue un symbole de la Première Guerre mondiale ?",a:["La Somme","La Marne","Verdun","Les Dardanelles"],c:2,f:""},
  {q:"Quel est le fleuve qui traverse Bordeaux ?",a:["La Loire","La Seine","Le Rhône","La Garonne"],c:3,f:""},
  {q:"Quel pâtissier français a inventé le macaron moderne ?",a:["Gaston Lenôtre","Pierre Hermé","Antonin Carême","Auguste Escoffier"],c:1,f:""},
  {q:"Que signifie l'expression 'avoir un chat dans la gorge' ?",a:["Avoir faim","Être enroué","Avoir peur","Être muet"],c:1,f:""},
  {q:"Quel est le département le plus peuplé de France ?",a:["Les Bouches-du-Rhône","Paris","Le Rhône","Le Nord"],c:3,f:""},
  {q:"Quelle femme de lettres française a écrit 'Le Deuxième Sexe' ?",a:["Marguerite Duras","Simone de Beauvoir","Colette","Marguerite Yourcenar"],c:1,f:""},
  {q:"Quel est le sport le plus pratiqué en France ?",a:["Le rugby","Le tennis","Le football","Le cyclisme"],c:2,f:""},
];
