/* ════════════════════════════════════════
   questions/francaise.js — Culture Française — 200 questions
   ════════════════════════════════════════ */
QUESTIONS.francaise = [
  {q:"Quelle est la capitale de la France ?",a:["Lyon","Marseille","Paris","Bordeaux"],c:2,f:""},
  {q:"Quel monument parisien a été construit pour l'Exposition universelle de 1889 ?",a:["La Tour Eiffel","L'Arc de Triomphe","Le Sacré-Cœur","Le Panthéon"],c:0,f:""},
  {q:"Quel fleuve traverse Paris ?",a:["La Loire","Le Rhône","La Garonne","La Seine"],c:3,f:""},
  {q:"Qui a écrit 'Les Misérables' ?",a:["Émile Zola","Victor Hugo","Gustave Flaubert","Alexandre Dumas"],c:1,f:""},
  {q:"Quel plat français est préparé avec des escargots ?",a:["Bouillabaisse","Escargots de Bourgogne","Ratatouille","Pot-au-feu"],c:1,f:""},
  {q:"En quelle année a eu lieu la Révolution française ?",a:["1776","1815","1789","1804"],c:2,f:""},
  {q:"Quel fromage français est surnommé 'le roi des fromages' ?",a:["Le Comté","Le Roquefort","Le Camembert","Le Brie de Meaux"],c:3,f:""},
  {q:"Qui était surnommé 'le Roi-Soleil' ?",a:["Louis XIV","Louis XVI","François Ier","Napoléon"],c:0,f:""},
  {q:"Dans quelle région française produit-on le champagne ?",a:["Bourgogne","Alsace","Champagne","Loire"],c:2,f:""},
  {q:"Quel est le plus long fleuve de France ?",a:["La Seine","Le Rhône","La Garonne","La Loire"],c:3,f:""},
  {q:"Qui a peint 'La Liberté guidant le peuple' ?",a:["Claude Monet","Eugène Delacroix","Auguste Renoir","Jacques-Louis David"],c:1,f:""},
  {q:"Quelle est la devise de la République française ?",a:["Honneur et Patrie","Liberté, Égalité, Fraternité","Dieu et mon Droit","Union fait la Force"],c:1,f:""},
  {q:"Quel est le nombre de régions métropolitaines en France depuis 2016 ?",a:["18","13","22","15"],c:1,f:""},
  {q:"Quel acteur français est célèbre pour le film 'Le Grand Bleu' ?",a:["Gérard Depardieu","Jean Reno","Jean-Marc Barr","Alain Delon"],c:2,f:""},
  {q:"Quelle ville française est connue pour son festival de cinéma ?",a:["Nice","Cannes","Marseille","Avignon"],c:1,f:""},
  {q:"Quel est le symbole national de la France ?",a:["L'aigle","Le coq","Le lion","L'ours"],c:1,f:""},
  {q:"Quel écrivain a créé le personnage d'Arsène Lupin ?",a:["Gaston Leroux","Maurice Leblanc","Jules Verne","Georges Simenon"],c:1,f:""},
  {q:"Dans quel département se trouve le Mont-Saint-Michel ?",a:["Calvados","Côtes-d'Armor","Manche","Ille-et-Vilaine"],c:2,f:""},
  {q:"Quelle chanteuse française est connue sous le surnom 'La Môme' ?",a:["Dalida","Édith Piaf","Mireille Mathieu","Barbara"],c:1,f:""},
  {q:"Quel roi de France a été guillotiné en 1793 ?",a:["Louis XIV","Louis XV","Louis XVI","Charles X"],c:2,f:""},
  {q:"Quelle spécialité culinaire est originaire de Marseille ?",a:["La choucroute","La bouillabaisse","Le cassoulet","La tartiflette"],c:1,f:""},
  {q:"Quel est le plus haut sommet de France ?",a:["Le Mont Ventoux","Le Pic du Midi","Le Mont Blanc","L'Aiguille du Midi"],c:2,f:""},
  {q:"Que signifie l'expression 'avoir le cafard' ?",a:["Avoir faim","Être en colère","Être triste","Avoir peur"],c:2,f:""},
  {q:"Qui a fondé la Cinquième République française ?",a:["Georges Pompidou","Charles de Gaulle","François Mitterrand","René Coty"],c:1,f:""},
  {q:"Quel peintre français est le chef de file de l'impressionnisme ?",a:["Paul Cézanne","Claude Monet","Edgar Degas","Pierre-Auguste Renoir"],c:1,f:""},
  {q:"Quelle est la plus grande île française de Méditerranée ?",a:["La Réunion","La Martinique","La Guadeloupe","La Corse"],c:3,f:""},
  {q:"Quel est le nom du palais où siège le président de la République ?",a:["Le Louvre","L'Élysée","Matignon","Versailles"],c:1,f:""},
  {q:"En quelle année la France a-t-elle remporté sa première Coupe du monde de football ?",a:["1994","2002","1998","2006"],c:2,f:""},
  {q:"Quel auteur a écrit 'Le Petit Prince' ?",a:["Albert Camus","Antoine de Saint-Exupéry","Jean-Paul Sartre","André Malraux"],c:1,f:""},
  {q:"Quelle région française est célèbre pour ses crêpes ?",a:["La Normandie","La Bretagne","La Picardie","Le Poitou"],c:1,f:""},
  {q:"Quel monument parisien abrite la Joconde ?",a:["Le Musée d'Orsay","Le Centre Pompidou","Le Louvre","Le Grand Palais"],c:2,f:""},
  {q:"Quel général français a dirigé la France Libre pendant la Seconde Guerre mondiale ?",a:["Philippe Pétain","Jean Moulin","Charles de Gaulle","Leclerc"],c:2,f:""},
  {q:"Quelle ville est la préfecture du département du Rhône ?",a:["Saint-Étienne","Grenoble","Lyon","Villeurbanne"],c:2,f:""},
  {q:"Que signifie l'expression 'poser un lapin' ?",a:["Offrir un cadeau","Ne pas venir à un rendez-vous","Faire une surprise","Dire un mensonge"],c:1,f:""},
  {q:"Quel compositeur français a écrit 'Boléro' ?",a:["Claude Debussy","Camille Saint-Saëns","Maurice Ravel","Hector Berlioz"],c:2,f:""},
  {q:"Combien de départements compte la France métropolitaine ?",a:["96","100","101","89"],c:0,f:""},
  {q:"Quel est le plat traditionnel du Nouvel An en France ?",a:["La dinde aux marrons","Le foie gras","La galette des rois","La bûche de Noël"],c:1,f:""},
  {q:"Quelle est la monnaie utilisée en France ?",a:["Le franc","Le dollar","L'euro","La livre"],c:2,f:""},
  {q:"Quel réalisateur français a dirigé 'Amélie Poulain' ?",a:["Luc Besson","Jean-Pierre Jeunet","François Truffaut","Claude Chabrol"],c:1,f:""},
  {q:"Quel scientifique français a découvert la radioactivité ?",a:["Louis Pasteur","Pierre Curie","Antoine Lavoisier","Henri Becquerel"],c:3,f:""},
  {q:"Dans quelle ville se trouve le Pont du Gard ?",a:["Nîmes","Vers-Pont-du-Gard","Avignon","Arles"],c:1,f:""},
  {q:"Quel est le nom de l'hymne national français ?",a:["La Brabançonne","La Marseillaise","Le Chant du Départ","God Save the Queen"],c:1,f:""},
  {q:"Quel philosophe français a dit 'Je pense, donc je suis' ?",a:["Voltaire","Jean-Jacques Rousseau","René Descartes","Blaise Pascal"],c:2,f:""},
  {q:"Quelle fête française se célèbre le 14 juillet ?",a:["La Fête du Travail","L'Armistice","La Fête nationale","La Toussaint"],c:2,f:""},
  {q:"Quel vin est produit dans la région de Bordeaux ?",a:["Le Riesling","Le Muscadet","Le Saint-Émilion","Le Chablis"],c:2,f:""},
  {q:"Quelle actrice française a remporté un Oscar pour 'La Vie en Rose' ?",a:["Juliette Binoche","Isabelle Huppert","Marion Cotillard","Catherine Deneuve"],c:2,f:""},
  {q:"Quel est le nom du train à grande vitesse français ?",a:["Eurostar","Thalys","TGV","ICE"],c:2,f:""},
  {q:"Quel écrivain français a reçu le prix Nobel de littérature en 1957 ?",a:["Jean-Paul Sartre","André Gide","Albert Camus","François Mauriac"],c:2,f:""},
  {q:"Quelle chaîne de montagnes sépare la France de l'Espagne ?",a:["Les Alpes","Le Jura","Le Massif central","Les Pyrénées"],c:3,f:""},
  {q:"Quel est le dessert traditionnel de l'Épiphanie en France ?",a:["La crêpe","La galette des rois","La bûche de Noël","Le Paris-Brest"],c:1,f:""},
  {q:"Quelle bataille napoléonienne de 1805 est considérée comme son chef-d'œuvre tactique ?",a:["Waterloo","Iéna","Austerlitz","Marengo"],c:2,f:""},
  {q:"Quel couturier français a créé le 'New Look' en 1947 ?",a:["Coco Chanel","Yves Saint Laurent","Christian Dior","Pierre Cardin"],c:2,f:""},
  {q:"Dans quelle ville française se trouve la basilique de Fourvière ?",a:["Marseille","Paris","Lyon","Toulouse"],c:2,f:""},
  {q:"Que signifie l'expression 'avoir la pêche' ?",a:["Avoir sommeil","Être en forme","Avoir faim","Être malade"],c:1,f:""},
  {q:"Quel président français a aboli la peine de mort en 1981 ?",a:["Valéry Giscard d'Estaing","Jacques Chirac","François Mitterrand","Georges Pompidou"],c:2,f:""},
  {q:"Quel est le plus grand parc d'attractions de France ?",a:["Le Puy du Fou","Astérix","Disneyland Paris","Le Futuroscope"],c:2,f:""},
  {q:"Quel fromage est fabriqué dans des caves naturelles à Roquefort-sur-Soulzon ?",a:["Le Bleu d'Auvergne","Le Roquefort","Le Munster","Le Reblochon"],c:1,f:""},
  {q:"Quel explorateur français a découvert le Canada ?",a:["Samuel de Champlain","Jacques Cartier","La Pérouse","Cavelier de La Salle"],c:1,f:""},
  {q:"Quelle est la spécialité culinaire de la région Alsace ?",a:["Le cassoulet","La choucroute","La ratatouille","Le gratin dauphinois"],c:1,f:""},
  {q:"Quel écrivain français a créé le personnage du commissaire Maigret ?",a:["Maurice Leblanc","Fred Vargas","Georges Simenon","Émile Gaboriau"],c:2,f:""},
  {q:"Quelle mer borde la Côte d'Azur ?",a:["L'océan Atlantique","La Manche","La mer du Nord","La mer Méditerranée"],c:3,f:""},
  {q:"Quel homme politique français est associé à la construction européenne ?",a:["Charles de Gaulle","Robert Schuman","Léon Blum","Georges Clemenceau"],c:1,f:""},
  {q:"Quel est le numéro du département de Paris ?",a:["69","75","13","33"],c:1,f:""},
  {q:"Quelle cathédrale gothique se trouve à Reims ?",a:["Notre-Dame de Paris","Notre-Dame de Reims","Saint-Denis","Chartres"],c:1,f:""},
  {q:"Quel cinéaste français est associé à la Nouvelle Vague ?",a:["Luc Besson","Jacques Tati","François Truffaut","Marcel Carné"],c:2,f:""},
  {q:"Que signifie l'expression 'tomber dans les pommes' ?",a:["Avoir faim","S'évanouir","Tomber amoureux","Se tromper"],c:1,f:""},
  {q:"Quel pont célèbre se trouve en Avignon ?",a:["Le Pont Neuf","Le Pont des Arts","Le Pont Saint-Bénézet","Le Pont Alexandre III"],c:2,f:""},
  {q:"Quel écrivain a dit 'L'enfer, c'est les autres' ?",a:["Albert Camus","Simone de Beauvoir","Jean-Paul Sartre","André Malraux"],c:2,f:""},
  {q:"Quelle région française est célèbre pour le calisson ?",a:["La Bretagne","La Provence","La Normandie","La Lorraine"],c:1,f:""},
  {q:"Quel roi de France a construit le château de Versailles ?",a:["François Ier","Henri IV","Louis XIII","Louis XIV"],c:3,f:""},
  {q:"Quelle ville française est surnommée 'la Ville Rose' ?",a:["Montpellier","Bordeaux","Toulouse","Lyon"],c:2,f:""},
  {q:"Qui a inventé le vaccin contre la rage ?",a:["Claude Bernard","Louis Pasteur","René Laennec","Ambroise Paré"],c:1,f:""},
  {q:"Quel département français porte le numéro 13 ?",a:["Le Rhône","La Gironde","Les Bouches-du-Rhône","L'Hérault"],c:2,f:""},
  {q:"Quelle est la plus ancienne université de France ?",a:["La Sorbonne","L'Université de Montpellier","L'Université de Toulouse","L'Université de Paris"],c:3,f:""},
  {q:"Quel auteur français a écrit 'Germinal' ?",a:["Victor Hugo","Honoré de Balzac","Émile Zola","Guy de Maupassant"],c:2,f:""},
  {q:"Quel est le plat traditionnel du sud-ouest associé au canard ?",a:["La blanquette","Le confit de canard","La quiche lorraine","Le bœuf bourguignon"],c:1,f:""},
  {q:"Quel peintre post-impressionniste a vécu à Tahiti ?",a:["Paul Cézanne","Henri Matisse","Paul Gauguin","Georges Seurat"],c:2,f:""},
  {q:"Que signifie l'expression 'coûter les yeux de la tête' ?",a:["Être gratuit","Être très cher","Être beau","Être rare"],c:1,f:""},
  {q:"Quel est le nom du résistant français qui a unifié les mouvements de Résistance ?",a:["Pierre Brossolette","Charles de Gaulle","Jean Moulin","Lucie Aubrac"],c:2,f:""},
  {q:"Quelle ville française accueille le Festival d'Avignon ?",a:["Aix-en-Provence","Orange","Avignon","Arles"],c:2,f:""},
  {q:"Quel chanteur français a interprété 'Que je t'aime' ?",a:["Charles Aznavour","Jacques Brel","Serge Gainsbourg","Johnny Hallyday"],c:3,f:""},
  {q:"Combien d'habitants compte approximativement la France métropolitaine ?",a:["50 millions","68 millions","80 millions","45 millions"],c:1,f:""},
  {q:"Quel est le nom de la résidence officielle du Premier ministre ?",a:["L'Élysée","Matignon","Le Quai d'Orsay","Le Palais Bourbon"],c:1,f:""},
  {q:"Quel architecte a conçu la pyramide du Louvre ?",a:["Jean Nouvel","Le Corbusier","Ieoh Ming Pei","Renzo Piano"],c:2,f:""},
  {q:"Dans quelle région se trouve le château de Chambord ?",a:["Île-de-France","Centre-Val de Loire","Pays de la Loire","Nouvelle-Aquitaine"],c:1,f:""},
  {q:"Quel est le fromage emblématique de la Savoie utilisé dans la tartiflette ?",a:["Le Beaufort","Le Reblochon","L'Abondance","Le Comté"],c:1,f:""},
  {q:"Que signifie l'expression 'mettre son grain de sel' ?",a:["Cuisiner","Se mêler de ce qui ne nous regarde pas","Ajouter du piquant","Être discret"],c:1,f:""},
  {q:"Quel est le volcan le plus connu du Massif central ?",a:["Le Puy de Dôme","Le Mont Dore","Le Cantal","Le Plomb du Cantal"],c:0,f:""},
  {q:"Quel écrivain français a écrit 'Les Fleurs du mal' ?",a:["Arthur Rimbaud","Paul Verlaine","Charles Baudelaire","Stéphane Mallarmé"],c:2,f:""},
  {q:"Quelle est la spécialité de la ville de Dijon ?",a:["Le nougat","La moutarde","Le calisson","La navette"],c:1,f:""},
  {q:"Quel personnage de bande dessinée française vit dans un village gaulois ?",a:["Tintin","Lucky Luke","Astérix","Gaston Lagaffe"],c:2,f:""},
  {q:"En quelle année les femmes ont-elles obtenu le droit de vote en France ?",a:["1936","1944","1952","1920"],c:1,f:""},
  {q:"Quel est le nom de la place principale de la ville de Lyon ?",a:["Place de la Concorde","Place Bellecour","Place du Capitole","Place de la Bourse"],c:1,f:""},
  {q:"Quel cinéaste français a réalisé 'Le Cinquième Élément' ?",a:["Jean-Pierre Jeunet","Luc Besson","Mathieu Kassovitz","Jacques Audiard"],c:1,f:""},
  {q:"Quelle bataille de 1916 est devenue un symbole de la Première Guerre mondiale ?",a:["La Somme","La Marne","Verdun","Les Dardanelles"],c:2,f:""},
  {q:"Quel est le fleuve qui traverse Bordeaux ?",a:["La Loire","La Seine","Le Rhône","La Garonne"],c:3,f:""},
  {q:"Quel pâtissier français a inventé le macaron moderne ?",a:["Gaston Lenôtre","Pierre Hermé","Antonin Carême","Auguste Escoffier"],c:1,f:""},
  {q:"Que signifie l'expression 'avoir un chat dans la gorge' ?",a:["Avoir faim","Être enroué","Avoir peur","Être muet"],c:1,f:""},
  {q:"Quel est le département le plus peuplé de France ?",a:["Les Bouches-du-Rhône","Paris","Le Rhône","Le Nord"],c:3,f:""},
  {q:"Quelle femme de lettres française a écrit 'Le Deuxième Sexe' ?",a:["Marguerite Duras","Simone de Beauvoir","Colette","Marguerite Yourcenar"],c:1,f:""},
  {q:"Quel est le sport le plus pratiqué en France ?",a:["Le rugby","Le tennis","Le football","Le cyclisme"],c:2,f:""},

  // ═══════════════════════════════════════════════
  // 100 NOUVELLES QUESTIONS (101–200)
  // ═══════════════════════════════════════════════

  // --- Rois et Reines de France ---
  {q:"Quel roi de France a signé l'Édit de Nantes en 1598 ?",a:["Louis XIII","François Ier","Henri IV","Charles IX"],c:2,f:""},
  {q:"Quelle reine de France était surnommée 'l'Autrichienne' ?",a:["Catherine de Médicis","Anne d'Autriche","Marie-Antoinette","Marie de Médicis"],c:2,f:""},
  {q:"Quel roi de France a été sacré à Reims en 1429 grâce à Jeanne d'Arc ?",a:["Charles VII","Louis XI","Charles VI","Philippe VI"],c:0,f:""},
  {q:"Quel roi capétien a régné de 987 à 996, fondant la dynastie capétienne ?",a:["Philippe Auguste","Robert le Pieux","Hugues Capet","Louis VI"],c:2,f:""},
  {q:"Quelle reine a exercé la régence pendant la minorité de Louis XIV ?",a:["Catherine de Médicis","Marie-Antoinette","Anne d'Autriche","Blanche de Castille"],c:2,f:""},

  // --- DOM-TOM ---
  {q:"Quel est le chef-lieu de la Guadeloupe ?",a:["Pointe-à-Pitre","Fort-de-France","Basse-Terre","Les Abymes"],c:2,f:""},
  {q:"Dans quel océan se trouve La Réunion ?",a:["Océan Atlantique","Océan Pacifique","Océan Indien","Mer Méditerranée"],c:2,f:""},
  {q:"Quel territoire français du Pacifique est célèbre pour son lagon classé à l'UNESCO ?",a:["Wallis-et-Futuna","Polynésie française","Nouvelle-Calédonie","Saint-Pierre-et-Miquelon"],c:2,f:""},
  {q:"Quel est le chef-lieu de la Martinique ?",a:["Basse-Terre","Cayenne","Fort-de-France","Pointe-à-Pitre"],c:2,f:""},
  {q:"Quel département d'outre-mer se trouve en Amérique du Sud ?",a:["La Martinique","La Guadeloupe","La Guyane","Mayotte"],c:2,f:""},
  {q:"Quel DOM-TOM est devenu le 101e département français en 2011 ?",a:["La Réunion","Saint-Martin","Mayotte","Wallis-et-Futuna"],c:2,f:""},

  // --- Inventions françaises ---
  {q:"Quel Français a inventé le cinématographe en 1895 ?",a:["Georges Méliès","Les frères Lumière","Léon Gaumont","Charles Pathé"],c:1,f:""},
  {q:"Qui a inventé le stéthoscope en 1816 ?",a:["Ambroise Paré","Louis Pasteur","René Laennec","Claude Bernard"],c:2,f:""},
  {q:"Quel Français a inventé le système d'écriture pour aveugles ?",a:["Louis Braille","Denis Diderot","Valentin Haüy","Charles Barbier"],c:0,f:""},
  {q:"Quel ingénieur français a mis au point la pasteurisation ?",a:["Antoine Lavoisier","Louis Pasteur","Marie Curie","Henri Becquerel"],c:1,f:""},
  {q:"Quel Français a inventé la carte à puce ?",a:["Roland Moreno","Louis Pouzin","Jacques-Yves Cousteau","Marcel Dassault"],c:0,f:""},

  // --- Champions sportifs français ---
  {q:"Quel judoka français est le plus titré de l'histoire olympique française ?",a:["David Douillet","Teddy Riner","Thierry Rey","Angelo Parisi"],c:1,f:""},
  {q:"Quel cycliste français a remporté cinq Tours de France entre 1957 et 1964 ?",a:["Bernard Hinault","Laurent Fignon","Jacques Anquetil","Raymond Poulidor"],c:2,f:""},
  {q:"Quelle nageuse française a remporté trois médailles d'or aux JO de 2012 et 2016 ?",a:["Laure Manaudou","Camille Muffat","Charlotte Bonnet","Florent Manaudou"],c:1,f:""},
  {q:"Quel footballeur français a remporté le Ballon d'or en 1998 ?",a:["Thierry Henry","Michel Platini","Zinédine Zidane","Just Fontaine"],c:2,f:""},
  {q:"Quel skieur français a remporté trois médailles d'or olympiques en ski alpin ?",a:["Jean-Claude Killy","Luc Alphand","Edgar Grospiron","Alexis Pinturault"],c:0,f:""},

  // --- Émissions de télévision françaises ---
  {q:"Quelle émission culte de France 2 était présentée par Patrice Laffont ?",a:["Intervilles","Fort Boyard","Des chiffres et des lettres","Pyramide"],c:3,f:""},
  {q:"Quel animateur a présenté 'Nulle Part Ailleurs' sur Canal+ ?",a:["Michel Drucker","Thierry Ardisson","Antoine de Caunes","Laurent Ruquier"],c:2,f:""},
  {q:"Quelle série télévisée française se déroule au Moyen Âge avec le roi Arthur ?",a:["Hero Corp","Kaamelott","Les Visiteurs","Merlin"],c:1,f:""},
  {q:"Quel jeu télévisé français se déroule dans un fort maritime ?",a:["Intervilles","Le Maillon faible","Fort Boyard","Koh-Lanta"],c:2,f:""},
  {q:"Quelle émission de variétés était présentée par Michel Drucker le dimanche ?",a:["Tout le monde en parle","Vivement Dimanche","C à vous","Taratata"],c:1,f:""},

  // --- Bande dessinée (BD) ---
  {q:"Quel dessinateur belge a créé Tintin ?",a:["René Goscinny","Hergé","Peyo","Morris"],c:1,f:""},
  {q:"Dans quel journal les aventures d'Astérix ont-elles été publiées pour la première fois ?",a:["Spirou","Tintin","Pilote","Pif Gadget"],c:2,f:""},
  {q:"Quel personnage de BD est un gaffeur travaillant dans un journal ?",a:["Spirou","Tintin","Gaston Lagaffe","Titeuf"],c:2,f:""},
  {q:"Qui est le créateur de la bande dessinée 'Le Petit Nicolas' ?",a:["Sempé et Goscinny","Uderzo et Goscinny","Franquin","Peyo"],c:0,f:""},
  {q:"Quel personnage de BD créé par Peyo vit dans des champignons ?",a:["Gaston Lagaffe","Spirou","Les Schtroumpfs","Boule et Bill"],c:2,f:""},

  // --- Musique française ---
  {q:"Quel rappeur français a sorti l'album 'Civilisation' ?",a:["Nekfeu","Booba","Orelsan","Jul"],c:2,f:""},
  {q:"Quel chanteur de variété française a interprété 'La Bohème' ?",a:["Jacques Brel","Georges Brassens","Charles Aznavour","Serge Gainsbourg"],c:2,f:""},
  {q:"Quel duo électro français est célèbre pour 'Around the World' ?",a:["Justice","Air","Daft Punk","Phoenix"],c:2,f:""},
  {q:"Quel chanteur français est surnommé 'le Grand Jacques' ?",a:["Jacques Dutronc","Jacques Higelin","Jacques Brel","Jacques Prévert"],c:2,f:""},
  {q:"Quelle chanteuse française a interprété 'Voyage, Voyage' en 1986 ?",a:["Mylène Farmer","Desireless","Patricia Kaas","Vanessa Paradis"],c:1,f:""},
  {q:"Quel rappeur marseillais est membre du groupe IAM ?",a:["MC Solaar","Booba","Akhenaton","Oxmo Puccino"],c:2,f:""},

  // --- Expressions et proverbes ---
  {q:"Que signifie l'expression 'avoir le beurre et l'argent du beurre' ?",a:["Être riche","Tout vouloir sans rien sacrifier","Aimer cuisiner","Être avare"],c:1,f:""},
  {q:"Que signifie le proverbe 'Pierre qui roule n'amasse pas mousse' ?",a:["Il faut être patient","Qui change souvent ne s'enrichit pas","Il faut travailler dur","Les voyages forment la jeunesse"],c:1,f:""},
  {q:"Que signifie l'expression 'donner sa langue au chat' ?",a:["Être gourmand","Parler trop","Renoncer à deviner","Mentir"],c:2,f:""},
  {q:"Que signifie l'expression 'faire la grasse matinée' ?",a:["Manger un gros petit-déjeuner","Dormir tard le matin","Faire du sport le matin","Se lever tôt"],c:1,f:""},
  {q:"Que signifie l'expression 'il pleut des cordes' ?",a:["Il fait très froid","Il y a du vent","Il pleut très fort","Il neige"],c:2,f:""},

  // --- Architecture française ---
  {q:"Quel architecte français a conçu la Cité Radieuse à Marseille ?",a:["Gustave Eiffel","Jean Nouvel","Le Corbusier","Hector Guimard"],c:2,f:""},
  {q:"Quel style architectural caractérise la cathédrale de Chartres ?",a:["Roman","Baroque","Gothique","Renaissance"],c:2,f:""},
  {q:"Quel architecte a dessiné les entrées du métro parisien en style Art Nouveau ?",a:["Le Corbusier","Hector Guimard","Gustave Eiffel","Auguste Perret"],c:1,f:""},
  {q:"Quel château de la Loire est célèbre pour son escalier à double révolution ?",a:["Chenonceau","Amboise","Chambord","Azay-le-Rideau"],c:2,f:""},
  {q:"Quel bâtiment parisien conçu par Renzo Piano et Richard Rogers abrite un centre d'art moderne ?",a:["Le Grand Palais","Le Centre Pompidou","La Fondation Louis Vuitton","Le Palais de Tokyo"],c:1,f:""},

  // --- Créateurs de mode ---
  {q:"Quelle créatrice de mode française a popularisé la petite robe noire ?",a:["Elsa Schiaparelli","Sonia Rykiel","Coco Chanel","Jeanne Lanvin"],c:2,f:""},
  {q:"Quel couturier français a lancé la première collection de prêt-à-porter de luxe en 1966 ?",a:["Pierre Cardin","Christian Dior","Yves Saint Laurent","Hubert de Givenchy"],c:2,f:""},
  {q:"Quelle maison de mode française est célèbre pour son sac 'Birkin' ?",a:["Louis Vuitton","Chanel","Hermès","Dior"],c:2,f:""},
  {q:"Quel couturier français a habillé Audrey Hepburn dans 'Breakfast at Tiffany's' ?",a:["Christian Dior","Pierre Balmain","Hubert de Givenchy","Yves Saint Laurent"],c:2,f:""},

  // --- Scientifiques français ---
  {q:"Quel chimiste français est considéré comme le père de la chimie moderne ?",a:["Louis Pasteur","Marie Curie","Antoine Lavoisier","Henri Moissan"],c:2,f:""},
  {q:"Quelle scientifique d'origine polonaise a reçu deux prix Nobel en France ?",a:["Irène Joliot-Curie","Marie Curie","Marguerite Perey","Claudie Haigneré"],c:1,f:""},
  {q:"Quel mathématicien français a inventé la géométrie analytique avec Descartes ?",a:["Blaise Pascal","Pierre de Fermat","Henri Poincaré","Joseph Fourier"],c:1,f:""},
  {q:"Quel physicien français a donné son nom à l'unité de pression ?",a:["André-Marie Ampère","Charles-Augustin de Coulomb","Blaise Pascal","Joseph Louis Gay-Lussac"],c:2,f:""},
  {q:"Quel océanographe français a co-inventé le scaphandre autonome ?",a:["Paul-Émile Victor","Jean-Baptiste Charcot","Jacques-Yves Cousteau","Théodore Monod"],c:2,f:""},

  // --- Explorateurs français ---
  {q:"Quel explorateur français a fondé la ville de Québec en 1608 ?",a:["Jacques Cartier","La Pérouse","Samuel de Champlain","René-Robert Cavelier de La Salle"],c:2,f:""},
  {q:"Quel explorateur français a revendiqué la Louisiane pour la France ?",a:["Samuel de Champlain","Jacques Cartier","Cavelier de La Salle","Louis Antoine de Bougainville"],c:2,f:""},
  {q:"Quel navigateur français a réalisé le premier tour du monde français au XVIIIe siècle ?",a:["La Pérouse","Jacques Cartier","Louis Antoine de Bougainville","Dumont d'Urville"],c:2,f:""},
  {q:"Quel explorateur français a donné son nom à un détroit entre l'Australie et la Tasmanie ?",a:["Bougainville","La Pérouse","Dumont d'Urville","Bruni d'Entrecasteaux"],c:3,f:""},

  // --- Système politique français ---
  {q:"Comment s'appelle la chambre basse du Parlement français ?",a:["Le Sénat","Le Conseil d'État","L'Assemblée nationale","Le Conseil constitutionnel"],c:2,f:""},
  {q:"Combien de sénateurs siègent au Sénat français ?",a:["348","577","300","450"],c:0,f:""},
  {q:"Combien de députés siègent à l'Assemblée nationale ?",a:["348","450","577","650"],c:2,f:""},
  {q:"Quel est le mandat du président de la République française depuis 2000 ?",a:["7 ans","4 ans","5 ans","6 ans"],c:2,f:""},
  {q:"Où siège le Sénat français ?",a:["Le Palais Bourbon","Le Palais du Luxembourg","L'Élysée","Matignon"],c:1,f:""},

  // --- Fêtes et traditions ---
  {q:"Quel jour fête-t-on la Chandeleur en France ?",a:["1er janvier","2 février","14 février","1er mai"],c:1,f:""},
  {q:"Que mange-t-on traditionnellement à la Chandeleur ?",a:["Des galettes","Des crêpes","Des gaufres","Du pain d'épices"],c:1,f:""},
  {q:"Quel jour célèbre-t-on la Fête de la Musique en France ?",a:["14 juillet","1er mai","21 juin","25 décembre"],c:2,f:""},
  {q:"Quel est le jour férié du 11 novembre en France ?",a:["La Fête nationale","L'Armistice de 1918","La Toussaint","L'Assomption"],c:1,f:""},
  {q:"Que distribue-t-on traditionnellement le 1er mai en France ?",a:["Des œufs en chocolat","Des crêpes","Du muguet","Des roses"],c:2,f:""},

  // --- Fleuves et montagnes ---
  {q:"Quel fleuve français se jette dans la Manche ?",a:["La Garonne","Le Rhône","La Seine","La Loire"],c:2,f:""},
  {q:"Quel massif montagneux se situe entre la France et la Suisse ?",a:["Les Pyrénées","Le Massif central","Les Vosges","Le Jura"],c:3,f:""},
  {q:"Quel fleuve français prend sa source au mont Gerbier-de-Jonc ?",a:["La Seine","Le Rhône","La Garonne","La Loire"],c:3,f:""},
  {q:"Quel est le point culminant des Pyrénées françaises ?",a:["Le Pic du Midi","Le Vignemale","Le Pic d'Aneto","Le Pic du Canigou"],c:1,f:""},
  {q:"Dans quel massif se trouve le Puy de Sancy, point culminant du Massif central ?",a:["Les Monts du Cantal","Les Monts Dore","Les Monts du Forez","Les Causses"],c:1,f:""},

  // --- Îles françaises ---
  {q:"Quelle île française se situe au large de Cannes ?",a:["L'île de Ré","L'île d'Oléron","L'île Sainte-Marguerite","L'île de Porquerolles"],c:2,f:""},
  {q:"Quelle île bretonne est célèbre pour ses alignements mégalithiques ?",a:["Belle-Île-en-Mer","L'île de Bréhat","L'île de Groix","Carnac n'est pas une île"],c:0,f:""},
  {q:"Quelle île française de l'Atlantique est reliée au continent par un pont ?",a:["L'île de Ré","L'île d'Yeu","Belle-Île-en-Mer","L'île de Batz"],c:0,f:""},
  {q:"Quel volcan actif se trouve à La Réunion ?",a:["La Montagne Pelée","Le Piton de la Fournaise","Le Piton des Neiges","Le Karthala"],c:1,f:""},

  // --- Vins et AOC ---
  {q:"Quel vignoble français produit le Gewurztraminer ?",a:["La Bourgogne","Le Bordelais","L'Alsace","La Vallée du Rhône"],c:2,f:""},
  {q:"Quel vin de Bourgogne est considéré comme l'un des plus prestigieux au monde ?",a:["Le Châteauneuf-du-Pape","Le Romanée-Conti","Le Margaux","Le Sancerre"],c:1,f:""},
  {q:"Dans quelle région produit-on le Muscadet ?",a:["La Bourgogne","L'Alsace","La Vallée de la Loire","La Provence"],c:2,f:""},
  {q:"Quel type de vin est le Sauternes ?",a:["Un vin rouge","Un vin rosé","Un vin blanc sec","Un vin blanc liquoreux"],c:3,f:""},
  {q:"Quelle appellation viticole se trouve sur les pentes du Rhône près de Lyon ?",a:["Le Beaujolais","Le Côtes-du-Rhône","Le Côte-Rôtie","Le Condrieu"],c:2,f:""},

  // --- Régions et spécialités régionales ---
  {q:"Quelle spécialité culinaire est originaire de Nice ?",a:["La quiche lorraine","La socca","Le kouign-amann","La flammekueche"],c:1,f:""},
  {q:"Quel gâteau breton est préparé avec beaucoup de beurre ?",a:["Le far breton","Le kouign-amann","La galette bretonne","Le gâteau nantais"],c:1,f:""},
  {q:"Quelle ville du Nord est célèbre pour ses moules-frites ?",a:["Amiens","Roubaix","Lille","Dunkerque"],c:2,f:""},
  {q:"Quelle confiserie est une spécialité de Montélimar ?",a:["La praline","Le calisson","Le nougat","La bergamote"],c:2,f:""},
  {q:"De quelle région est originaire la flammekueche (tarte flambée) ?",a:["La Lorraine","La Bretagne","L'Alsace","La Franche-Comté"],c:2,f:""},

  // --- Divers culture française ---
  {q:"Quel est le nom de la femme symbolisant la République française ?",a:["Jeanne","Marianne","Marie","Françoise"],c:1,f:""},
  {q:"Quel navigateur français a remporté le Vendée Globe en 2001 en solitaire ?",a:["Éric Tabarly","Michel Desjoyeaux","Alain Colas","François Gabart"],c:1,f:""},
  {q:"Quel comédien français a créé le personnage de Coluche ?",a:["Michel Colucci","Pierre Desproges","Raymond Devos","Fernand Raynaud"],c:0,f:""},
  {q:"Quel humoriste français a fondé les Restos du Cœur ?",a:["Pierre Desproges","Thierry Le Luron","Coluche","Guy Bedos"],c:2,f:""},
  {q:"Quel philosophe des Lumières est l'auteur de 'Candide' ?",a:["Montesquieu","Jean-Jacques Rousseau","Denis Diderot","Voltaire"],c:3,f:""},
  {q:"Quelle est la plus grande forêt domaniale de France métropolitaine ?",a:["La forêt de Fontainebleau","La forêt de Compiègne","La forêt d'Orléans","La forêt de Brocéliande"],c:2,f:""},
  {q:"Quel prix littéraire français est décerné chaque année en novembre ?",a:["Le prix Femina","Le prix Goncourt","Le prix Renaudot","Le prix Médicis"],c:1,f:""},
  {q:"Dans quelle ville française se trouve le Vieux-Port ?",a:["Nice","Toulon","Marseille","La Rochelle"],c:2,f:""},
  {q:"Quel monument de Paris abrite le tombeau de Napoléon Ier ?",a:["Le Panthéon","L'Arc de Triomphe","Les Invalides","Notre-Dame de Paris"],c:2,f:""},
  {q:"Quel chanteur français a interprété 'Ne me quitte pas' ?",a:["Charles Aznavour","Georges Brassens","Serge Gainsbourg","Jacques Brel"],c:3,f:""},
];
