/* ════════════════════════════════════════
   questions/gaming.js — Jeux Vidéo — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.gaming = [
  {q:"Quel personnage est le héros principal de Super Mario Bros. ?",a:["Luigi","Mario","Bowser","Toad"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Link ?",a:["Final Fantasy","The Legend of Zelda","Dragon Quest","Monster Hunter"],c:1,f:""},
  {q:"Quel jeu de Mojang consiste à construire avec des blocs ?",a:["Terraria","Minecraft","Roblox","Fortnite"],c:1,f:""},
  {q:"Quelle entreprise a créé la console PlayStation ?",a:["Nintendo","Microsoft","Sony","Sega"],c:2,f:""},
  {q:"Quel est le rival principal de Mario dans les jeux Nintendo ?",a:["Yoshi","Bowser","Wario","Donkey Kong"],c:1,f:""},
  {q:"Quel personnage est la mascotte de Sega ?",a:["Mario","Sonic","Crash","Kirby"],c:1,f:""},
  {q:"Quelle entreprise développe Grand Theft Auto ?",a:["Ubisoft","Rockstar Games","EA","Square Enix"],c:1,f:""},
  {q:"Quel jeu consiste à capturer des créatures et les faire combattre ?",a:["Digimon","Pokémon","Monster Hunter","Palworld"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on Master Chief ?",a:["Halo","Destiny","Mass Effect","Doom"],c:0,f:""},
  {q:"Quel jeu de course met en scène Mario et ses amis ?",a:["Forza","Gran Turismo","Mario Kart","Need for Speed"],c:2,f:""},
  {q:"Dans quel jeu incarne-t-on Kratos ?",a:["God of War","Devil May Cry","Dark Souls","Diablo"],c:0,f:""},
  {q:"Quel jeu populaire est un FPS tactique de Riot Games ?",a:["Counter-Strike","Valorant","Rainbow Six","Overwatch"],c:1,f:""},
  {q:"Dans quel jeu explore-t-on Hyrule ?",a:["The Legend of Zelda","Elden Ring","The Witcher 3","Skyrim"],c:0,f:""},
  {q:"Quel jeu est célèbre pour 'Victory Royale' ?",a:["Fortnite","PUBG","Apex Legends","Warzone"],c:0,f:""},
  {q:"Dans quel jeu combat-on avec Tracer et Genji ?",a:["Overwatch","Valorant","League of Legends","Paladins"],c:0,f:""},
  {q:"Quel jeu est un MOBA développé par Riot Games ?",a:["Dota 2","League of Legends","Heroes of the Storm","Smite"],c:1,f:""},
  {q:"Quel jeu se déroule dans la région de Skyrim ?",a:["The Elder Scrolls V: Skyrim","Dragon Age","The Witcher 3","Elden Ring"],c:0,f:""},
  {q:"Quel jeu monde ouvert avec des cow-boys est développé par Rockstar ?",a:["Red Dead Redemption 2","GTA V","Far Cry 5","Days Gone"],c:0,f:""},
  {q:"Dans quel jeu incarne-t-on un criminel dans une grande ville ?",a:["Watch Dogs","Grand Theft Auto V","Sleeping Dogs","Mafia"],c:1,f:""},
  {q:"Quel jeu consiste à survivre sur une île avec des dinosaures ?",a:["Ark: Survival Evolved","Subnautica","Rust","Green Hell"],c:0,f:""},
  {q:"Quel jeu propose un monde médiéval très difficile créé par FromSoftware ?",a:["Dark Souls","Dragon Age","Fable","Kingdom Come"],c:0,f:""},
  {q:"Quel jeu de football est développé par EA Sports ?",a:["Pro Evolution Soccer","FIFA/EA FC","Football Manager","Winning Eleven"],c:1,f:""},
  {q:"Dans quel jeu incarne-t-on Joel et Ellie ?",a:["Days Gone","The Last of Us","Dying Light","Resident Evil"],c:1,f:""},
  {q:"Quel jeu est un battle royale développé par PUBG Corp ?",a:["Fortnite","PUBG","Apex Legends","Warzone"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on les personnages Solid Snake ?",a:["Splinter Cell","Metal Gear Solid","Hitman","Deus Ex"],c:1,f:""},
  {q:"Quelle console Nintendo a été lancée en 2017 ?",a:["Wii U","3DS","Nintendo Switch","Nintendo DS"],c:2,f:""},
  {q:"Dans quel jeu incarne-t-on un chasseur de démons nommé Doom Guy ?",a:["Quake","Doom","Heretic","Blood"],c:1,f:""},
  {q:"Quel jeu de stratégie met en scène des civilisations historiques ?",a:["Age of Empires","Total War","Civilization","Rise of Nations"],c:2,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Nathan Drake ?",a:["Tomb Raider","Uncharted","Indiana Jones","Prince of Persia"],c:1,f:""},
  {q:"Quel jeu se déroule dans un monde post-apocalyptique nommé le Wasteland ?",a:["Fallout","Metro","The Last of Us","Mad Max"],c:0,f:""},
  {q:"Dans quel jeu incarne-t-on Lara Croft ?",a:["Uncharted","Tomb Raider","Prince of Persia","Assassin's Creed"],c:1,f:""},
  {q:"Quel jeu de simulation de vie a été créé par Will Wright ?",a:["SimCity","The Sims","Animal Crossing","Stardew Valley"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on la Princess Zelda ?",a:["Mario","The Legend of Zelda","Metroid","Fire Emblem"],c:1,f:""},
  {q:"Quel jeu est un FPS multijoueur développé par Valve ?",a:["Counter-Strike 2","Team Fortress 2","Overwatch","Halo"],c:0,f:""},
  {q:"Dans quel jeu incarne-t-on un fantôme de lumière nommé Guardian ?",a:["Halo","Destiny","Mass Effect","Anthem"],c:1,f:""},
  {q:"Quel jeu de combat met en scène des personnages de Street Fighter ?",a:["Tekken","Mortal Kombat","Street Fighter","King of Fighters"],c:2,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage d'Ezio Auditore ?",a:["Dishonored","Assassin's Creed","Prince of Persia","Batman"],c:1,f:""},
  {q:"Quel jeu propose des parties de Tetris ?",a:["Tetris","Puyo Puyo","Columns","Dr. Mario"],c:0,f:""},
  {q:"Dans quel jeu incarne-t-on un plombier qui sauve une princesse ?",a:["Donkey Kong","Super Mario Bros.","Kirby","Yoshi"],c:1,f:""},
  {q:"Quel jeu de sport électronique (e-sport) est célèbre pour ses tournois à millions ?",a:["FIFA","Fortnite","Dota 2","Call of Duty"],c:2,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Commander Shepard ?",a:["Halo","Star Wars: KOTOR","Mass Effect","Destiny"],c:2,f:""},
  {q:"Quel jeu propose de construire et gérer un zoo ?",a:["Planet Zoo","Jurassic World Evolution","Zoo Tycoon","Wildlife Park"],c:0,f:""},
  {q:"Dans quel jeu incarne-t-on V dans un monde cyberpunk ?",a:["Deus Ex","Cyberpunk 2077","Shadowrun","Observer"],c:1,f:""},
  {q:"Quel jeu de courses de karting est développé par Nintendo ?",a:["Crash Team Racing","Mario Kart","Sonic & All-Stars Racing","Diddy Kong Racing"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Master Chief Petty Officer ?",a:["Gears of War","Halo","Killzone","Resistance"],c:1,f:""},
  {q:"Quel jeu propose un monde ouvert dans l'espace avec exploration de planètes ?",a:["No Man's Sky","Elite Dangerous","Star Citizen","Outer Wilds"],c:0,f:""},
  {q:"Dans quel jeu incarne-t-on Arthur Morgan ?",a:["GTA V","Red Dead Redemption 2","L.A. Noire","Mafia III"],c:1,f:""},
  {q:"Quel jeu de rôle japonais met en scène Cloud Strife ?",a:["Dragon Quest","Final Fantasy VII","Kingdom Hearts","Tales of"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Geralt de Riv ?",a:["Dragon Age","The Witcher","Baldur's Gate","Neverwinter"],c:1,f:""},
  {q:"Quel jeu propose des combats de robots géants nommés Titans ?",a:["Armored Core","Titanfall","Mechwarrior","Front Mission"],c:1,f:""},
  {q:"Dans quel jeu incarne-t-on un agent secret capable de ralentir le temps ?",a:["Superhot","Control","Max Payne","Mirror's Edge"],c:2,f:""},
  {q:"Quel jeu de stratégie en temps réel met en scène des factions comme les Terrans et les Zergs ?",a:["Warcraft","StarCraft","Command & Conquer","Age of Empires"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Aloy ?",a:["Horizon Zero Dawn","Tomb Raider","Beyond Good & Evil","Enslaved"],c:0,f:""},
  {q:"Quel jeu de simulation agricole est développé par ConcernedApe ?",a:["Farming Simulator","Stardew Valley","My Time at Portia","Harvest Moon"],c:1,f:""},
  {q:"Dans quel jeu incarne-t-on un chasseur de monstres qui forge son équipement ?",a:["Dark Souls","Monster Hunter","God Eater","Toukiden"],c:1,f:""},
  {q:"Quel jeu propose d'explorer des donjons générés aléatoirement et de mourir souvent ?",a:["Dark Souls","Hades","Rogue Legacy","Dead Cells"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on les personnages de Marcus Fenix et Dom ?",a:["Halo","Call of Duty","Gears of War","Killzone"],c:2,f:""},
  {q:"Quel jeu de plateforme met en scène un hérisson bleu ?",a:["Crash Bandicoot","Spyro","Sonic the Hedgehog","Rayman"],c:2,f:""},
  {q:"Dans quel jeu incarne-t-on un personnage dans la Rome antique (Assassin's Creed) ?",a:["AC Origins","AC Unity","AC Brotherhood","AC Odyssey"],c:2,f:""},
  {q:"Quel jeu multijoueur oppose deux équipes de 5 joueurs dans une arène ?",a:["Fortnite","League of Legends","Overwatch","Valorant"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Samus Aran ?",a:["Kirby","Metroid","Star Fox","F-Zero"],c:1,f:""},
  {q:"Quel jeu de puzzle est célèbre pour ses portails téléporteurs ?",a:["Portal","Q.U.B.E.","Antichamber","The Turing Test"],c:0,f:""},
  {q:"Dans quel jeu incarne-t-on un personnage dans l'Égypte antique (Assassin's Creed) ?",a:["AC Origins","AC Unity","AC Odyssey","AC Valhalla"],c:0,f:""},
  {q:"Quel jeu propose de piloter des vaisseaux spatiaux dans des batailles épiques ?",a:["Star Wars Battlefront","Eve Online","Freelancer","Star Citizen"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on les personnages Banjo et Kazooie ?",a:["Donkey Kong","Banjo-Kazooie","Conker","Yooka-Laylee"],c:1,f:""},
  {q:"Quel jeu de sport met en scène des voitures jouant au football ?",a:["Hot Wheels","Rocket League","Car Soccer","Turbo Soccer"],c:1,f:""},
  {q:"Dans quel jeu incarne-t-on un inspecteur de douane dans un pays fictif ?",a:["This War of Mine","Papers Please","Orwell","Beholder"],c:1,f:""},
  {q:"Quel jeu de tir se déroule dans un futur lointain avec des classes de héros ?",a:["Titanfall","Apex Legends","Battleborn","Overwatch"],c:3,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Ratchet et Clank ?",a:["Jak and Daxter","Ratchet & Clank","Sly Cooper","Spyro"],c:1,f:""},
  {q:"Quel jeu de survie sous-marin a été développé par Unknown Worlds ?",a:["Abzû","Subnautica","Feed and Grow: Fish","Depth"],c:1,f:""},
  {q:"Dans quel jeu incarne-t-on un guerrier spartiate dans la Grèce antique ?",a:["AC Brotherhood","AC Origins","AC Odyssey","AC Valhalla"],c:2,f:""},
  {q:"Quel jeu de course est célèbre pour la série Forza Horizon ?",a:["Need for Speed","Gran Turismo","Forza Horizon","Project CARS"],c:2,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de Toad (Mario) ?",a:["Super Mario Bros.","Donkey Kong","Kirby","Yoshi"],c:0,f:""},
  {q:"Quel jeu de construction et gestion de parcs à thème a été développé par Frontier ?",a:["RollerCoaster Tycoon","Planet Coaster","Thrillville","Theme Park"],c:1,f:""},
  {q:"Dans quel jeu incarne-t-on un viking en Angleterre (Assassin's Creed) ?",a:["AC Origins","AC Odyssey","AC Valhalla","AC Syndicate"],c:2,f:""},
  {q:"Quel jeu de combat met en scène Scorpion et Sub-Zero ?",a:["Street Fighter","Tekken","Mortal Kombat","Injustice"],c:2,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de D.Va et Reinhardt ?",a:["Valorant","League of Legends","Overwatch","Paladins"],c:2,f:""},
  {q:"Quel jeu de simulation de vol est développé par Microsoft ?",a:["X-Plane","DCS World","Flight Simulator","Ace Combat"],c:2,f:""},
  {q:"Dans quel jeu incarne-t-on un enfant qui explore un monde magique avec un crayon ?",a:["Drawn to Life","Okami","Scribblenauts","Epic Mickey"],c:2,f:""},
  {q:"Quel jeu de tir à la première personne se déroule dans les tranchées de la 1ère GM ?",a:["Call of Duty WWI","Battlefield 1","Verdun","Medal of Honor"],c:1,f:""},
  {q:"Dans quel jeu trouve-t-on Pikachu comme mascotte ?",a:["Digimon","Yokai Watch","Pokémon","Monster Rancher"],c:2,f:""},
  {q:"Quel jeu met en scène des dinosaures dans un parc géré par le joueur ?",a:["Zoo Tycoon","Planet Zoo","Jurassic World Evolution","Carnivores"],c:2,f:""},
  {q:"Dans quel jeu incarne-t-on un fantôme dans l'espace (Destiny) ?",a:["Destiny 1","Destiny 2","Les deux","Aucun"],c:2,f:""},
  {q:"Quel jeu de survie propose de construire une base contre des zombies ?",a:["7 Days to Die","Dying Light","State of Decay","Project Zomboid"],c:0,f:""},
  {q:"Dans quel jeu trouve-t-on les personnages Isaac Clarke combattant des Nécromorphes ?",a:["System Shock","Dead Space","Alien: Isolation","Prey"],c:1,f:""},
  {q:"Quel jeu de gestion de ville a été créé par Maxis ?",a:["Cities: Skylines","SimCity","Anno","Tropico"],c:1,f:""},
  {q:"Dans quel jeu incarne-t-on un pilote de mecha dans un futur post-apocalyptique ?",a:["Armored Core","Zone of the Enders","Titanfall","Mechwarrior"],c:0,f:""},
  {q:"Quel jeu de plateforme 3D met en scène un chapeau sentient nommé Cappy ?",a:["Super Mario Galaxy","Super Mario 3D World","Super Mario Odyssey","Super Mario 64"],c:2,f:""},
  {q:"Dans quel jeu trouve-t-on Niko Bellic comme personnage principal ?",a:["GTA IV","GTA V","GTA San Andreas","GTA Vice City"],c:0,f:""},
  {q:"Quel jeu de stratégie spatial a été développé par Paradox ?",a:["Stellaris","Endless Space","Galactic Civilizations","Sins of a Solar Empire"],c:0,f:""},
  {q:"Dans quel jeu incarne-t-on un homme araignée amateur de pizza ?",a:["Marvel's Spider-Man","Batman Arkham","Prototype","InFAMOUS"],c:0,f:""},
  {q:"Quel jeu de combat met en scène des personnages Nintendo comme Mario et Link ?",a:["Super Smash Bros.","PlayStation All-Stars","MultiVersus","Brawlhalla"],c:0,f:""},
  {q:"Dans quel jeu trouve-t-on le personnage de CJ (Carl Johnson) ?",a:["GTA IV","GTA Vice City","GTA San Andreas","GTA III"],c:2,f:""},
  {q:"Quel jeu de tir coopératif contre des zombies est développé par Turtle Rock Studios ?",a:["Left 4 Dead","Back 4 Blood","World War Z","Killing Floor"],c:0,f:""},
];
