/* ════════════════════════════════════════
   questions/geo.js — Géographie — 200 questions
   ════════════════════════════════════════ */
QUESTIONS.geo = [
  {q:"Quelle est la capitale de la France ?",a:["Lyon","Marseille","Paris","Toulouse"],c:2,f:""},
  {q:"Quel est le plus grand océan de la planète ?",a:["Atlantique","Indien","Pacifique","Arctique"],c:2,f:""},
  {q:"Quel fleuve traverse la ville de Londres ?",a:["Rhin","Tamise","Danube","Seine"],c:1,f:""},
  {q:"Quel est le plus grand pays du monde par superficie ?",a:["Canada","Chine","Russie","États-Unis"],c:2,f:""},
  {q:"Quelle chaîne de montagnes sépare la France et l'Espagne ?",a:["Alpes","Pyrénées","Carpates","Apennins"],c:1,f:""},
  {q:"Quelle est la capitale du Japon ?",a:["Osaka","Kyoto","Tokyo","Nagoya"],c:2,f:""},
  {q:"Quel est le plus long fleuve du monde ?",a:["Amazone","Nil","Yangtsé","Mississippi"],c:1,f:""},
  {q:"Quel est le plus haut sommet du monde ?",a:["K2","Mont Everest","Kangchenjunga","Mont Blanc"],c:1,f:""},
  {q:"Quel pays a la forme d'une botte ?",a:["Espagne","Italie","Portugal","Grèce"],c:1,f:""},
  {q:"Quelle est la capitale de l'Allemagne ?",a:["Munich","Hambourg","Berlin","Cologne"],c:2,f:""},
  {q:"Sur quel continent se trouve l'Égypte ?",a:["Europe","Asie","Afrique","Amérique"],c:2,f:""},
  {q:"Quel fleuve traverse la ville de Paris ?",a:["Rhin","Loire","Seine","Rhône"],c:2,f:""},
  {q:"Quelle est la capitale du Canada ?",a:["Toronto","Montréal","Ottawa","Vancouver"],c:2,f:""},
  {q:"Quel est le plus grand continent ?",a:["Afrique","Amérique du Nord","Asie","Europe"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Barcelone ?",a:["Portugal","Espagne","Italie","France"],c:1,f:""},
  {q:"Quel océan borde la côte ouest des États-Unis ?",a:["Atlantique","Pacifique","Indien","Arctique"],c:1,f:""},
  {q:"Quelle est la capitale du Royaume-Uni ?",a:["Manchester","Liverpool","Londres","Birmingham"],c:2,f:""},
  {q:"Dans quel pays se trouve la Grande Muraille ?",a:["Japon","Corée du Sud","Chine","Mongolie"],c:2,f:""},
  {q:"Quelle est la capitale de l'Espagne ?",a:["Barcelone","Valence","Madrid","Séville"],c:2,f:""},
  {q:"Sur quel continent se trouve l'Argentine ?",a:["Europe","Afrique","Amérique du Sud","Asie"],c:2,f:""},
  {q:"Quelle mer borde la côte sud de la France ?",a:["Mer Noire","Mer Méditerranée","Mer Baltique","Mer Rouge"],c:1,f:""},
  {q:"Quel est le plus grand lac d'Afrique ?",a:["Lac Tanganyika","Lac Victoria","Lac Malawi","Lac Tchad"],c:1,f:""},
  {q:"Quelle est la capitale des États-Unis ?",a:["New York","Los Angeles","Washington D.C.","Chicago"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Dubaï ?",a:["Qatar","Émirats arabes unis","Oman","Arabie saoudite"],c:1,f:""},
  {q:"Quelle est la capitale de l'Australie ?",a:["Sydney","Melbourne","Canberra","Perth"],c:2,f:""},
  {q:"Quel fleuve traverse l'Égypte ?",a:["Tigre","Congo","Nil","Niger"],c:2,f:""},
  {q:"Dans quel pays se trouve le mont Fuji ?",a:["Chine","Corée","Japon","Vietnam"],c:2,f:""},
  {q:"Quelle est la capitale du Brésil ?",a:["Rio de Janeiro","São Paulo","Brasilia","Salvador"],c:2,f:""},
  {q:"Quel est le plus petit continent ?",a:["Europe","Australie/Océanie","Antarctique","Amérique du Sud"],c:1,f:""},
  {q:"Dans quel pays se trouve la ville de Buenos Aires ?",a:["Chili","Uruguay","Brésil","Argentine"],c:3,f:""},
  {q:"Quel est le plus grand désert chaud du monde ?",a:["Gobi","Kalahari","Sahara","Arabie"],c:2,f:""},
  {q:"Quelle est la capitale de la Russie ?",a:["Saint-Pétersbourg","Moscou","Kiev","Minsk"],c:1,f:""},
  {q:"Dans quel pays se trouve le Machu Picchu ?",a:["Mexique","Colombie","Pérou","Bolivie"],c:2,f:""},
  {q:"Quel est le plus long fleuve d'Europe ?",a:["Rhin","Danube","Volga","Loire"],c:2,f:""},
  {q:"Quelle est la capitale de la Chine ?",a:["Shanghai","Hong Kong","Pékin","Canton"],c:2,f:""},
  {q:"Dans quel pays se trouve le Taj Mahal ?",a:["Pakistan","Bangladesh","Inde","Sri Lanka"],c:2,f:""},
  {q:"Quel est le plus grand lac du monde ?",a:["Lac Supérieur","Lac Victoria","Mer Caspienne","Lac Baïkal"],c:2,f:""},
  {q:"Quelle est la capitale de l'Inde ?",a:["Mumbai","Kolkata","Chennai","New Delhi"],c:3,f:""},
  {q:"Dans quel pays se trouve Amsterdam ?",a:["Belgique","Allemagne","Pays-Bas","Danemark"],c:2,f:""},
  {q:"Quel est le plus haut volcan du monde ?",a:["Vésuve","Etna","Mauna Kea","Ojos del Salado"],c:3,f:""},
  {q:"Quelle est la capitale du Mexique ?",a:["Guadalajara","Cancún","Mexico","Monterrey"],c:2,f:""},
  {q:"Dans quel pays se trouve le désert de Gobi ?",a:["Chine et Mongolie","Russie","Kazakhstan","Inde"],c:0,f:""},
  {q:"Quel est le plus long fleuve d'Asie ?",a:["Gange","Yangtsé","Mékong","Fleuve Jaune"],c:1,f:""},
  {q:"Quelle est la capitale de la Corée du Sud ?",a:["Busan","Incheon","Seoul","Daegu"],c:2,f:""},
  {q:"Dans quel pays se trouve le mont Kilimandjaro ?",a:["Kenya","Tanzanie","Éthiopie","Uganda"],c:1,f:""},
  {q:"Quel est le plus grand archipel du monde ?",a:["Japon","Philippines","Indonésie","Maldives"],c:2,f:""},
  {q:"Quelle est la capitale de l'Afrique du Sud ?",a:["Johannesburg","Cape Town","Durban","Pretoria"],c:3,f:""},
  {q:"Dans quel pays se trouve Angkor Wat ?",a:["Thaïlande","Vietnam","Myanmar","Cambodge"],c:3,f:""},
  {q:"Quel est le plus long fleuve d'Amérique du Sud ?",a:["Orénoque","Amazone","Paraguay","Paraná"],c:1,f:""},
  {q:"Quelle est la capitale de l'Argentine ?",a:["Santiago","Lima","Montevideo","Buenos Aires"],c:3,f:""},
  {q:"Dans quel pays se trouve le lac Titicaca ?",a:["Pérou et Bolivie","Chili","Équateur","Colombie"],c:0,f:""},
  {q:"Quel est le plus grand pays d'Afrique ?",a:["Congo","Soudan","Algérie","Libye"],c:2,f:""},
  {q:"Quelle est la capitale du Portugal ?",a:["Porto","Lisbonne","Braga","Faro"],c:1,f:""},
  {q:"Dans quel pays se trouve le Grand Canyon ?",a:["Canada","Mexique","États-Unis","Brésil"],c:2,f:""},
  {q:"Quel est le plus petit pays du monde ?",a:["Monaco","Saint-Marin","Liechtenstein","Vatican"],c:3,f:""},
  {q:"Quelle est la capitale de la Turquie ?",a:["Istanbul","Izmir","Ankara","Bursa"],c:2,f:""},
  {q:"Dans quel pays se trouve le volcan Etna ?",a:["Grèce","Espagne","Portugal","Italie"],c:3,f:""},
  {q:"Quel est le plus grand fleuve d'Afrique ?",a:["Congo","Niger","Nil","Zambèze"],c:2,f:""},
  {q:"Quelle est la capitale de la Suède ?",a:["Oslo","Copenhague","Helsinki","Stockholm"],c:3,f:""},
  {q:"Dans quel pays se trouve le Sphinx de Gizeh ?",a:["Libye","Égypte","Tunisie","Maroc"],c:1,f:""},
  {q:"Quel est le plus long fleuve de France ?",a:["Rhône","Garonne","Seine","Loire"],c:3,f:""},
  {q:"Quelle est la capitale de la Norvège ?",a:["Bergen","Oslo","Stavanger","Trondheim"],c:1,f:""},
  {q:"Dans quel pays se trouve l'Acropole ?",a:["Italie","Grèce","Turquie","Croatie"],c:1,f:""},
  {q:"Quel est le plus haut plateau du monde ?",a:["Plateau de l'Anatolie","Plateau iranien","Plateau tibétain","Plateau de Mongolie"],c:2,f:""},
  {q:"Quelle est la capitale de la Pologne ?",a:["Cracovie","Gdansk","Varsovie","Wroclaw"],c:2,f:""},
  {q:"Dans quel pays se trouve le fjord de Milford Sound ?",a:["Norvège","Canada","Nouvelle-Zélande","Islande"],c:3,f:""},
  {q:"Quel est le plus grand golfe du monde ?",a:["Golfe du Mexique","Golfe Persique","Golfe de Guinée","Golfe du Bengale"],c:3,f:""},
  {q:"Quelle est la capitale de l'Égypte ?",a:["Alexandrie","Louxor","Le Caire","Assouan"],c:2,f:""},
  {q:"Dans quel pays se trouve le lac Baïkal ?",a:["Chine","Mongolie","Kazakhstan","Russie"],c:3,f:""},
  {q:"Quel est le plus grand pays d'Amérique du Sud ?",a:["Argentine","Colombie","Pérou","Brésil"],c:3,f:""},
  {q:"Quelle est la capitale de la Grèce ?",a:["Thessalonique","Héraklion","Athènes","Patras"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Petra ?",a:["Israël","Égypte","Jordanie","Arabie saoudite"],c:2,f:""},
  {q:"Quel est le plus grand pays d'Europe ?",a:["France","Ukraine","Russie","Kazakstan"],c:2,f:""},
  {q:"Quelle est la capitale de la Belgique ?",a:["Anvers","Gand","Liège","Bruxelles"],c:3,f:""},
  {q:"Dans quel pays se trouve la statue de la Liberté (offerte par) ?",a:["France","Royaume-Uni","Allemagne","Italie"],c:0,f:""},
  {q:"Quel est le plus long fleuve d'Amérique du Nord ?",a:["Colorado","Missouri-Mississippi","Rio Grande","Columbia"],c:1,f:""},
  {q:"Quelle est la capitale de la Suisse ?",a:["Genève","Zurich","Lausanne","Berne"],c:3,f:""},
  {q:"Dans quel pays se trouve le Serengeti ?",a:["Kenya","Tanzanie","Namibie","Botswana"],c:1,f:""},
  {q:"Quel est le plus grand lac d'Europe ?",a:["Lac de Constance","Lac Ladoga","Lac Léman","Lac Onega"],c:1,f:""},
  {q:"Quelle est la capitale de l'Iran ?",a:["Ispahan","Shiraz","Tabriz","Téhéran"],c:3,f:""},
  {q:"Dans quel pays se trouve Carthage (ancienne) ?",a:["Libye","Tunisie","Maroc","Algérie"],c:1,f:""},
  {q:"Quel est le plus haut sommet d'Afrique ?",a:["Mont Kenya","Kilimandjaro","Mont Cameroun","Ras Dashen"],c:1,f:""},
  {q:"Quelle est la capitale de l'Autriche ?",a:["Salzbourg","Vienne","Graz","Linz"],c:1,f:""},
  {q:"Dans quel pays se trouve l'île de Pâques ?",a:["Pérou","Polynésie française","Chili","Équateur"],c:2,f:""},
  {q:"Quel est le plus grand fleuve d'Europe ?",a:["Rhin","Danube","Volga","Don"],c:2,f:""},
  {q:"Quelle est la capitale du Pakistan ?",a:["Karachi","Lahore","Islamabad","Rawalpindi"],c:2,f:""},
  {q:"Dans quel pays se trouve le fleuve Amazone ?",a:["Venezuela","Colombie","Brésil et Pérou","Équateur"],c:2,f:""},
  {q:"Quel est le plus grand lac d'Amérique du Nord ?",a:["Lac Huron","Lac Michigan","Lac Supérieur","Lac Ontario"],c:2,f:""},
  {q:"Quelle est la capitale de la Hongrie ?",a:["Prague","Vienne","Budapest","Bratislava"],c:2,f:""},
  {q:"Dans quel pays se trouve le volcan Popocatépetl ?",a:["Guatemala","Nicaragua","Mexique","Costa Rica"],c:2,f:""},
  {q:"Quel est le plus long fleuve d'Australie ?",a:["Darling","Murray","Murrumbidgee","Lachlan"],c:1,f:""},
  {q:"Quelle est la capitale de l'Indonésie ?",a:["Surabaya","Bandung","Jakarta","Medan"],c:2,f:""},
  {q:"Dans quel pays se trouve le désert d'Atacama ?",a:["Pérou","Bolivie","Chili","Argentine"],c:2,f:""},
  {q:"Quel est le plus haut sommet d'Europe ?",a:["Mont Rosa","Mont Blanc","Elbrouz","Matterhorn"],c:2,f:""},
  {q:"Quelle est la capitale de l'Ukraine ?",a:["Lviv","Odessa","Kharkiv","Kiev"],c:3,f:""},
  // ─── Nouvelles questions (97-200) ───────────────────────────────
  {q:"Quel pays a un drapeau composé uniquement de rouge et blanc avec un cercle central ?",a:["Chine","Corée du Sud","Japon","Bangladesh"],c:2,f:""},
  {q:"Quelle est la monnaie officielle du Royaume-Uni ?",a:["Euro","Dollar","Livre sterling","Couronne"],c:2,f:""},
  {q:"Quel pays insulaire est le plus peuplé du monde ?",a:["Philippines","Madagascar","Japon","Indonésie"],c:3,f:""},
  {q:"Lequel de ces pays est enclavé (sans accès à la mer) ?",a:["Paraguay","Colombie","Uruguay","Venezuela"],c:0,f:""},
  {q:"Quel détroit sépare l'Europe de l'Asie à Istanbul ?",a:["Détroit de Gibraltar","Détroit de Malacca","Bosphore","Détroit d'Ormuz"],c:2,f:""},
  {q:"Dans quel pays se trouve le parc national de Yellowstone ?",a:["Canada","Mexique","États-Unis","Brésil"],c:2,f:""},
  {q:"Quel site UNESCO se trouve à Agra en Inde ?",a:["Angkor Wat","Taj Mahal","Borobudur","Sigiriya"],c:1,f:""},
  {q:"Quel type de climat caractérise la forêt amazonienne ?",a:["Tempéré","Méditerranéen","Équatorial","Polaire"],c:2,f:""},
  {q:"Quel est le pays le plus peuplé du monde ?",a:["États-Unis","Inde","Chine","Indonésie"],c:1,f:""},
  {q:"Quel est le lac le plus profond du monde ?",a:["Lac Tanganyika","Lac Supérieur","Mer Caspienne","Lac Baïkal"],c:3,f:""},
  {q:"Quel canal relie la mer Méditerranée à la mer Rouge ?",a:["Canal de Panama","Canal de Suez","Canal de Kiel","Canal de Corinthe"],c:1,f:""},
  {q:"Combien de fuseaux horaires la Russie couvre-t-elle ?",a:["5","8","11","15"],c:2,f:""},
  {q:"Quel pays africain a pour capitale Nairobi ?",a:["Tanzanie","Ouganda","Kenya","Éthiopie"],c:2,f:""},
  {q:"Quel est le plus grand pays d'Asie du Sud-Est ?",a:["Thaïlande","Vietnam","Myanmar","Indonésie"],c:3,f:""},
  {q:"Quelle est la plus haute cascade du monde ?",a:["Chutes du Niagara","Salto Angel","Chutes Victoria","Chutes d'Iguazu"],c:1,f:""},
  {q:"Quel pays possède un drapeau avec une feuille d'érable ?",a:["Australie","Nouvelle-Zélande","Canada","États-Unis"],c:2,f:""},
  {q:"Quelle est la monnaie du Japon ?",a:["Won","Yuan","Yen","Ringgit"],c:2,f:""},
  {q:"Quel pays insulaire se situe au sud de l'Inde ?",a:["Maldives","Sri Lanka","Madagascar","Seychelles"],c:1,f:""},
  {q:"Lequel de ces pays africains est enclavé ?",a:["Cameroun","Mali","Sénégal","Nigeria"],c:1,f:""},
  {q:"Quel détroit sépare l'Afrique de l'Europe ?",a:["Bosphore","Détroit de Gibraltar","Détroit de Magellan","Détroit de Béring"],c:1,f:""},
  {q:"Dans quel pays se trouve le parc national de Kruger ?",a:["Namibie","Zimbabwe","Afrique du Sud","Botswana"],c:2,f:""},
  {q:"La Grande Barrière de corail est un site UNESCO situé où ?",a:["Indonésie","Philippines","Fidji","Australie"],c:3,f:""},
  {q:"Quel climat caractérise le pourtour méditerranéen ?",a:["Continental","Océanique","Méditerranéen","Subarctique"],c:2,f:""},
  {q:"Quel est le continent le moins peuplé (hors Antarctique) ?",a:["Amérique du Sud","Europe","Asie","Océanie"],c:3,f:""},
  {q:"Quel est le point le plus bas sur terre (sur la croûte terrestre) ?",a:["Vallée de la Mort","Mer Morte","Lac Assal","Fosse des Mariannes"],c:1,f:""},
  {q:"Quel pays a le plus de frontières terrestres au monde ?",a:["Brésil","Russie","Chine","Allemagne"],c:2,f:""},
  {q:"Quel pays a un drapeau vert avec un croissant et une étoile blancs ?",a:["Turquie","Algérie","Pakistan","Arabie saoudite"],c:2,f:""},
  {q:"Quelle est la monnaie utilisée dans la zone euro ?",a:["Dollar","Franc","Livre","Euro"],c:3,f:""},
  {q:"Quel État insulaire du Pacifique a pour capitale Suva ?",a:["Tonga","Samoa","Fidji","Vanuatu"],c:2,f:""},
  {q:"Lequel de ces pays européens est enclavé ?",a:["Danemark","Suisse","Portugal","Roumanie"],c:1,f:""},
  {q:"Quel canal relie l'océan Atlantique à l'océan Pacifique ?",a:["Canal de Suez","Canal de Kiel","Canal de Corinthe","Canal de Panama"],c:3,f:""},
  {q:"Dans quel pays se trouve le parc national de Banff ?",a:["États-Unis","Islande","Canada","Norvège"],c:2,f:""},
  {q:"Dans quel pays se trouvent les temples de Bagan, site UNESCO ?",a:["Cambodge","Thaïlande","Myanmar","Laos"],c:2,f:""},
  {q:"Quel type de climat trouve-t-on en Sibérie ?",a:["Tropical","Désertique","Continental froid","Méditerranéen"],c:2,f:""},
  {q:"Quel est le pays le plus densément peuplé du monde ?",a:["Singapour","Monaco","Bangladesh","Inde"],c:1,f:""},
  {q:"Quelle est la plus grande île du monde (hors continent) ?",a:["Bornéo","Madagascar","Groenland","Nouvelle-Guinée"],c:2,f:""},
  {q:"Quel pays partage la plus longue frontière avec les États-Unis ?",a:["Mexique","Canada","Cuba","Bahamas"],c:1,f:""},
  {q:"Quel fuseau horaire a le plus grand décalage avec le méridien de Greenwich ?",a:["UTC+10","UTC-12","UTC+14","UTC+8"],c:2,f:""},
  {q:"Quel pays africain a pour capitale Addis-Abeba ?",a:["Somalie","Soudan","Érythrée","Éthiopie"],c:3,f:""},
  {q:"Quel est le fleuve le plus long d'Asie du Sud-Est ?",a:["Irrawaddy","Chao Phraya","Mékong","Rivière Rouge"],c:2,f:""},
  {q:"Quelle montagne est le plus haut sommet d'Amérique ?",a:["Mont McKinley","Aconcagua","Mont Logan","Chimborazo"],c:1,f:""},
  {q:"De quel pays le drapeau comporte trois bandes horizontales noir, rouge et or ?",a:["Belgique","Allemagne","Autriche","Espagne"],c:1,f:""},
  {q:"Quelle est la monnaie de l'Inde ?",a:["Roupie","Taka","Ringit","Baht"],c:0,f:""},
  {q:"Quel pays insulaire a pour capitale Antananarivo ?",a:["Comores","Maurice","Seychelles","Madagascar"],c:3,f:""},
  {q:"Lequel de ces pays d'Asie centrale est enclavé ?",a:["Iran","Pakistan","Ouzbékistan","Inde"],c:2,f:""},
  {q:"Quel détroit relie la mer de Marmara à la mer Noire ?",a:["Bosphore","Dardanelles","Gibraltar","Messine"],c:0,f:""},
  {q:"Dans quel pays se trouve le parc national de Fiordland ?",a:["Chili","Norvège","Islande","Nouvelle-Zélande"],c:3,f:""},
  {q:"La vieille ville de Dubrovnik, site UNESCO, se trouve dans quel pays ?",a:["Monténégro","Slovénie","Croatie","Grèce"],c:2,f:""},
  {q:"Quel type de climat domine en Arabie saoudite ?",a:["Tropical humide","Désertique","Tempéré","Polaire"],c:1,f:""},
  {q:"Quel pays a la plus grande espérance de vie au monde ?",a:["Suisse","Japon","Islande","Singapour"],c:1,f:""},
  {q:"Quel est le point culminant de l'Océanie ?",a:["Mont Cook","Puncak Jaya","Mauna Kea","Mont Wilhelm"],c:1,f:""},
  {q:"Quel pays possède des frontières avec 14 autres pays ?",a:["Russie","Brésil","Inde","Chine"],c:3,f:""},
  {q:"Quel pays a un drapeau avec un soleil à 32 rayons ?",a:["Argentine","Uruguay","Macédoine du Nord","Kazakhstan"],c:2,f:""},
  {q:"Quelle est la monnaie de la Chine ?",a:["Yen","Won","Yuan (renminbi)","Dong"],c:2,f:""},
  {q:"Quel est le plus petit pays insulaire du monde ?",a:["Nauru","Tuvalu","Maldives","Palau"],c:0,f:""},
  {q:"Lequel de ces pays est enclavé en Afrique australe ?",a:["Mozambique","Zambie","Lesotho","Tanzanie"],c:2,f:""},
  {q:"Quel détroit sépare l'Asie de l'Amérique du Nord ?",a:["Détroit de Magellan","Détroit de Malacca","Détroit de Béring","Détroit de Torrès"],c:2,f:""},
  {q:"Le parc national de Komodo est célèbre pour ses dragons ; dans quel pays ?",a:["Philippines","Malaisie","Thaïlande","Indonésie"],c:3,f:""},
  {q:"Dans quel pays se trouve Tombouctou, ville historique inscrite à l'UNESCO ?",a:["Niger","Sénégal","Mali","Burkina Faso"],c:2,f:""},
  {q:"Quel type de climat trouve-t-on en Islande ?",a:["Méditerranéen","Océanique froid","Tropical","Désertique"],c:1,f:""},
  {q:"Quel est le pays le plus peuplé d'Afrique ?",a:["Éthiopie","Égypte","Afrique du Sud","Nigeria"],c:3,f:""},
  {q:"Quelle est la fosse océanique la plus profonde du monde ?",a:["Fosse de Porto Rico","Fosse des Kouriles","Fosse des Mariannes","Fosse de Java"],c:2,f:""},
  {q:"Combien de pays l'Allemagne a-t-elle comme voisins frontaliers ?",a:["6","7","9","11"],c:2,f:""},
  {q:"Quel pays utilise le franc CFA en Afrique de l'Ouest ?",a:["Ghana","Nigeria","Sénégal","Afrique du Sud"],c:2,f:""},
  {q:"Quelle île-nation se trouve au large de la côte est de l'Afrique dans l'océan Indien ?",a:["Cuba","Sri Lanka","Fidji","Madagascar"],c:3,f:""},
  {q:"Lequel de ces pays d'Amérique du Sud est enclavé ?",a:["Bolivie","Équateur","Guyana","Suriname"],c:0,f:""},
  {q:"Quel détroit relie la mer Méditerranée à l'océan Atlantique ?",a:["Détroit de Béring","Détroit d'Ormuz","Détroit de Malacca","Détroit de Gibraltar"],c:3,f:""},
  {q:"Dans quel pays se trouve le parc national de Galápagos ?",a:["Colombie","Pérou","Équateur","Chili"],c:2,f:""},
  {q:"La cité de Cuzco, ancienne capitale inca et site UNESCO, est dans quel pays ?",a:["Bolivie","Colombie","Pérou","Équateur"],c:2,f:""},
  {q:"Quel climat domine dans le sud de la Scandinavie ?",a:["Continental","Océanique","Méditerranéen","Subarctique"],c:1,f:""},
  {q:"Quel pays a le taux de natalité le plus faible au monde ?",a:["Corée du Sud","Japon","Italie","Allemagne"],c:0,f:""},
  {q:"Quel est le plus grand désert froid du monde ?",a:["Gobi","Patagonie","Sahara","Antarctique"],c:3,f:""},
  {q:"Quel pays africain a pour capitale Dakar ?",a:["Mali","Gambie","Sénégal","Guinée"],c:2,f:""},
  {q:"Quel est le plus haut sommet du Japon ?",a:["Mont Kita","Mont Hotaka","Mont Fuji","Mont Tsurugi"],c:2,f:""},
  {q:"Quel pays possède un drapeau à croix blanche sur fond rouge ?",a:["Danemark","Autriche","Suisse","Pologne"],c:2,f:""},
  {q:"Quelle est la monnaie du Brésil ?",a:["Peso","Real","Sol","Bolivar"],c:1,f:""},
  {q:"Quel pays insulaire des Caraïbes a pour capitale La Havane ?",a:["Jamaïque","République dominicaine","Cuba","Porto Rico"],c:2,f:""},
  {q:"Lequel de ces pays est enclavé en Europe centrale ?",a:["Slovénie","Croatie","Autriche","Roumanie"],c:2,f:""},
  {q:"Quel détroit sépare le Yémen de Djibouti ?",a:["Détroit de Malacca","Détroit d'Ormuz","Bab-el-Mandeb","Détroit de Mozambique"],c:2,f:""},
  {q:"Dans quel pays africain se trouve le parc national du Serengeti ?",a:["Kenya","Ouganda","Tanzanie","Rwanda"],c:2,f:""},
  {q:"Les chutes Victoria, site UNESCO, se trouvent à la frontière de quels pays ?",a:["Congo et Angola","Zambie et Zimbabwe","Tanzanie et Kenya","Mozambique et Malawi"],c:1,f:""},
  {q:"Quel climat caractérise la steppe de Mongolie ?",a:["Tropical","Océanique","Continental aride","Polaire"],c:2,f:""},
  {q:"Quel est le pays le plus peuplé d'Amérique du Sud ?",a:["Argentine","Colombie","Brésil","Pérou"],c:2,f:""},
  {q:"Quel est le plus vaste récif corallien du monde ?",a:["Récif mésoaméricain","Grande Barrière de corail","Récif de Nouvelle-Calédonie","Récif de la mer Rouge"],c:1,f:""},
  {q:"Quel pays asiatique a pour capitale Oulan-Bator ?",a:["Kazakhstan","Kirghizistan","Mongolie","Turkménistan"],c:2,f:""},
  {q:"Quel fleuve forme une grande partie de la frontière entre les États-Unis et le Mexique ?",a:["Colorado","Mississippi","Rio Grande","Columbia"],c:2,f:""},
  {q:"Quelle est la monnaie de la Russie ?",a:["Hryvnia","Rouble","Zloty","Couronne"],c:1,f:""},
  {q:"Quel petit État insulaire du Pacifique risque de disparaître à cause de la montée des eaux ?",a:["Fidji","Samoa","Tonga","Tuvalu"],c:3,f:""},
  {q:"Lequel de ces pays asiatiques est enclavé ?",a:["Vietnam","Laos","Cambodge","Myanmar"],c:1,f:""},
  {q:"Quel est le nom du passage maritime entre la Malaisie et l'Indonésie ?",a:["Détroit de Béring","Détroit de Malacca","Détroit de Torrès","Détroit de Formose"],c:1,f:""},
  {q:"Le parc national de Zhangjiajie, qui a inspiré le film Avatar, se trouve dans quel pays ?",a:["Thaïlande","Vietnam","Chine","Corée du Sud"],c:2,f:""},
  {q:"La ville de Fès, site UNESCO célèbre pour sa médina, se trouve dans quel pays ?",a:["Tunisie","Algérie","Maroc","Libye"],c:2,f:""},
  {q:"Quel type de climat trouve-t-on dans le sud du Chili ?",a:["Désertique","Tropical","Océanique tempéré","Continental"],c:2,f:""},
  {q:"Quelle est la capitale la plus haute du monde en altitude ?",a:["Quito","Bogota","La Paz","Katmandou"],c:2,f:""},
  {q:"Quel est le volcan le plus actif d'Europe ?",a:["Vésuve","Stromboli","Etna","Hekla"],c:2,f:""},
  {q:"Quel pays africain a pour capitale Maputo ?",a:["Angola","Malawi","Mozambique","Zimbabwe"],c:2,f:""},
  {q:"Quel est le plus grand lac d'Asie ?",a:["Lac Baïkal","Mer d'Aral","Lac Balkhach","Mer Caspienne"],c:3,f:""},
  {q:"De quel pays le drapeau est composé de bandes horizontales bleu, blanc et rouge (de haut en bas) ?",a:["Russie","Pays-Bas","France","Luxembourg"],c:3,f:""},
  {q:"Quelle est la monnaie de la Suisse ?",a:["Euro","Franc suisse","Mark","Couronne"],c:1,f:""},
  {q:"Quel pays insulaire est situé entre la Malaisie et les Philippines ?",a:["Timor oriental","Brunei","Singapour","Taïwan"],c:1,f:""},
  {q:"Quelle ville est traversée par le méridien de Greenwich ?",a:["Paris","Londres","Berlin","Amsterdam"],c:1,f:""},
  {q:"Quel pays d'Afrique de l'Est a pour capitale Kigali ?",a:["Burundi","Ouganda","Rwanda","Tanzanie"],c:2,f:""},
  {q:"Quel est le plus haut sommet de l'Amérique du Nord ?",a:["Mont Logan","Mont Whitney","Denali","Mont Rainier"],c:2,f:""},
  {q:"Quel pays possède un drapeau avec un dragon ?",a:["Mongolie","Bhoutan","Népal","Tibet"],c:1,f:""},
  {q:"Quelle est la monnaie de la Corée du Sud ?",a:["Yen","Baht","Won","Dong"],c:2,f:""}
];
