/* ════════════════════════════════════════
   questions/geo.js — Géographie — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.geo = [
  {q:"Quelle est la capitale de la France ?",a:["Lyon","Marseille","Paris","Toulouse"],c:2,f:""},
  {q:"Quel est le plus grand océan de la planète ?",a:["Atlantique","Indien","Pacifique","Arctique"],c:2,f:""},
  {q:"Quel fleuve traverse la ville de Londres ?",a:["Rhin","Tamise","Danube","Seine"],c:1,f:""},
  {q:"Quel est le plus grand pays du monde par superficie ?",a:["Canada","Chine","Russie","États-Unis"],c:2,f:""},
  {q:"Quelle chaîne de montagnes sépare la France et l'Espagne ?",a:["Alpes","Pyrénées","Carpates","Apennins"],c:1,f:""},
  {q:"Quelle est la capitale du Japon ?",a:["Osaka","Kyoto","Tokyo","Nagoya"],c:2,f:""},
  {q:"Quel est le plus long fleuve du monde ?",a:["Amazone","Nil","Yangtsé","Mississippi"],c:1,f:""},
  {q:"Quel est le plus haut sommet du monde ?",a:["K2","Mont Everest","Kangchenjunga","Mont Blanc"],c:1,f:""},
  {q:"Quel pays a la forme d'une botte ?",a:["Espagne","Italie","Portugal","Grèce"],c:1,f:""},
  {q:"Quelle est la capitale de l'Allemagne ?",a:["Munich","Hambourg","Berlin","Cologne"],c:2,f:""},
  {q:"Sur quel continent se trouve l'Égypte ?",a:["Europe","Asie","Afrique","Amérique"],c:2,f:""},
  {q:"Quel fleuve traverse la ville de Paris ?",a:["Rhin","Loire","Seine","Rhône"],c:2,f:""},
  {q:"Quelle est la capitale du Canada ?",a:["Toronto","Montréal","Ottawa","Vancouver"],c:2,f:""},
  {q:"Quel est le plus grand continent ?",a:["Afrique","Amérique du Nord","Asie","Europe"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Barcelone ?",a:["Portugal","Espagne","Italie","France"],c:1,f:""},
  {q:"Quel océan borde la côte ouest des États-Unis ?",a:["Atlantique","Pacifique","Indien","Arctique"],c:1,f:""},
  {q:"Quelle est la capitale du Royaume-Uni ?",a:["Manchester","Liverpool","Londres","Birmingham"],c:2,f:""},
  {q:"Dans quel pays se trouve la Grande Muraille ?",a:["Japon","Corée du Sud","Chine","Mongolie"],c:2,f:""},
  {q:"Quelle est la capitale de l'Espagne ?",a:["Barcelone","Valence","Madrid","Séville"],c:2,f:""},
  {q:"Sur quel continent se trouve l'Argentine ?",a:["Europe","Afrique","Amérique du Sud","Asie"],c:2,f:""},
  {q:"Quelle mer borde la côte sud de la France ?",a:["Mer Noire","Mer Méditerranée","Mer Baltique","Mer Rouge"],c:1,f:""},
  {q:"Quel est le plus grand lac d'Afrique ?",a:["Lac Tanganyika","Lac Victoria","Lac Malawi","Lac Tchad"],c:1,f:""},
  {q:"Quelle est la capitale des États-Unis ?",a:["New York","Los Angeles","Washington D.C.","Chicago"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Dubaï ?",a:["Qatar","Émirats arabes unis","Oman","Arabie saoudite"],c:1,f:""},
  {q:"Quelle est la capitale de l'Australie ?",a:["Sydney","Melbourne","Canberra","Perth"],c:2,f:""},
  {q:"Quel fleuve traverse l'Égypte ?",a:["Tigre","Congo","Nil","Niger"],c:2,f:""},
  {q:"Dans quel pays se trouve le mont Fuji ?",a:["Chine","Corée","Japon","Vietnam"],c:2,f:""},
  {q:"Quelle est la capitale du Brésil ?",a:["Rio de Janeiro","São Paulo","Brasilia","Salvador"],c:2,f:""},
  {q:"Quel est le plus petit continent ?",a:["Europe","Australie/Océanie","Antarctique","Amérique du Sud"],c:1,f:""},
  {q:"Dans quel pays se trouve la ville de Buenos Aires ?",a:["Chili","Uruguay","Brésil","Argentine"],c:3,f:""},
  {q:"Quel est le plus grand désert chaud du monde ?",a:["Gobi","Kalahari","Sahara","Arabie"],c:2,f:""},
  {q:"Quelle est la capitale de la Russie ?",a:["Saint-Pétersbourg","Moscou","Kiev","Minsk"],c:1,f:""},
  {q:"Dans quel pays se trouve le Machu Picchu ?",a:["Mexique","Colombie","Pérou","Bolivie"],c:2,f:""},
  {q:"Quel est le plus long fleuve d'Europe ?",a:["Rhin","Danube","Volga","Loire"],c:2,f:""},
  {q:"Quelle est la capitale de la Chine ?",a:["Shanghai","Hong Kong","Pékin","Canton"],c:2,f:""},
  {q:"Dans quel pays se trouve le Taj Mahal ?",a:["Pakistan","Bangladesh","Inde","Sri Lanka"],c:2,f:""},
  {q:"Quel est le plus grand lac du monde ?",a:["Lac Supérieur","Lac Victoria","Mer Caspienne","Lac Baïkal"],c:2,f:""},
  {q:"Quelle est la capitale de l'Inde ?",a:["Mumbai","Kolkata","Chennai","New Delhi"],c:3,f:""},
  {q:"Dans quel pays se trouve Amsterdam ?",a:["Belgique","Allemagne","Pays-Bas","Danemark"],c:2,f:""},
  {q:"Quel est le plus haut volcan du monde ?",a:["Vésuve","Etna","Mauna Kea","Ojos del Salado"],c:3,f:""},
  {q:"Quelle est la capitale du Mexique ?",a:["Guadalajara","Cancún","Mexico","Monterrey"],c:2,f:""},
  {q:"Dans quel pays se trouve le désert de Gobi ?",a:["Chine et Mongolie","Russie","Kazakhstan","Inde"],c:0,f:""},
  {q:"Quel est le plus long fleuve d'Asie ?",a:["Gange","Yangtsé","Mékong","Fleuve Jaune"],c:1,f:""},
  {q:"Quelle est la capitale de la Corée du Sud ?",a:["Busan","Incheon","Seoul","Daegu"],c:2,f:""},
  {q:"Dans quel pays se trouve le mont Kilimandjaro ?",a:["Kenya","Tanzanie","Éthiopie","Uganda"],c:1,f:""},
  {q:"Quel est le plus grand archipel du monde ?",a:["Japon","Philippines","Indonésie","Maldives"],c:2,f:""},
  {q:"Quelle est la capitale de l'Afrique du Sud ?",a:["Johannesburg","Cape Town","Durban","Pretoria"],c:3,f:""},
  {q:"Dans quel pays se trouve Angkor Wat ?",a:["Thaïlande","Vietnam","Myanmar","Cambodge"],c:3,f:""},
  {q:"Quel est le plus long fleuve d'Amérique du Sud ?",a:["Orénoque","Amazone","Paraguay","Paraná"],c:1,f:""},
  {q:"Quelle est la capitale de l'Argentine ?",a:["Santiago","Lima","Montevideo","Buenos Aires"],c:3,f:""},
  {q:"Dans quel pays se trouve le lac Titicaca ?",a:["Pérou et Bolivie","Chili","Équateur","Colombie"],c:0,f:""},
  {q:"Quel est le plus grand pays d'Afrique ?",a:["Congo","Soudan","Algérie","Libye"],c:2,f:""},
  {q:"Quelle est la capitale du Portugal ?",a:["Porto","Lisbonne","Braga","Faro"],c:1,f:""},
  {q:"Dans quel pays se trouve le Grand Canyon ?",a:["Canada","Mexique","États-Unis","Brésil"],c:2,f:""},
  {q:"Quel est le plus petit pays du monde ?",a:["Monaco","Saint-Marin","Liechtenstein","Vatican"],c:3,f:""},
  {q:"Quelle est la capitale de la Turquie ?",a:["Istanbul","Izmir","Ankara","Bursa"],c:2,f:""},
  {q:"Dans quel pays se trouve le volcan Etna ?",a:["Grèce","Espagne","Portugal","Italie"],c:3,f:""},
  {q:"Quel est le plus grand fleuve d'Afrique ?",a:["Congo","Niger","Nil","Zambèze"],c:2,f:""},
  {q:"Quelle est la capitale de la Suède ?",a:["Oslo","Copenhague","Helsinki","Stockholm"],c:3,f:""},
  {q:"Dans quel pays se trouve le Sphinx de Gizeh ?",a:["Libye","Égypte","Tunisie","Maroc"],c:1,f:""},
  {q:"Quel est le plus long fleuve de France ?",a:["Rhône","Garonne","Seine","Loire"],c:3,f:""},
  {q:"Quelle est la capitale de la Norvège ?",a:["Bergen","Oslo","Stavanger","Trondheim"],c:1,f:""},
  {q:"Dans quel pays se trouve l'Acropole ?",a:["Italie","Grèce","Turquie","Croatie"],c:1,f:""},
  {q:"Quel est le plus haut plateau du monde ?",a:["Plateau de l'Anatolie","Plateau iranien","Plateau tibétain","Plateau de Mongolie"],c:2,f:""},
  {q:"Quelle est la capitale de la Pologne ?",a:["Cracovie","Gdansk","Varsovie","Wroclaw"],c:2,f:""},
  {q:"Dans quel pays se trouve le fjord de Milford Sound ?",a:["Norvège","Canada","Nouvelle-Zélande","Islande"],c:3,f:""},
  {q:"Quel est le plus grand golfe du monde ?",a:["Golfe du Mexique","Golfe Persique","Golfe de Guinée","Golfe du Bengale"],c:3,f:""},
  {q:"Quelle est la capitale de l'Égypte ?",a:["Alexandrie","Louxor","Le Caire","Assouan"],c:2,f:""},
  {q:"Dans quel pays se trouve le lac Baïkal ?",a:["Chine","Mongolie","Kazakhstan","Russie"],c:3,f:""},
  {q:"Quel est le plus grand pays d'Amérique du Sud ?",a:["Argentine","Colombie","Pérou","Brésil"],c:3,f:""},
  {q:"Quelle est la capitale de la Grèce ?",a:["Thessalonique","Héraklion","Athènes","Patras"],c:2,f:""},
  {q:"Dans quel pays se trouve la ville de Petra ?",a:["Israël","Égypte","Jordanie","Arabie saoudite"],c:2,f:""},
  {q:"Quel est le plus grand pays d'Europe ?",a:["France","Ukraine","Russie","Kazakstan"],c:2,f:""},
  {q:"Quelle est la capitale de la Belgique ?",a:["Anvers","Gand","Liège","Bruxelles"],c:3,f:""},
  {q:"Dans quel pays se trouve la statue de la Liberté (offerte par) ?",a:["France","Royaume-Uni","Allemagne","Italie"],c:0,f:""},
  {q:"Quel est le plus long fleuve d'Amérique du Nord ?",a:["Colorado","Missouri-Mississippi","Rio Grande","Columbia"],c:1,f:""},
  {q:"Quelle est la capitale de la Suisse ?",a:["Genève","Zurich","Lausanne","Berne"],c:3,f:""},
  {q:"Dans quel pays se trouve le Serengeti ?",a:["Kenya","Tanzanie","Namibie","Botswana"],c:1,f:""},
  {q:"Quel est le plus grand lac d'Europe ?",a:["Lac de Constance","Lac Ladoga","Lac Léman","Lac Onega"],c:1,f:""},
  {q:"Quelle est la capitale de l'Iran ?",a:["Ispahan","Shiraz","Tabriz","Téhéran"],c:3,f:""},
  {q:"Dans quel pays se trouve Carthage (ancienne) ?",a:["Libye","Tunisie","Maroc","Algérie"],c:1,f:""},
  {q:"Quel est le plus haut sommet d'Afrique ?",a:["Mont Kenya","Kilimandjaro","Mont Cameroun","Ras Dashen"],c:1,f:""},
  {q:"Quelle est la capitale de l'Autriche ?",a:["Salzbourg","Vienne","Graz","Linz"],c:1,f:""},
  {q:"Dans quel pays se trouve l'île de Pâques ?",a:["Pérou","Polynésie française","Chili","Équateur"],c:2,f:""},
  {q:"Quel est le plus grand fleuve d'Europe ?",a:["Rhin","Danube","Volga","Don"],c:2,f:""},
  {q:"Quelle est la capitale du Pakistan ?",a:["Karachi","Lahore","Islamabad","Rawalpindi"],c:2,f:""},
  {q:"Dans quel pays se trouve le fleuve Amazone ?",a:["Venezuela","Colombie","Brésil et Pérou","Équateur"],c:2,f:""},
  {q:"Quel est le plus grand lac d'Amérique du Nord ?",a:["Lac Huron","Lac Michigan","Lac Supérieur","Lac Ontario"],c:2,f:""},
  {q:"Quelle est la capitale de la Hongrie ?",a:["Prague","Vienne","Budapest","Bratislava"],c:2,f:""},
  {q:"Dans quel pays se trouve le volcan Popocatépetl ?",a:["Guatemala","Nicaragua","Mexique","Costa Rica"],c:2,f:""},
  {q:"Quel est le plus long fleuve d'Australie ?",a:["Darling","Murray","Murrumbidgee","Lachlan"],c:1,f:""},
  {q:"Quelle est la capitale de l'Indonésie ?",a:["Surabaya","Bandung","Jakarta","Medan"],c:2,f:""},
  {q:"Dans quel pays se trouve le désert d'Atacama ?",a:["Pérou","Bolivie","Chili","Argentine"],c:2,f:""},
  {q:"Quel est le plus haut sommet d'Europe ?",a:["Mont Rosa","Mont Blanc","Elbrouz","Matterhorn"],c:2,f:""},
  {q:"Quelle est la capitale de l'Ukraine ?",a:["Lviv","Odessa","Kharkiv","Kiev"],c:3,f:""},
];
