/* ════════════════════════════════════════
   questions/histoire.js — Histoire — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.histoire = [
  {q:"Qui était le premier empereur des Français ?",a:["Louis XIV","Napoléon Bonaparte","Louis XVI","Charles de Gaulle"],c:1,f:""},
  {q:"En quelle année a eu lieu la Révolution française ?",a:["1776","1789","1799","1815"],c:1,f:""},
  {q:"Quel mur a été détruit en 1989 ?",a:["Mur d'Hadrian","Mur de Berlin","Grande Muraille","Mur de Jéricho"],c:1,f:""},
  {q:"Quelle civilisation a construit les pyramides de Gizeh ?",a:["Grecs","Romains","Égyptiens","Perses"],c:2,f:""},
  {q:"En quelle année a commencé la Première Guerre mondiale ?",a:["1912","1914","1916","1918"],c:1,f:""},
  {q:"Quel explorateur a découvert l'Amérique en 1492 ?",a:["Vasco da Gama","Christophe Colomb","Ferdinand Magellan","James Cook"],c:1,f:""},
  {q:"En quelle année s'est terminée la Seconde Guerre mondiale ?",a:["1943","1944","1945","1946"],c:2,f:""},
  {q:"Qui était le chef de l'Allemagne nazie ?",a:["Adolf Hitler","Benito Mussolini","Joseph Staline","Francisco Franco"],c:0,f:""},
  {q:"En quelle année l'homme a-t-il marché sur la Lune ?",a:["1965","1969","1971","1975"],c:1,f:""},
  {q:"Quelle bataille a marqué la défaite finale de Napoléon ?",a:["Austerlitz","Waterloo","Trafalgar","Leipzig"],c:1,f:""},
  {q:"Qui était président des États-Unis pendant la guerre de Sécession ?",a:["George Washington","Abraham Lincoln","Thomas Jefferson","Theodore Roosevelt"],c:1,f:""},
  {q:"Quel événement a déclenché la Première Guerre mondiale ?",a:["Invasion de la Pologne","Assassinat de l'archiduc François-Ferdinand","Traité de Versailles","Révolution russe"],c:1,f:""},
  {q:"Quel traité a mis fin à la Première Guerre mondiale ?",a:["Traité de Rome","Traité de Versailles","Traité de Vienne","Traité de Tordesillas"],c:1,f:""},
  {q:"Quel pharaon avait un tombeau découvert en 1922 ?",a:["Ramsès II","Toutankhamon","Akhenaton","Thoutmôsis III"],c:1,f:""},
  {q:"Qui était le premier président de la Ve République française ?",a:["Georges Pompidou","Charles de Gaulle","François Mitterrand","Valéry Giscard d'Estaing"],c:1,f:""},
  {q:"Quelle catastrophe nucléaire a eu lieu en 1986 ?",a:["Fukushima","Tchernobyl","Three Mile Island","Hiroshima"],c:1,f:""},
  {q:"Qui a dirigé l'Inde vers l'indépendance avec une stratégie non violente ?",a:["Jawaharlal Nehru","Mahatma Gandhi","Indira Gandhi","Subhas Chandra Bose"],c:1,f:""},
  {q:"Quel pays était dirigé par Benito Mussolini ?",a:["Espagne","Allemagne","Italie","Portugal"],c:2,f:""},
  {q:"Quelle organisation a été créée en 1945 pour maintenir la paix ?",a:["OTAN","ONU","UNESCO","FMI"],c:1,f:""},
  {q:"Qui a dirigé la Révolution bolchévique en Russie ?",a:["Trotsky","Staline","Lénine","Kerenski"],c:2,f:""},
  {q:"En quelle année la France a-t-elle aboli l'esclavage définitivement ?",a:["1794","1815","1848","1905"],c:2,f:""},
  {q:"Quelle reine a régné le plus longtemps en Grande-Bretagne ?",a:["Victoria","Élisabeth I","Marie Tudor","Élisabeth II"],c:3,f:""},
  {q:"En quelle année a eu lieu l'attentat du 11 septembre ?",a:["1999","2000","2001","2002"],c:2,f:""},
  {q:"Qui a été le premier homme à orbiter autour de la Terre ?",a:["Neil Armstrong","Buzz Aldrin","Youri Gagarine","Alan Shepard"],c:2,f:""},
  {q:"Quelle ville a été détruite par l'éruption du Vésuve en 79 ap. J.-C. ?",a:["Rome","Pompéi","Naples","Herculanum"],c:1,f:""},
  {q:"En quelle année la Chine est-elle devenue une République populaire ?",a:["1945","1947","1949","1951"],c:2,f:""},
  {q:"Qui était le premier tsar de Russie ?",a:["Ivan IV (le Terrible)","Pierre le Grand","Catherine la Grande","Alexandre Ier"],c:0,f:""},
  {q:"Quelle guerre civile a opposé républicains et nationalistes en Espagne ?",a:["Guerre carliste","Guerre d'Espagne","Guerre civile espagnole","Reconquista"],c:2,f:""},
  {q:"En quelle année a eu lieu la chute de Constantinople ?",a:["1353","1453","1553","1653"],c:1,f:""},
  {q:"Qui a fondé l'Empire mongol ?",a:["Kublai Khan","Tamerlan","Gengis Khan","Timur"],c:2,f:""},
  {q:"En quelle année a été signée la Déclaration d'indépendance américaine ?",a:["1774","1775","1776","1777"],c:2,f:""},
  {q:"Quel général a reconquis la France après la bataille de la Marne en 1914 ?",a:["Foch","Joffre","Pétain","Gallieni"],c:1,f:""},
  {q:"Quelle est la date du débarquement en Normandie ?",a:["6 juin 1944","6 mai 1944","6 juin 1943","6 août 1944"],c:0,f:""},
  {q:"Qui était le premier président de la République française ?",a:["Louis-Napoléon Bonaparte","Adolphe Thiers","Patrice de Mac-Mahon","Jules Grévy"],c:0,f:""},
  {q:"En quelle année a été construite la Tour Eiffel ?",a:["1879","1887","1889","1891"],c:2,f:""},
  {q:"Quelle empire avait Rome comme capitale ?",a:["Empire grec","Empire romain","Empire byzantin","Empire ottoman"],c:1,f:""},
  {q:"Qui a conduit les Alliés vers la victoire en Europe lors de la 2e GM ?",a:["MacArthur","Eisenhower","Montgomery","Patton"],c:1,f:""},
  {q:"En quelle année Nelson Mandela est-il devenu président de l'Afrique du Sud ?",a:["1990","1992","1994","1996"],c:2,f:""},
  {q:"Qui était le premier ministre britannique pendant la Seconde Guerre mondiale ?",a:["Neville Chamberlain","Winston Churchill","Clement Attlee","Anthony Eden"],c:1,f:""},
  {q:"Quelle civilisation a développé l'écriture cunéiforme ?",a:["Égyptiens","Grecs","Sumériens","Phéniciens"],c:2,f:""},
  {q:"En quelle année a commencé la guerre du Vietnam pour les États-Unis ?",a:["1955","1961","1964","1968"],c:2,f:""},
  {q:"Qui était le dernier tsar de Russie ?",a:["Alexandre III","Nicolas II","Alexandre II","Nicolas I"],c:1,f:""},
  {q:"Quelle est la date de la prise de la Bastille ?",a:["14 juillet 1789","14 juillet 1790","14 juillet 1791","14 juillet 1792"],c:0,f:""},
  {q:"En quelle année a été créée la Communauté économique européenne (CEE) ?",a:["1951","1957","1963","1967"],c:1,f:""},
  {q:"Qui a été le premier président des États-Unis après la guerre civile ?",a:["Andrew Johnson","Ulysses Grant","Rutherford Hayes","James Garfield"],c:0,f:""},
  {q:"Quelle bataille a marqué la fin des guerres napoléoniennes ?",a:["Austerlitz","Borodino","Leipzig","Waterloo"],c:3,f:""},
  {q:"En quelle année l'Allemagne a-t-elle été réunifiée ?",a:["1988","1989","1990","1991"],c:2,f:""},
  {q:"Qui a été le premier leader de l'URSS ?",a:["Trotsky","Lénine","Staline","Khrouchtchev"],c:1,f:""},
  {q:"Quelle révolution a renversé la monarchie en France en 1848 ?",a:["Révolution de juillet","Révolution de février","Révolution de juin","Révolution d'octobre"],c:1,f:""},
  {q:"En quelle année a été fondée la République française (IIIe) ?",a:["1848","1870","1875","1880"],c:2,f:""},
  {q:"Qui a dirigé la Résistance française depuis Londres ?",a:["Jean Moulin","Charles de Gaulle","Henri Giraud","Pierre Mendès France"],c:1,f:""},
  {q:"Quelle civilisation a inventé l'alphabet phénicien ?",a:["Grecs","Phéniciens","Sumériens","Hébreux"],c:1,f:""},
  {q:"En quelle année a eu lieu la Révolution russe (bolchévique) ?",a:["1905","1914","1917","1920"],c:2,f:""},
  {q:"Qui était le roi de France pendant la Révolution française ?",a:["Louis XIV","Louis XV","Louis XVI","Louis XVII"],c:2,f:""},
  {q:"Quelle guerre a opposé la France et la Prusse en 1870 ?",a:["Guerre de Crimée","Guerre franco-prussienne","Guerre des Deux-Roses","Guerre de Sept Ans"],c:1,f:""},
  {q:"En quelle année a été lancé le premier Spoutnik ?",a:["1955","1957","1959","1961"],c:1,f:""},
  {q:"Qui a fondé la ville de Constantinople ?",a:["Dioclétien","Constantin Ier","Théodose","Justinien"],c:1,f:""},
  {q:"Quelle révolution industrielle a commencé en Angleterre au XVIIIe siècle ?",a:["Première","Deuxième","Troisième","Quatrième"],c:0,f:""},
  {q:"En quelle année la Société des Nations a-t-elle été créée ?",a:["1918","1919","1920","1921"],c:2,f:""},
  {q:"Qui était le chef de l'État français sous l'Occupation (gouvernement de Vichy) ?",a:["Pierre Laval","Joseph Darnand","Philippe Pétain","Fernand de Brinon"],c:2,f:""},
  {q:"Quelle guerre a abouti à la création d'Israël en 1948 ?",a:["Guerre des Six Jours","Guerre d'indépendance","Guerre de Kippour","Guerre du Liban"],c:1,f:""},
  {q:"En quelle année Napoléon Bonaparte est-il mort ?",a:["1815","1818","1821","1824"],c:2,f:""},
  {q:"Qui a découvert l'Amérique du Nord pour les Européens (avant Colomb) ?",a:["Erik le Rouge","Leif Erikson","Brendan l'Irlandais","Bjorn Ironside"],c:1,f:""},
  {q:"Quelle est la date de l'Armistice de la Première Guerre mondiale ?",a:["11 novembre 1918","11 novembre 1919","11 novembre 1917","11 octobre 1918"],c:0,f:""},
  {q:"En quelle année a été publié le Manifeste du Parti communiste ?",a:["1844","1848","1852","1856"],c:1,f:""},
  {q:"Qui était le président de la France pendant la Seconde Guerre mondiale (gouvernement en exil) ?",a:["Édouard Daladier","Paul Reynaud","Charles de Gaulle","Léon Blum"],c:2,f:""},
  {q:"Quelle période historique suit le Moyen Âge ?",a:["Antiquité","Renaissance","Époque moderne","Époque contemporaine"],c:1,f:""},
  {q:"En quelle année a commencé la Guerre froide ?",a:["1943","1945","1947","1949"],c:2,f:""},
  {q:"Qui a été le premier à faire le tour du monde par voie maritime ?",a:["Christophe Colomb","Magellan/Elcano","Vasco de Gama","James Cook"],c:1,f:""},
  {q:"Quelle ville a été le siège de la conférence de paix après la 1ère GM ?",a:["Genève","Vienne","Paris","Berlin"],c:2,f:""},
  {q:"En quelle année la Bastille a-t-elle été prise ?",a:["1787","1788","1789","1790"],c:2,f:""},
  {q:"Qui a dirigé la Chine après la Révolution culturelle ?",a:["Zhou Enlai","Deng Xiaoping","Jiang Zemin","Mao Zedong"],c:1,f:""},
  {q:"Quelle bataille de 1415 a vu la victoire anglaise sur les Français ?",a:["Crécy","Poitiers","Azincourt","Bouvines"],c:2,f:""},
  {q:"En quelle année le mur de Berlin a-t-il été érigé ?",a:["1959","1961","1963","1965"],c:1,f:""},
  {q:"Qui était le premier président américain noir ?",a:["Barack Obama","Jesse Jackson","Colin Powell","Condoleezza Rice"],c:0,f:""},
  {q:"Quelle guerre a été surnommée 'la Der des Ders' ?",a:["Guerre de Sécession","Première Guerre mondiale","Seconde Guerre mondiale","Guerre de Crimée"],c:1,f:""},
  {q:"En quelle année Jeanne d'Arc a-t-elle été brûlée vive ?",a:["1429","1430","1431","1432"],c:2,f:""},
  {q:"Qui a été assassiné à Dallas en 1963 ?",a:["Martin Luther King","Malcolm X","John F. Kennedy","Robert Kennedy"],c:2,f:""},
  {q:"Quelle civilisation a construit le Colisée ?",a:["Grecs","Romains","Étrusques","Carthaginois"],c:1,f:""},
  {q:"En quelle année a été signé le traité de Rome créant la CEE ?",a:["1955","1957","1959","1961"],c:1,f:""},
  {q:"Qui était le chef des forces alliées lors du débarquement de Normandie ?",a:["MacArthur","Patton","Eisenhower","Montgomery"],c:2,f:""},
  {q:"Quelle est la date de la chute de l'Empire romain d'Occident ?",a:["376","410","455","476"],c:3,f:""},
  {q:"En quelle année Charles de Gaulle est-il revenu au pouvoir ?",a:["1956","1957","1958","1959"],c:2,f:""},
  {q:"Qui était le roi de France lors de la bataille de Marignan (1515) ?",a:["Louis XII","François Ier","Henri II","Charles VIII"],c:1,f:""},
  {q:"Quelle nation a la première accordé le droit de vote aux femmes ?",a:["France","Royaume-Uni","Nouvelle-Zélande","États-Unis"],c:2,f:""},
  {q:"En quelle année a eu lieu l'Exposition universelle à Paris qui a vu la Tour Eiffel inaugurée ?",a:["1887","1889","1891","1893"],c:1,f:""},
  {q:"Qui a été le dernier roi de France ?",a:["Louis XVIII","Charles X","Louis-Philippe Ier","Napoléon III"],c:2,f:""},
  {q:"Quelle bataille de 1066 a conduit à la conquête normande de l'Angleterre ?",a:["Hastings","Stamford Bridge","Tinchebray","Lincoln"],c:0,f:""},
  {q:"En quelle année la Première République française a-t-elle été proclamée ?",a:["1789","1790","1792","1793"],c:2,f:""},
  {q:"Qui était le dernier roi de l'Égypte ancienne ?",a:["Cléopâtre VII","Ptolémée XV","Ptolémée XVI","Ramsès III"],c:0,f:""},
  {q:"Quelle ville a été fondée par Alexandre le Grand en Égypte ?",a:["Le Caire","Alexandrie","Louxor","Assouan"],c:1,f:""},
  {q:"En quelle année a eu lieu le massacre de la Saint-Barthélemy ?",a:["1562","1572","1582","1592"],c:1,f:""},
  {q:"Qui a été le premier secrétaire général de l'ONU ?",a:["Dag Hammarskjöld","Trygve Lie","U Thant","Kurt Waldheim"],c:1,f:""},
  {q:"Quelle guerre a opposé la Corée du Nord et la Corée du Sud ?",a:["Guerre du Vietnam","Guerre de Corée","Guerre froide","Guerre du Pacifique"],c:1,f:""},
  {q:"En quelle année a eu lieu la révolution de 1848 en France ?",a:["1846","1847","1848","1849"],c:2,f:""},
  {q:"Qui a été le premier ministre de l'Intérieur à instaurer la police nationale française ?",a:["Talleyrand","Fouché","Carnot","Sieyès"],c:1,f:""},
];
