/* ════════════════════════════════════════
   questions/hp.js — Harry Potter — 200 questions
   ════════════════════════════════════════ */
QUESTIONS.hp = [
  {q:"Dans quelle maison est Harry ?",a:["Serdaigle","Serpentard","Gryffondor","Poufsouffle"],c:2,f:""},
  {q:"Quel est le prenom du professeur Dumbledore ?",a:["Albert","Albus","Adrian","Arthur"],c:1,f:""},
  {q:"Quel est le sport joue sur balais volants ?",a:["Bludger","Quidditch","Nimbus","Cognard"],c:1,f:""},
  {q:"Comment s'appelle la banque des sorciers ?",a:["Gringotts","Ollivander","Azkaban","Durmstrang"],c:0,f:""},
  {q:"Quel est le prenom du meilleur ami masculin de Harry ?",a:["Ron","Fred","Percy","George"],c:0,f:""},
  {q:"Quel professeur enseigne les potions lors des premiers livres ?",a:["Lupin","Rogue","McGonagall","Flitwick"],c:1,f:""},
  {q:"Comment s'appelle l'elfe de maison ami de Harry ?",a:["Kreattur","Dobby","Winky","Hokey"],c:1,f:""},
  {q:"Quel est le nom de la prison des sorciers ?",a:["Durmstrang","Azkaban","Beauxbatons","Godric's Hollow"],c:1,f:""},
  {q:"Quel objet Harry recoit-il de son pere (cape) ?",a:["Une baguette","Une cape d'invisibilite","Un balai","Une carte"],c:1,f:""},
  {q:"Quel monstre vit dans la Chambre des Secrets ?",a:["Un basilic","Un dragon","Un troll","Un hippogriffe"],c:0,f:""},
  {q:"Quel sort sert a desarmer un adversaire ?",a:["Expelliarmus","Lumos","Stupefix","Alohomora"],c:0,f:""},
  {q:"Quel est le nom complet de Voldemort ?",a:["Tom Elvis Jedusor","Tom Marvolo Jedusor","Tom Marcus Jedusor","Tom Magnus Jedusor"],c:1,f:""},
  {q:"Comment s'appelle la carte magique montrant Poudlard ?",a:["Carte de Merlin","Carte des Maraudeurs","Carte du Ministere","Carte du Phenix"],c:1,f:""},
  {q:"Quel est le prenom de la soeur de Ron ?",a:["Luna","Ginny","Molly","Cho"],c:1,f:""},
  {q:"Comment s'appelle le garde-chasse de Poudlard ?",a:["Hagrid","Lupin","Sirius","Kingsley"],c:0,f:""},
  {q:"Quelle creature garde la banque Gringotts ?",a:["Les gobelins","Les elfes","Les trolls","Les geants"],c:0,f:""},
  {q:"Quel est le nom du chien a trois tetes ?",a:["Touffu","Crockdur","Norbert","Aragog"],c:0,f:""},
  {q:"Qui est le parrain de Harry ?",a:["Lupin","Sirius Black","Hagrid","Arthur Weasley"],c:1,f:""},
  {q:"Quelle maison valorise le courage ?",a:["Serdaigle","Gryffondor","Serpentard","Poufsouffle"],c:1,f:""},
  {q:"Quel professeur enseigne la divination ?",a:["Trelawney","Bibine","Vector","Chourave"],c:0,f:""},
  {q:"Comment s'appelle le phenix de Dumbledore ?",a:["Fumseck","Hedwige","Nagini","Aragog"],c:0,f:""},
  {q:"Quel est le prenom de Malfoy ?",a:["Draco","Lucius","Scorpius","Antonin"],c:0,f:""},
  {q:"Quelle creature est Aragog ?",a:["Un serpent geant","Une araignee geante","Un dragon","Un basilic"],c:1,f:""},
  {q:"Quel animal est l'animal de compagnie de Hermione ?",a:["Un hibou","Un crapaud","Un chat","Un rat"],c:2,f:""},
  {q:"Quel objet permet de voir les souvenirs ?",a:["Le Miroir du Rised","La Pensine","Le Retourneur de Temps","La Coupe de Feu"],c:1,f:""},
  {q:"Quelle ecole participe au Tournoi des Trois Sorciers avec Poudlard ?",a:["Ilvermorny","Beauxbatons","Castelobruxo","Mahoutokoro"],c:1,f:""},
  {q:"Quel animal est l'animal de compagnie de Ron ?",a:["Un hibou","Un crapaud","Un chat","Un rat"],c:3,f:""},
  {q:"Quelle maison valorise la loyaute et le travail ?",a:["Serdaigle","Gryffondor","Serpentard","Poufsouffle"],c:3,f:""},
  {q:"Quel est le sort de la mort utilise par Voldemort ?",a:["Crucio","Imperio","Avada Kedavra","Sectum Sempra"],c:2,f:""},
  {q:"Comment s'appelle le hibou de Harry ?",a:["Fumseck","Hedwige","Pattenrond","Croutard"],c:1,f:""},
  {q:"Quelle est la deuxieme epreuve du Tournoi des Trois Sorciers ?",a:["Recuperer un oeuf de dragon","Sauver des otages dans le lac","Trouver la coupe dans le labyrinthe","Braver le feu"],c:1,f:""},
  {q:"Quel personnage est le fondateur de la maison Gryffondor ?",a:["Godric Gryffondor","Salazar Serpentard","Helga Poufsouffle","Rowena Serdaigle"],c:0,f:""},
  {q:"Comment s'appelle le train qui emmene les eleves a Poudlard ?",a:["L'Orient-Express","Le Poudlard Express","Le Mage Express","Le Sorcier Express"],c:1,f:""},
  {q:"Quel sort permet d'ouvrir les serrures ?",a:["Expelliarmus","Lumos","Alohomora","Accio"],c:2,f:""},
  {q:"Quel est le prenom du professeur McGonagall ?",a:["Minerva","Millicent","Miranda","Moira"],c:0,f:""},
  {q:"Quel sort permet de faire leviter un objet ?",a:["Accio","Wingardium Leviosa","Reparo","Confundo"],c:1,f:""},
  {q:"Quel est le nom de la rue ou habitent les Dursley ?",a:["Chemin de Traverse","Allee des Sorciers","Privet Drive","Little Whinging"],c:2,f:""},
  {q:"Quel objet Hermione utilise-t-elle pour aller a plusieurs cours en meme temps ?",a:["Cape d'invisibilite","Retourneur de Temps","Miroir du Rised","Oeuf d'or"],c:1,f:""},
  {q:"Quelle maison est dirigee par le professeur Chourave ?",a:["Gryffondor","Serdaigle","Poufsouffle","Serpentard"],c:2,f:""},
  {q:"Quel est le prenom de la fille de Voldemort dans La Malediction de l'Enfant ?",a:["Helena","Hermia","Delphi","Diana"],c:2,f:""},
  {q:"Quel animal magique peut mourir et renaitre de ses cendres ?",a:["Hippogriffe","Phenix","Dragon","Basilic"],c:1,f:""},
  {q:"Comment s'appelle la salle secrete qui apparait seulement quand on en a besoin ?",a:["Salle des Besoins","Salle Commune","Salle Cachee","Salle Mysterieuse"],c:0,f:""},
  {q:"Quel professeur enseigne l'histoire de la magie ?",a:["Binns","Bibine","Trelawney","Chourave"],c:0,f:""},
  {q:"Quelle est la premiere creature que Harry rencontre au zoo avec les Dursley ?",a:["Un lion","Un serpent","Un basilic","Un crocodile"],c:1,f:""},
  {q:"Quel est le sort qui repousse les detraqueurs ?",a:["Patronus","Riddikulus","Expecto Patronum","Protego"],c:2,f:""},
  {q:"Comment s'appelle la directrice de Beauxbatons ?",a:["Madame Maxime","Madame Pomfresh","Madame Hooch","Madame Longbottom"],c:0,f:""},
  {q:"Quelle couleur sont les uniformes de la maison Serpentard ?",a:["Rouge et or","Bleu et bronze","Jaune et noir","Vert et argent"],c:3,f:""},
  {q:"Quel est le prenom du pere de Harry ?",a:["John","James","Jacob","Jonathan"],c:1,f:""},
  {q:"Quel Horcruxe est un journal intime ?",a:["Le Medaillon","La Coupe","Le Journal de Jedusor","La Bague"],c:2,f:""},
  {q:"Quel est le sort de protection personnelle ?",a:["Stupefix","Expelliarmus","Protego","Accio"],c:2,f:""},
  {q:"Comment s'appelle le pub magique a Londres ?",a:["La Tete de Cochon","Le Chaudron Baveur","Le Poudlard Arms","Le Trois Balais"],c:1,f:""},
  {q:"Quel personnage est un loup-garou professeur a Poudlard ?",a:["Sirius Black","Remus Lupin","Peter Pettigrow","James Potter"],c:1,f:""},
  {q:"Quel est le sort pour appeler un objet a soi ?",a:["Lumos","Accio","Reparo","Incendio"],c:1,f:""},
  {q:"Comment s'appelle le fantome de Serdaigle ?",a:["Le Baron Sanglant","Quasi-Sans-Tete Nick","Le Moine Grassouillet","La Dame Grise"],c:3,f:""},
  {q:"Quel est le nom du pere adoptif de Harry ?",a:["Vernon Dursley","Petunia Dursley","Dudley Dursley","Arthur Weasley"],c:0,f:""},
  {q:"Comment s'appelle le pub du village de Pre-au-Lard ?",a:["Le Chaudron Baveur","La Tete de Cochon","Les Trois Balais","La Citrouille Doree"],c:2,f:""},
  {q:"Quel Horcruxe est un medaillon portant le S de Serpentard ?",a:["La Coupe de Poufsouffle","Le Medaillon de Serpentard","Le Journal de Jedusor","La Bague des Gaunt"],c:1,f:""},
  {q:"Comment s'appelle la famille de sang pur la plus celebre de Serpentard ?",a:["Les Weasley","Les Granger","Les Malfoy","Les Longbottom"],c:2,f:""},

  // ─── Questions 68-200 : sujets avances ───────────────────────────

  {q:"Quel acteur joue Harry Potter dans les films ?",a:["Rupert Grint","Tom Felton","Daniel Radcliffe","Matthew Lewis"],c:2,f:""},
  {q:"Quelle actrice joue Hermione Granger dans les films ?",a:["Bonnie Wright","Emma Watson","Evanna Lynch","Katie Leung"],c:1,f:""},
  {q:"Quel acteur incarne Severus Rogue dans les huit films ?",a:["Gary Oldman","Ralph Fiennes","Alan Rickman","Jason Isaacs"],c:2,f:""},
  {q:"Quel est le Patronus de Luna Lovegood ?",a:["Un cerf","Un lievre","Un chat","Un cheval"],c:1,f:""},
  {q:"Quel est le vrai prenom de Tonks ?",a:["Nymphadora","Andromeda","Bellatrix","Narcissa"],c:0,f:""},
  {q:"Quel oeil magique possede Alastor Maugrey ?",a:["Un oeil de verre ordinaire","Un oeil magique rotatif","Un oeil invisible","Un oeil de basilic"],c:1,f:""},
  {q:"Quelle plante Neville Londubat etudie-t-il avec passion ?",a:["Le Saule Cogneur","La Mandragore","Le Filet du Diable","La Branchiflore"],c:2,f:""},
  {q:"Comment s'appelle la creature mi-aigle mi-cheval que Hagrid presente en cours ?",a:["Un Thestral","Un Hippogriffe","Un Griffon","Un Pegase"],c:1,f:""},
  {q:"Quel est le nom de l'hippogriffe de Hagrid ?",a:["Norbert","Buck","Crockdur","Fumseck"],c:1,f:""},
  {q:"Quel est le surnom de Remus Lupin parmi les Maraudeurs ?",a:["Cornedrue","Patmol","Lunard","Queudver"],c:2,f:""},
  {q:"Quel est le surnom de Sirius Black parmi les Maraudeurs ?",a:["Cornedrue","Patmol","Lunard","Queudver"],c:1,f:""},
  {q:"Quel est le surnom de James Potter parmi les Maraudeurs ?",a:["Cornedrue","Patmol","Lunard","Queudver"],c:0,f:""},
  {q:"Quel est le surnom de Peter Pettigrow parmi les Maraudeurs ?",a:["Cornedrue","Patmol","Lunard","Queudver"],c:3,f:""},
  {q:"En quel animal se transforme Sirius Black (Animagus) ?",a:["Un cerf","Un loup","Un rat","Un gros chien noir"],c:3,f:""},
  {q:"En quel animal se transforme Peter Pettigrow (Animagus) ?",a:["Un cerf","Un rat","Un chien","Un loup"],c:1,f:""},
  {q:"Qui etait le mage noir vaincu par Dumbledore en 1945 ?",a:["Voldemort","Salazar Serpentard","Gellert Grindelwald","Morfin Gaunt"],c:2,f:""},
  {q:"Quel lien unissait Dumbledore et Grindelwald dans leur jeunesse ?",a:["Ils etaient freres","Ils etaient amis proches","Ils ne se connaissaient pas","Ils etaient rivaux depuis l'enfance"],c:1,f:""},
  {q:"Comment s'appelle le frere de Dumbledore ?",a:["Percival","Aberforth","Aurelius","Credence"],c:1,f:""},
  {q:"Comment s'appelle la soeur de Dumbledore decedee dans sa jeunesse ?",a:["Ariana","Arianna","Aurelia","Andromeda"],c:0,f:""},
  {q:"Quel est le nom de la Baguette de Sureau dans la version anglaise ?",a:["The Death Stick","The Elder Wand","The Unbeatable Wand","The Ancient Rod"],c:1,f:""},
  {q:"Quels sont les trois objets des Reliques de la Mort ?",a:["Baguette, Cape, Pierre","Baguette, Epee, Cape","Cape, Pierre, Miroir","Baguette, Pensine, Pierre"],c:0,f:""},
  {q:"Dans les Animaux Fantastiques, quel est le metier de Norbert Dragonneau ?",a:["Auror","Professeur","Magizoologiste","Medicomage"],c:2,f:""},
  {q:"Quel acteur incarne Norbert Dragonneau dans les films Animaux Fantastiques ?",a:["Jude Law","Eddie Redmayne","Colin Farrell","Johnny Depp"],c:1,f:""},
  {q:"Quel acteur joue le jeune Dumbledore dans Les Animaux Fantastiques 2 et 3 ?",a:["Ian McKellen","Michael Gambon","Jude Law","Eddie Redmayne"],c:2,f:""},
  {q:"Comment s'appelle la creature qui vole des objets brillants dans Les Animaux Fantastiques ?",a:["Demiguise","Niffleur","Occamy","Eruptif"],c:1,f:""},
  {q:"Dans quelle ville se deroule le premier film Les Animaux Fantastiques ?",a:["Londres","Paris","Berlin","New York"],c:3,f:""},
  {q:"Comment s'appelle l'organisation magique americaine dans Les Animaux Fantastiques ?",a:["Le Ministere","Le MACUSA","L'Ordre du Phenix","Le Congres Magique"],c:1,f:""},
  {q:"Quel personnage est un Obscurial dans Les Animaux Fantastiques ?",a:["Norbert Dragonneau","Tina Goldstein","Credence Barebone","Jacob Kowalski"],c:2,f:""},
  {q:"Combien de balles sont utilisees dans un match de Quidditch ?",a:["3","4","5","2"],c:1,f:""},
  {q:"Comment s'appelle la balle doree au Quidditch ?",a:["Le Souafle","Le Cognard","Le Vif d'Or","Le Nimbus"],c:2,f:""},
  {q:"Combien de points vaut l'attrapage du Vif d'Or ?",a:["50","100","150","200"],c:2,f:""},
  {q:"Quel poste joue Harry dans l'equipe de Quidditch ?",a:["Gardien","Poursuiveur","Batteur","Attrapeur"],c:3,f:""},
  {q:"Quel est le premier balai de Harry Potter ?",a:["Comete 260","Nimbus 2000","Eclair de Feu","Nimbus 2001"],c:1,f:""},
  {q:"Qui offre l'Eclair de Feu a Harry ?",a:["Dumbledore","Hagrid","Sirius Black","Lupin"],c:2,f:""},
  {q:"Quel sort provoque une douleur insoutenable (sort Impardonnable) ?",a:["Avada Kedavra","Imperio","Crucio","Sectum Sempra"],c:2,f:""},
  {q:"Quel sort Impardonnable permet de controler l'esprit de quelqu'un ?",a:["Crucio","Avada Kedavra","Imperio","Legilimens"],c:2,f:""},
  {q:"Quel sort Harry utilise contre Drago dans les toilettes (livre 6) ?",a:["Expelliarmus","Stupefix","Sectum Sempra","Petrificus Totalus"],c:2,f:""},
  {q:"Comment s'appelle le sort qui petrifie completement le corps ?",a:["Stupefix","Petrificus Totalus","Impedimenta","Silencio"],c:1,f:""},
  {q:"Quel sort permet d'effacer la memoire de quelqu'un ?",a:["Confundo","Obliviate","Legilimens","Silencio"],c:1,f:""},
  {q:"Quelle creature magique ressemble a un petit homme de bois ?",a:["Un Botruc","Un Niffleur","Un Demiguise","Un Strangulot"],c:0,f:""},
  {q:"Comment s'appelle le serpent geant de Voldemort ?",a:["Basilic","Aragog","Nagini","Norberta"],c:2,f:""},
  {q:"Quelle creature marine attaque Harry lors de la 2e tache du Tournoi ?",a:["Les Strangulots","Les Sirenes","Les Kelpies","Les Selkies"],c:0,f:""},
  {q:"Quel type de dragon Harry affronte lors de la premiere tache du Tournoi ?",a:["Boutefeu Chinois","Vert Gallois","Suedois a museau court","Magyar a pointes"],c:3,f:""},
  {q:"Quelle creature invisible peut voir l'avenir et se rendre invisible ?",a:["Le Niffleur","Le Demiguise","Le Botruc","L'Occamy"],c:1,f:""},
  {q:"Comment s'appelle le loup-garou cruel qui mord Lupin enfant ?",a:["Greyback","Scabior","Yaxley","Dolohov"],c:0,f:""},
  {q:"Quel est le Patronus de Severus Rogue ?",a:["Un cerf","Un loup","Une biche","Un serpent"],c:2,f:""},
  {q:"Quel est le Patronus de Harry Potter ?",a:["Un lion","Un cerf","Un phenix","Un loup"],c:1,f:""},
  {q:"Quel est le Patronus de Hermione Granger ?",a:["Un chat","Une loutre","Un lievre","Un phenix"],c:1,f:""},
  {q:"Quel est le Patronus de Ron Weasley ?",a:["Un chien","Un lievre","Un Jack Russell terrier","Un renard"],c:2,f:""},
  {q:"Dans La Malediction de l'Enfant, qui est le fils de Harry ?",a:["James","Teddy","Albus","Hugo"],c:2,f:""},
  {q:"Dans La Malediction de l'Enfant, quel objet Albus et Scorpius utilisent-ils pour voyager dans le temps ?",a:["Un Retourneur de Temps","Une Pensine","Un Portoloin","La Carte des Maraudeurs"],c:0,f:""},
  {q:"Dans quelle maison est reparti Albus Potter dans La Malediction de l'Enfant ?",a:["Gryffondor","Serdaigle","Poufsouffle","Serpentard"],c:3,f:""},
  {q:"Quel est le nom complet d'Albus, le fils de Harry ?",a:["Albus Rubeus Potter","Albus Severus Potter","Albus Sirius Potter","Albus Remus Potter"],c:1,f:""},
  {q:"Quel fondateur de Poudlard possedait un diademe celebre ?",a:["Godric Gryffondor","Salazar Serpentard","Helga Poufsouffle","Rowena Serdaigle"],c:3,f:""},
  {q:"Quel fondateur de Poudlard possedait une coupe en or ?",a:["Godric Gryffondor","Salazar Serpentard","Helga Poufsouffle","Rowena Serdaigle"],c:2,f:""},
  {q:"Quel objet de Godric Gryffondor peut apparaitre a un vrai Gryffondor en situation de besoin ?",a:["La Cape d'invisibilite","Le Choixpeau magique","L'Epee de Gryffondor","La Baguette de Sureau"],c:2,f:""},
  {q:"Quel est le don rare de Harry qui lui permet de parler aux serpents ?",a:["Legilimens","Fourchelang","Metamorphomagie","Divination"],c:1,f:""},
  {q:"Quelle est la capacite speciale de Tonks ?",a:["Fourchelang","Legilimens","Metamorphomagie","Animagus"],c:2,f:""},
  {q:"Quel professeur remplace Dumbledore et impose des decrets a Poudlard ?",a:["Rogue","Ombrage","Croupton","Fudge"],c:1,f:""},
  {q:"Quel objet Ombrage force les eleves a utiliser en retenue qui grave dans la peau ?",a:["Une baguette maudite","Une plume de sang","Un parchemin ensorcelee","Une corde enchantee"],c:1,f:""},
  {q:"Comment s'appelle le groupe secret cree par Harry pour enseigner la defense ?",a:["L'Ordre du Phenix","L'Armee de Dumbledore","Le Club de Duel","La Brigade Inquisitoriale"],c:1,f:""},
  {q:"Quel acteur joue Voldemort dans les films ?",a:["Gary Oldman","Jason Isaacs","Ralph Fiennes","Ciaran Hinds"],c:2,f:""},
  {q:"Quel acteur joue Hagrid dans les films ?",a:["Brendan Gleeson","Robbie Coltrane","Warwick Davis","John Hurt"],c:1,f:""},
  {q:"Quel acteur joue Draco Malfoy dans les films ?",a:["Tom Felton","Rupert Grint","Devon Murray","Alfred Enoch"],c:0,f:""},
  {q:"Quel acteur joue Sirius Black dans les films ?",a:["Alan Rickman","Gary Oldman","David Thewlis","Timothy Spall"],c:1,f:""},
  {q:"Qui a realise les deux premiers films Harry Potter ?",a:["Alfonso Cuaron","David Yates","Mike Newell","Chris Columbus"],c:3,f:""},
  {q:"Dans quel pays le chateau utilise pour Poudlard dans les films est-il situe ?",a:["Ecosse","Angleterre","Irlande","Pays de Galles"],c:1,f:""},
  {q:"Quel est le premier livre Harry Potter publie ?",a:["La Chambre des Secrets","Le Prisonnier d'Azkaban","L'Ecole des Sorciers","La Coupe de Feu"],c:2,f:""},
  {q:"En quelle annee le premier livre Harry Potter a-t-il ete publie ?",a:["1995","1997","1999","2001"],c:1,f:""},
  {q:"Combien de livres compte la serie principale Harry Potter ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Quel Horcruxe est cache dans la Salle sur Demande a Poudlard ?",a:["Le Medaillon","La Coupe","Le Diademe de Serdaigle","La Bague des Gaunt"],c:2,f:""},
  {q:"Qui detruit le journal de Jedusor dans la Chambre des Secrets ?",a:["Dumbledore","Ron","Hermione","Harry"],c:3,f:""},
  {q:"Avec quoi Harry detruit-il le journal de Jedusor ?",a:["L'Epee de Gryffondor","Un croc de basilic","Sa baguette","Le Choixpeau"],c:1,f:""},
  {q:"Quel elfe de maison appartient a la famille Black ?",a:["Dobby","Winky","Hokey","Kreattur"],c:3,f:""},
  {q:"Comment s'appelle la mere de Voldemort ?",a:["Merope Gaunt","Cecilia Gaunt","Helena Gaunt","Hepzibah Smith"],c:0,f:""},
  {q:"Quel objet magique montre le desir le plus profond de celui qui le regarde ?",a:["La Pensine","Le Miroir du Rised","La Boule de Cristal","Le Retourneur de Temps"],c:1,f:""},
  {q:"Comment s'appelle le conducteur du Magicobus ?",a:["Stan Rocade","Ernie Danlmur","Tom","Dedalus Diggle"],c:0,f:""},
  {q:"Quel est le numero du coffre de Harry a Gringotts ?",a:["713","687","711","694"],c:1,f:""},
  {q:"Quel professeur de Defense contre les forces du Mal est un imposteur dans le livre 4 ?",a:["Quirrell","Lockhart","Faux Maugrey","Ombrage"],c:2,f:""},
  {q:"Qui se faisait passer pour Maugrey Fol Oeil grace au Polynectar ?",a:["Lucius Malfoy","Peter Pettigrow","Barty Croupton Jr","Bellatrix Lestrange"],c:2,f:""},
  {q:"Quel est le nom du village entierement sorcier pres de Poudlard ?",a:["Godric's Hollow","Pre-au-Lard","Chemin de Traverse","Little Hangleton"],c:1,f:""},
  {q:"Comment les eleves de premiere annee traversent-ils le lac pour arriver a Poudlard ?",a:["En balai","En barque","En Portoloin","A la nage"],c:1,f:""},
  {q:"Quel est le metier de Arthur Weasley au Ministere de la Magie ?",a:["Auror","Service des detournements de l'artisanat moldu","Departement des mysteres","Brigade magique"],c:1,f:""},
  {q:"Quel dragon Hagrid fait eclore en secret dans le premier livre ?",a:["Un Magyar a pointes","Un Boutefeu Chinois","Un Norvegien a crete","Un Vert Gallois"],c:2,f:""},
  {q:"Quel est le vrai genre (sexe) de Norbert revele plus tard ?",a:["Male","Femelle","Inconnu","Hermaphrodite"],c:1,f:""},
  {q:"Quel personnage meurt au Ministere dans le livre 5 ?",a:["Lupin","Sirius Black","Tonks","Maugrey"],c:1,f:""},
  {q:"Quelle est la forme d'Animagus de McGonagall ?",a:["Un hibou","Un chat tigre","Un phenix","Un cerf"],c:1,f:""},
  {q:"Quel objet Luna porte-t-elle souvent en boucles d'oreilles ?",a:["Des plumes","Des radis","Des etoiles","Des lunes"],c:1,f:""},
  {q:"Quel magazine le pere de Luna publie-t-il ?",a:["La Gazette du Sorcier","Le Chicaneur","Le Sorcier Hebdo","Le Hibou du Matin"],c:1,f:""},
  {q:"Comment s'appelle le pere de Luna Lovegood ?",a:["Pandora","Lorcan","Xenophilius","Lysander"],c:2,f:""},
  {q:"Quel est le Patronus de Dumbledore ?",a:["Un cerf","Un lion","Un phenix","Un aigle"],c:2,f:""},
  {q:"Quel poste Kingsley Shacklebolt occupe-t-il apres la guerre ?",a:["Directeur de Poudlard","Ministre de la Magie","Chef des Aurors","Ambassadeur magique"],c:1,f:""},
  {q:"Quel est le nom de la potion qui permet de prendre l'apparence d'un autre ?",a:["Felix Felicis","Veritaserum","Polynectar","Amortentia"],c:2,f:""},
  {q:"Quelle potion est connue comme le serum de verite ?",a:["Polynectar","Veritaserum","Felix Felicis","Amortentia"],c:1,f:""},
  {q:"Quelle potion donne une chance extraordinaire pendant une journee ?",a:["Polynectar","Veritaserum","Felix Felicis","Amortentia"],c:2,f:""},
  {q:"Quel est le nom de la plus puissante potion d'amour ?",a:["Felix Felicis","Polynectar","Veritaserum","Amortentia"],c:3,f:""},
  {q:"Quelle matiere Firenze le centaure enseigne-t-il a Poudlard ?",a:["Botanique","Astronomie","Divination","Defense contre les forces du Mal"],c:2,f:""},

  // ─── Questions supplementaires ───────────────────────────────────

  {q:"Comment s'appelle la mere de Narcissa et Bellatrix ?",a:["Walburga Black","Druella Rosier","Irma Crabbe","Elladora Black"],c:1,f:""},
  {q:"Quel est le nom de l'Occamy dans Les Animaux Fantastiques ?",a:["Un serpent aile qui retrecit ou grandit","Un oiseau de feu","Un lezard geant","Un insecte magique"],c:0,f:""},
  {q:"Comment s'appelle la soeur de Norbert Dragonneau ?",a:["Leta Lestrange","Tina Goldstein","Queenie Goldstein","Il n'a pas de soeur"],c:3,f:""},
  {q:"Quel est le prenom du frere de Norbert Dragonneau ?",a:["Theseus","Perseus","Achilles","Hercules"],c:0,f:""},
  {q:"Quel metier exerce Tina Goldstein dans Les Animaux Fantastiques ?",a:["Magizoologiste","Auror","Journaliste","Professeur"],c:1,f:""},
  {q:"Quel est le don special de Queenie Goldstein ?",a:["Metamorphomagie","Fourchelang","Legilimens naturelle","Animagus"],c:2,f:""},
  {q:"Quel Moldu accompagne Norbert dans Les Animaux Fantastiques ?",a:["Henry Shaw","Jacob Kowalski","Langdon Shaw","Abernathy"],c:1,f:""},
  {q:"Dans quelle ville se deroule le deuxieme film Les Animaux Fantastiques ?",a:["New York","Berlin","Paris","Rio de Janeiro"],c:2,f:""},
  {q:"Quel est le titre du troisieme film Les Animaux Fantastiques ?",a:["Les Crimes de Grindelwald","Les Secrets de Dumbledore","Le Retour du Phenix","La Guerre des Sorciers"],c:1,f:""},
  {q:"Quel est le nom de la creature semblable a un gros rhinoceros dans Les Animaux Fantastiques ?",a:["L'Eruptif","Le Niffleur","Le Demiguise","Le Botruc"],c:0,f:""},
  {q:"Combien de joueurs composent une equipe de Quidditch ?",a:["5","6","7","11"],c:2,f:""},
  {q:"Comment s'appelle la balle rouge au Quidditch ?",a:["Le Cognard","Le Vif d'Or","Le Souafle","Le Nimbus"],c:2,f:""},
  {q:"Quel poste Ron Weasley occupe-t-il dans l'equipe de Quidditch ?",a:["Attrapeur","Poursuiveur","Batteur","Gardien"],c:3,f:""},
  {q:"Quelle equipe nationale de Quidditch Viktor Krum represente-t-il ?",a:["La Russie","La Bulgarie","La Roumanie","L'Allemagne"],c:1,f:""},
  {q:"Quel est le poste de Krum dans son equipe de Quidditch ?",a:["Gardien","Poursuiveur","Batteur","Attrapeur"],c:3,f:""},
  {q:"Quel fondateur de Poudlard a quitte l'ecole apres un desaccord ?",a:["Godric Gryffondor","Rowena Serdaigle","Helga Poufsouffle","Salazar Serpentard"],c:3,f:""},
  {q:"Quel objet magique repartit les eleves dans les maisons ?",a:["La Pensine","Le Choixpeau magique","Le Miroir du Rised","La Pierre philosophale"],c:1,f:""},
  {q:"Quel animal symbolise la maison Serdaigle dans les films ?",a:["Un serpent","Un lion","Un aigle","Un blaireau"],c:2,f:""},
  {q:"Quel animal symbolise la maison Poufsouffle ?",a:["Un serpent","Un lion","Un aigle","Un blaireau"],c:3,f:""},
  {q:"Quel animal symbolise la maison Serpentard ?",a:["Un serpent","Un lion","Un aigle","Un blaireau"],c:0,f:""},
  {q:"Quel professeur enseigne les sortileges (Enchantements) a Poudlard ?",a:["McGonagall","Chourave","Flitwick","Bibine"],c:2,f:""},
  {q:"Comment s'appelle l'infirmiere de Poudlard ?",a:["Madame Bibine","Madame Pomfresh","Madame Chourave","Madame Maxime"],c:1,f:""},
  {q:"Quel sort Hermione utilise pour reparer les lunettes de Harry ?",a:["Reparo","Accio","Lumos","Finite Incantatem"],c:0,f:""},
  {q:"Quel est le nom du concierge de Poudlard ?",a:["Argus Rusard","Rubeus Hagrid","Albus Dumbledore","Neville Londubat"],c:0,f:""},
  {q:"Comment s'appelle le chat du concierge de Poudlard ?",a:["Pattenrond","Miss Teigne","Croutard","Hedwige"],c:1,f:""},
  {q:"Quel professeur de Defense contre les forces du Mal a Voldemort a l'arriere du crane ?",a:["Lockhart","Ombrage","Quirrell","Lupin"],c:2,f:""},
  {q:"Quel personnage est un celebre auteur de livres mais un vrai imposteur ?",a:["Rita Skeeter","Gilderoy Lockhart","Bathilda Tourdesac","Xenophilius Lovegood"],c:1,f:""},
  {q:"Quel objet Dumbledore legue-t-il a Ron dans son testament ?",a:["Le Deluminateur","L'Epee de Gryffondor","Le Vif d'Or","Un livre de contes"],c:0,f:""},
  {q:"Quel objet Dumbledore legue-t-il a Hermione dans son testament ?",a:["Le Deluminateur","L'Epee de Gryffondor","Le Vif d'Or","Les Contes de Beedle le Barde"],c:3,f:""},
  {q:"Que contient le Vif d'Or legue par Dumbledore a Harry ?",a:["Un message","La Pierre de Resurrection","La Baguette de Sureau","Une carte"],c:1,f:""},
  {q:"Quel personnage est la journaliste sensationnaliste de La Gazette du Sorcier ?",a:["Bathilda Tourdesac","Molly Weasley","Rita Skeeter","Dolores Ombrage"],c:2,f:""},
  {q:"En quel animal Rita Skeeter se transforme-t-elle illegalement ?",a:["Une mouche","Un cafard","Un scarabee","Un papillon"],c:2,f:""},
  {q:"Quel est le nom du pere de Voldemort (Moldu) ?",a:["Morfin Jedusor","Tom Jedusor Sr","Marvolo Gaunt","Caractacus Burke"],c:1,f:""},
  {q:"Quel est le nom du grand-pere maternel de Voldemort ?",a:["Tom Jedusor Sr","Morfin Gaunt","Marvolo Gaunt","Caractacus Burke"],c:2,f:""},
  {q:"Dans La Malediction de l'Enfant, qui est le meilleur ami d'Albus Potter ?",a:["Rose Granger-Weasley","James Potter II","Scorpius Malfoy","Teddy Lupin"],c:2,f:""},
  {q:"Dans La Malediction de l'Enfant, quel evenement Albus tente-t-il de modifier dans le passe ?",a:["La mort de Dumbledore","La mort de Cedric Diggory","La mort de Sirius","La naissance de Voldemort"],c:1,f:""},
  {q:"Quel acteur joue Dumbledore dans les films 3 a 8 ?",a:["Richard Harris","Michael Gambon","Ian McKellen","Jude Law"],c:1,f:""},
  {q:"Quel acteur jouait Dumbledore dans les deux premiers films ?",a:["Michael Gambon","Ian McKellen","Richard Harris","Patrick Stewart"],c:2,f:""},
  {q:"Quel realisateur a dirige le film Le Prisonnier d'Azkaban ?",a:["Chris Columbus","David Yates","Alfonso Cuaron","Mike Newell"],c:2,f:""},
  {q:"Combien de films Harry Potter ont ete realises au total ?",a:["7","8","9","10"],c:1,f:""},
  {q:"Quel film Harry Potter est sorti en deux parties ?",a:["Le Prince de Sang-Mele","L'Ordre du Phenix","Les Reliques de la Mort","La Coupe de Feu"],c:2,f:""},
  {q:"Quelle gare londonienne abrite la celebre voie 9 3/4 ?",a:["Paddington","Victoria","Waterloo","King's Cross"],c:3,f:""},
  {q:"Comment s'appelle la maison de la famille Weasley ?",a:["Le Terrier","Le Nid","La Taniere","La Hutte"],c:0,f:""},
  {q:"Quel est le coeur de la baguette de Harry Potter ?",a:["Crin de licorne","Ventricule de dragon","Plume de phenix","Cheveu de Veela"],c:2,f:""},
  {q:"Comment s'appelle le fabricant de baguettes du Chemin de Traverse ?",a:["Gregorovitch","Ollivander","Flamel","Fortarrome"],c:1,f:""},
];
