/* ════════════════════════════════════════
   questions/hp.js — Harry Potter — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.hp = [
  {q:"Dans quelle maison est Harry ?",a:["Serdaigle","Serpentard","Gryffondor","Poufsouffle"],c:2,f:""},
  {q:"Quel est le prénom du professeur Dumbledore ?",a:["Albert","Albus","Adrian","Arthur"],c:1,f:""},
  {q:"Quel est le sport joué sur balais volants ?",a:["Bludger","Quidditch","Nimbus","Cognard"],c:1,f:""},
  {q:"Comment s'appelle la banque des sorciers ?",a:["Gringotts","Ollivander","Azkaban","Durmstrang"],c:0,f:""},
  {q:"Quel est le prénom du meilleur ami masculin de Harry ?",a:["Ron","Fred","Percy","George"],c:0,f:""},
  {q:"Quel professeur enseigne les potions lors des premiers livres ?",a:["Lupin","Rogue","McGonagall","Flitwick"],c:1,f:""},
  {q:"Comment s'appelle l'elfe de maison ami de Harry ?",a:["Kreattur","Dobby","Winky","Hokey"],c:1,f:""},
  {q:"Quel est le nom de la prison des sorciers ?",a:["Durmstrang","Azkaban","Beauxbâtons","Godric's Hollow"],c:1,f:""},
  {q:"Quel objet Harry reçoit-il de son père (cape) ?",a:["Une baguette","Une cape d'invisibilité","Un balai","Une carte"],c:1,f:""},
  {q:"Quel monstre vit dans la Chambre des Secrets ?",a:["Un basilic","Un dragon","Un troll","Un hippogriffe"],c:0,f:""},
  {q:"Quel sort sert à désarmer un adversaire ?",a:["Expelliarmus","Lumos","Stupefix","Alohomora"],c:0,f:""},
  {q:"Quel est le nom complet de Voldemort ?",a:["Tom Elvis Jedusor","Tom Marvolo Jedusor","Tom Marcus Jedusor","Tom Magnus Jedusor"],c:1,f:""},
  {q:"Comment s'appelle la carte magique montrant Poudlard ?",a:["Carte de Merlin","Carte des Maraudeurs","Carte du Ministère","Carte du Phénix"],c:1,f:""},
  {q:"Quel est le prénom de la sœur de Ron ?",a:["Luna","Ginny","Molly","Cho"],c:1,f:""},
  {q:"Comment s'appelle le garde-chasse de Poudlard ?",a:["Hagrid","Lupin","Sirius","Kingsley"],c:0,f:""},
  {q:"Quelle créature garde la banque Gringotts ?",a:["Les gobelins","Les elfes","Les trolls","Les géants"],c:0,f:""},
  {q:"Quel est le nom du chien à trois têtes ?",a:["Touffu","Crockdur","Norbert","Aragog"],c:0,f:""},
  {q:"Qui est le parrain de Harry ?",a:["Lupin","Sirius Black","Hagrid","Arthur Weasley"],c:1,f:""},
  {q:"Quelle maison valorise le courage ?",a:["Serdaigle","Gryffondor","Serpentard","Poufsouffle"],c:1,f:""},
  {q:"Quel professeur enseigne la divination ?",a:["Trelawney","Bibine","Vector","Chourave"],c:0,f:""},
  {q:"Comment s'appelle le phénix de Dumbledore ?",a:["Fumseck","Hedwige","Nagini","Aragog"],c:0,f:""},
  {q:"Quel est le prénom de Malfoy ?",a:["Draco","Lucius","Scorpius","Antonin"],c:0,f:""},
  {q:"Quelle créature est Aragog ?",a:["Un serpent géant","Une araignée géante","Un dragon","Un basilic"],c:1,f:""},
  {q:"Quel animal est l'animal de compagnie de Hermione ?",a:["Un hibou","Un crapaud","Un chat","Un rat"],c:2,f:""},
  {q:"Quel objet permet de voir les souvenirs ?",a:["Le Miroir du Riséd","La Pensine","Le Retourneur de Temps","La Coupe de Feu"],c:1,f:""},
  {q:"Quelle école participe au Tournoi des Trois Sorciers avec Poudlard ?",a:["Ilvermorny","Beauxbâtons","Castelobruxo","Mahoutokoro"],c:1,f:""},
  {q:"Quel animal est l'animal de compagnie de Ron ?",a:["Un hibou","Un crapaud","Un chat","Un rat"],c:3,f:""},
  {q:"Quel sort permet d'allumer sa baguette ?",a:["Expelliarmus","Lumos","Nox","Alohomora"],c:1,f:""},
  {q:"Quelle maison valorise la loyauté et le travail ?",a:["Serdaigle","Gryffondor","Serpentard","Poufsouffle"],c:3,f:""},
  {q:"Quel est le sort de la mort utilisé par Voldemort ?",a:["Crucio","Imperio","Avada Kedavra","Sectum Sempra"],c:2,f:""},
  {q:"Comment s'appelle le hibou de Harry ?",a:["Fumseck","Hedwige","Pattenrond","Croûtard"],c:1,f:""},
  {q:"Quel objet permet à Harry de lire les pensées de Dumbledore ?",a:["Le Miroir du Riséd","La Pensine","La Pierre de Résurrection","L'Œil magique"],c:1,f:""},
  {q:"Quelle est la deuxième épreuve du Tournoi des Trois Sorciers ?",a:["Récupérer un œuf de dragon","Sauver des otages dans le lac","Trouver la coupe dans le labyrinthe","Braver le feu"],c:1,f:""},
  {q:"Quel personnage est le fondateur de la maison Gryffondor ?",a:["Godric Gryffondor","Salazar Serpentard","Helga Poufsouffle","Rowena Serdaigle"],c:0,f:""},
  {q:"Comment s'appelle le train qui emmène les élèves à Poudlard ?",a:["L'Orient-Express","Le Poudlard Express","Le Mage Express","Le Sorcier Express"],c:1,f:""},
  {q:"Quel sort permet d'ouvrir les serrures ?",a:["Expelliarmus","Lumos","Alohomora","Accio"],c:2,f:""},
  {q:"Quel est le prénom du professeur McGonagall ?",a:["Minerva","Millicent","Miranda","Moira"],c:0,f:""},
  {q:"Quelle est la première maison fondée selon la légende de Poudlard ?",a:["Serdaigle","Gryffondor","Serpentard","Poufsouffle"],c:1,f:""},
  {q:"Comment s'appelle la sœur de Voldemort ?",a:["Il n'en a pas","Méropé","Narcissa","Bellatrix"],c:0,f:""},
  {q:"Quel sort permet de faire léviter un objet ?",a:["Accio","Wingardium Leviosa","Reparo","Confundo"],c:1,f:""},
  {q:"Quelle est la matière enseignée par le professeur Bibine ?",a:["Potions","Défense contre les forces du Mal","Transfiguration","Soins aux créatures magiques"],c:1,f:""},
  {q:"Comment s'appelle la mère de Neville Londubat ?",a:["Alice","Augusta","Arabella","Amelia"],c:0,f:""},
  {q:"Quel animal fantastique est un cheval ailé ?",a:["Hippogriffe","Pégase","Thestral","Abraxan"],c:0,f:""},
  {q:"Quel est le nom de la rue où habitent les Dursley ?",a:["Chemin de Traverse","Allée des Sorciers","Privet Drive","Little Whinging"],c:2,f:""},
  {q:"Quel objet Hermione utilise-t-elle pour aller à plusieurs cours en même temps ?",a:["Cape d'invisibilité","Retourneur de Temps","Miroir du Riséd","Oeuf d'or"],c:1,f:""},
  {q:"Quel est le vrai prénom du professeur Rogue ?",a:["Sévère","Sébastian","Silas","Simon"],c:0,f:""},
  {q:"Quelle maison est dirigée par le professeur Chourave ?",a:["Gryffondor","Serdaigle","Poufsouffle","Serpentard"],c:2,f:""},
  {q:"Comment s'appelle le père de Drago Malfoy ?",a:["Lucius","Narcisse","Abraxas","Scorpius"],c:0,f:""},
  {q:"Quel est le sort de désillusion qui rend invisible ?",a:["Lumos","Nox","Dissimulo","Obscuro"],c:2,f:""},
  {q:"Quelle créature est utilisée pour garder la Coupe de Feu ?",a:["Dragon","Basilic","Sphinx","Hippogriffe"],c:0,f:""},
  {q:"Comment s'appelle l'ennemi juré de Hermione en 1ère année ?",a:["Draco Malfoy","Vincent Crabbe","Gregory Goyle","Pansy Parkinson"],c:0,f:""},
  {q:"Quel est le prénom de la fille de Voldemort dans La Malédiction de l'Enfant ?",a:["Helena","Hermia","Delphi","Diana"],c:2,f:""},
  {q:"Quel animal magique peut mourir et renaître de ses cendres ?",a:["Hippogriffe","Phénix","Dragon","Basilic"],c:1,f:""},
  {q:"Comment s'appelle la salle secrète qui apparaît seulement quand on en a besoin ?",a:["Salle des Besoins","Salle Commune","Salle Cachée","Salle Mystérieuse"],c:0,f:""},
  {q:"Quel professeur enseigne l'histoire de la magie ?",a:["Binns","Bibine","Trelawney","Chourave"],c:0,f:""},
  {q:"Quelle est la première créature que Harry rencontre au zoo avec les Dursley ?",a:["Un lion","Un serpent","Un basilic","Un crocodile"],c:1,f:""},
  {q:"Comment s'appelle le personnage de la Sorcière des sucreries dans le Poudlard Express ?",a:["Hortense Bibine","La Dame aux Bonbons","La Sorcière du Train","Elle n'a pas de nom"],c:1,f:""},
  {q:"Quel est le sort qui repousse les détraqueurs ?",a:["Patronus","Riddikulus","Expecto Patronum","Protego"],c:2,f:""},
  {q:"Comment s'appelle la directrice de Beauxbâtons ?",a:["Madame Maxime","Madame Pomfresh","Madame Hooch","Madame Longbottom"],c:0,f:""},
  {q:"Quelle couleur sont les uniformes de la maison Serpentard ?",a:["Rouge et or","Bleu et bronze","Jaune et noir","Vert et argent"],c:3,f:""},
  {q:"Quel est le prénom du père de Harry ?",a:["John","James","Jacob","Jonathan"],c:1,f:""},
  {q:"Comment s'appelle le détraqueur qui embrasse ses victimes ?",a:["Le Baiser de la Mort","Le Baiser du Détraqueur","Le Baiser Dementeur","Le Baiser Glacial"],c:1,f:""},
  {q:"Quel objet Harry utilise pour voir dans les souvenirs des autres ?",a:["Miroir du Riséd","Pensine","Pierre de Résurrection","Lunettes de vérité"],c:1,f:""},
  {q:"Comment s'appelle l'araignée géante amie de Hagrid ?",a:["Nagini","Aragog","Touffu","Norbert"],c:1,f:""},
  {q:"Quel sort permet de réparer un objet cassé ?",a:["Accio","Reparo","Reducto","Repairo"],c:1,f:""},
  {q:"Quelle est la couleur des robes de Gryffondor ?",a:["Bleu et or","Rouge et or","Jaune et noir","Vert et argent"],c:1,f:""},
  {q:"Comment s'appelle la mère de Drago Malfoy ?",a:["Bellatrix","Lucie","Narcissa","Andromeda"],c:2,f:""},
  {q:"Quel animal magique ressemble à un cheval mais ne peut être vu que par ceux ayant vu la mort ?",a:["Hippogriffe","Pégase","Thestral","Abraxan"],c:2,f:""},
  {q:"Comment s'appelle le fantôme de Gryffondor ?",a:["Bloody Baron","Nearly Headless Nick","Fat Friar","Grey Lady"],c:1,f:""},
  {q:"Quel est le vrai nom du livre 'Les Animaux Fantastiques' auteur en univers HP ?",a:["Albus Dumbledore","Gilderoy Lockhart","Newt Scamander","Bathilda Tourdesac"],c:2,f:""},
  {q:"Quelle est la couleur des robes de Serpentard ?",a:["Rouge et or","Bleu et bronze","Vert et argent","Jaune et noir"],c:2,f:""},
  {q:"Comment s'appelle la directrice de Poudlard après Dumbledore brièvement ?",a:["McGonagall","Rogue","Ombrage","Moody"],c:2,f:""},
  {q:"Quel sort transforme un épouvantard en quelque chose de ridicule ?",a:["Expelliarmus","Riddikulus","Stupefix","Protego"],c:1,f:""},
  {q:"Comment s'appelle la rue magique cachée dans Londres ?",a:["Chemin de Traverse","Passage Moldus","Allée des Sorciers","Rue Magique"],c:0,f:""},
  {q:"Quel est le nom du fantôme de Serpentard ?",a:["Le Baron Sanglant","Quasi-Sans-Tête Nick","Le Moine Grassouillet","La Dame Grise"],c:0,f:""},
  {q:"Quel est le prénom de la mère de Harry ?",a:["Rose","Lily","Iris","Violet"],c:1,f:""},
  {q:"Comment s'appelle l'Auror qui enquête sur les crimes de Voldemort ?",a:["Mad-Eye Moody","Kingsley Shacklebolt","Nymphadora Tonks","Arthur Weasley"],c:0,f:""},
  {q:"Quel Horcruxe est un journal intime ?",a:["Le Médaillon","La Coupe","Le Journal de Jedusor","La Bague"],c:2,f:""},
  {q:"Comment s'appelle le lutin espiègle dans La Chambre des Secrets ?",a:["Dobby","Pixie Cornouaillais","Lutin des Bois","Farfadet"],c:1,f:""},
  {q:"Quel est le sort de protection personnelle ?",a:["Stupefix","Expelliarmus","Protego","Accio"],c:2,f:""},
  {q:"Comment s'appelle le pub magique à Londres où l'on prend le Knight Bus ?",a:["La Tête de Cochon","Le Chaudron Baveur","Le Poudlard Arms","Le Trois Balais"],c:1,f:""},
  {q:"Quel personnage est un loup-garou professeur à Poudlard ?",a:["Sirius Black","Remus Lupin","Peter Pettigrow","James Potter"],c:1,f:""},
  {q:"Quel est le sort pour appeler un objet à soi ?",a:["Lumos","Accio","Reparo","Incendio"],c:1,f:""},
  {q:"Comment s'appelle le fantôme de Serdaigle ?",a:["Le Baron Sanglant","Quasi-Sans-Tête Nick","Le Moine Grassouillet","La Dame Grise"],c:3,f:""},
  {q:"Quel animal magique a le corps d'un lion et la tête d'un aigle ?",a:["Hippogriffe","Griffe d'Or","Pégase","Sphynx"],c:0,f:""},
  {q:"Comment s'appelle la salle commune de Serpentard ?",a:["Elle est dans les tours","Elle est dans les souterrains","Elle est dans la forêt","Elle est dans les cachots"],c:1,f:""},
  {q:"Quel est le sort pour lancer des flammes ?",a:["Lumos","Alohomora","Incendio","Flagrate"],c:2,f:""},
  {q:"Comment s'appelle le portier de Gringotts (responsable des trésors) ?",a:["Gripsec","Ripostecroc","Gournay","Gripsec"],c:0,f:""},
  {q:"Quel est le nom du père adoptif de Harry ?",a:["Vernon Dursley","Petunia Dursley","Dudley Dursley","Arthur Weasley"],c:0,f:""},
  {q:"Quelle est la couleur des robes de Poufsouffle ?",a:["Rouge et or","Bleu et bronze","Jaune et noir","Vert et argent"],c:2,f:""},
  {q:"Comment s'appelle la chauve-souris familière de Neville en 1ère année ?",a:["Crapaud Trevor","Hedwige","Pattenrond","Il n'a pas de familier"],c:0,f:""},
  {q:"Quel est le vrai nom de Voldemort avant de prendre ce surnom ?",a:["Gellert Grindelwald","Tom Marvolo Jedusor","Salazar Serpentard","Morfin Gaunt"],c:1,f:""},
  {q:"Quel sort permet de voir dans l'obscurité ?",a:["Lumos","Nox","Lumos Maxima","Alohomora"],c:2,f:""},
  {q:"Comment s'appelle le pub du village de Pré-au-Lard fréquenté par les élèves de 3e année et plus ?",a:["Le Chaudron Baveur","La Tête de Cochon","Les Trois Balais","La Citrouille Dorée"],c:2,f:""},
  {q:"Quel Horcruxe est un médaillon portant le S de Serpentard ?",a:["La Coupe de Poufsouffle","Le Médaillon de Serpentard","Le Journal de Jedusor","La Bague des Gaunt"],c:1,f:""},
  {q:"Comment s'appelle la famille de sang pur la plus célèbre de Serpentard ?",a:["Les Weasley","Les Granger","Les Malfoy","Les Longbottom"],c:2,f:""},
];
