/* ════════════════════════════════════════
   questions/lotr.js — Seigneur des Anneaux — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.lotr = [
  {q:"Comment s'appelle le magicien qui accompagne Frodon au début de sa quête ?",a:["Saroumane","Radagast","Gandalf","Alatar"],c:2,f:""},
  {q:"Quel est le nom de la région où vivent les Hobbits ?",a:["Le Rohan","La Comté","Le Gondor","La Lothlórien"],c:1,f:""},
  {q:"Combien d'anneaux de pouvoir ont été forgés pour les Elfes ?",a:["Neuf","Sept","Un","Trois"],c:3,f:""},
  {q:"Quel acteur incarne Aragorn dans la trilogie de Peter Jackson ?",a:["Orlando Bloom","Sean Bean","Viggo Mortensen","Karl Urban"],c:2,f:""},
  {q:"Quel est le vrai nom de Grands-Pas ?",a:["Boromir","Faramir","Aragorn","Éomer"],c:2,f:""},
  {q:"Comment s'appelle l'épée brisée d'Aragorn ?",a:["Glamdring","Narsil","Dard","Orcrist"],c:1,f:""},
  {q:"Quel est le nom de l'araignée géante qui attaque Frodon ?",a:["Ungoliant","Arachne","Shelob","Mirkwood"],c:2,f:""},
  {q:"Dans quel volcan l'Anneau Unique doit-il être détruit ?",a:["Le Mont Venteux","La Montagne du Destin","Le Mont Caradhras","Les Mines de la Moria"],c:1,f:""},
  {q:"Quel Hobbit devient finalement le porteur de l'Anneau après Frodon ?",a:["Pippin","Merry","Sam","Gollum"],c:2,f:""},
  {q:"Qui est le Seigneur Ténébreux du Mordor ?",a:["Morgoth","Saroumane","Sauron","Le Roi-Sorcier"],c:2,f:""},
  {q:"Comment s'appelle le royaume des Nains sous la montagne dans Le Hobbit ?",a:["La Moria","Erebor","Les Havres Gris","Khazad-dûm"],c:1,f:""},
  {q:"Quel personnage dit « Mon précieux » ?",a:["Frodon","Bilbon","Gollum","Sauron"],c:2,f:""},
  {q:"Combien de membres compte la Communauté de l'Anneau ?",a:["Huit","Dix","Sept","Neuf"],c:3,f:""},
  {q:"Quel est le nom elfique de Fondcombe ?",a:["Lothlórien","Imladris","Valinor","Minas Tirith"],c:1,f:""},
  {q:"Qui tue le Roi-Sorcier d'Angmar ?",a:["Aragorn","Gandalf","Éowyn","Legolas"],c:2,f:""},
  {q:"Quel acteur joue Legolas ?",a:["Elijah Wood","Orlando Bloom","Dominic Monaghan","Billy Boyd"],c:1,f:""},
  {q:"Quel est le nom de l'épée de Frodon ?",a:["Narsil","Glamdring","Dard","Andúril"],c:2,f:""},
  {q:"Quel est le peuple de Gimli ?",a:["Les Elfes","Les Hommes","Les Hobbits","Les Nains"],c:3,f:""},
  {q:"Qui est le père d'Aragorn ?",a:["Arathorn","Elrond","Théoden","Denethor"],c:0,f:""},
  {q:"Comment s'appelle l'arbre blanc du Gondor ?",a:["Telperion","L'Arbre Blanc","Laurelin","Nimloth"],c:3,f:""},
  {q:"Quel est le premier film de la trilogie de Peter Jackson ?",a:["Les Deux Tours","Le Retour du Roi","La Communauté de l'Anneau","La Bataille des Cinq Armées"],c:2,f:""},
  {q:"Comment s'appelle le cheval de Gandalf ?",a:["Bill","Hasufel","Gripoil","Arod"],c:2,f:""},
  {q:"Quel est le nom de la forêt habitée par les Ents ?",a:["La Forêt Noire","Fangorn","La Vieille Forêt","La Lothlórien"],c:1,f:""},
  {q:"Qui est le chef des Ents ?",a:["Vif-Bois","Sylvebarbe","Bregalad","Fladrif"],c:1,f:""},
  {q:"Quel Hobbit est aussi connu sous le nom de Peregrin Touque ?",a:["Sam","Merry","Frodon","Pippin"],c:3,f:""},
  {q:"Quel est le nom du royaume de Théoden ?",a:["Le Gondor","Le Rohan","L'Arnor","L'Isengard"],c:1,f:""},
  {q:"Comment s'appelle la forteresse de Saroumane ?",a:["Barad-dûr","Minas Morgul","Orthanc","Cirith Ungol"],c:2,f:""},
  {q:"Quel personnage est surnommé « Le Blanc » après sa résurrection ?",a:["Saroumane","Aragorn","Gandalf","Elrond"],c:2,f:""},
  {q:"Quel cadeau Galadriel offre-t-elle à Gimli ?",a:["Une épée elfique","Un arc d'or","Trois cheveux de sa tête","Un anneau de pouvoir"],c:2,f:""},
  {q:"Quel est le vrai nom de Gollum ?",a:["Déagol","Sméagol","Gríma","Gorbag"],c:1,f:""},
  {q:"Qui a écrit Le Seigneur des Anneaux ?",a:["C.S. Lewis","J.R.R. Tolkien","George R.R. Martin","Terry Pratchett"],c:1,f:""},
  {q:"Dans quel lieu se déroule la bataille du Gouffre de Helm ?",a:["Fort le Cor","Minas Tirith","Edoras","Osgiliath"],c:0,f:""},
  {q:"Combien d'anneaux de pouvoir ont été forgés pour les Nains ?",a:["Trois","Neuf","Sept","Un"],c:2,f:""},
  {q:"Quel est le nom du balrog combattu par Gandalf ?",a:["Gothmog","Le Fléau de Durin","Ancalagon","Glaurung"],c:1,f:""},
  {q:"Qui est l'intendant du Gondor pendant la Guerre de l'Anneau ?",a:["Faramir","Boromir","Denethor","Imrahil"],c:2,f:""},
  {q:"Quel Hobbit trouve l'Anneau Unique dans la grotte de Gollum ?",a:["Frodon","Sam","Bilbon","Merry"],c:2,f:""},
  {q:"Comment s'appelle le fils de Denethor qui fait partie de la Communauté ?",a:["Faramir","Éomer","Boromir","Haldir"],c:2,f:""},
  {q:"Quel acteur interprète Gandalf ?",a:["Patrick Stewart","Christopher Lee","Ian McKellen","Michael Gambon"],c:2,f:""},
  {q:"Quel est le nom de l'étoile qu'Eärendil porte au front ?",a:["Le Silmaril","L'Arkenstone","Le Palantír","Le Phial"],c:0,f:""},
  {q:"Qui offre à Frodon la fiole de lumière d'Eärendil ?",a:["Elrond","Arwen","Galadriel","Celeborn"],c:2,f:""},
  {q:"De quelle race est Legolas ?",a:["Nain","Hobbit","Humain","Elfe"],c:3,f:""},
  {q:"Comment s'appelle le père de Legolas ?",a:["Celeborn","Elrond","Thranduil","Gil-galad"],c:2,f:""},
  {q:"Quel objet permet de voir à distance dans le monde de Tolkien ?",a:["Un Silmaril","Un Palantír","Un Anneau","Un Miroir"],c:1,f:""},
  {q:"Quelle bataille conclut la trilogie du Seigneur des Anneaux ?",a:["La Bataille de la Morannon","La Bataille du Gouffre de Helm","La Bataille des Champs du Pelennor","La Bataille des Cinq Armées"],c:0,f:""},
  {q:"Comment s'appelle la femme qu'Aragorn épouse ?",a:["Galadriel","Éowyn","Arwen","Rosie"],c:2,f:""},
  {q:"Quel dragon Bilbon rencontre-t-il dans Le Hobbit ?",a:["Ancalagon","Glaurung","Smaug","Scatha"],c:2,f:""},
  {q:"Combien d'anneaux de pouvoir ont été forgés pour les Hommes ?",a:["Sept","Trois","Un","Neuf"],c:3,f:""},
  {q:"Qui forge l'Anneau Unique ?",a:["Celebrimbor","Fëanor","Sauron","Aulë"],c:2,f:""},
  {q:"Comment s'appelle la cotte de mailles en mithril de Frodon ?",a:["L'Armure de Durin","La Cotte de Mithril","Le Haubert de Narsil","La Brigandine d'Erebor"],c:1,f:""},
  {q:"Quel est le nombre total d'Anneaux de Pouvoir mentionnés dans le poème ?",a:["Vingt","Dix-neuf","Dix-sept","Seize"],c:0,f:""},
  {q:"Qui est Déagol par rapport à Sméagol ?",a:["Son frère","Son cousin","Son père","Son ami"],c:1,f:""},
  {q:"Quel est le nom de la tour de Sauron ?",a:["Orthanc","Minas Morgul","Barad-dûr","Cirith Ungol"],c:2,f:""},
  {q:"Comment s'appelle le poney de Sam ?",a:["Gripoil","Hasufel","Bill","Brego"],c:2,f:""},
  {q:"Quel personnage est aussi connu comme l'Elessar ?",a:["Gandalf","Elrond","Aragorn","Boromir"],c:2,f:""},
  {q:"Quelle est la dernière demeure des Elfes à l'ouest ?",a:["La Comté","Les Terres Immortelles","Le Mordor","Le Rohan"],c:1,f:""},
  {q:"Quel est le surnom de Gandalf en Rohan ?",a:["Mithrandir","Olórin","Tharkûn","Pied-de-Tempête"],c:3,f:""},
  {q:"Qui tranche les doigts de Sauron pour lui prendre l'Anneau ?",a:["Elendil","Gil-galad","Isildur","Elrond"],c:2,f:""},
  {q:"Quel événement marque la fin du Troisième Âge ?",a:["La chute de Sauron","La mort de Gandalf","La destruction de la Comté","Le départ des Elfes"],c:0,f:""},
  {q:"Comment appelle-t-on les spectres à cheval serviteurs de Sauron ?",a:["Les Uruk-hai","Les Nazgûl","Les Wargs","Les Balrogs"],c:1,f:""},
  {q:"Quel est le nom de la forteresse où se déroule la Bataille des Champs du Pelennor ?",a:["Edoras","Osgiliath","Minas Tirith","Helm"],c:2,f:""},
  {q:"Qui est la Dame de la Lothlórien ?",a:["Arwen","Éowyn","Celebrían","Galadriel"],c:3,f:""},
  {q:"Quel acteur incarne Frodon dans les films de Peter Jackson ?",a:["Daniel Radcliffe","Elijah Wood","Tobey Maguire","Sean Astin"],c:1,f:""},
  {q:"Comment s'appelle le frère de Boromir ?",a:["Éomer","Faramir","Imrahil","Haldir"],c:1,f:""},
  {q:"Quel est le nom du premier Seigneur Ténébreux, le maître de Sauron ?",a:["Ungoliant","Morgoth","Glaurung","Gothmog"],c:1,f:""},
  {q:"En quelle année est sorti le film La Communauté de l'Anneau ?",a:["1999","2001","2003","2000"],c:1,f:""},
  {q:"Combien de films composent la trilogie du Hobbit de Peter Jackson ?",a:["Deux","Quatre","Trois","Un"],c:2,f:""},
  {q:"Quel personnage tombe avec le Balrog dans les Mines de la Moria ?",a:["Aragorn","Boromir","Legolas","Gandalf"],c:3,f:""},
  {q:"Quel est le cri de guerre des Rohirrim ?",a:["Gondor !","Pour Frodon !","Mort !","Elendil !"],c:2,f:""},
  {q:"Comment s'appelle le conseiller corrompu du roi Théoden ?",a:["Gríma Langue-de-Serpent","Denethor","Alfrid","Gothmog"],c:0,f:""},
  {q:"Quel métal précieux se trouve dans les Mines de la Moria ?",a:["L'or","L'argent","Le mithril","L'acier"],c:2,f:""},
  {q:"Qui interprète Gollum grâce à la capture de mouvement ?",a:["Benedict Cumberbatch","Andy Serkis","Hugo Weaving","Cate Blanchett"],c:1,f:""},
  {q:"Comment s'appelle le lieu de résidence de Bilbon à la Comté ?",a:["Bree","Cul-de-Sac","Hobbitebourg","Le Creux-de-Crique"],c:1,f:""},
  {q:"Quel est le nom de l'auberge où les Hobbits rencontrent Grands-Pas ?",a:["Le Dragon Vert","L'auberge de Bree","Le Poney Fringant","Le Cheval d'Or"],c:2,f:""},
  {q:"Quel est le nom elfique de Gandalf ?",a:["Olórin","Curunír","Aiwendil","Pallando"],c:0,f:""},
  {q:"Qui devient roi du Gondor à la fin de la guerre ?",a:["Faramir","Éomer","Boromir","Aragorn"],c:3,f:""},
  {q:"Comment s'appelle la porte secrète des Mines de la Moria ?",a:["La Porte Noire","Les Portes de Durin","La Porte d'Argonath","Les Portes de Minas Tirith"],c:1,f:""},
  {q:"Quel mot ouvre les Portes de Durin ?",a:["Ami","Mellon","Edro","Annon"],c:1,f:""},
  {q:"Quel personnage du Hobbit est le chef des Nains de la compagnie ?",a:["Balin","Dwalin","Thorin Écu-de-Chêne","Kíli"],c:2,f:""},
  {q:"Quelle créature Bilbon rencontre-t-il en trouvant l'Anneau ?",a:["Un troll","Smaug","Gollum","Un dragon"],c:2,f:""},
  {q:"Quel est le nom de la rivière qui borde Fondcombe ?",a:["L'Anduin","Le Bruinen","L'Entaluve","Le Sirannon"],c:1,f:""},
  {q:"Qui est le roi des Elfes de la Forêt Noire dans Le Hobbit ?",a:["Elrond","Celeborn","Gil-galad","Thranduil"],c:3,f:""},
  {q:"Comment s'appelle la pierre précieuse au cœur d'Erebor ?",a:["Le Silmaril","Le Palantír","L'Arkenstone","L'Evenstar"],c:2,f:""},
  {q:"Quel acteur joue Bilbon âgé dans Le Seigneur des Anneaux ?",a:["Martin Freeman","Ian Holm","Ian McKellen","Christopher Lee"],c:1,f:""},
  {q:"Comment meurt Boromir ?",a:["Noyé dans l'Anduin","Percé de flèches d'Uruk-hai","Tué par le Balrog","Empoisonné par Saroumane"],c:1,f:""},
  {q:"Quel est le dernier mot du Seigneur des Anneaux (livre) ?",a:["Fin","Bien","Partie","Rentré"],c:1,f:""},
  {q:"Dans Le Hobbit, combien de Nains accompagnent Bilbon ?",a:["Douze","Treize","Quatorze","Onze"],c:1,f:""},
  {q:"Qui détruit finalement l'Anneau Unique en tombant dans le feu ?",a:["Frodon","Sam","Gollum","Gandalf"],c:2,f:""},
  {q:"Comment s'appelle le fils d'Aragorn et Arwen ?",a:["Eldarion","Arathorn","Théodred","Elrohir"],c:0,f:""},
  {q:"Quelle race créa les Silmarils ?",a:["Les Nains","Les Hommes","Les Elfes","Les Maiar"],c:2,f:""},
  {q:"Comment s'appelle le compagnon de Merry lors de la Bataille des Champs du Pelennor ?",a:["Aragorn","Éowyn","Théoden","Gandalf"],c:1,f:""},
  {q:"Quel est le nom de la cité en ruines entre le Gondor et le Mordor ?",a:["Minas Morgul","Helm","Osgiliath","Edoras"],c:2,f:""},
  {q:"Qui prononce la phrase « Vous ne passerez pas ! » ?",a:["Aragorn","Théoden","Gandalf","Elrond"],c:2,f:""},
  {q:"Quel acteur incarne Saroumane dans les films ?",a:["Ian McKellen","Hugo Weaving","Christopher Lee","John Rhys-Davies"],c:2,f:""},
  {q:"Comment s'appelle l'épée de Gandalf ?",a:["Orcrist","Dard","Andúril","Glamdring"],c:3,f:""},
  {q:"Quel Hobbit est surnommé « le Magnifique » ?",a:["Frodon","Bilbon","Sam","Pippin"],c:1,f:""},
  {q:"Qui interprète Elrond dans les films de Peter Jackson ?",a:["Hugo Weaving","Cate Blanchett","Lee Pace","Marton Csokas"],c:0,f:""},
  {q:"Comment s'appelle l'étoile du soir portée par Arwen ?",a:["Le Silmaril","L'Evenstar","Le Phial","Le Palantír"],c:1,f:""},
  {q:"Quel est le nom du col dangereux traversé par Frodon et Sam ?",a:["Le Col de Caradhras","Cirith Ungol","Le Pas de Dimrill","L'Escalier en Colimaçon"],c:1,f:""},
  {q:"Quelle est la particularité des pieds des Hobbits ?",a:["Ils sont très petits","Ils ont six orteils","Ils sont recouverts de poils épais","Ils sont palmés"],c:2,f:""},
  {q:"Qui est le roi du Rohan pendant la Guerre de l'Anneau ?",a:["Éomer","Théodred","Théoden","Helm"],c:2,f:""},
  {q:"Comment s'appelle le pont où Gandalf affronte le Balrog ?",a:["Le Pont de l'Anduin","Le Pont de Khazad-dûm","Le Pont d'Osgiliath","Le Pont de Fondcombe"],c:1,f:""}
];
