/* ════════════════════════════════════════
   questions/lotr.js — Seigneur des Anneaux — 200 questions
   ════════════════════════════════════════ */
QUESTIONS.lotr = [
  {q:"Comment s'appelle le magicien qui accompagne Frodon au début de sa quête ?",a:["Saroumane","Radagast","Gandalf","Alatar"],c:2,f:""},
  {q:"Quel est le nom de la région où vivent les Hobbits ?",a:["Le Rohan","La Comté","Le Gondor","La Lothlórien"],c:1,f:""},
  {q:"Combien d'anneaux de pouvoir ont été forgés pour les Elfes ?",a:["Neuf","Sept","Un","Trois"],c:3,f:""},
  {q:"Quel acteur incarne Aragorn dans la trilogie de Peter Jackson ?",a:["Orlando Bloom","Sean Bean","Viggo Mortensen","Karl Urban"],c:2,f:""},
  {q:"Quel est le vrai nom de Grands-Pas ?",a:["Boromir","Faramir","Aragorn","Éomer"],c:2,f:""},
  {q:"Comment s'appelle l'épée brisée d'Aragorn ?",a:["Glamdring","Narsil","Dard","Orcrist"],c:1,f:""},
  {q:"Quel est le nom de l'araignée géante qui attaque Frodon ?",a:["Ungoliant","Arachne","Shelob","Mirkwood"],c:2,f:""},
  {q:"Dans quel volcan l'Anneau Unique doit-il être détruit ?",a:["Le Mont Venteux","La Montagne du Destin","Le Mont Caradhras","Les Mines de la Moria"],c:1,f:""},
  {q:"Quel Hobbit devient finalement le porteur de l'Anneau après Frodon ?",a:["Pippin","Merry","Sam","Gollum"],c:2,f:""},
  {q:"Qui est le Seigneur Ténébreux du Mordor ?",a:["Morgoth","Saroumane","Sauron","Le Roi-Sorcier"],c:2,f:""},
  {q:"Comment s'appelle le royaume des Nains sous la montagne dans Le Hobbit ?",a:["La Moria","Erebor","Les Havres Gris","Khazad-dûm"],c:1,f:""},
  {q:"Quel personnage dit « Mon précieux » ?",a:["Frodon","Bilbon","Gollum","Sauron"],c:2,f:""},
  {q:"Combien de membres compte la Communauté de l'Anneau ?",a:["Huit","Dix","Sept","Neuf"],c:3,f:""},
  {q:"Quel est le nom elfique de Fondcombe ?",a:["Lothlórien","Imladris","Valinor","Minas Tirith"],c:1,f:""},
  {q:"Qui tue le Roi-Sorcier d'Angmar ?",a:["Aragorn","Gandalf","Éowyn","Legolas"],c:2,f:""},
  {q:"Quel acteur joue Legolas ?",a:["Elijah Wood","Orlando Bloom","Dominic Monaghan","Billy Boyd"],c:1,f:""},
  {q:"Quel est le nom de l'épée de Frodon ?",a:["Narsil","Glamdring","Dard","Andúril"],c:2,f:""},
  {q:"Quel est le peuple de Gimli ?",a:["Les Elfes","Les Hommes","Les Hobbits","Les Nains"],c:3,f:""},
  {q:"Qui est le père d'Aragorn ?",a:["Arathorn","Elrond","Théoden","Denethor"],c:0,f:""},
  {q:"Comment s'appelle l'arbre blanc du Gondor ?",a:["Telperion","L'Arbre Blanc","Laurelin","Nimloth"],c:3,f:""},
  {q:"Quel est le premier film de la trilogie de Peter Jackson ?",a:["Les Deux Tours","Le Retour du Roi","La Communauté de l'Anneau","La Bataille des Cinq Armées"],c:2,f:""},
  {q:"Comment s'appelle le cheval de Gandalf ?",a:["Bill","Hasufel","Gripoil","Arod"],c:2,f:""},
  {q:"Quel est le nom de la forêt habitée par les Ents ?",a:["La Forêt Noire","Fangorn","La Vieille Forêt","La Lothlórien"],c:1,f:""},
  {q:"Qui est le chef des Ents ?",a:["Vif-Bois","Sylvebarbe","Bregalad","Fladrif"],c:1,f:""},
  {q:"Quel Hobbit est aussi connu sous le nom de Peregrin Touque ?",a:["Sam","Merry","Frodon","Pippin"],c:3,f:""},
  {q:"Quel est le nom du royaume de Théoden ?",a:["Le Gondor","Le Rohan","L'Arnor","L'Isengard"],c:1,f:""},
  {q:"Comment s'appelle la forteresse de Saroumane ?",a:["Barad-dûr","Minas Morgul","Orthanc","Cirith Ungol"],c:2,f:""},
  {q:"Quel personnage est surnommé « Le Blanc » après sa résurrection ?",a:["Saroumane","Aragorn","Gandalf","Elrond"],c:2,f:""},
  {q:"Quel cadeau Galadriel offre-t-elle à Gimli ?",a:["Une épée elfique","Un arc d'or","Trois cheveux de sa tête","Un anneau de pouvoir"],c:2,f:""},
  {q:"Quel est le vrai nom de Gollum ?",a:["Déagol","Sméagol","Gríma","Gorbag"],c:1,f:""},
  {q:"Qui a écrit Le Seigneur des Anneaux ?",a:["C.S. Lewis","J.R.R. Tolkien","George R.R. Martin","Terry Pratchett"],c:1,f:""},
  {q:"Dans quel lieu se déroule la bataille du Gouffre de Helm ?",a:["Fort le Cor","Minas Tirith","Edoras","Osgiliath"],c:0,f:""},
  {q:"Combien d'anneaux de pouvoir ont été forgés pour les Nains ?",a:["Trois","Neuf","Sept","Un"],c:2,f:""},
  {q:"Quel est le nom du balrog combattu par Gandalf ?",a:["Gothmog","Le Fléau de Durin","Ancalagon","Glaurung"],c:1,f:""},
  {q:"Qui est l'intendant du Gondor pendant la Guerre de l'Anneau ?",a:["Faramir","Boromir","Denethor","Imrahil"],c:2,f:""},
  {q:"Quel Hobbit trouve l'Anneau Unique dans la grotte de Gollum ?",a:["Frodon","Sam","Bilbon","Merry"],c:2,f:""},
  {q:"Comment s'appelle le fils de Denethor qui fait partie de la Communauté ?",a:["Faramir","Éomer","Boromir","Haldir"],c:2,f:""},
  {q:"Quel acteur interprète Gandalf ?",a:["Patrick Stewart","Christopher Lee","Ian McKellen","Michael Gambon"],c:2,f:""},
  {q:"Quel est le nom de l'étoile qu'Eärendil porte au front ?",a:["Le Silmaril","L'Arkenstone","Le Palantír","Le Phial"],c:0,f:""},
  {q:"Qui offre à Frodon la fiole de lumière d'Eärendil ?",a:["Elrond","Arwen","Galadriel","Celeborn"],c:2,f:""},
  {q:"De quelle race est Legolas ?",a:["Nain","Hobbit","Humain","Elfe"],c:3,f:""},
  {q:"Comment s'appelle le père de Legolas ?",a:["Celeborn","Elrond","Thranduil","Gil-galad"],c:2,f:""},
  {q:"Quel objet permet de voir à distance dans le monde de Tolkien ?",a:["Un Silmaril","Un Palantír","Un Anneau","Un Miroir"],c:1,f:""},
  {q:"Quelle bataille conclut la trilogie du Seigneur des Anneaux ?",a:["La Bataille de la Morannon","La Bataille du Gouffre de Helm","La Bataille des Champs du Pelennor","La Bataille des Cinq Armées"],c:0,f:""},
  {q:"Comment s'appelle la femme qu'Aragorn épouse ?",a:["Galadriel","Éowyn","Arwen","Rosie"],c:2,f:""},
  {q:"Quel dragon Bilbon rencontre-t-il dans Le Hobbit ?",a:["Ancalagon","Glaurung","Smaug","Scatha"],c:2,f:""},
  {q:"Combien d'anneaux de pouvoir ont été forgés pour les Hommes ?",a:["Sept","Trois","Un","Neuf"],c:3,f:""},
  {q:"Qui forge l'Anneau Unique ?",a:["Celebrimbor","Fëanor","Sauron","Aulë"],c:2,f:""},
  {q:"Comment s'appelle la cotte de mailles en mithril de Frodon ?",a:["L'Armure de Durin","La Cotte de Mithril","Le Haubert de Narsil","La Brigandine d'Erebor"],c:1,f:""},
  {q:"Quel est le nombre total d'Anneaux de Pouvoir mentionnés dans le poème ?",a:["Vingt","Dix-neuf","Dix-sept","Seize"],c:0,f:""},
  {q:"Qui est Déagol par rapport à Sméagol ?",a:["Son frère","Son cousin","Son père","Son ami"],c:1,f:""},
  {q:"Quel est le nom de la tour de Sauron ?",a:["Orthanc","Minas Morgul","Barad-dûr","Cirith Ungol"],c:2,f:""},
  {q:"Comment s'appelle le poney de Sam ?",a:["Gripoil","Hasufel","Bill","Brego"],c:2,f:""},
  {q:"Quel personnage est aussi connu comme l'Elessar ?",a:["Gandalf","Elrond","Aragorn","Boromir"],c:2,f:""},
  {q:"Quelle est la dernière demeure des Elfes à l'ouest ?",a:["La Comté","Les Terres Immortelles","Le Mordor","Le Rohan"],c:1,f:""},
  {q:"Quel est le surnom de Gandalf en Rohan ?",a:["Mithrandir","Olórin","Tharkûn","Pied-de-Tempête"],c:3,f:""},
  {q:"Qui tranche les doigts de Sauron pour lui prendre l'Anneau ?",a:["Elendil","Gil-galad","Isildur","Elrond"],c:2,f:""},
  {q:"Quel événement marque la fin du Troisième Âge ?",a:["La chute de Sauron","La mort de Gandalf","La destruction de la Comté","Le départ des Elfes"],c:0,f:""},
  {q:"Comment appelle-t-on les spectres à cheval serviteurs de Sauron ?",a:["Les Uruk-hai","Les Nazgûl","Les Wargs","Les Balrogs"],c:1,f:""},
  {q:"Quel est le nom de la forteresse où se déroule la Bataille des Champs du Pelennor ?",a:["Edoras","Osgiliath","Minas Tirith","Helm"],c:2,f:""},
  {q:"Qui est la Dame de la Lothlórien ?",a:["Arwen","Éowyn","Celebrían","Galadriel"],c:3,f:""},
  {q:"Quel acteur incarne Frodon dans les films de Peter Jackson ?",a:["Daniel Radcliffe","Elijah Wood","Tobey Maguire","Sean Astin"],c:1,f:""},
  {q:"Comment s'appelle le frère de Boromir ?",a:["Éomer","Faramir","Imrahil","Haldir"],c:1,f:""},
  {q:"Quel est le nom du premier Seigneur Ténébreux, le maître de Sauron ?",a:["Ungoliant","Morgoth","Glaurung","Gothmog"],c:1,f:""},
  {q:"En quelle année est sorti le film La Communauté de l'Anneau ?",a:["1999","2001","2003","2000"],c:1,f:""},
  {q:"Combien de films composent la trilogie du Hobbit de Peter Jackson ?",a:["Deux","Quatre","Trois","Un"],c:2,f:""},
  {q:"Quel personnage tombe avec le Balrog dans les Mines de la Moria ?",a:["Aragorn","Boromir","Legolas","Gandalf"],c:3,f:""},
  {q:"Quel est le cri de guerre des Rohirrim ?",a:["Gondor !","Pour Frodon !","Mort !","Elendil !"],c:2,f:""},
  {q:"Comment s'appelle le conseiller corrompu du roi Théoden ?",a:["Gríma Langue-de-Serpent","Denethor","Alfrid","Gothmog"],c:0,f:""},
  {q:"Quel métal précieux se trouve dans les Mines de la Moria ?",a:["L'or","L'argent","Le mithril","L'acier"],c:2,f:""},
  {q:"Qui interprète Gollum grâce à la capture de mouvement ?",a:["Benedict Cumberbatch","Andy Serkis","Hugo Weaving","Cate Blanchett"],c:1,f:""},
  {q:"Comment s'appelle le lieu de résidence de Bilbon à la Comté ?",a:["Bree","Cul-de-Sac","Hobbitebourg","Le Creux-de-Crique"],c:1,f:""},
  {q:"Quel est le nom de l'auberge où les Hobbits rencontrent Grands-Pas ?",a:["Le Dragon Vert","L'auberge de Bree","Le Poney Fringant","Le Cheval d'Or"],c:2,f:""},
  {q:"Quel est le nom elfique de Gandalf ?",a:["Olórin","Curunír","Aiwendil","Pallando"],c:0,f:""},
  {q:"Qui devient roi du Gondor à la fin de la guerre ?",a:["Faramir","Éomer","Boromir","Aragorn"],c:3,f:""},
  {q:"Comment s'appelle la porte secrète des Mines de la Moria ?",a:["La Porte Noire","Les Portes de Durin","La Porte d'Argonath","Les Portes de Minas Tirith"],c:1,f:""},
  {q:"Quel mot ouvre les Portes de Durin ?",a:["Ami","Mellon","Edro","Annon"],c:1,f:""},
  {q:"Quel personnage du Hobbit est le chef des Nains de la compagnie ?",a:["Balin","Dwalin","Thorin Écu-de-Chêne","Kíli"],c:2,f:""},
  {q:"Quelle créature Bilbon rencontre-t-il en trouvant l'Anneau ?",a:["Un troll","Smaug","Gollum","Un dragon"],c:2,f:""},
  {q:"Quel est le nom de la rivière qui borde Fondcombe ?",a:["L'Anduin","Le Bruinen","L'Entaluve","Le Sirannon"],c:1,f:""},
  {q:"Qui est le roi des Elfes de la Forêt Noire dans Le Hobbit ?",a:["Elrond","Celeborn","Gil-galad","Thranduil"],c:3,f:""},
  {q:"Comment s'appelle la pierre précieuse au cœur d'Erebor ?",a:["Le Silmaril","Le Palantír","L'Arkenstone","L'Evenstar"],c:2,f:""},
  {q:"Quel acteur joue Bilbon âgé dans Le Seigneur des Anneaux ?",a:["Martin Freeman","Ian Holm","Ian McKellen","Christopher Lee"],c:1,f:""},
  {q:"Comment meurt Boromir ?",a:["Noyé dans l'Anduin","Percé de flèches d'Uruk-hai","Tué par le Balrog","Empoisonné par Saroumane"],c:1,f:""},
  {q:"Quel est le dernier mot du Seigneur des Anneaux (livre) ?",a:["Fin","Bien","Partie","Rentré"],c:1,f:""},
  {q:"Dans Le Hobbit, combien de Nains accompagnent Bilbon ?",a:["Douze","Treize","Quatorze","Onze"],c:1,f:""},
  {q:"Qui détruit finalement l'Anneau Unique en tombant dans le feu ?",a:["Frodon","Sam","Gollum","Gandalf"],c:2,f:""},
  {q:"Comment s'appelle le fils d'Aragorn et Arwen ?",a:["Eldarion","Arathorn","Théodred","Elrohir"],c:0,f:""},
  {q:"Quelle race créa les Silmarils ?",a:["Les Nains","Les Hommes","Les Elfes","Les Maiar"],c:2,f:""},
  {q:"Comment s'appelle le compagnon de Merry lors de la Bataille des Champs du Pelennor ?",a:["Aragorn","Éowyn","Théoden","Gandalf"],c:1,f:""},
  {q:"Quel est le nom de la cité en ruines entre le Gondor et le Mordor ?",a:["Minas Morgul","Helm","Osgiliath","Edoras"],c:2,f:""},
  {q:"Qui prononce la phrase « Vous ne passerez pas ! » ?",a:["Aragorn","Théoden","Gandalf","Elrond"],c:2,f:""},
  {q:"Quel acteur incarne Saroumane dans les films ?",a:["Ian McKellen","Hugo Weaving","Christopher Lee","John Rhys-Davies"],c:2,f:""},
  {q:"Comment s'appelle l'épée de Gandalf ?",a:["Orcrist","Dard","Andúril","Glamdring"],c:3,f:""},
  {q:"Quel Hobbit est surnommé « le Magnifique » ?",a:["Frodon","Bilbon","Sam","Pippin"],c:1,f:""},
  {q:"Qui interprète Elrond dans les films de Peter Jackson ?",a:["Hugo Weaving","Cate Blanchett","Lee Pace","Marton Csokas"],c:0,f:""},
  {q:"Comment s'appelle l'étoile du soir portée par Arwen ?",a:["Le Silmaril","L'Evenstar","Le Phial","Le Palantír"],c:1,f:""},
  {q:"Quel est le nom du col dangereux traversé par Frodon et Sam ?",a:["Le Col de Caradhras","Cirith Ungol","Le Pas de Dimrill","L'Escalier en Colimaçon"],c:1,f:""},
  {q:"Quelle est la particularité des pieds des Hobbits ?",a:["Ils sont très petits","Ils ont six orteils","Ils sont recouverts de poils épais","Ils sont palmés"],c:2,f:""},
  {q:"Qui est le roi du Rohan pendant la Guerre de l'Anneau ?",a:["Éomer","Théodred","Théoden","Helm"],c:2,f:""},
  {q:"Comment s'appelle le pont où Gandalf affronte le Balrog ?",a:["Le Pont de l'Anduin","Le Pont de Khazad-dûm","Le Pont d'Osgiliath","Le Pont de Fondcombe"],c:1,f:""},

  // ── 98 nouvelles questions (103 à 200) ──────────────────────────────

  {q:"Quel Vala est le forgeron qui a créé les Nains ?",a:["Manwë","Ulmo","Aulë","Oromë"],c:2,f:""},
  {q:"Comment s'appelle le personnage mystérieux de la Vieille Forêt qui porte un chapeau bleu ?",a:["Radagast","Sylvebarbe","Tom Bombadil","Beorn"],c:2,f:""},
  {q:"Quel est le nom quenya du Seigneur des Valar, roi d'Arda ?",a:["Aulë","Manwë","Tulkas","Ulmo"],c:1,f:""},
  {q:"Dans Le Silmarillion, qui crée les deux Arbres de Valinor ?",a:["Manwë","Varda","Yavanna","Nienna"],c:2,f:""},
  {q:"Comment s'appellent les deux Arbres de Valinor ?",a:["Nimloth et Galathilion","Telperion et Laurelin","Celeborn et Galadriel","Anor et Ithil"],c:1,f:""},
  {q:"Quel Elfe forge les trois Anneaux elfiques ?",a:["Fëanor","Gil-galad","Celebrimbor","Galadriel"],c:2,f:""},
  {q:"Qui est Fëanor dans Le Silmarillion ?",a:["Un Maia","Un Vala","Le créateur des Silmarils","Le premier roi du Gondor"],c:2,f:""},
  {q:"Combien de Silmarils Fëanor a-t-il créés ?",a:["Un","Deux","Trois","Sept"],c:2,f:""},
  {q:"Quel est le nom sindarin de la Terre du Milieu ?",a:["Arda","Aman","Endor","Valinor"],c:2,f:""},
  {q:"Comment s'appelle le magicien brun, ami des animaux ?",a:["Alatar","Pallando","Radagast","Olórin"],c:2,f:""},
  {q:"Quel est le véritable nom maiar de Saroumane ?",a:["Olórin","Aiwendil","Curunír","Pallando"],c:2,f:""},
  {q:"Dans quel pays a été tournée la trilogie du Seigneur des Anneaux ?",a:["L'Australie","L'Irlande","La Nouvelle-Zélande","L'Écosse"],c:2,f:""},
  {q:"Comment s'appelle le studio d'effets spéciaux fondé par Peter Jackson ?",a:["ILM","WETA Workshop","Framestore","Double Negative"],c:1,f:""},
  {q:"Combien d'Oscars le film Le Retour du Roi a-t-il remportés ?",a:["Huit","Onze","Six","Neuf"],c:1,f:""},
  {q:"Qui a composé la bande originale de la trilogie du Seigneur des Anneaux ?",a:["John Williams","Hans Zimmer","Howard Shore","James Horner"],c:2,f:""},
  {q:"Quel Vala est associé à la mer et aux océans ?",a:["Oromë","Aulë","Manwë","Ulmo"],c:3,f:""},
  {q:"Quel est le nom de la Vala qui crée les étoiles ?",a:["Yavanna","Nienna","Varda","Estë"],c:2,f:""},
  {q:"Quel est le nom quenya de Sauron avant sa chute ?",a:["Melkor","Mairon","Curunír","Ossë"],c:1,f:""},
  {q:"Qui est Glorfindel dans l'univers de Tolkien ?",a:["Un Nain de la Moria","Un seigneur elfe qui a tué un Balrog","Le roi des Hommes de l'Est","Un Istari oublié"],c:1,f:""},
  {q:"Quel personnage remplace Glorfindel dans les films de Peter Jackson ?",a:["Legolas","Elrond","Arwen","Haldir"],c:2,f:""},
  {q:"Comment s'appelle le frère d'Éowyn, maréchal du Riddermark ?",a:["Théodred","Háma","Éomer","Erkenbrand"],c:2,f:""},
  {q:"Quel est le nom du fils de Théoden, tué par les Orques ?",a:["Éomer","Háma","Théodred","Gamelin"],c:2,f:""},
  {q:"Comment s'appelle la femme de Tom Bombadil ?",a:["Arwen","Baie d'Or","Rosie Cotton","Ioreth"],c:1,f:""},
  {q:"Quel est le nom de l'épée de Thorin Écu-de-Chêne dans Le Hobbit ?",a:["Glamdring","Dard","Orcrist","Narsil"],c:2,f:""},
  {q:"Dans Le Hobbit, comment s'appelle le changeur de peau qui se transforme en ours ?",a:["Radagast","Tom Bombadil","Beorn","Grimbeorn"],c:2,f:""},
  {q:"Qui tue Smaug dans Le Hobbit ?",a:["Thorin","Bilbon","Gandalf","Bard l'Archer"],c:3,f:""},
  {q:"Avec quelle arme Bard tue-t-il Smaug ?",a:["Une épée elfique","Un arc ordinaire","La Flèche Noire","Une lance de Nain"],c:2,f:""},
  {q:"Dans la série Les Anneaux de Pouvoir, à quel Âge se situe l'action ?",a:["Le Premier Âge","Le Deuxième Âge","Le Troisième Âge","Le Quatrième Âge"],c:1,f:""},
  {q:"Comment s'appelle l'Elfe original créé pour la série Les Anneaux de Pouvoir ?",a:["Celebrimbor","Arondir","Gil-galad","Círdan"],c:1,f:""},
  {q:"Quel personnage féminin Harfoot est central dans Les Anneaux de Pouvoir ?",a:["Bronwyn","Disa","Nori Brandyfoot","Míriel"],c:2,f:""},
  {q:"Dans Le Silmarillion, quel est le plus grand dragon ailé de tous les temps ?",a:["Smaug","Glaurung","Scatha","Ancalagon le Noir"],c:3,f:""},
  {q:"Quel est le premier dragon de Morgoth, incapable de voler ?",a:["Smaug","Ancalagon","Glaurung","Scatha"],c:2,f:""},
  {q:"Comment s'appelle la grande bataille qui met fin au Premier Âge ?",a:["La Bataille de la Dernière Alliance","La Guerre de la Colère","La Bataille des Cinq Armées","Dagor Bragollach"],c:1,f:""},
  {q:"Quel est le nom de la grande forteresse de Morgoth dans le Nord ?",a:["Barad-dûr","Utumno","Angband","Orthanc"],c:2,f:""},
  {q:"Dans quelle université Tolkien a-t-il enseigné la majeure partie de sa carrière ?",a:["Cambridge","Oxford","Edinburgh","Londres"],c:1,f:""},
  {q:"Quelle était la spécialité académique de J.R.R. Tolkien ?",a:["L'histoire médiévale","La philologie et les langues anciennes","La théologie","La botanique"],c:1,f:""},
  {q:"En quelle année Le Hobbit a-t-il été publié pour la première fois ?",a:["1937","1942","1954","1929"],c:0,f:""},
  {q:"Quel ami proche de Tolkien a écrit Les Chroniques de Narnia ?",a:["Charles Williams","Owen Barfield","C.S. Lewis","Roger Lancelyn Green"],c:2,f:""},
  {q:"Comment s'appelle le groupe littéraire auquel appartenaient Tolkien et C.S. Lewis ?",a:["Le Bloomsbury Group","Les Inklings","Le Cercle de Vienne","Les Préraphaélites"],c:1,f:""},
  {q:"Quel est le mot sindarin pour « ami » inscrit sur les Portes de Durin ?",a:["Annon","Edro","Mellon","Pedo"],c:2,f:""},
  {q:"Comment dit-on « salut » en quenya ?",a:["Mellon","Aiya","Namárië","Elen síla"],c:1,f:""},
  {q:"Que signifie « Namárië » en quenya ?",a:["Bienvenue","Bonjour","Au revoir","Merci"],c:2,f:""},
  {q:"Quel est le nom quenya de la langue commune parlée en Terre du Milieu ?",a:["Sindarin","Westron","Quenya","Khuzdul"],c:1,f:""},
  {q:"Comment s'appelle la langue secrète des Nains inventée par Tolkien ?",a:["Le Sindarin","Le Quenya","Le Khuzdul","L'Adûnaic"],c:2,f:""},
  {q:"Combien d'Istari (magiciens) ont été envoyés en Terre du Milieu ?",a:["Trois","Deux","Cinq","Sept"],c:2,f:""},
  {q:"Quel cadeau Galadriel offre-t-elle à Legolas ?",a:["Une cape elfique","Un arc de la Galadhrim","Une fiole de lumière","Des lembas"],c:1,f:""},
  {q:"Quel cadeau Galadriel offre-t-elle à Sam ?",a:["Une fiole de lumière","De la terre de son jardin","Une épée elfique","Un anneau"],c:1,f:""},
  {q:"Comment s'appelle le pain de route elfique donné à la Communauté ?",a:["Le cram","Le lembas","Le miruvor","Le galenas"],c:1,f:""},
  {q:"Quel est le nom du continent où se trouve Valinor ?",a:["Endor","Númenor","Aman","Beleriand"],c:2,f:""},
  {q:"Comment s'appelle l'île en forme d'étoile offerte aux Hommes fidèles ?",a:["Tol Eressëa","Valinor","Númenor","Himling"],c:2,f:""},
  {q:"Quel roi de Númenor défie les Valar et provoque la submersion de l'île ?",a:["Elendil","Isildur","Ar-Pharazôn","Tar-Míriel"],c:2,f:""},
  {q:"Comment s'appelle la reine de Númenor dans Les Anneaux de Pouvoir ?",a:["Galadriel","Tar-Míriel","Arwen","Celebrían"],c:1,f:""},
  {q:"Quel est le nom de la bataille finale de la Dernière Alliance des Elfes et des Hommes ?",a:["La Bataille de Dagorlad","La Guerre de la Colère","Helm","La Bataille de Fornost"],c:0,f:""},
  {q:"Quelle arme Théoden brandit-il à la charge du Pelennor ?",a:["Andúril","Herugrim","Glamdring","Gúthwinë"],c:1,f:""},
  {q:"Comment s'appelle l'épée d'Éomer ?",a:["Herugrim","Narsil","Gúthwinë","Orcrist"],c:2,f:""},
  {q:"Quel est le nom de l'épée reforgée à partir de Narsil ?",a:["Glamdring","Dard","Andúril","Orcrist"],c:2,f:""},
  {q:"Qui reforge Narsil en Andúril dans le livre ?",a:["Elrond","Les forgerons elfes de Fondcombe","Aragorn lui-même","Celebrimbor"],c:1,f:""},
  {q:"Comment s'appelle le cor que Boromir porte toujours avec lui ?",a:["Le Cor du Gondor","Le Cor de Helm","Le Cor du Rohan","Le Cor de Buckland"],c:0,f:""},
  {q:"Quelle chanson Pippin chante-t-il devant Denethor dans le film ?",a:["La Route se poursuit","Au bord de la mer","The Edge of Night","A Elbereth Gilthoniel"],c:2,f:""},
  {q:"Comment s'appelle le village de Hobbitebourg en anglais, utilisé comme décor en Nouvelle-Zélande ?",a:["Hobbiton","Bag End","Bywater","Michel Delving"],c:0,f:""},
  {q:"Dans quelle région de Nouvelle-Zélande se trouve le décor de Hobbiton ?",a:["Queenstown","Wellington","Matamata","Christchurch"],c:2,f:""},
  {q:"Quel volcan néo-zélandais a servi de décor pour la Montagne du Destin ?",a:["Le Mont Cook","Le Mont Ruapehu","Le Mont Ngauruhoe","Le Mont Taranaki"],c:2,f:""},
  {q:"Combien d'Oscars La Communauté de l'Anneau a-t-elle remportés ?",a:["Onze","Deux","Quatre","Six"],c:2,f:""},
  {q:"Quelle catégorie d'Oscar Le Retour du Roi a-t-il remportée pour la première fois pour un film fantastique ?",a:["Meilleur acteur","Meilleur film","Meilleurs effets visuels","Meilleure musique"],c:1,f:""},
  {q:"Quel acteur joue Sam dans les films de Peter Jackson ?",a:["Billy Boyd","Dominic Monaghan","Sean Astin","Elijah Wood"],c:2,f:""},
  {q:"Comment s'appelle la femme que Sam épouse à la fin du livre ?",a:["Rosie Cotton","Baie d'Or","Lobelia","Estella Bolger"],c:0,f:""},
  {q:"Quel est le nom complet de Merry ?",a:["Meriadoc Brandebouc","Meriadoc Touque","Meridian Sacquet","Meriadoc Gamegie"],c:0,f:""},
  {q:"Quel est le surnom donné à Aragorn par les Elfes ?",a:["Estel","Thorongil","Elessar","Telcontar"],c:0,f:""},
  {q:"Quel est le nom de la montagne sous laquelle se trouvent les Mines de la Moria ?",a:["Le Caradhras","Le Celebdil","Le Mont Venteux","Les trois pics : Caradhras, Celebdil et Fanuidhol"],c:3,f:""},
  {q:"Quel personnage aide Frodon à traverser le gué de Bruinen dans le livre ?",a:["Arwen","Gandalf","Glorfindel","Legolas"],c:2,f:""},
  {q:"Qui est le Maia serviteur de Morgoth qui prend la forme d'une araignée géante ?",a:["Shelob","Ungoliant","Sauron","Gothmog"],c:1,f:""},
  {q:"Quel objet Bilbon écrit-il pendant sa retraite à Fondcombe ?",a:["L'histoire de la Comté","Histoire d'un aller et retour","Le Livre Rouge","Les Contes de Fées"],c:1,f:""},
  {q:"Comment s'appelle la chaîne de montagnes qui sépare l'Eriador du Rhovanion ?",a:["Les Monts de Fer","Les Monts Brumeux","Les Montagnes Blanches","Les Montagnes du Mordor"],c:1,f:""},
  {q:"Quel fleuve majeur traverse le Gondor du nord au sud ?",a:["Le Bruinen","L'Entaluve","L'Anduin","Le Sirannon"],c:2,f:""},
  {q:"Comment s'appelle le lieu où la Communauté se sépare à la fin du premier volume ?",a:["L'Argonath","Amon Hen","Les Chutes de Rauros","Parth Galen"],c:3,f:""},
  {q:"Quel est le nom des deux grandes statues qui gardent l'entrée du Gondor sur l'Anduin ?",a:["Les Portes de Durin","L'Argonath","Les Piliers des Rois","Les Tours de Guet"],c:1,f:""},
  {q:"Quelle est la durée totale de la version longue des trois films du Seigneur des Anneaux ?",a:["Environ 9 heures","Environ 11 heures 30","Environ 8 heures","Environ 13 heures"],c:1,f:""},
  {q:"Combien de minutes supplémentaires la version longue de La Communauté de l'Anneau ajoute-t-elle ?",a:["Environ 15 minutes","Environ 30 minutes","Environ 50 minutes","Environ 70 minutes"],c:1,f:""},
  {q:"Quel instrument de musique est associé au thème de la Comté dans la bande originale ?",a:["Le violon","La flûte irlandaise (tin whistle)","Le piano","La harpe"],c:1,f:""},
  {q:"Quel chœur chante les passages en langues elfiques dans la bande originale de Howard Shore ?",a:["Le Chœur de Vienne","Le London Philharmonic Choir","Le New Zealand Symphony Orchestra","Le Chœur de la Radio de Berlin"],c:1,f:""},
  {q:"Quel est le nom du thème musical principal associé à la Communauté ?",a:["Le thème du Rohan","Le thème de la Communauté de l'Anneau","Le thème du Gondor","Le thème de la Comté"],c:1,f:""},
  {q:"Qui chante « Into the West » à la fin du Retour du Roi ?",a:["Enya","Annie Lennox","Celine Dion","Liv Tyler"],c:1,f:""},
  {q:"Dans la série Les Anneaux de Pouvoir, qui est Halbrand ?",a:["Un roi du Rohan","Sauron déguisé","Un Nain d'Erebor","Un Hobbit"],c:1,f:""},
  {q:"Quel est le nom nain de la Moria ?",a:["Erebor","Nogrod","Khazad-dûm","Belegost"],c:2,f:""},
  {q:"Quel Vala est associé aux songes et aux visions ?",a:["Irmo (Lórien)","Mandos","Tulkas","Oromë"],c:0,f:""},
  {q:"Comment s'appelle le lieu où les Elfes morts attendent en Valinor ?",a:["Les Cavernes de Mandos","Les Jardins de Lórien","Les Halls de Manwë","Les Forges d'Aulë"],c:0,f:""},
  {q:"Quel est le nom de l'écriture inventée par Fëanor, utilisée par les Elfes ?",a:["Les Cirth","Les Tengwar","Les Runes","L'Angerthas"],c:1,f:""},
  {q:"Quelle est la langue des inscriptions sur l'Anneau Unique ?",a:["Le Quenya","Le Sindarin","Le Noir Parler du Mordor","Le Khuzdul"],c:2,f:""},
  {q:"Comment Théoden meurt-il lors de la Bataille des Champs du Pelennor ?",a:["Frappé par une flèche","Écrasé sous son cheval","Tué par le Roi-Sorcier","Empoisonné"],c:1,f:""},
  {q:"Quel animal fantastique chevauche le Roi-Sorcier lors de la Bataille du Pelennor ?",a:["Un dragon","Un Warg","Un fell beast (bête ailée)","Un Balrog"],c:2,f:""},
  {q:"Comment s'appelle le Capitaine des Haradrim à la Bataille du Pelennor dans les films ?",a:["Gothmog","Le Roi-Sorcier","Le Chef des Corsaires","Le Serpent du Sud"],c:0,f:""},
  {q:"Quel cadeau Galadriel offre-t-elle à Frodon en plus de la fiole ?",a:["Une cotte de mithril","Une cape elfique","Rien d'autre","Un anneau de pouvoir"],c:1,f:""},
  {q:"Que devient Saroumane après la guerre dans les livres ?",a:["Il retourne en Valinor","Il meurt à la Comté","Il s'exile dans l'Est","Il est emprisonné à Fondcombe"],c:1,f:""},
  {q:"Comment s'appelle l'épisode de la Comté ravagée par Saroumane dans le livre ?",a:["La Bataille de Lézeau","Le Nettoyage de la Comté","La Guerre de la Comté","Le Sac de Hobbitebourg"],c:1,f:""},
  {q:"Quel Maia se transforme en loup-garou géant au service de Morgoth dans Le Silmarillion ?",a:["Sauron","Gothmog","Thuringwethil","Draugluin"],c:0,f:""},
  {q:"Qui sont Beren et Lúthien dans Le Silmarillion ?",a:["Deux rois elfes","Un Homme et une Elfe qui volent un Silmaril à Morgoth","Les parents de Fëanor","Les fondateurs du Gondor"],c:1,f:""},
  {q:"Quel couple de l'histoire de Tolkien est gravé sur la tombe de J.R.R. et Edith Tolkien ?",a:["Aragorn et Arwen","Beren et Lúthien","Tuor et Idril","Eärendil et Elwing"],c:1,f:""},
  {q:"Quel est le nom du chien de chasse géant qui accompagne Beren et Lúthien ?",a:["Draugluin","Carcharoth","Huan","Tevildo"],c:2,f:""},
  {q:"En quelle année J.R.R. Tolkien est-il décédé ?",a:["1971","1973","1975","1977"],c:1,f:""},
];
