/* ════════════════════════════════════════
   questions/music.js — Musique — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.music = [
  {q:"Quel groupe a chanté 'Bohemian Rhapsody' ?",a:["The Beatles","Queen","The Rolling Stones","Pink Floyd"],c:1,f:""},
  {q:"Quel chanteur est surnommé 'The King of Pop' ?",a:["Prince","Elvis Presley","Michael Jackson","Stevie Wonder"],c:2,f:""},
  {q:"Quel instrument possède généralement 6 cordes ?",a:["Violon","Guitare","Harpe","Piano"],c:1,f:""},
  {q:"Qui a composé la 9e symphonie ?",a:["Johann Sebastian Bach","Ludwig van Beethoven","Wolfgang Amadeus Mozart","Franz Schubert"],c:1,f:""},
  {q:"Quel groupe a chanté 'Hey Jude' ?",a:["The Rolling Stones","The Beatles","Queen","Oasis"],c:1,f:""},
  {q:"Quel chanteur a interprété 'Shape of You' ?",a:["Ed Sheeran","Justin Bieber","Shawn Mendes","Sam Smith"],c:0,f:""},
  {q:"Quel chanteur français est connu pour 'Je te promets' ?",a:["Florent Pagny","Jean-Jacques Goldman","Johnny Hallyday","Michel Sardou"],c:2,f:""},
  {q:"Dans quel pays est né Bob Marley ?",a:["États-Unis","Jamaïque","Royaume-Uni","Brésil"],c:1,f:""},
  {q:"Quel groupe a chanté 'Smells Like Teen Spirit' ?",a:["Nirvana","Metallica","Pearl Jam","Green Day"],c:0,f:""},
  {q:"Quel chanteur est célèbre pour 'Rocket Man' ?",a:["Elton John","David Bowie","Freddie Mercury","George Michael"],c:0,f:""},
  {q:"Qui chante 'Rolling in the Deep' ?",a:["Adele","Amy Winehouse","Dua Lipa","Sia"],c:0,f:""},
  {q:"Quel groupe a chanté 'Hotel California' ?",a:["Eagles","Fleetwood Mac","Aerosmith","Bon Jovi"],c:0,f:""},
  {q:"Quel groupe a chanté 'Viva La Vida' ?",a:["Coldplay","U2","Imagine Dragons","Muse"],c:0,f:""},
  {q:"Qui a chanté 'Like a Virgin' ?",a:["Madonna","Whitney Houston","Cyndi Lauper","Cher"],c:0,f:""},
  {q:"Quel groupe a chanté 'Wonderwall' ?",a:["Blur","Oasis","Radiohead","Arctic Monkeys"],c:1,f:""},
  {q:"Quel chanteur français est connu pour 'Formidable' ?",a:["Stromae","Orelsan","Vianney","Soprano"],c:0,f:""},
  {q:"Quel groupe a chanté 'We Will Rock You' ?",a:["Queen","AC/DC","Kiss","Bon Jovi"],c:0,f:""},
  {q:"Qui chante 'Bad Romance' ?",a:["Katy Perry","Lady Gaga","Rihanna","Beyoncé"],c:1,f:""},
  {q:"Quel groupe est connu pour 'Another Brick in the Wall' ?",a:["Pink Floyd","Deep Purple","Genesis","Yes"],c:0,f:""},
  {q:"Quel chanteur a interprété 'Someone Like You' ?",a:["Adele","Sam Smith","Lewis Capaldi","Ed Sheeran"],c:0,f:""},
  {q:"Dans quel pays est né Freddie Mercury ?",a:["Royaume-Uni","Inde","Tanzanie","États-Unis"],c:2,f:""},
  {q:"Quel groupe a chanté 'Sweet Child O' Mine' ?",a:["Guns N' Roses","Aerosmith","Metallica","Nirvana"],c:0,f:""},
  {q:"Combien de notes y a-t-il dans la gamme musicale classique ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Quel instrument utilise des baguettes ?",a:["Piano","Batterie","Harpe","Flûte"],c:1,f:""},
  {q:"Dans quel genre musical chante Bob Marley ?",a:["Jazz","Soul","Reggae","Ska"],c:2,f:""},
  {q:"Quel chanteur est connu pour 'Purple Rain' ?",a:["Prince","Michael Jackson","David Bowie","Stevie Wonder"],c:0,f:""},
  {q:"Quel groupe britannique est formé de Mick Jagger ?",a:["The Beatles","The Rolling Stones","Led Zeppelin","The Who"],c:1,f:""},
  {q:"Qui chante 'Thriller' ?",a:["Prince","Michael Jackson","Stevie Wonder","James Brown"],c:1,f:""},
  {q:"Quel groupe a chanté 'One' et 'With or Without You' ?",a:["Coldplay","U2","R.E.M.","Radiohead"],c:1,f:""},
  {q:"Quel chanteur français est connu pour 'La Vie en Rose' ?",a:["Charles Aznavour","Jacques Brel","Édith Piaf","Serge Gainsbourg"],c:2,f:""},
  {q:"Quel groupe a chanté 'Back in Black' ?",a:["Metallica","AC/DC","Iron Maiden","Judas Priest"],c:1,f:""},
  {q:"Qui chante 'Umbrella' ?",a:["Beyoncé","Rihanna","Nicki Minaj","Cardi B"],c:1,f:""},
  {q:"Quel chanteur est connu pour 'Space Oddity' ?",a:["Elton John","David Bowie","Freddie Mercury","Lou Reed"],c:1,f:""},
  {q:"Quel groupe a chanté 'Stairway to Heaven' ?",a:["Deep Purple","Black Sabbath","Led Zeppelin","The Who"],c:2,f:""},
  {q:"Qui chante 'Poker Face' ?",a:["Katy Perry","Lady Gaga","Britney Spears","Rihanna"],c:1,f:""},
  {q:"Quel chanteur est connu pour 'Superstition' ?",a:["Marvin Gaye","Stevie Wonder","Ray Charles","James Brown"],c:1,f:""},
  {q:"Quel groupe a chanté 'Losing My Religion' ?",a:["Radiohead","R.E.M.","Nirvana","Pearl Jam"],c:1,f:""},
  {q:"Qui chante 'Hello' (2015) ?",a:["Adele","Beyoncé","Sam Smith","Sia"],c:0,f:""},
  {q:"Quel groupe a chanté 'Mr. Brightside' ?",a:["The Killers","Interpol","Franz Ferdinand","Arctic Monkeys"],c:0,f:""},
  {q:"Quel chanteur est connu pour 'Heroes' ?",a:["Elton John","David Bowie","Lou Reed","Iggy Pop"],c:1,f:""},
  {q:"Qui chante 'Toxic' ?",a:["Britney Spears","Christina Aguilera","Kylie Minogue","Paris Hilton"],c:0,f:""},
  {q:"Quel groupe a chanté 'Don't Look Back in Anger' ?",a:["Blur","Oasis","Radiohead","Pulp"],c:1,f:""},
  {q:"Qui chante 'What's Going On' ?",a:["Stevie Wonder","Marvin Gaye","Al Green","Curtis Mayfield"],c:1,f:""},
  {q:"Quel groupe a chanté 'Creep' ?",a:["Radiohead","Muse","Portishead","Massive Attack"],c:0,f:""},
  {q:"Qui chante 'Halo' ?",a:["Adele","Rihanna","Beyoncé","Alicia Keys"],c:2,f:""},
  {q:"Quel groupe a chanté 'Hysteria' ?",a:["Def Leppard","Poison","Bon Jovi","Whitesnake"],c:0,f:""},
  {q:"Qui chante 'Thinking Out Loud' ?",a:["Sam Smith","James Bay","Ed Sheeran","Harry Styles"],c:2,f:""},
  {q:"Quel groupe a chanté 'Knockin' on Heaven's Door' (original) ?",a:["Bob Dylan","Neil Young","Bruce Springsteen","Tom Petty"],c:0,f:""},
  {q:"Qui chante 'No One' ?",a:["Mary J. Blige","Alicia Keys","Erykah Badu","Lauryn Hill"],c:1,f:""},
  {q:"Quel groupe a chanté 'Yellow' ?",a:["Coldplay","Muse","U2","Radiohead"],c:0,f:""},
  {q:"Qui chante 'Crazy in Love' ?",a:["Rihanna","Beyoncé","Mariah Carey","Whitney Houston"],c:1,f:""},
  {q:"Quel groupe a chanté 'Come As You Are' ?",a:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],c:2,f:""},
  {q:"Qui chante 'Chandelier' ?",a:["Lorde","Lana Del Rey","Sia","Halsey"],c:2,f:""},
  {q:"Quel groupe a chanté 'Paint It Black' ?",a:["The Beatles","The Rolling Stones","The Doors","The Kinks"],c:1,f:""},
  {q:"Qui chante 'Stay With Me' ?",a:["Sam Smith","James Arthur","Olly Murs","Shawn Mendes"],c:0,f:""},
  {q:"Quel groupe a chanté 'Nothing Else Matters' ?",a:["Metallica","Megadeth","Slayer","Pantera"],c:0,f:""},
  {q:"Qui chante 'Royals' ?",a:["Lorde","Halsey","Alessia Cara","Billie Eilish"],c:0,f:""},
  {q:"Quel groupe a chanté 'In the End' ?",a:["Linkin Park","System of a Down","Slipknot","Korn"],c:0,f:""},
  {q:"Qui chante 'Bad Guy' ?",a:["Lorde","Halsey","Billie Eilish","Olivia Rodrigo"],c:2,f:""},
  {q:"Quel groupe a chanté 'Seven Nation Army' ?",a:["The Black Keys","The White Stripes","The Strokes","Jack Johnson"],c:1,f:""},
  {q:"Qui chante 'Shallow' dans A Star Is Born ?",a:["Adele","Lady Gaga","Pink","Sia"],c:1,f:""},
  {q:"Quel groupe a chanté 'Supermassive Black Hole' ?",a:["Muse","Radiohead","Placebo","Interpol"],c:0,f:""},
  {q:"Qui chante 'Diamonds' ?",a:["Beyoncé","Rihanna","Katy Perry","Nicki Minaj"],c:1,f:""},
  {q:"Quel groupe a chanté 'Under the Bridge' ?",a:["Red Hot Chili Peppers","Foo Fighters","Rage Against the Machine","Green Day"],c:0,f:""},
  {q:"Qui chante 'Empire State of Mind' ?",a:["Kanye West","Jay-Z","Drake","Lil Wayne"],c:1,f:""},
  {q:"Quel groupe a chanté 'Every Breath You Take' ?",a:["The Police","Sting","Dire Straits","Genesis"],c:0,f:""},
  {q:"Qui chante 'Valerie' (version Amy Winehouse) ?",a:["Amy Winehouse","Duffy","Adele","Joss Stone"],c:0,f:""},
  {q:"Quel groupe a chanté 'Smack My Bitch Up' ?",a:["Chemical Brothers","Prodigy","Fatboy Slim","Daft Punk"],c:1,f:""},
  {q:"Qui chante 'Get Lucky' ?",a:["Justice","Daft Punk","Disclosure","Calvin Harris"],c:1,f:""},
  {q:"Quel groupe a chanté 'Blue (Da Ba Dee)' ?",a:["Aqua","Eiffel 65","Vengaboys","Technotronic"],c:1,f:""},
  {q:"Qui chante 'Despacito' ?",a:["Maluma","Ozuna","Luis Fonsi","J Balvin"],c:2,f:""},
  {q:"Quel groupe a chanté 'I Will Always Love You' (original) ?",a:["Dolly Parton","Whitney Houston","Celine Dion","Tina Turner"],c:0,f:""},
  {q:"Qui chante 'Blinding Lights' ?",a:["Drake","The Weeknd","Post Malone","Travis Scott"],c:1,f:""},
  {q:"Quel groupe a chanté 'Africa' ?",a:["Toto","Chicago","Journey","Boston"],c:0,f:""},
  {q:"Qui chante 'Levitating' ?",a:["Dua Lipa","Lizzo","Doja Cat","Ariana Grande"],c:0,f:""},
  {q:"Quel groupe a chanté 'Don't Stop Me Now' ?",a:["Queen","The Beatles","The Rolling Stones","David Bowie"],c:0,f:""},
  {q:"Qui chante 'Watermelon Sugar' ?",a:["Niall Horan","Liam Payne","Harry Styles","Zayn"],c:2,f:""},
  {q:"Quel groupe a chanté 'Eye of the Tiger' ?",a:["Foreigner","Journey","Survivor","REO Speedwagon"],c:2,f:""},
  {q:"Qui chante 'drivers license' ?",a:["Billie Eilish","Olivia Rodrigo","Sabrina Carpenter","Taylor Swift"],c:1,f:""},
  {q:"Quel groupe a chanté 'Take on Me' ?",a:["a-ha","Duran Duran","Erasure","Pet Shop Boys"],c:0,f:""},
  {q:"Qui chante 'Flowers' (2023) ?",a:["Dua Lipa","Lizzo","Miley Cyrus","Doja Cat"],c:2,f:""},
  {q:"Quel groupe a chanté 'Sweet Home Alabama' ?",a:["Lynyrd Skynyrd","The Allman Brothers","CCR","ZZ Top"],c:0,f:""},
  {q:"Qui chante 'As It Was' ?",a:["Lewis Capaldi","Harry Styles","Niall Horan","Sam Smith"],c:1,f:""},
  {q:"Quel groupe a chanté 'Livin' on a Prayer' ?",a:["Bon Jovi","Aerosmith","Def Leppard","Whitesnake"],c:0,f:""},
  {q:"Qui chante 'Anti-Hero' ?",a:["Adele","Billie Eilish","Taylor Swift","Olivia Rodrigo"],c:2,f:""},
  {q:"Quel groupe a chanté 'Mr. Jones' ?",a:["Counting Crows","Matchbox Twenty","Third Eye Blind","Semisonic"],c:0,f:""},
  {q:"Qui chante 'Stay' (2021) ?",a:["The Kid LAROI seul","Justin Bieber seul","The Kid LAROI ft. Justin Bieber","Juice WRLD"],c:2,f:""},
  {q:"Quel groupe a chanté 'Numb' ?",a:["Linkin Park","System of a Down","Korn","Limp Bizkit"],c:0,f:""},
  {q:"Qui chante 'Peaches' (2021) ?",a:["Drake","The Weeknd","Justin Bieber","Post Malone"],c:2,f:""},
  {q:"Quel chanteur français est connu pour 'Alexandrie Alexandra' ?",a:["Claude François","Michel Sardou","Joe Dassin","Daniel Guichard"],c:0,f:""},
  {q:"Qui chante 'As Long as You Love Me' ?",a:["*NSYNC","Backstreet Boys","New Kids on the Block","Boyz II Men"],c:1,f:""},
  {q:"Quel groupe a chanté 'Don't You (Forget About Me)' ?",a:["Simple Minds","New Order","The Cure","Depeche Mode"],c:0,f:""},
  {q:"Qui chante 'good 4 u' ?",a:["Billie Eilish","Olivia Rodrigo","Sabrina Carpenter","Gracie Abrams"],c:1,f:""},
  {q:"Quel groupe a chanté 'Walking on Sunshine' ?",a:["Katrina and the Waves","Bananarama","The Go-Go's","Cyndi Lauper"],c:0,f:""},
  {q:"Qui chante 'Lose Yourself' ?",a:["Jay-Z","Kanye West","Eminem","50 Cent"],c:2,f:""},
  {q:"Quel groupe a chanté 'Should I Stay or Should I Go' ?",a:["The Clash","Sex Pistols","The Jam","The Buzzcocks"],c:0,f:""},
  {q:"Qui chante 'Titanium' ?",a:["Sia ft. David Guetta","Adele","Beyoncé","Pink"],c:0,f:""},
];
