/* ════════════════════════════════════════
   questions/music.js — Musique — 200 questions
   ════════════════════════════════════════ */
QUESTIONS.music = [
  // ── Existing 98 questions ──
  {q:"Quel groupe a chanté 'Bohemian Rhapsody' ?",a:["The Beatles","Queen","The Rolling Stones","Pink Floyd"],c:1,f:""},
  {q:"Quel chanteur est surnommé 'The King of Pop' ?",a:["Prince","Elvis Presley","Michael Jackson","Stevie Wonder"],c:2,f:""},
  {q:"Quel instrument possède généralement 6 cordes ?",a:["Violon","Guitare","Harpe","Piano"],c:1,f:""},
  {q:"Qui a composé la 9e symphonie ?",a:["Johann Sebastian Bach","Ludwig van Beethoven","Wolfgang Amadeus Mozart","Franz Schubert"],c:1,f:""},
  {q:"Quel groupe a chanté 'Hey Jude' ?",a:["The Rolling Stones","The Beatles","Queen","Oasis"],c:1,f:""},
  {q:"Quel chanteur a interprété 'Shape of You' ?",a:["Ed Sheeran","Justin Bieber","Shawn Mendes","Sam Smith"],c:0,f:""},
  {q:"Quel chanteur français est connu pour 'Je te promets' ?",a:["Florent Pagny","Jean-Jacques Goldman","Johnny Hallyday","Michel Sardou"],c:2,f:""},
  {q:"Dans quel pays est né Bob Marley ?",a:["États-Unis","Jamaïque","Royaume-Uni","Brésil"],c:1,f:""},
  {q:"Quel groupe a chanté 'Smells Like Teen Spirit' ?",a:["Nirvana","Metallica","Pearl Jam","Green Day"],c:0,f:""},
  {q:"Quel chanteur est célèbre pour 'Rocket Man' ?",a:["Elton John","David Bowie","Freddie Mercury","George Michael"],c:0,f:""},
  {q:"Qui chante 'Rolling in the Deep' ?",a:["Adele","Amy Winehouse","Dua Lipa","Sia"],c:0,f:""},
  {q:"Quel groupe a chanté 'Hotel California' ?",a:["Eagles","Fleetwood Mac","Aerosmith","Bon Jovi"],c:0,f:""},
  {q:"Quel groupe a chanté 'Viva La Vida' ?",a:["Coldplay","U2","Imagine Dragons","Muse"],c:0,f:""},
  {q:"Qui a chanté 'Like a Virgin' ?",a:["Madonna","Whitney Houston","Cyndi Lauper","Cher"],c:0,f:""},
  {q:"Quel groupe a chanté 'Wonderwall' ?",a:["Blur","Oasis","Radiohead","Arctic Monkeys"],c:1,f:""},
  {q:"Quel chanteur français est connu pour 'Formidable' ?",a:["Stromae","Orelsan","Vianney","Soprano"],c:0,f:""},
  {q:"Quel groupe a chanté 'We Will Rock You' ?",a:["Queen","AC/DC","Kiss","Bon Jovi"],c:0,f:""},
  {q:"Qui chante 'Bad Romance' ?",a:["Katy Perry","Lady Gaga","Rihanna","Beyoncé"],c:1,f:""},
  {q:"Quel groupe est connu pour 'Another Brick in the Wall' ?",a:["Pink Floyd","Deep Purple","Genesis","Yes"],c:0,f:""},
  {q:"Quel chanteur a interprété 'Someone Like You' ?",a:["Adele","Sam Smith","Lewis Capaldi","Ed Sheeran"],c:0,f:""},
  {q:"Dans quel pays est né Freddie Mercury ?",a:["Royaume-Uni","Inde","Tanzanie","États-Unis"],c:2,f:""},
  {q:"Quel groupe a chanté 'Sweet Child O' Mine' ?",a:["Guns N' Roses","Aerosmith","Metallica","Nirvana"],c:0,f:""},
  {q:"Combien de notes y a-t-il dans la gamme musicale classique ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Quel instrument utilise des baguettes ?",a:["Piano","Batterie","Harpe","Flûte"],c:1,f:""},
  {q:"Dans quel genre musical chante Bob Marley ?",a:["Jazz","Soul","Reggae","Ska"],c:2,f:""},
  {q:"Quel chanteur est connu pour 'Purple Rain' ?",a:["Prince","Michael Jackson","David Bowie","Stevie Wonder"],c:0,f:""},
  {q:"Quel groupe britannique est formé de Mick Jagger ?",a:["The Beatles","The Rolling Stones","Led Zeppelin","The Who"],c:1,f:""},
  {q:"Qui chante 'Thriller' ?",a:["Prince","Michael Jackson","Stevie Wonder","James Brown"],c:1,f:""},
  {q:"Quel groupe a chanté 'One' et 'With or Without You' ?",a:["Coldplay","U2","R.E.M.","Radiohead"],c:1,f:""},
  {q:"Quel chanteur français est connu pour 'La Vie en Rose' ?",a:["Charles Aznavour","Jacques Brel","Édith Piaf","Serge Gainsbourg"],c:2,f:""},
  {q:"Quel groupe a chanté 'Back in Black' ?",a:["Metallica","AC/DC","Iron Maiden","Judas Priest"],c:1,f:""},
  {q:"Qui chante 'Umbrella' ?",a:["Beyoncé","Rihanna","Nicki Minaj","Cardi B"],c:1,f:""},
  {q:"Quel chanteur est connu pour 'Space Oddity' ?",a:["Elton John","David Bowie","Freddie Mercury","Lou Reed"],c:1,f:""},
  {q:"Quel groupe a chanté 'Stairway to Heaven' ?",a:["Deep Purple","Black Sabbath","Led Zeppelin","The Who"],c:2,f:""},
  {q:"Qui chante 'Poker Face' ?",a:["Katy Perry","Lady Gaga","Britney Spears","Rihanna"],c:1,f:""},
  {q:"Quel chanteur est connu pour 'Superstition' ?",a:["Marvin Gaye","Stevie Wonder","Ray Charles","James Brown"],c:1,f:""},
  {q:"Quel groupe a chanté 'Losing My Religion' ?",a:["Radiohead","R.E.M.","Nirvana","Pearl Jam"],c:1,f:""},
  {q:"Qui chante 'Hello' (2015) ?",a:["Adele","Beyoncé","Sam Smith","Sia"],c:0,f:""},
  {q:"Quel groupe a chanté 'Mr. Brightside' ?",a:["The Killers","Interpol","Franz Ferdinand","Arctic Monkeys"],c:0,f:""},
  {q:"Quel chanteur est connu pour 'Heroes' ?",a:["Elton John","David Bowie","Lou Reed","Iggy Pop"],c:1,f:""},
  {q:"Qui chante 'Toxic' ?",a:["Britney Spears","Christina Aguilera","Kylie Minogue","Paris Hilton"],c:0,f:""},
  {q:"Quel groupe a chanté 'Don't Look Back in Anger' ?",a:["Blur","Oasis","Radiohead","Pulp"],c:1,f:""},
  {q:"Qui chante 'What's Going On' ?",a:["Stevie Wonder","Marvin Gaye","Al Green","Curtis Mayfield"],c:1,f:""},
  {q:"Quel groupe a chanté 'Creep' ?",a:["Radiohead","Muse","Portishead","Massive Attack"],c:0,f:""},
  {q:"Qui chante 'Halo' ?",a:["Adele","Rihanna","Beyoncé","Alicia Keys"],c:2,f:""},
  {q:"Quel groupe a chanté 'Hysteria' ?",a:["Def Leppard","Poison","Bon Jovi","Whitesnake"],c:0,f:""},
  {q:"Qui chante 'Thinking Out Loud' ?",a:["Sam Smith","James Bay","Ed Sheeran","Harry Styles"],c:2,f:""},
  {q:"Quel groupe a chanté 'Knockin' on Heaven's Door' (original) ?",a:["Bob Dylan","Neil Young","Bruce Springsteen","Tom Petty"],c:0,f:""},
  {q:"Qui chante 'No One' ?",a:["Mary J. Blige","Alicia Keys","Erykah Badu","Lauryn Hill"],c:1,f:""},
  {q:"Quel groupe a chanté 'Yellow' ?",a:["Coldplay","Muse","U2","Radiohead"],c:0,f:""},
  {q:"Qui chante 'Crazy in Love' ?",a:["Rihanna","Beyoncé","Mariah Carey","Whitney Houston"],c:1,f:""},
  {q:"Quel groupe a chanté 'Come As You Are' ?",a:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],c:2,f:""},
  {q:"Qui chante 'Chandelier' ?",a:["Lorde","Lana Del Rey","Sia","Halsey"],c:2,f:""},
  {q:"Quel groupe a chanté 'Paint It Black' ?",a:["The Beatles","The Rolling Stones","The Doors","The Kinks"],c:1,f:""},
  {q:"Qui chante 'Stay With Me' ?",a:["Sam Smith","James Arthur","Olly Murs","Shawn Mendes"],c:0,f:""},
  {q:"Quel groupe a chanté 'Nothing Else Matters' ?",a:["Metallica","Megadeth","Slayer","Pantera"],c:0,f:""},
  {q:"Qui chante 'Royals' ?",a:["Lorde","Halsey","Alessia Cara","Billie Eilish"],c:0,f:""},
  {q:"Quel groupe a chanté 'In the End' ?",a:["Linkin Park","System of a Down","Slipknot","Korn"],c:0,f:""},
  {q:"Qui chante 'Bad Guy' ?",a:["Lorde","Halsey","Billie Eilish","Olivia Rodrigo"],c:2,f:""},
  {q:"Quel groupe a chanté 'Seven Nation Army' ?",a:["The Black Keys","The White Stripes","The Strokes","Jack Johnson"],c:1,f:""},
  {q:"Qui chante 'Shallow' dans A Star Is Born ?",a:["Adele","Lady Gaga","Pink","Sia"],c:1,f:""},
  {q:"Quel groupe a chanté 'Supermassive Black Hole' ?",a:["Muse","Radiohead","Placebo","Interpol"],c:0,f:""},
  {q:"Qui chante 'Diamonds' ?",a:["Beyoncé","Rihanna","Katy Perry","Nicki Minaj"],c:1,f:""},
  {q:"Quel groupe a chanté 'Under the Bridge' ?",a:["Red Hot Chili Peppers","Foo Fighters","Rage Against the Machine","Green Day"],c:0,f:""},
  {q:"Qui chante 'Empire State of Mind' ?",a:["Kanye West","Jay-Z","Drake","Lil Wayne"],c:1,f:""},
  {q:"Quel groupe a chanté 'Every Breath You Take' ?",a:["The Police","Sting","Dire Straits","Genesis"],c:0,f:""},
  {q:"Qui chante 'Valerie' (version Amy Winehouse) ?",a:["Amy Winehouse","Duffy","Adele","Joss Stone"],c:0,f:""},
  {q:"Quel groupe a chanté 'Smack My Bitch Up' ?",a:["Chemical Brothers","Prodigy","Fatboy Slim","Daft Punk"],c:1,f:""},
  {q:"Qui chante 'Get Lucky' ?",a:["Justice","Daft Punk","Disclosure","Calvin Harris"],c:1,f:""},
  {q:"Quel groupe a chanté 'Blue (Da Ba Dee)' ?",a:["Aqua","Eiffel 65","Vengaboys","Technotronic"],c:1,f:""},
  {q:"Qui chante 'Despacito' ?",a:["Maluma","Ozuna","Luis Fonsi","J Balvin"],c:2,f:""},
  {q:"Quel groupe a chanté 'I Will Always Love You' (original) ?",a:["Dolly Parton","Whitney Houston","Celine Dion","Tina Turner"],c:0,f:""},
  {q:"Qui chante 'Blinding Lights' ?",a:["Drake","The Weeknd","Post Malone","Travis Scott"],c:1,f:""},
  {q:"Quel groupe a chanté 'Africa' ?",a:["Toto","Chicago","Journey","Boston"],c:0,f:""},
  {q:"Qui chante 'Levitating' ?",a:["Dua Lipa","Lizzo","Doja Cat","Ariana Grande"],c:0,f:""},
  {q:"Quel groupe a chanté 'Don't Stop Me Now' ?",a:["Queen","The Beatles","The Rolling Stones","David Bowie"],c:0,f:""},
  {q:"Qui chante 'Watermelon Sugar' ?",a:["Niall Horan","Liam Payne","Harry Styles","Zayn"],c:2,f:""},
  {q:"Quel groupe a chanté 'Eye of the Tiger' ?",a:["Foreigner","Journey","Survivor","REO Speedwagon"],c:2,f:""},
  {q:"Qui chante 'drivers license' ?",a:["Billie Eilish","Olivia Rodrigo","Sabrina Carpenter","Taylor Swift"],c:1,f:""},
  {q:"Quel groupe a chanté 'Take on Me' ?",a:["a-ha","Duran Duran","Erasure","Pet Shop Boys"],c:0,f:""},
  {q:"Qui chante 'Flowers' (2023) ?",a:["Dua Lipa","Lizzo","Miley Cyrus","Doja Cat"],c:2,f:""},
  {q:"Quel groupe a chanté 'Sweet Home Alabama' ?",a:["Lynyrd Skynyrd","The Allman Brothers","CCR","ZZ Top"],c:0,f:""},
  {q:"Qui chante 'As It Was' ?",a:["Lewis Capaldi","Harry Styles","Niall Horan","Sam Smith"],c:1,f:""},
  {q:"Quel groupe a chanté 'Livin' on a Prayer' ?",a:["Bon Jovi","Aerosmith","Def Leppard","Whitesnake"],c:0,f:""},
  {q:"Qui chante 'Anti-Hero' ?",a:["Adele","Billie Eilish","Taylor Swift","Olivia Rodrigo"],c:2,f:""},
  {q:"Quel groupe a chanté 'Mr. Jones' ?",a:["Counting Crows","Matchbox Twenty","Third Eye Blind","Semisonic"],c:0,f:""},
  {q:"Qui chante 'Stay' (2021) ?",a:["The Kid LAROI seul","Justin Bieber seul","The Kid LAROI ft. Justin Bieber","Juice WRLD"],c:2,f:""},
  {q:"Quel groupe a chanté 'Numb' ?",a:["Linkin Park","System of a Down","Korn","Limp Bizkit"],c:0,f:""},
  {q:"Qui chante 'Peaches' (2021) ?",a:["Drake","The Weeknd","Justin Bieber","Post Malone"],c:2,f:""},
  {q:"Quel chanteur français est connu pour 'Alexandrie Alexandra' ?",a:["Claude François","Michel Sardou","Joe Dassin","Daniel Guichard"],c:0,f:""},
  {q:"Qui chante 'As Long as You Love Me' ?",a:["*NSYNC","Backstreet Boys","New Kids on the Block","Boyz II Men"],c:1,f:""},
  {q:"Quel groupe a chanté 'Don't You (Forget About Me)' ?",a:["Simple Minds","New Order","The Cure","Depeche Mode"],c:0,f:""},
  {q:"Qui chante 'good 4 u' ?",a:["Billie Eilish","Olivia Rodrigo","Sabrina Carpenter","Gracie Abrams"],c:1,f:""},
  {q:"Quel groupe a chanté 'Walking on Sunshine' ?",a:["Katrina and the Waves","Bananarama","The Go-Go's","Cyndi Lauper"],c:0,f:""},
  {q:"Qui chante 'Lose Yourself' ?",a:["Jay-Z","Kanye West","Eminem","50 Cent"],c:2,f:""},
  {q:"Quel groupe a chanté 'Should I Stay or Should I Go' ?",a:["The Clash","Sex Pistols","The Jam","The Buzzcocks"],c:0,f:""},
  {q:"Qui chante 'Titanium' ?",a:["Sia ft. David Guetta","Adele","Beyoncé","Pink"],c:0,f:""},

  // ── 102 nouvelles questions ──

  // Rap / Hip-hop
  {q:"Quel rappeur américain a sorti l'album 'The Marshall Mathers LP' ?",a:["50 Cent","Dr. Dre","Eminem","Snoop Dogg"],c:2,f:""},
  {q:"Quel rappeur est connu pour le titre 'HUMBLE.' ?",a:["J. Cole","Kendrick Lamar","Drake","Travis Scott"],c:1,f:""},
  {q:"Quel groupe de hip-hop new-yorkais a sorti 'C.R.E.A.M.' ?",a:["Wu-Tang Clan","A Tribe Called Quest","Mobb Deep","Run-DMC"],c:0,f:""},
  {q:"Qui a rappé 'Juicy' en 1994 ?",a:["Tupac","Jay-Z","The Notorious B.I.G.","Nas"],c:2,f:""},
  {q:"Quel rappeur a popularisé le terme 'YOLO' ?",a:["Lil Wayne","Drake","Kanye West","Nicki Minaj"],c:1,f:""},
  {q:"Quel est le vrai prénom de Jay-Z ?",a:["Shawn","Calvin","Andre","Marshall"],c:0,f:""},
  {q:"Quel rappeur a sorti l'album 'Astroworld' ?",a:["Post Malone","Travis Scott","Lil Uzi Vert","21 Savage"],c:1,f:""},
  {q:"Quel duo de rap est composé d'André 3000 et Big Boi ?",a:["Mobb Deep","OutKast","Run the Jewels","Clipse"],c:1,f:""},

  // French rap
  {q:"Quel rappeur français a sorti l'album 'Civilisation' ?",a:["Booba","Orelsan","Nekfeu","Jul"],c:1,f:""},
  {q:"Quel groupe de rap marseillais est connu pour 'Badge' ?",a:["NTM","IAM","Fonky Family","113"],c:1,f:""},
  {q:"Quel rappeur français est surnommé 'le Duc de Boulogne' ?",a:["Orelsan","Nekfeu","Booba","Kaaris"],c:2,f:""},
  {q:"Qui a rappé 'Bande organisée' en 2020 ?",a:["PNL","Jul et d'autres rappeurs marseillais","Nekfeu","Soprano seul"],c:1,f:""},
  {q:"Quel duo de rap français est connu pour 'Le monde de demain' ?",a:["Bigflo et Oli","PNL","NTM","113"],c:2,f:""},
  {q:"Quel rappeur français a sorti l'album 'JVLIVS' ?",a:["Ninho","Damso","SCH","Booba"],c:2,f:""},
  {q:"Quel groupe de rap français a chanté 'Ma Benz' ?",a:["IAM","NTM","Assassin","Ministère A.M.E.R."],c:1,f:""},
  {q:"Quel rappeur belge francophone a sorti 'Batterie faible' ?",a:["Angèle","Stromae","Damso","Roméo Elvis"],c:2,f:""},

  // Electronic music
  {q:"Quel DJ français a produit 'One More Time' ?",a:["David Guetta","Daft Punk","Justice","Martin Solveig"],c:1,f:""},
  {q:"Quel DJ néerlandais était connu pour 'Levels' ?",a:["Tiësto","Armin van Buuren","Avicii","Martin Garrix"],c:2,f:""},
  {q:"Quel genre de musique électronique est originaire de Detroit ?",a:["House","Trance","Techno","Drum and Bass"],c:2,f:""},
  {q:"Quel duo électronique français a composé la B.O. de Tron: Legacy ?",a:["Justice","Air","Daft Punk","M83"],c:2,f:""},
  {q:"Quel DJ a produit 'Scary Monsters and Nice Sprites' ?",a:["Deadmau5","Skrillex","Diplo","Marshmello"],c:1,f:""},
  {q:"Dans quelle ville est née la musique house ?",a:["New York","Detroit","Chicago","Los Angeles"],c:2,f:""},
  {q:"Quel artiste électronique a sorti l'album 'Play' en 1999 ?",a:["Fatboy Slim","Moby","The Chemical Brothers","Aphex Twin"],c:1,f:""},
  {q:"Quel groupe électronique allemand est pionnier de la musique électronique avec 'Autobahn' ?",a:["Tangerine Dream","Can","Kraftwerk","Neu!"],c:2,f:""},

  // K-pop
  {q:"Quel groupe de K-pop est composé de 7 membres dont RM et Jungkook ?",a:["EXO","BTS","BLACKPINK","SEVENTEEN"],c:1,f:""},
  {q:"Quel groupe féminin de K-pop a chanté 'DDU-DU DDU-DU' ?",a:["TWICE","Red Velvet","BLACKPINK","ITZY"],c:2,f:""},
  {q:"De quel pays vient la K-pop ?",a:["Japon","Chine","Corée du Sud","Thaïlande"],c:2,f:""},
  {q:"Quel artiste solo de K-pop a chanté 'Gangnam Style' ?",a:["PSY","G-Dragon","Rain","Jay Park"],c:0,f:""},
  {q:"Quel groupe de K-pop féminin est connu pour 'TT' et 'Cheer Up' ?",a:["BLACKPINK","Red Velvet","TWICE","aespa"],c:2,f:""},
  {q:"Comment appelle-t-on les fans de BTS ?",a:["Blinks","Once","ARMY","Exo-L"],c:2,f:""},

  // Latin music
  {q:"Quel chanteur portoricain a popularisé le reggaeton mondial ?",a:["J Balvin","Bad Bunny","Daddy Yankee","Ozuna"],c:2,f:""},
  {q:"Quel chanteur colombien est connu pour 'Hips Don't Lie' ?",a:["Juanes","Maluma","J Balvin","Shakira"],c:3,f:""},
  {q:"Quel genre musical latino combine reggae et hip-hop ?",a:["Salsa","Bachata","Reggaeton","Cumbia"],c:2,f:""},
  {q:"Quel artiste portoricain a dominé les charts avec 'Un Verano Sin Ti' ?",a:["Daddy Yankee","J Balvin","Bad Bunny","Ozuna"],c:2,f:""},
  {q:"De quel pays est originaire la cumbia ?",a:["Mexique","Argentine","Colombie","Cuba"],c:2,f:""},
  {q:"Quel chanteur dominicain est associé à la bachata moderne ?",a:["Daddy Yankee","Romeo Santos","Marc Anthony","Enrique Iglesias"],c:1,f:""},

  // Jazz legends
  {q:"Quel trompettiste de jazz est surnommé 'Satchmo' ?",a:["Miles Davis","Dizzy Gillespie","Louis Armstrong","Chet Baker"],c:2,f:""},
  {q:"Quel saxophoniste a enregistré l'album 'A Love Supreme' ?",a:["Charlie Parker","Sonny Rollins","John Coltrane","Ornette Coleman"],c:2,f:""},
  {q:"Quelle chanteuse de jazz est connue pour 'Strange Fruit' ?",a:["Ella Fitzgerald","Billie Holiday","Sarah Vaughan","Nina Simone"],c:1,f:""},
  {q:"Quel trompettiste a révolutionné le jazz avec 'Kind of Blue' ?",a:["Louis Armstrong","Chet Baker","Miles Davis","Wynton Marsalis"],c:2,f:""},
  {q:"Quel pianiste de jazz est connu pour 'Take the A Train' ?",a:["Thelonious Monk","Count Basie","Duke Ellington","Oscar Peterson"],c:2,f:""},
  {q:"Dans quelle ville américaine le jazz est-il né ?",a:["Chicago","New York","La Nouvelle-Orléans","Memphis"],c:2,f:""},

  // Classical composers
  {q:"Qui a composé 'Les Quatre Saisons' ?",a:["Bach","Handel","Vivaldi","Telemann"],c:2,f:""},
  {q:"Quel compositeur autrichien est mort à 35 ans en 1791 ?",a:["Haydn","Schubert","Mozart","Beethoven"],c:2,f:""},
  {q:"Qui a composé 'Le Lac des cygnes' ?",a:["Stravinsky","Rachmaninov","Tchaïkovski","Prokofiev"],c:2,f:""},
  {q:"Quel compositeur allemand a écrit 'La Chevauchée des Walkyries' ?",a:["Brahms","Wagner","Strauss","Mahler"],c:1,f:""},
  {q:"Qui a composé 'Clair de lune' pour piano ?",a:["Ravel","Debussy","Satie","Fauré"],c:1,f:""},
  {q:"Quel compositeur polonais est célèbre pour ses nocturnes et polonaises ?",a:["Liszt","Chopin","Schumann","Mendelssohn"],c:1,f:""},
  {q:"Qui a composé 'Le Sacre du printemps' ?",a:["Prokofiev","Stravinsky","Bartók","Ravel"],c:1,f:""},
  {q:"Quel compositeur a écrit 'Le Boléro' ?",a:["Debussy","Satie","Ravel","Fauré"],c:2,f:""},

  // Music theory
  {q:"Comment appelle-t-on un groupe de 4 musiciens ?",a:["Trio","Quatuor","Quintette","Sextuor"],c:1,f:""},
  {q:"Combien de demi-tons contient une octave ?",a:["7","10","12","14"],c:2,f:""},
  {q:"Quel terme italien indique de jouer doucement ?",a:["Forte","Allegro","Piano","Adagio"],c:2,f:""},
  {q:"Quel signe musical augmente la durée d'une note de moitié ?",a:["Le bémol","Le dièse","Le point","La liaison"],c:2,f:""},
  {q:"Comment appelle-t-on la vitesse d'un morceau de musique ?",a:["La nuance","Le tempo","Le timbre","L'harmonie"],c:1,f:""},
  {q:"Combien de lignes possède une portée musicale ?",a:["4","5","6","7"],c:1,f:""},
  {q:"Quel terme désigne deux notes jouées simultanément ?",a:["Mélodie","Accord","Intervalle","Arpège"],c:2,f:""},
  {q:"Quelle clé est la plus utilisée pour les instruments aigus ?",a:["Clé de fa","Clé d'ut","Clé de sol","Clé d'ut 4"],c:2,f:""},

  // Eurovision
  {q:"Quel pays a remporté l'Eurovision le plus de fois ?",a:["Suède","France","Irlande","Royaume-Uni"],c:2,f:""},
  {q:"Quel groupe suédois a gagné l'Eurovision 1974 avec 'Waterloo' ?",a:["Roxette","ABBA","Ace of Base","Europe"],c:1,f:""},
  {q:"Quel pays a accueilli l'Eurovision 2023 au nom de l'Ukraine ?",a:["Pologne","Allemagne","Royaume-Uni","Suède"],c:2,f:""},
  {q:"Quelle chanteuse a représenté la France en 2024 avec 'Mon amour' ?",a:["Aya Nakamura","Slimane","Amir","Angèle"],c:1,f:""},
  {q:"Quel chanteur canadien a gagné l'Eurovision 1988 pour la Suisse ?",a:["Garou","Céline Dion","Roch Voisine","Lara Fabian"],c:1,f:""},
  {q:"Dans quelle ville se déroule traditionnellement la finale de l'Eurovision ?",a:["Toujours à Genève","Dans le pays vainqueur de l'année précédente","Toujours à Paris","Toujours à Stockholm"],c:1,f:""},

  // Grammy Awards
  {q:"Quel artiste a remporté le plus de Grammy Awards de tous les temps ?",a:["Quincy Jones","Georg Solti","Beyoncé","Stevie Wonder"],c:2,f:""},
  {q:"Quel album de Michael Jackson a remporté 8 Grammy en 1984 ?",a:["Bad","Off the Wall","Thriller","Dangerous"],c:2,f:""},
  {q:"Quel rappeur a remporté le Pulitzer de la musique en 2018 ?",a:["Jay-Z","Kanye West","Kendrick Lamar","J. Cole"],c:2,f:""},
  {q:"Dans quelle ville se tient habituellement la cérémonie des Grammy Awards ?",a:["New York","Nashville","Los Angeles","Las Vegas"],c:2,f:""},

  // Music festivals
  {q:"Dans quel pays se déroule le festival de Glastonbury ?",a:["États-Unis","Australie","Angleterre","Irlande"],c:2,f:""},
  {q:"Quel célèbre festival de musique se tient dans le désert californien chaque avril ?",a:["Burning Man","Lollapalooza","Coachella","Bonnaroo"],c:2,f:""},
  {q:"Dans quelle ville française se déroulent les Francofolies ?",a:["Lyon","Bordeaux","La Rochelle","Nantes"],c:2,f:""},
  {q:"Quel festival de musique électronique belge rassemble des centaines de milliers de personnes ?",a:["Pukkelpop","Rock Werchter","Tomorrowland","Dour Festival"],c:2,f:""},
  {q:"Quel festival français de rock se tient près de Clisson ?",a:["Les Vieilles Charrues","Hellfest","Garorock","Solidays"],c:1,f:""},
  {q:"Dans quel pays a lieu le festival de Roskilde ?",a:["Suède","Norvège","Danemark","Finlande"],c:2,f:""},

  // Musical instruments
  {q:"Combien de touches possède un piano standard ?",a:["76","82","88","92"],c:2,f:""},
  {q:"Quel instrument à vent est en forme de J ?",a:["Hautbois","Clarinette","Saxophone","Basson"],c:2,f:""},
  {q:"Quel instrument indien à cordes est associé à Ravi Shankar ?",a:["Tabla","Sitar","Sarangi","Veena"],c:1,f:""},
  {q:"Quel instrument à percussion est typique de la samba brésilienne ?",a:["Djembé","Surdo","Cajón","Bodhrán"],c:1,f:""},
  {q:"Quel instrument à anche double fait partie de la famille des bois ?",a:["Clarinette","Flûte traversière","Hautbois","Saxophone"],c:2,f:""},
  {q:"Combien de cordes possède un violon ?",a:["3","4","5","6"],c:1,f:""},

  // Opera
  {q:"Qui a composé l'opéra 'Carmen' ?",a:["Verdi","Puccini","Bizet","Rossini"],c:2,f:""},
  {q:"Quel compositeur italien a écrit 'La Traviata' ?",a:["Puccini","Rossini","Verdi","Donizetti"],c:2,f:""},
  {q:"Dans quel opéra de Mozart retrouve-t-on l'air 'La Reine de la nuit' ?",a:["Don Giovanni","Les Noces de Figaro","La Flûte enchantée","Così fan tutte"],c:2,f:""},
  {q:"Quel ténor italien surnommé 'Big Luciano' a popularisé l'opéra ?",a:["Andrea Bocelli","Plácido Domingo","Luciano Pavarotti","José Carreras"],c:2,f:""},
  {q:"Qui a composé l'opéra 'La Bohème' ?",a:["Verdi","Puccini","Rossini","Bellini"],c:1,f:""},
  {q:"Quel terme désigne la voix féminine la plus grave à l'opéra ?",a:["Soprano","Mezzo-soprano","Contralto","Baryton"],c:2,f:""},

  // Film soundtracks
  {q:"Qui a composé la musique de 'Star Wars' ?",a:["Hans Zimmer","Howard Shore","John Williams","Danny Elfman"],c:2,f:""},
  {q:"Quel compositeur a écrit la bande originale de 'The Dark Knight' ?",a:["John Williams","Howard Shore","Hans Zimmer","James Horner"],c:2,f:""},
  {q:"Qui a composé la célèbre musique du film 'Psychose' ?",a:["John Williams","Bernard Herrmann","Jerry Goldsmith","Ennio Morricone"],c:1,f:""},
  {q:"Quel compositeur italien est célèbre pour les musiques de westerns spaghetti ?",a:["Nino Rota","Ennio Morricone","Nicola Piovani","Ludovico Einaudi"],c:1,f:""},
  {q:"Qui a composé la musique du film 'Le Seigneur des anneaux' ?",a:["Hans Zimmer","John Williams","Howard Shore","James Horner"],c:2,f:""},
  {q:"Quel compositeur français a écrit la B.O. du film 'Amélie Poulain' ?",a:["Alexandre Desplat","Jean-Michel Jarre","Yann Tiersen","Ludovico Einaudi"],c:2,f:""},

  // More variety topics
  {q:"Quel rappeur a fondé le label 'Beats Electronics' ?",a:["Jay-Z","Eminem","Dr. Dre","Kanye West"],c:2,f:""},
  {q:"Quel chanteur reggaeton est surnommé 'El Conejo Malo' ?",a:["J Balvin","Daddy Yankee","Bad Bunny","Ozuna"],c:2,f:""},
  {q:"Quel groupe de K-pop masculin est surnommé 'les rois du K-pop' et compte EXO parmi eux ?",a:["BTS","BIGBANG","EXO","Super Junior"],c:2,f:""},
  {q:"Quel style de jazz rapide est apparu dans les années 1940 ?",a:["Cool jazz","Swing","Bebop","Free jazz"],c:2,f:""},
  {q:"Quel compositeur a écrit la 'Symphonie du Nouveau Monde' ?",a:["Smetana","Janáček","Dvořák","Brahms"],c:2,f:""},
  {q:"Quel terme musical signifie jouer en reprenant progressivement du volume ?",a:["Diminuendo","Sforzando","Crescendo","Staccato"],c:2,f:""},
  {q:"Quel pays a accueilli le tout premier concours Eurovision en 1956 ?",a:["France","Italie","Suisse","Pays-Bas"],c:2,f:""},
  {q:"Quel album de Beyoncé sorti en 2016 aborde des thèmes sociaux et personnels ?",a:["4","Beyoncé","Lemonade","Renaissance"],c:2,f:""},
  {q:"Quel festival français se déroule chaque été à Carhaix en Bretagne ?",a:["Hellfest","Solidays","Les Vieilles Charrues","Rock en Seine"],c:2,f:""},
  {q:"Quel instrument de musique japonais ressemble à une cithare à 13 cordes ?",a:["Shamisen","Koto","Biwa","Shakuhachi"],c:1,f:""},
  {q:"Qui a composé l'opéra 'Le Barbier de Séville' ?",a:["Verdi","Mozart","Rossini","Puccini"],c:2,f:""},
];
