/* ════════════════════════════════════════
   questions/nba.js — NBA — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.nba = [
  {q:"Quel joueur est surnommé 'The King' ?",a:["Kobe Bryant","LeBron James","Kevin Durant","Tim Duncan"],c:1,f:""},
  {q:"Combien de championnats NBA Michael Jordan a-t-il remportés ?",a:["4","5","6","7"],c:2,f:""},
  {q:"Quelle équipe a remporté le plus de titres NBA dans l'histoire ?",a:["Los Angeles Lakers","Chicago Bulls","Boston Celtics","Golden State Warriors"],c:2,f:""},
  {q:"En quelle année la NBA a-t-elle été fondée ?",a:["1936","1946","1956","1966"],c:1,f:""},
  {q:"Quel joueur détient le record du plus grand nombre de points marqués en un seul match NBA ?",a:["Michael Jordan","Kobe Bryant","Wilt Chamberlain","Kareem Abdul-Jabbar"],c:2,f:""},
  {q:"Combien de points Wilt Chamberlain a-t-il marqués lors de son match record ?",a:["81","90","100","110"],c:2,f:""},
  {q:"Quel joueur a remporté le plus de titres de MVP de la saison régulière ?",a:["Michael Jordan","LeBron James","Kareem Abdul-Jabbar","Bill Russell"],c:2,f:""},
  {q:"Dans quelle ville se trouvent les Knicks ?",a:["Los Angeles","Chicago","New York","Boston"],c:2,f:""},
  {q:"Quel joueur est connu pour son 'Sky Hook' ?",a:["Hakeem Olajuwon","Kareem Abdul-Jabbar","Shaquille O'Neal","Patrick Ewing"],c:1,f:""},
  {q:"Combien de joueurs sont sur le terrain par équipe en NBA ?",a:["4","5","6","7"],c:1,f:""},
  {q:"Quelle équipe a réalisé un bilan de 73 victoires et 9 défaites en saison régulière 2015-2016 ?",a:["Chicago Bulls","San Antonio Spurs","Golden State Warriors","Miami Heat"],c:2,f:""},
  {q:"Quel joueur a été choisi en premier lors de la Draft NBA 2003 ?",a:["Carmelo Anthony","Dwyane Wade","Chris Bosh","LeBron James"],c:3,f:""},
  {q:"Combien de quart-temps comporte un match NBA ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quelle est la durée d'un quart-temps en NBA ?",a:["10 minutes","12 minutes","15 minutes","20 minutes"],c:1,f:""},
  {q:"Quel joueur a le surnom 'Black Mamba' ?",a:["LeBron James","Kobe Bryant","Allen Iverson","Tracy McGrady"],c:1,f:""},
  {q:"Combien de points Kobe Bryant a-t-il marqués lors de son match record contre Toronto en 2006 ?",a:["71","76","81","86"],c:2,f:""},
  {q:"Quelle équipe a drafté Kobe Bryant en 1996 ?",a:["Los Angeles Lakers","Charlotte Hornets","Philadelphia 76ers","Boston Celtics"],c:1,f:""},
  {q:"Quel joueur détient le record de passes décisives en carrière NBA ?",a:["Magic Johnson","Steve Nash","John Stockton","Jason Kidd"],c:2,f:""},
  {q:"Quel trophée est remis au MVP des Finales NBA ?",a:["Trophée Larry O'Brien","Trophée Bill Russell","Trophée Maurice Podoloff","Trophée Red Auerbach"],c:1,f:""},
  {q:"En quelle année les Chicago Bulls ont-ils remporté leur premier titre NBA ?",a:["1989","1991","1993","1995"],c:1,f:""},
  {q:"Quel joueur français a remporté le titre NBA avec les San Antonio Spurs en 2003 ?",a:["Nicolas Batum","Boris Diaw","Tony Parker","Rudy Gobert"],c:2,f:""},
  {q:"Combien de titres NBA Tony Parker a-t-il remportés ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quel est le nom du trophée remis au champion NBA ?",a:["Trophée Bill Russell","Trophée Larry O'Brien","Trophée James Naismith","Trophée Wilt Chamberlain"],c:1,f:""},
  {q:"Quelle est la hauteur réglementaire du panier en NBA ?",a:["2,75 mètres","3,05 mètres","3,25 mètres","3,50 mètres"],c:1,f:""},
  {q:"Combien de points vaut un tir derrière la ligne à trois points ?",a:["1","2","3","4"],c:2,f:""},
  {q:"Quel joueur est surnommé 'The Answer' ?",a:["Steve Nash","Allen Iverson","Dwyane Wade","Ray Allen"],c:1,f:""},
  {q:"Quelle équipe Magic Johnson a-t-il représentée durant toute sa carrière ?",a:["Boston Celtics","Chicago Bulls","Los Angeles Lakers","New York Knicks"],c:2,f:""},
  {q:"Quel joueur a remporté le concours de dunks le plus de fois ?",a:["Michael Jordan","Vince Carter","Nate Robinson","Dominique Wilkins"],c:2,f:""},
  {q:"En quelle année le match All-Star NBA a-t-il été créé ?",a:["1941","1951","1961","1971"],c:1,f:""},
  {q:"Quel joueur détient le record du plus grand nombre de rebonds en carrière NBA ?",a:["Kareem Abdul-Jabbar","Bill Russell","Wilt Chamberlain","Moses Malone"],c:2,f:""},
  {q:"Dans quelle ville se trouvent les Spurs ?",a:["Houston","Dallas","San Antonio","Austin"],c:2,f:""},
  {q:"Quel entraîneur a remporté le plus de titres NBA ?",a:["Pat Riley","Gregg Popovich","Phil Jackson","Red Auerbach"],c:2,f:""},
  {q:"Combien de titres NBA Phil Jackson a-t-il remportés en tant qu'entraîneur ?",a:["9","10","11","13"],c:2,f:""},
  {q:"Quel joueur est connu pour avoir changé son nom en 'World Peace' ?",a:["Dennis Rodman","Ron Artest","Lamar Odom","Stephen Jackson"],c:1,f:""},
  {q:"Quelle équipe a remporté les Finales NBA en 2016 après avoir été menée 3-1 ?",a:["Golden State Warriors","Cleveland Cavaliers","San Antonio Spurs","Oklahoma City Thunder"],c:1,f:""},
  {q:"Quel joueur a été élu MVP des Finales NBA 2016 ?",a:["Kyrie Irving","Kevin Love","LeBron James","Stephen Curry"],c:2,f:""},
  {q:"Quel joueur détient le record du plus grand nombre de contres en carrière ?",a:["Dikembe Mutombo","Hakeem Olajuwon","Kareem Abdul-Jabbar","Tim Duncan"],c:1,f:""},
  {q:"En combien de matchs les Golden State Warriors ont-ils terminé la saison régulière 2015-2016 ?",a:["80","82","84","86"],c:1,f:""},
  {q:"Quel joueur a inscrit le tir 'The Shot' contre Cleveland en 1989 ?",a:["Scottie Pippen","Michael Jordan","John Paxson","Dennis Rodman"],c:1,f:""},
  {q:"Quelle est la distance de la ligne à trois points dans les coins en NBA ?",a:["6,32 m","6,71 m","7,24 m","7,50 m"],c:2,f:""},
  {q:"Quel joueur nigérian a été deux fois champion NBA avec Houston ?",a:["Dikembe Mutombo","Hakeem Olajuwon","Bismack Biyombo","Serge Ibaka"],c:1,f:""},
  {q:"Combien de fautes personnelles entraînent l'exclusion d'un joueur en NBA ?",a:["4","5","6","7"],c:2,f:""},
  {q:"Quel joueur est surnommé 'The Big Fundamental' ?",a:["Shaquille O'Neal","Tim Duncan","Kevin Garnett","Dirk Nowitzki"],c:1,f:""},
  {q:"Quelle équipe Dirk Nowitzki a-t-il représentée durant toute sa carrière NBA ?",a:["San Antonio Spurs","Houston Rockets","Dallas Mavericks","Phoenix Suns"],c:2,f:""},
  {q:"En quelle année Dirk Nowitzki a-t-il remporté le titre NBA ?",a:["2007","2009","2011","2013"],c:2,f:""},
  {q:"Quel joueur détient le record du plus grand nombre de points en carrière NBA ?",a:["Karl Malone","Kareem Abdul-Jabbar","Michael Jordan","LeBron James"],c:3,f:""},
  {q:"Quel joueur a été le premier choix de la Draft NBA 2019 ?",a:["Ja Morant","RJ Barrett","Zion Williamson","De'Andre Hunter"],c:2,f:""},
  {q:"Combien de secondes une équipe a-t-elle pour tirer en NBA ?",a:["20","24","30","35"],c:1,f:""},
  {q:"Quel joueur est surnommé 'Chef Curry' ?",a:["Seth Curry","Dell Curry","Stephen Curry","Eddy Curry"],c:2,f:""},
  {q:"Combien de titres NBA Stephen Curry a-t-il remportés ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quel joueur serbe a été élu MVP de la saison régulière 2021 ?",a:["Bogdan Bogdanovic","Nikola Jokic","Luka Doncic","Boban Marjanovic"],c:1,f:""},
  {q:"Quelle équipe joue au Madison Square Garden ?",a:["Brooklyn Nets","New York Knicks","Boston Celtics","Philadelphia 76ers"],c:1,f:""},
  {q:"Quel joueur est surnommé 'The Greek Freak' ?",a:["Luka Doncic","Nikola Jokic","Giannis Antetokounmpo","Kristaps Porzingis"],c:2,f:""},
  {q:"Dans quel pays Giannis Antetokounmpo est-il né ?",a:["Nigeria","Cameroun","Grèce","Allemagne"],c:2,f:""},
  {q:"Quelle équipe a remporté le titre NBA en 2021 ?",a:["Phoenix Suns","Milwaukee Bucks","Atlanta Hawks","Brooklyn Nets"],c:1,f:""},
  {q:"Quel joueur a été sélectionné en premier lors de la Draft 2020 ?",a:["James Wiseman","Anthony Edwards","LaMelo Ball","Tyrese Haliburton"],c:1,f:""},
  {q:"Quel joueur français a été élu trois fois Défenseur de l'année en NBA ?",a:["Nicolas Batum","Tony Parker","Rudy Gobert","Evan Fournier"],c:2,f:""},
  {q:"Combien d'équipes composent la NBA actuellement ?",a:["28","29","30","32"],c:2,f:""},
  {q:"Quelle conférence regroupe les Lakers et les Warriors ?",a:["Conférence Est","Conférence Ouest","Conférence Centrale","Conférence Sud"],c:1,f:""},
  {q:"Quel duo légendaire formaient Magic Johnson et Larry Bird ?",a:["Même équipe","Rivaux Celtics-Lakers","Coéquipiers All-Star uniquement","Ils ne se sont jamais affrontés"],c:1,f:""},
  {q:"Quel joueur a porté le numéro 23 aux Chicago Bulls ?",a:["Scottie Pippen","Dennis Rodman","Michael Jordan","Derrick Rose"],c:2,f:""},
  {q:"Quelle équipe Dennis Rodman a-t-il rejoint en 1995 ?",a:["San Antonio Spurs","Los Angeles Lakers","Chicago Bulls","Detroit Pistons"],c:2,f:""},
  {q:"Comment s'appelle la formation des Detroit Pistons de la fin des années 1980 ?",a:["Showtime","Bad Boys","Big Three","Fab Five"],c:1,f:""},
  {q:"Quel joueur a été le premier européen élu MVP de la saison régulière ?",a:["Pau Gasol","Tony Parker","Dirk Nowitzki","Giannis Antetokounmpo"],c:2,f:""},
  {q:"En quelle année Shaquille O'Neal a-t-il rejoint les Los Angeles Lakers ?",a:["1994","1996","1998","2000"],c:1,f:""},
  {q:"Combien de titres NBA Shaquille O'Neal a-t-il remportés ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quel joueur est surnommé 'The Mailman' ?",a:["Charles Barkley","Karl Malone","John Stockton","Patrick Ewing"],c:1,f:""},
  {q:"Quelle équipe a remporté huit titres NBA consécutifs de 1959 à 1966 ?",a:["Los Angeles Lakers","New York Knicks","Boston Celtics","Philadelphia 76ers"],c:2,f:""},
  {q:"Quel joueur a le record du plus grand nombre de triple-doubles en carrière ?",a:["Magic Johnson","LeBron James","Russell Westbrook","Oscar Robertson"],c:2,f:""},
  {q:"En quelle année Russell Westbrook a-t-il réalisé la moyenne d'un triple-double sur une saison entière pour la première fois ?",a:["2015","2016","2017","2018"],c:2,f:""},
  {q:"Quel joueur canadien est surnommé 'Vinsanity' ?",a:["Steve Nash","Vince Carter","Andrew Wiggins","Jamal Murray"],c:1,f:""},
  {q:"Quel est le nom de la salle des Los Angeles Lakers ?",a:["Staples Center","Crypto.com Arena","The Forum","Chase Center"],c:1,f:""},
  {q:"Quel joueur a remporté le titre de meilleur marqueur 10 fois consécutives ?",a:["Kobe Bryant","Wilt Chamberlain","Michael Jordan","Kevin Durant"],c:2,f:""},
  {q:"Quelle équipe a sélectionné Tim Duncan en premier choix de la Draft 1997 ?",a:["Chicago Bulls","Los Angeles Lakers","San Antonio Spurs","Utah Jazz"],c:2,f:""},
  {q:"Combien de titres NBA Tim Duncan a-t-il remportés ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Quel joueur chinois a joué pour les Houston Rockets de 2002 à 2011 ?",a:["Yi Jianlian","Jeremy Lin","Yao Ming","Wang Zhizhi"],c:2,f:""},
  {q:"Comment appelle-t-on un tir marqué à la dernière seconde pour gagner le match ?",a:["Buzzer beater","Alley-oop","Fadeaway","Crossover"],c:0,f:""},
  {q:"Quel joueur a réalisé un célèbre 'buzzer beater' contre Toronto en 2019 avec quatre rebonds sur le cercle ?",a:["LeBron James","Damian Lillard","Kawhi Leonard","Jimmy Butler"],c:2,f:""},
  {q:"Pour quelle équipe Kawhi Leonard jouait-il lors de ce tir historique en 2019 ?",a:["San Antonio Spurs","Los Angeles Clippers","Toronto Raptors","Los Angeles Lakers"],c:2,f:""},
  {q:"Quel joueur allemand est le meilleur marqueur européen de l'histoire de la NBA ?",a:["Luka Doncic","Tony Parker","Pau Gasol","Dirk Nowitzki"],c:3,f:""},
  {q:"Quel surnom donne-t-on au duo Shaquille O'Neal et Kobe Bryant aux Lakers ?",a:["Twin Towers","Showtime","Shaq & Kobe","The Dynamic Duo"],c:2,f:""},
  {q:"Quel joueur a mené les Toronto Raptors à leur premier titre NBA en 2019 ?",a:["Kyle Lowry","Pascal Siakam","Kawhi Leonard","Marc Gasol"],c:2,f:""},
  {q:"Combien de points le record NBA en un match de Stephen Curry en saison régulière atteint-il ?",a:["54","57","62","66"],c:2,f:""},
  {q:"Quel joueur a été élu Rookie de l'année en 2019 ?",a:["Trae Young","Deandre Ayton","Luka Doncic","Shai Gilgeous-Alexander"],c:2,f:""},
  {q:"Quel est le surnom de l'équipe de Miami construite autour de LeBron, Wade et Bosh ?",a:["Big Two","Big Three","Super Team","Dream Team"],c:1,f:""},
  {q:"Combien de titres NBA LeBron James a-t-il remportés avec Miami ?",a:["1","2","3","4"],c:1,f:""},
  {q:"Quel joueur détient le record du plus grand nombre de interceptions en carrière NBA ?",a:["Michael Jordan","Gary Payton","John Stockton","Scottie Pippen"],c:2,f:""},
  {q:"Quel est le nombre maximum de joueurs dans un effectif NBA en saison régulière ?",a:["12","13","15","17"],c:2,f:""},
  {q:"Quelle équipe NBA est basée à Toronto ?",a:["Nets","Celtics","Raptors","76ers"],c:2,f:""},
  {q:"Quel joueur est surnommé 'King James' ?",a:["James Harden","LeBron James","James Worthy","Chris Paul"],c:1,f:""},
  {q:"Quel était le surnom du style de jeu des Lakers de Magic Johnson dans les années 1980 ?",a:["Bad Boys","Showtime","Lob City","Splash Brothers"],c:1,f:""},
  {q:"Quel duo des Golden State Warriors est surnommé les 'Splash Brothers' ?",a:["Curry et Green","Curry et Thompson","Thompson et Green","Curry et Durant"],c:1,f:""},
  {q:"Quelle équipe Kevin Durant a-t-il rejoint en 2016 ?",a:["Brooklyn Nets","Oklahoma City Thunder","Golden State Warriors","Phoenix Suns"],c:2,f:""},
  {q:"En quelle année la Dream Team américaine a-t-elle participé aux Jeux Olympiques ?",a:["1988","1992","1996","2000"],c:1,f:""},
  {q:"Quel joueur a marqué le plus de points lors d'un match des Finales NBA ?",a:["Michael Jordan","LeBron James","Elgin Baylor","Rick Barry"],c:2,f:""},
  {q:"Quel est le record de victoires consécutives en NBA réalisé par les Lakers en 1971-1972 ?",a:["27","33","38","41"],c:1,f:""},
  {q:"Quel joueur a été le premier choix de la Draft NBA 2018 ?",a:["Marvin Bagley III","Luka Doncic","Trae Young","Deandre Ayton"],c:3,f:""},
  {q:"Combien de sélections All-Star LeBron James a-t-il obtenues dans sa carrière ?",a:["15","17","19","20"],c:3,f:""},
  {q:"Quel entraîneur a dirigé les San Antonio Spurs pendant plus de 25 ans ?",a:["Pat Riley","Phil Jackson","Gregg Popovich","Larry Brown"],c:2,f:""},
  {q:"Quel joueur a été élu MVP des Finales en 2014 avec les Spurs ?",a:["Tim Duncan","Tony Parker","Manu Ginobili","Kawhi Leonard"],c:3,f:""},
  {q:"Quelle est la plus longue série de titres NBA consécutifs dans l'histoire ?",a:["6","7","8","9"],c:2,f:""},
  {q:"Quel joueur des Celtics a remporté 11 titres NBA en 13 saisons ?",a:["Larry Bird","Bob Cousy","Bill Russell","John Havlicek"],c:2,f:""},
];
