/* ════════════════════════════════════════
   questions/science.js — Sciences — 200 questions
   ════════════════════════════════════════ */
QUESTIONS.science = [
  // ── Sciences générales (1-50) ──
  {q:"Quelle est la formule chimique de l'eau ?",a:["HO","H2O","H3O","OH"],c:1,f:""},
  {q:"Combien de chromosomes possède un être humain ?",a:["23","46","48","44"],c:1,f:""},
  {q:"Quelle planète est la plus proche du Soleil ?",a:["Vénus","Mars","Mercure","Terre"],c:2,f:""},
  {q:"Quel est le symbole chimique de l'oxygène ?",a:["Ox","O2","O","Oy"],c:2,f:""},
  {q:"Quelle est la vitesse de la lumière ?",a:["200 000 km/s","300 000 km/s","400 000 km/s","500 000 km/s"],c:1,f:""},
  {q:"Qui a découvert la pénicilline ?",a:["Louis Pasteur","Alexander Fleming","Marie Curie","Charles Darwin"],c:1,f:""},
  {q:"Quel est l'élément le plus abondant dans l'Univers ?",a:["Oxygène","Hélium","Hydrogène","Carbone"],c:2,f:""},
  {q:"Quelle est la température d'ébullition de l'eau à pression normale ?",a:["90°C","95°C","100°C","105°C"],c:2,f:""},
  {q:"Quel organe produit l'insuline ?",a:["Foie","Rein","Pancréas","Rate"],c:2,f:""},
  {q:"Quelle est la formule chimique du sel de table ?",a:["NaOH","KCl","NaCl","CaCl2"],c:2,f:""},
  {q:"Combien de planètes y a-t-il dans notre système solaire ?",a:["7","8","9","10"],c:1,f:""},
  {q:"Quel scientifique a formulé la théorie de l'évolution ?",a:["Gregor Mendel","Louis Pasteur","Charles Darwin","Alfred Wallace"],c:2,f:""},
  {q:"Quel est le plus petit os du corps humain ?",a:["Péroné","Étrier (oreille)","Sésamoïde","Phalange"],c:1,f:""},
  {q:"Quel gaz est principalement responsable de l'effet de serre ?",a:["Oxygène","Azote","CO2","Méthane"],c:2,f:""},
  {q:"Quelle est la distance moyenne entre la Terre et le Soleil ?",a:["100 millions km","150 millions km","200 millions km","250 millions km"],c:1,f:""},
  {q:"Quel est le symbole chimique du sodium ?",a:["So","Sd","Na","No"],c:2,f:""},
  {q:"Combien de vertèbres a la colonne vertébrale humaine ?",a:["24","30","33","36"],c:2,f:""},
  {q:"Quel est le noyau de l'atome composé de ?",a:["Électrons et protons","Protons et neutrons","Neutrons et électrons","Quarks et leptons"],c:1,f:""},
  {q:"Quelle planète est surnommée la 'géante gazeuse' bleue ?",a:["Saturne","Jupiter","Uranus","Neptune"],c:3,f:""},
  {q:"Quelle est la formule chimique du dioxyde de carbone ?",a:["CO","CO2","C2O","CO3"],c:1,f:""},
  {q:"Quel est le métal liquide à température ambiante ?",a:["Plomb","Étain","Mercure","Gallium"],c:2,f:""},
  {q:"Quelle est la loi de Newton sur la gravitation universelle ?",a:["F=ma","E=mc²","F=Gm1m2/r²","PV=nRT"],c:2,f:""},
  {q:"Combien de chambres possède le cœur humain ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quel est le groupe sanguin universel donneur ?",a:["A","B","AB","O"],c:3,f:""},
  {q:"Quelle est la particule négative de l'atome ?",a:["Proton","Neutron","Électron","Positron"],c:2,f:""},
  {q:"Quelle est la formule de la force selon Newton ?",a:["F=mv","F=ma","F=mgh","F=mv²"],c:1,f:""},
  {q:"Combien d'os a le corps humain adulte ?",a:["196","206","216","226"],c:1,f:""},
  {q:"Quel est le processus par lequel les plantes fabriquent leur nourriture ?",a:["Respiration","Fermentation","Photosynthèse","Digestion"],c:2,f:""},
  {q:"Quel est le symbole chimique du potassium ?",a:["Po","Pt","K","Ka"],c:2,f:""},
  {q:"Quel est le gaz le plus abondant dans l'atmosphère terrestre ?",a:["Oxygène","CO2","Azote","Argon"],c:2,f:""},
  {q:"Quelle est la célèbre équation d'Einstein ?",a:["F=ma","E=mc²","PV=nRT","a²+b²=c²"],c:1,f:""},
  {q:"Quel est le pH d'une solution neutre ?",a:["0","5","7","14"],c:2,f:""},
  {q:"Quelle est la durée d'une révolution de la Terre autour du Soleil ?",a:["364 jours","365 jours","365,25 jours","366 jours"],c:2,f:""},
  {q:"Quel est le symbole chimique du calcium ?",a:["Ca","Cl","Co","Cu"],c:0,f:""},
  {q:"Quel est le point de congélation de l'eau en degrés Celsius ?",a:["-5°C","0°C","5°C","-10°C"],c:1,f:""},
  {q:"Quelle est la particule portant une charge positive ?",a:["Électron","Neutron","Proton","Positron"],c:2,f:""},
  {q:"Quel est le plus grand organe interne du corps humain ?",a:["Cœur","Rein","Foie","Poumon"],c:2,f:""},
  {q:"Quelle force maintient les planètes en orbite autour du Soleil ?",a:["Force magnétique","Force nucléaire","Gravitation","Force électrique"],c:2,f:""},
  {q:"Quel est le symbole chimique du cuivre ?",a:["Co","Cu","Cp","Cr"],c:1,f:""},
  {q:"Quelle est la durée d'une rotation de la Terre sur elle-même ?",a:["12h","18h","24h","48h"],c:2,f:""},
  {q:"Quel est le nom du processus de division cellulaire ?",a:["Méiose","Mitose","Cytokinèse","Anaphase"],c:1,f:""},
  {q:"Quelle est la formule chimique du méthane ?",a:["CH2","CH3","CH4","C2H4"],c:2,f:""},
  {q:"Quel est le symbole chimique du plomb ?",a:["Pb","Pl","Pd","Po"],c:0,f:""},
  {q:"Quelle est la théorie qui explique l'origine de l'Univers ?",a:["Théorie des cordes","Big Bang","Théorie de la relativité","Mécanique quantique"],c:1,f:""},
  {q:"Quelle est la particule sans charge électrique ?",a:["Proton","Électron","Neutron","Photon"],c:2,f:""},
  {q:"Quel est le symbole chimique du zinc ?",a:["Zi","Zn","Zc","Ze"],c:1,f:""},
  {q:"Quel est le plus rapide : son ou lumière ?",a:["Son","Lumière","Égaux","Dépend du milieu"],c:1,f:""},
  {q:"Quelle est la formule du théorème de Pythagore ?",a:["a+b=c","a²+b²=c","a²+b²=c²","a×b=c²"],c:2,f:""},
  {q:"Quel est le symbole chimique du fer ?",a:["Fe","Fr","Fi","Fo"],c:0,f:""},
  {q:"Quelle est la vitesse du son dans l'air ?",a:["340 m/s","540 m/s","740 m/s","940 m/s"],c:0,f:""},
  // ── Génétique / ADN (51-60) ──
  {q:"Quelle molécule porte l'information génétique ?",a:["ARN","Protéine","ADN","Lipide"],c:2,f:""},
  {q:"Combien de paires de bases l'ADN humain contient-il environ ?",a:["300 millions","3 milliards","30 milliards","300 milliards"],c:1,f:""},
  {q:"Quel scientifique a découvert la structure en double hélice de l'ADN ?",a:["Mendel","Watson et Crick","Darwin","Pasteur"],c:1,f:""},
  {q:"Que signifie le sigle ADN ?",a:["Acide DésoxyriboNucléique","Acide DiNitrique","Adénosine DiNucléotide","Aucune de ces réponses"],c:0,f:""},
  {q:"Quel est le rôle de l'ARN messager ?",a:["Stocker l'énergie","Transporter l'information génétique vers les ribosomes","Répliquer l'ADN","Détruire les virus"],c:1,f:""},
  {q:"Combien de bases azotées composent l'ADN ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quel outil permet de couper l'ADN à des endroits précis ?",a:["Microscope","CRISPR-Cas9","Centrifugeuse","Spectromètre"],c:1,f:""},
  {q:"Comment appelle-t-on un organisme dont le génome a été modifié ?",a:["OGM","Clone","Hybride","Mutant naturel"],c:0,f:""},
  {q:"Quelle base azotée remplace la thymine dans l'ARN ?",a:["Adénine","Guanine","Cytosine","Uracile"],c:3,f:""},
  {q:"Quel projet international a cartographié le génome humain ?",a:["Projet Manhattan","Projet Génome Humain","Projet Apollo","Projet ENCODE"],c:1,f:""},
  // ── Physique quantique (61-70) ──
  {q:"Quel physicien est considéré comme le père de la mécanique quantique ?",a:["Einstein","Bohr","Max Planck","Heisenberg"],c:2,f:""},
  {q:"Comment s'appelle le principe d'incertitude en physique quantique ?",a:["Principe de Pauli","Principe de Heisenberg","Principe de Fermat","Principe de Boltzmann"],c:1,f:""},
  {q:"Qu'est-ce qu'un photon ?",a:["Un atome d'hydrogène","Une particule de lumière","Un électron libre","Un noyau atomique"],c:1,f:""},
  {q:"Quel phénomène quantique lie deux particules à distance ?",a:["La diffraction","L'intrication quantique","La fission","La fusion froide"],c:1,f:""},
  {q:"Quelle expérience de pensée met en scène un chat à la fois vivant et mort ?",a:["Expérience de Young","Chat de Schrödinger","Démon de Maxwell","Paradoxe EPR"],c:1,f:""},
  {q:"Quel est le nom du boson découvert au CERN en 2012 ?",a:["Boson W","Boson Z","Boson de Higgs","Gluon"],c:2,f:""},
  {q:"Quelle propriété quantique interdit à deux fermions d'occuper le même état ?",a:["Principe de Heisenberg","Principe d'exclusion de Pauli","Loi de Planck","Effet tunnel"],c:1,f:""},
  {q:"Qu'est-ce que l'effet tunnel en physique quantique ?",a:["Un trou noir miniature","Une particule traversant une barrière d'énergie","Un laser ultra-puissant","La création de matière"],c:1,f:""},
  {q:"Quelle expérience démontre la dualité onde-particule de la lumière ?",a:["Expérience de Michelson-Morley","Expérience des fentes de Young","Expérience de Stern-Gerlach","Expérience de Rutherford"],c:1,f:""},
  {q:"Comment appelle-t-on l'état où une particule existe dans plusieurs états simultanément ?",a:["Dualité","Superposition quantique","Décohérence","Intrication"],c:1,f:""},
  // ── Astronomie : exoplanètes et trous noirs (71-82) ──
  {q:"Comment appelle-t-on une planète en orbite autour d'une étoile autre que le Soleil ?",a:["Astéroïde","Comète","Exoplanète","Naine brune"],c:2,f:""},
  {q:"Quel télescope spatial a découvert des milliers d'exoplanètes ?",a:["Hubble","Kepler","Spitzer","Chandra"],c:1,f:""},
  {q:"Qu'est-ce qu'un trou noir ?",a:["Une étoile très brillante","Une région où la gravité empêche la lumière de s'échapper","Un nuage de gaz","Une planète sombre"],c:1,f:""},
  {q:"Comment s'appelle la frontière d'un trou noir au-delà de laquelle rien ne s'échappe ?",a:["Couronne solaire","Horizon des événements","Ceinture de Kuiper","Héliosphère"],c:1,f:""},
  {q:"Quelle est la première image d'un trou noir, prise en 2019 ?",a:["Sagittarius A*","M87*","Cygnus X-1","Andromède"],c:1,f:""},
  {q:"Combien d'exoplanètes confirmées a-t-on découvertes à ce jour (ordre de grandeur) ?",a:["Environ 500","Environ 5 000","Environ 50 000","Environ 500 000"],c:1,f:""},
  {q:"Quel type d'exoplanète est surnommé 'Jupiter chaud' ?",a:["Planète rocheuse proche de son étoile","Géante gazeuse très proche de son étoile","Planète glacée géante","Planète naine lointaine"],c:1,f:""},
  {q:"Quelle est la zone habitable autour d'une étoile ?",a:["Zone où il fait toujours nuit","Zone où l'eau liquide peut exister","Zone sans gravité","Zone de radiation maximale"],c:1,f:""},
  {q:"Quel est le nom de la galaxie la plus proche de la Voie lactée ?",a:["Galaxie du Triangle","Galaxie d'Andromède","Grand Nuage de Magellan","Galaxie du Sombrero"],c:1,f:""},
  {q:"Quel télescope spatial lancé en 2021 observe l'univers en infrarouge ?",a:["Hubble","Spitzer","James Webb","Chandra"],c:2,f:""},
  {q:"Comment appelle-t-on l'explosion d'une étoile massive en fin de vie ?",a:["Nova","Supernova","Pulsar","Quasar"],c:1,f:""},
  {q:"Quelle est la planète la plus grande du système solaire ?",a:["Saturne","Neptune","Uranus","Jupiter"],c:3,f:""},
  // ── Biologie marine (83-92) ──
  {q:"Quel est le plus grand animal vivant sur Terre ?",a:["Éléphant d'Afrique","Requin baleine","Baleine bleue","Calmar géant"],c:2,f:""},
  {q:"Comment s'appelle le phénomène de blanchissement des coraux ?",a:["Érosion marine","Blanchissement corallien","Marée noire","Eutrophisation"],c:1,f:""},
  {q:"Quel pourcentage de la surface terrestre est recouvert par les océans ?",a:["50%","61%","71%","81%"],c:2,f:""},
  {q:"Quelle est la fosse océanique la plus profonde ?",a:["Fosse des Tonga","Fosse des Mariannes","Fosse de Porto Rico","Fosse du Japon"],c:1,f:""},
  {q:"Quel organisme marin produit la majorité de l'oxygène sur Terre ?",a:["Les algues brunes","Le phytoplancton","Les coraux","Les mangroves"],c:1,f:""},
  {q:"Quel est le nom du courant océanique chaud dans le Pacifique associé à des perturbations climatiques ?",a:["Gulf Stream","El Niño","Kuroshio","Courant de Humboldt"],c:1,f:""},
  {q:"Quelle créature marine possède trois cœurs ?",a:["Méduse","Étoile de mer","Pieuvre","Hippocampe"],c:2,f:""},
  {q:"Quelle est la profondeur approximative de la fosse des Mariannes ?",a:["5 000 m","8 000 m","11 000 m","15 000 m"],c:2,f:""},
  {q:"Quel mammifère marin utilise l'écholocation pour se repérer ?",a:["Phoque","Dauphin","Loutre de mer","Lamantin"],c:1,f:""},
  {q:"Comment appelle-t-on les organismes vivant dans les grandes profondeurs océaniques ?",a:["Planctoniques","Pélagiques","Abyssaux","Benthiques"],c:2,f:""},
  // ── Géologie (93-102) ──
  {q:"Combien de plaques tectoniques majeures la Terre possède-t-elle ?",a:["5","7","12","15"],c:3,f:""},
  {q:"Comment appelle-t-on la couche externe solide de la Terre ?",a:["Manteau","Lithosphère","Asthénosphère","Noyau"],c:1,f:""},
  {q:"Quel type de roche est formé par le refroidissement du magma ?",a:["Sédimentaire","Métamorphique","Magmatique","Calcaire"],c:2,f:""},
  {q:"Comment mesure-t-on la magnitude d'un séisme ?",a:["Échelle de Beaufort","Échelle de Richter","Échelle de Mohs","Échelle de Mercalli"],c:1,f:""},
  {q:"Quel est l'âge approximatif de la Terre ?",a:["1,5 milliard d'années","3 milliards d'années","4,5 milliards d'années","6 milliards d'années"],c:2,f:""},
  {q:"Comment s'appelle la roche en fusion sous la surface terrestre ?",a:["Lave","Magma","Basalte","Granite"],c:1,f:""},
  {q:"Quel supercontinent existait il y a environ 250 millions d'années ?",a:["Gondwana","Laurasia","Pangée","Rodinia"],c:2,f:""},
  {q:"Quelle échelle mesure la dureté des minéraux ?",a:["Échelle de Richter","Échelle de Beaufort","Échelle de Mohs","Échelle de Kelvin"],c:2,f:""},
  {q:"Quel est le minéral le plus dur sur l'échelle de Mohs ?",a:["Quartz","Topaze","Corindon","Diamant"],c:3,f:""},
  {q:"Comment appelle-t-on une ouverture dans la croûte terrestre par laquelle s'écoule du magma ?",a:["Geyser","Volcan","Faille","Grotte"],c:1,f:""},
  // ── Écologie / Changement climatique (103-114) ──
  {q:"Quel accord international de 2015 vise à limiter le réchauffement climatique ?",a:["Protocole de Kyoto","Accord de Paris","Sommet de Rio","Accord de Montréal"],c:1,f:""},
  {q:"Quelle couche de l'atmosphère nous protège des rayons UV ?",a:["Troposphère","Stratosphère (couche d'ozone)","Mésosphère","Thermosphère"],c:1,f:""},
  {q:"Quel gaz détruit la couche d'ozone ?",a:["CO2","Méthane","CFC (chlorofluorocarbures)","Vapeur d'eau"],c:2,f:""},
  {q:"Quel est le principal puits de carbone naturel sur Terre ?",a:["Les déserts","Les forêts tropicales","Les océans","Les glaciers"],c:2,f:""},
  {q:"De combien de degrés la température moyenne a-t-elle augmenté depuis l'ère préindustrielle ?",a:["0,3°C","0,7°C","1,1°C","2,0°C"],c:2,f:""},
  {q:"Quel phénomène désigne la perte de biodiversité massive actuelle ?",a:["Ère glaciaire","Sixième extinction de masse","Désertification","Effet de serre"],c:1,f:""},
  {q:"Quel protocole de 1987 a interdit les CFC pour protéger la couche d'ozone ?",a:["Protocole de Kyoto","Accord de Paris","Protocole de Montréal","Convention de Bâle"],c:2,f:""},
  {q:"Quel est le plus grand biome terrestre ?",a:["Forêt tropicale","Désert","Taïga","Savane"],c:2,f:""},
  {q:"Quel gaz à effet de serre est produit par l'élevage bovin ?",a:["CO2","Ozone","Méthane","Protoxyde d'azote"],c:2,f:""},
  {q:"Comment appelle-t-on la montée du niveau des océans due au réchauffement ?",a:["Tsunami","Transgression marine","Marée haute","Submersion côtière"],c:1,f:""},
  {q:"Quel phénomène amplifie le réchauffement quand la glace fond et réduit l'albédo ?",a:["Effet de serre","Rétroaction positive glace-albédo","Courant thermohalin","Inversion thermique"],c:1,f:""},
  {q:"Quel est le pourcentage approximatif de CO2 dans l'atmosphère actuelle ?",a:["0,004%","0,04%","0,4%","4%"],c:1,f:""},
  // ── Intelligence artificielle / Informatique (115-126) ──
  {q:"Qui est considéré comme le père de l'informatique théorique ?",a:["Bill Gates","Steve Jobs","Alan Turing","John von Neumann"],c:2,f:""},
  {q:"Quel test évalue si une machine peut imiter l'intelligence humaine ?",a:["Test de Rorschach","Test de Turing","Test de Voight-Kampff","Test de Babbage"],c:1,f:""},
  {q:"Que signifie le sigle IA ?",a:["Information Automatique","Intelligence Artificielle","Interface Avancée","Ingénierie Appliquée"],c:1,f:""},
  {q:"Quel langage de programmation est le plus utilisé en intelligence artificielle ?",a:["Java","C++","Python","Ruby"],c:2,f:""},
  {q:"Comment appelle-t-on un réseau de neurones à plusieurs couches cachées ?",a:["Réseau simple","Réseau profond (deep learning)","Réseau linéaire","Réseau analogique"],c:1,f:""},
  {q:"En quelle année l'ordinateur Deep Blue a-t-il battu Kasparov aux échecs ?",a:["1995","1997","2000","2003"],c:1,f:""},
  {q:"Quel composant électronique a remplacé les tubes à vide dans les ordinateurs ?",a:["Résistance","Condensateur","Transistor","Diode"],c:2,f:""},
  {q:"Combien de bits y a-t-il dans un octet ?",a:["4","6","8","16"],c:2,f:""},
  {q:"Quel programme d'IA de Google a battu le champion du monde de Go en 2016 ?",a:["Watson","AlphaGo","GPT","Siri"],c:1,f:""},
  {q:"Comment appelle-t-on un algorithme qui apprend à partir de données étiquetées ?",a:["Apprentissage non supervisé","Apprentissage supervisé","Apprentissage par renforcement","Apprentissage automatique"],c:1,f:""},
  {q:"Quel est le système de numération utilisé par les ordinateurs ?",a:["Décimal","Octal","Binaire","Hexadécimal"],c:2,f:""},
  {q:"Qui a conçu la première machine programmable mécanique au XIXe siècle ?",a:["Ada Lovelace","Charles Babbage","Blaise Pascal","Gottfried Leibniz"],c:1,f:""},
  // ── Découvertes médicales (127-138) ──
  {q:"Qui a réalisé la première transplantation cardiaque en 1967 ?",a:["Michael DeBakey","Christiaan Barnard","René Leriche","Alain Carpentier"],c:1,f:""},
  {q:"Quel médecin anglais a inventé la vaccination contre la variole ?",a:["Pasteur","Jenner","Koch","Fleming"],c:1,f:""},
  {q:"Quelle technologie d'imagerie médicale utilise des champs magnétiques ?",a:["Radiographie","Scanner","IRM","Échographie"],c:2,f:""},
  {q:"Quel type de vaccin utilise de l'ARN messager ?",a:["Vaccin vivant atténué","Vaccin inactivé","Vaccin à ARNm","Vaccin à sous-unité"],c:2,f:""},
  {q:"Qui a découvert les rayons X en 1895 ?",a:["Marie Curie","Wilhelm Röntgen","Henri Becquerel","Max Planck"],c:1,f:""},
  {q:"Quel anticoagulant naturel est produit par les sangsues ?",a:["Héparine","Hirudine","Aspirine","Warfarine"],c:1,f:""},
  {q:"Comment appelle-t-on la thérapie qui utilise le système immunitaire pour combattre le cancer ?",a:["Chimiothérapie","Radiothérapie","Immunothérapie","Hormonothérapie"],c:2,f:""},
  {q:"Quel virus est responsable du SIDA ?",a:["VHC","VIH","VPH","VHB"],c:1,f:""},
  {q:"Quelle découverte a valu à Alexander Fleming le prix Nobel de médecine ?",a:["L'aspirine","La pénicilline","L'insuline","La morphine"],c:1,f:""},
  {q:"Quel médecin hongrois a promu le lavage des mains pour prévenir les infections ?",a:["Pasteur","Semmelweis","Lister","Koch"],c:1,f:""},
  {q:"Quelle technique permet de visualiser l'activité cérébrale en temps réel ?",a:["Radiographie","IRMf (IRM fonctionnelle)","Échographie","Scanner"],c:1,f:""},
  {q:"Quel est le nom de la première brebis clonée en 1996 ?",a:["Polly","Molly","Dolly","Holly"],c:2,f:""},
  // ── Prix Nobel de sciences (139-148) ──
  {q:"Qui a reçu deux prix Nobel dans deux disciplines scientifiques différentes ?",a:["Albert Einstein","Linus Pauling","Marie Curie","Niels Bohr"],c:2,f:""},
  {q:"Dans quel domaine Albert Einstein a-t-il reçu son prix Nobel ?",a:["Relativité générale","Effet photoélectrique","Mécanique quantique","Physique nucléaire"],c:1,f:""},
  {q:"Quel scientifique a reçu le prix Nobel pour la découverte de la radioactivité ?",a:["Rutherford","Marie Curie","Fermi","Planck"],c:1,f:""},
  {q:"En quelle année le prix Nobel de physique a-t-il été décerné pour la première fois ?",a:["1895","1901","1905","1910"],c:1,f:""},
  {q:"Quel duo a reçu le prix Nobel 2020 de chimie pour CRISPR-Cas9 ?",a:["Watson et Crick","Charpentier et Doudna","Curie et Joliot","Pauling et Sanger"],c:1,f:""},
  {q:"Quel physicien a reçu le Nobel en 1921 pour l'effet photoélectrique ?",a:["Bohr","Planck","Einstein","Heisenberg"],c:2,f:""},
  {q:"Quel scientifique a reçu le Nobel de physique 2022 pour ses travaux sur l'intrication quantique ?",a:["Roger Penrose","Alain Aspect","Peter Higgs","Stephen Hawking"],c:1,f:""},
  {q:"Qui a reçu le prix Nobel de médecine pour la découverte du groupe sanguin ?",a:["Karl Landsteiner","Louis Pasteur","Robert Koch","Alexander Fleming"],c:0,f:""},
  {q:"Quel chimiste a reçu le prix Nobel pour l'invention de la dynamite ?",a:["Linus Pauling","Alfred Nobel","Fritz Haber","Marie Curie"],c:1,f:""},
  {q:"Quelle femme a reçu le prix Nobel de physique en 1903 ?",a:["Irène Joliot-Curie","Marie Curie","Dorothy Hodgkin","Lise Meitner"],c:1,f:""},
  // ── Mathématiques (149-160) ──
  {q:"Quelle est la valeur approchée du nombre pi ?",a:["2,14","3,14","4,14","5,14"],c:1,f:""},
  {q:"Quel mathématicien grec est célèbre pour ses travaux en géométrie ?",a:["Archimède","Euclide","Pythagore","Thalès"],c:1,f:""},
  {q:"Qu'est-ce qu'un nombre premier ?",a:["Divisible par 1 et lui-même uniquement","Un nombre pair","Un nombre négatif","Un nombre décimal"],c:0,f:""},
  {q:"Quelle est la racine carrée de 144 ?",a:["10","11","12","14"],c:2,f:""},
  {q:"Comment appelle-t-on la suite 0, 1, 1, 2, 3, 5, 8, 13... ?",a:["Suite arithmétique","Suite géométrique","Suite de Fibonacci","Suite de Cauchy"],c:2,f:""},
  {q:"Quel symbole représente l'infini en mathématiques ?",a:["Ω","∞","π","Σ"],c:1,f:""},
  {q:"Combien de faces a un dodécaèdre ?",a:["8","10","12","20"],c:2,f:""},
  {q:"Quel est le résultat de la factorielle de 5 (5!) ?",a:["25","60","120","720"],c:2,f:""},
  {q:"Quel nombre est considéré comme le nombre d'or ?",a:["1,414","1,618","2,718","3,141"],c:1,f:""},
  {q:"Comment appelle-t-on un polygone à huit côtés ?",a:["Hexagone","Heptagone","Octogone","Décagone"],c:2,f:""},
  {q:"Quel mathématicien a démontré le dernier théorème de Fermat en 1995 ?",a:["Euler","Gauss","Andrew Wiles","Riemann"],c:2,f:""},
  {q:"Quelle constante mathématique vaut environ 2,718 ?",a:["Pi","Phi","e (nombre d'Euler)","Racine de 2"],c:2,f:""},
  // ── Paléontologie (161-170) ──
  {q:"Il y a combien d'années les dinosaures ont-ils disparu ?",a:["25 millions","45 millions","66 millions","100 millions"],c:2,f:""},
  {q:"Quel événement a causé l'extinction des dinosaures ?",a:["Éruption volcanique seule","Impact d'un astéroïde","Glaciation","Épidémie"],c:1,f:""},
  {q:"Comment s'appelle le plus grand dinosaure carnivore connu ?",a:["Vélociraptor","Tyrannosaure rex","Spinosaurus","Allosaure"],c:2,f:""},
  {q:"Quel est le nom du premier fossile d'oiseau découvert ?",a:["Ptérodactyle","Archaeopteryx","Dodo","Ichthyornis"],c:1,f:""},
  {q:"Durant quelle ère géologique les dinosaures ont-ils vécu ?",a:["Paléozoïque","Mésozoïque","Cénozoïque","Précambrien"],c:1,f:""},
  {q:"Quel paléontologue a nommé le mot 'dinosaure' en 1842 ?",a:["Charles Darwin","Richard Owen","Mary Anning","Georges Cuvier"],c:1,f:""},
  {q:"Quel dinosaure herbivore est connu pour ses trois cornes ?",a:["Stégosaure","Ankylosaure","Tricératops","Brachiosaure"],c:2,f:""},
  {q:"Où a été découvert le cratère de Chicxulub lié à l'extinction des dinosaures ?",a:["Sibérie","Australie","Mexique","Antarctique"],c:2,f:""},
  {q:"Comment appelle-t-on l'étude des fossiles ?",a:["Archéologie","Géologie","Paléontologie","Minéralogie"],c:2,f:""},
  {q:"Quel dinosaure possédait des plaques osseuses le long de son dos ?",a:["Ankylosaure","Stégosaure","Parasaurolophus","Diplodocus"],c:1,f:""},
  // ── Neurosciences (171-182) ──
  {q:"Comment s'appelle la cellule de base du système nerveux ?",a:["Globule rouge","Plaquette","Neurone","Lymphocyte"],c:2,f:""},
  {q:"Quel neurotransmetteur est associé au plaisir et à la récompense ?",a:["Sérotonine","Dopamine","Adrénaline","GABA"],c:1,f:""},
  {q:"Quelle partie du cerveau contrôle l'équilibre et la coordination ?",a:["Cortex frontal","Hippocampe","Cervelet","Thalamus"],c:2,f:""},
  {q:"Comment s'appelle la gaine isolante qui entoure les axones ?",a:["Dendrite","Gaine de myéline","Synapse","Membrane plasmique"],c:1,f:""},
  {q:"Quelle structure cérébrale joue un rôle clé dans la mémoire ?",a:["Amygdale","Hippocampe","Hypothalamus","Cervelet"],c:1,f:""},
  {q:"Quel phénomène désigne la capacité du cerveau à se réorganiser ?",a:["Homéostasie","Neuroplasticité","Apoptose","Mitose"],c:1,f:""},
  {q:"Combien de nerfs spinaux possède le corps humain ?",a:["12 paires","21 paires","31 paires","42 paires"],c:2,f:""},
  {q:"Quel lobe du cerveau est principalement responsable de la vision ?",a:["Lobe frontal","Lobe pariétal","Lobe temporal","Lobe occipital"],c:3,f:""},
  {q:"Quel neurotransmetteur est principalement impliqué dans la régulation de l'humeur ?",a:["Dopamine","Acétylcholine","Sérotonine","Glutamate"],c:2,f:""},
  {q:"Comment appelle-t-on la jonction entre deux neurones ?",a:["Axone","Dendrite","Synapse","Nœud de Ranvier"],c:2,f:""},
  {q:"Quelle partie du cerveau régule la faim, la soif et la température corporelle ?",a:["Hippocampe","Hypothalamus","Thalamus","Amygdale"],c:1,f:""},
  {q:"Combien de neurones possède le cerveau humain environ ?",a:["1 milliard","86 milliards","500 milliards","1000 milliards"],c:1,f:""},
  // ── Énergies renouvelables (183-192) ──
  {q:"Quelle énergie renouvelable utilise la lumière du soleil pour produire de l'électricité ?",a:["Éolienne","Géothermique","Solaire photovoltaïque","Hydraulique"],c:2,f:""},
  {q:"Comment appelle-t-on l'énergie produite par le vent ?",a:["Énergie solaire","Énergie éolienne","Énergie marémotrice","Énergie biomasse"],c:1,f:""},
  {q:"Quel pays est le plus grand producteur d'énergie éolienne au monde ?",a:["États-Unis","Allemagne","Chine","Inde"],c:2,f:""},
  {q:"Qu'est-ce que la géothermie ?",a:["Énergie des vagues","Énergie de la chaleur terrestre","Énergie des marées","Énergie du vent"],c:1,f:""},
  {q:"Quel est le principal avantage des énergies renouvelables ?",a:["Coût nul","Faibles émissions de CO2","Production constante","Facilité de stockage"],c:1,f:""},
  {q:"Quelle énergie utilise la force de l'eau pour produire de l'électricité ?",a:["Solaire","Éolienne","Hydraulique","Nucléaire"],c:2,f:""},
  {q:"Quel est le combustible utilisé dans une pile à hydrogène ?",a:["Méthane","Hydrogène","Hélium","Oxygène"],c:1,f:""},
  {q:"Quel type de panneau solaire convertit directement la lumière en électricité ?",a:["Panneau thermique","Panneau photovoltaïque","Panneau hybride","Panneau aérothermique"],c:1,f:""},
  {q:"Quelle source d'énergie renouvelable exploite les mouvements des marées ?",a:["Éolienne","Géothermique","Marémotrice","Biomasse"],c:2,f:""},
  {q:"Quel matériau semi-conducteur est principalement utilisé dans les panneaux solaires ?",a:["Cuivre","Aluminium","Silicium","Germanium"],c:2,f:""},
  // ── Sujets variés supplémentaires (193-200) ──
  {q:"Quel élément chimique a le numéro atomique 79 (métal précieux jaune) ?",a:["Argent","Platine","Or","Cuivre"],c:2,f:""},
  {q:"Quel scientifique a formulé les lois de l'hérédité ?",a:["Darwin","Mendel","Lamarck","Wallace"],c:1,f:""},
  {q:"Quelle particule subatomique a été théorisée par Peter Higgs ?",a:["Quark top","Neutrino","Boson de Higgs","Graviton"],c:2,f:""},
  {q:"Quel est le nom de la sonde qui a atterri sur Mars en 2021 ?",a:["Curiosity","Opportunity","Perseverance","Spirit"],c:2,f:""},
  {q:"Quelle vitamine est synthétisée par la peau grâce au soleil ?",a:["Vitamine A","Vitamine B12","Vitamine C","Vitamine D"],c:3,f:""},
  {q:"Quel phénomène optique décompose la lumière blanche en un spectre de couleurs ?",a:["Réflexion","Réfraction","Diffraction","Dispersion"],c:3,f:""},
  {q:"Quel type de liaison chimique implique le partage d'électrons ?",a:["Liaison ionique","Liaison covalente","Liaison métallique","Liaison hydrogène"],c:1,f:""},
  {q:"Quelle planète possède un système d'anneaux spectaculaire ?",a:["Jupiter","Uranus","Neptune","Saturne"],c:3,f:""},
];
