/* ════════════════════════════════════════
   questions/science.js — Sciences — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.science = [
  {q:"Quelle est la formule chimique de l'eau ?",a:["HO","H2O","H3O","OH"],c:1,f:""},
  {q:"Combien de chromosomes possède un être humain ?",a:["23","46","48","44"],c:1,f:""},
  {q:"Quelle planète est la plus proche du Soleil ?",a:["Vénus","Mars","Mercure","Terre"],c:2,f:""},
  {q:"Quel est le symbole chimique de l'oxygène ?",a:["Ox","O2","O","Oy"],c:2,f:""},
  {q:"Quelle est la vitesse de la lumière ?",a:["200 000 km/s","300 000 km/s","400 000 km/s","500 000 km/s"],c:1,f:""},
  {q:"Qui a découvert la pénicilline ?",a:["Louis Pasteur","Alexander Fleming","Marie Curie","Charles Darwin"],c:1,f:""},
  {q:"Quel est l'élément le plus abondant dans l'Univers ?",a:["Oxygène","Hélium","Hydrogène","Carbone"],c:2,f:""},
  {q:"Quelle est la température d'ébullition de l'eau à pression normale ?",a:["90°C","95°C","100°C","105°C"],c:2,f:""},
  {q:"Combien de dents de lait a un enfant ?",a:["18","20","22","24"],c:1,f:""},
  {q:"Quel organe produit l'insuline ?",a:["Foie","Rein","Pancréas","Rate"],c:2,f:""},
  {q:"Quelle est la formule chimique du sel de table ?",a:["NaOH","KCl","NaCl","CaCl2"],c:2,f:""},
  {q:"Combien de planètes y a-t-il dans notre système solaire ?",a:["7","8","9","10"],c:1,f:""},
  {q:"Quel scientifique a formulé la théorie de l'évolution ?",a:["Gregor Mendel","Louis Pasteur","Charles Darwin","Alfred Wallace"],c:2,f:""},
  {q:"Quel est le plus petit os du corps humain ?",a:["Péroné","Étrier (oreille)","Sésamoïde","Phalange"],c:1,f:""},
  {q:"Quelle est la température de fusion du fer (environ) ?",a:["1000°C","1300°C","1538°C","1800°C"],c:2,f:""},
  {q:"Quel gaz est principalement responsable de l'effet de serre ?",a:["Oxygène","Azote","CO2","Méthane"],c:2,f:""},
  {q:"Combien de lobes a le cerveau humain ?",a:["2","3","4","5"],c:0,f:""},
  {q:"Quelle est la distance moyenne entre la Terre et le Soleil ?",a:["100 millions km","150 millions km","200 millions km","250 millions km"],c:1,f:""},
  {q:"Quel est le symbole chimique du sodium ?",a:["So","Sd","Na","No"],c:2,f:""},
  {q:"Combien de vertèbres a la colonne vertébrale humaine ?",a:["24","30","33","36"],c:2,f:""},
  {q:"Quel est le noyau de l'atome composé de ?",a:["Électrons et protons","Protons et neutrons","Neutrons et électrons","Quarks et leptons"],c:1,f:""},
  {q:"Quelle planète est surnommée la 'géante gazeuse' bleue ?",a:["Saturne","Jupiter","Uranus","Neptune"],c:3,f:""},
  {q:"Quel est l'organe qui filtre le sang dans le corps humain ?",a:["Foie","Rein","Poumon","Rate"],c:1,f:""},
  {q:"Quelle est la formule chimique du dioxyde de carbone ?",a:["CO","CO2","C2O","CO3"],c:1,f:""},
  {q:"Combien de grammes y a-t-il dans une mole d'eau ?",a:["16g","18g","20g","22g"],c:1,f:""},
  {q:"Quel est le métal liquide à température ambiante ?",a:["Plomb","Étain","Mercure","Gallium"],c:2,f:""},
  {q:"Quelle est la loi de Newton sur la gravitation universelle ?",a:["F=ma","E=mc²","F=Gm1m2/r²","PV=nRT"],c:2,f:""},
  {q:"Combien de chambres possède le cœur humain ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Quel est le groupe sanguin universel donneur ?",a:["A","B","AB","O"],c:3,f:""},
  {q:"Quelle est la particule négative de l'atome ?",a:["Proton","Neutron","Électron","Positron"],c:2,f:""},
  {q:"Quel est le satellite naturel de la Terre ?",a:["Phobos","Titan","La Lune","Ganymède"],c:2,f:""},
  {q:"Quelle est la formule de la force selon Newton ?",a:["F=mv","F=ma","F=mgh","F=mv²"],c:1,f:""},
  {q:"Combien d'os a le corps humain adulte ?",a:["196","206","216","226"],c:1,f:""},
  {q:"Quel est le processus par lequel les plantes fabriquent leur nourriture ?",a:["Respiration","Fermentation","Photosynthèse","Digestion"],c:2,f:""},
  {q:"Quelle est la température du Soleil en surface (environ) ?",a:["3000°C","5500°C","10000°C","15000°C"],c:1,f:""},
  {q:"Quel est le symbole chimique du potassium ?",a:["Po","Pt","K","Ka"],c:2,f:""},
  {q:"Combien de neurones possède le cerveau humain (environ) ?",a:["1 milliard","86 milliards","500 milliards","1000 milliards"],c:1,f:""},
  {q:"Quel est le gaz le plus abondant dans l'atmosphère terrestre ?",a:["Oxygène","CO2","Azote","Argon"],c:2,f:""},
  {q:"Quelle est la célèbre équation d'Einstein ?",a:["F=ma","E=mc²","PV=nRT","a²+b²=c²"],c:1,f:""},
  {q:"Combien de litres de sang le cœur pompe-t-il par jour environ ?",a:["3000L","5000L","7500L","10000L"],c:2,f:""},
  {q:"Quel est le pH d'une solution neutre ?",a:["0","5","7","14"],c:2,f:""},
  {q:"Quelle est la durée d'une révolution de la Terre autour du Soleil ?",a:["364 jours","365 jours","365,25 jours","366 jours"],c:2,f:""},
  {q:"Quel est le symbole chimique du calcium ?",a:["Ca","Cl","Co","Cu"],c:0,f:""},
  {q:"Combien de paires de chromosomes sexuels y a-t-il chez l'humain ?",a:["1","2","3","4"],c:0,f:""},
  {q:"Quel est le point de congélation de l'eau en degrés Celsius ?",a:["-5°C","0°C","5°C","-10°C"],c:1,f:""},
  {q:"Quelle est la particule portant une charge positive ?",a:["Électron","Neutron","Proton","Positron"],c:2,f:""},
  {q:"Combien de muscles possède le corps humain environ ?",a:["300","400","600","800"],c:2,f:""},
  {q:"Quel est le plus grand organe interne du corps humain ?",a:["Cœur","Rein","Foie","Poumon"],c:2,f:""},
  {q:"Quelle force maintient les planètes en orbite autour du Soleil ?",a:["Force magnétique","Force nucléaire","Gravitation","Force électrique"],c:2,f:""},
  {q:"Quel est le symbole chimique du cuivre ?",a:["Co","Cu","Cp","Cr"],c:1,f:""},
  {q:"Combien de litres de sang contient le corps humain adulte ?",a:["3-4L","5-6L","7-8L","9-10L"],c:1,f:""},
  {q:"Quelle est la durée d'une rotation de la Terre sur elle-même ?",a:["12h","18h","24h","48h"],c:2,f:""},
  {q:"Quel est le nom du processus de division cellulaire ?",a:["Méiose","Mitose","Cytokinèse","Anaphase"],c:1,f:""},
  {q:"Quelle est la formule chimique du méthane ?",a:["CH2","CH3","CH4","C2H4"],c:2,f:""},
  {q:"Combien de dents a un adulte avec les dents de sagesse ?",a:["28","30","32","34"],c:2,f:""},
  {q:"Quel est le symbole chimique du plomb ?",a:["Pb","Pl","Pd","Po"],c:0,f:""},
  {q:"Quelle est la théorie qui explique l'origine de l'Univers ?",a:["Théorie des cordes","Big Bang","Théorie de la relativité","Mécanique quantique"],c:1,f:""},
  {q:"Combien de lobes a le poumon droit humain ?",a:["2","3","4","5"],c:1,f:""},
  {q:"Quel est le pH du sang humain ?",a:["6,8-7,0","7,35-7,45","7,5-7,8","8,0-8,5"],c:1,f:""},
  {q:"Quelle est la particule sans charge électrique ?",a:["Proton","Électron","Neutron","Photon"],c:2,f:""},
  {q:"Combien de millilitres y a-t-il dans un litre ?",a:["10","100","1000","10000"],c:2,f:""},
  {q:"Quel est le symbole chimique du zinc ?",a:["Zi","Zn","Zc","Ze"],c:1,f:""},
  {q:"Quelle est la durée de la grossesse humaine ?",a:["7 mois","8 mois","9 mois","10 mois"],c:2,f:""},
  {q:"Quel est le plus rapide : son ou lumière ?",a:["Son","Lumière","Égaux","Dépend du milieu"],c:1,f:""},
  {q:"Quelle est la formule du théorème de Pythagore ?",a:["a+b=c","a²+b²=c","a²+b²=c²","a×b=c²"],c:2,f:""},
  {q:"Combien de litres d'air expire-t-on par respiration normale ?",a:["0,1L","0,5L","1L","2L"],c:1,f:""},
  {q:"Quel est le symbole chimique du fer ?",a:["Fe","Fr","Fi","Fo"],c:0,f:""},
  {q:"Quelle est la durée de vie d'un globule rouge ?",a:["30 jours","60 jours","90 jours","120 jours"],c:3,f:""},
  {q:"Quel est le processus par lequel l'eau passe de l'état liquide à gazeux ?",a:["Condensation","Évaporation","Sublimation","Fusion"],c:1,f:""},
  {q:"Combien de dents a un requin blanc adulte environ ?",a:["50","150","300","500"],c:2,f:""},
  {q:"Quel est le symbole chimique de l'aluminium ?",a:["Al","Am","An","Ah"],c:0,f:""},
  {q:"Quelle est la vitesse du son dans l'air ?",a:["340 m/s","540 m/s","740 m/s","940 m/s"],c:0,f:""},
  {q:"Combien de mégapixels a l'œil humain environ ?",a:["5 MP","15 MP","576 MP","1000 MP"],c:2,f:""},
  {q:"Quel est le symbole chimique du soufre ?",a:["So","Su","S","Sf"],c:2,f:""},
  {q:"Quelle est la durée de vie d'un neutron libre ?",a:["10 secondes","15 minutes","1 heure","1 jour"],c:1,f:""},
  {q:"Combien de lobes a le cerveau humain ?",a:["2","4","6","8"],c:1,f:""},
  {q:"Quel est le processus de transformation du raisin en vin ?",a:["Distillation","Fermentation","Pasteurisation","Oxydation"],c:1,f:""},
  {q:"Quelle est la formule de l'acide sulfurique ?",a:["HCl","H2SO4","H3PO4","HNO3"],c:1,f:""},
  {q:"Combien de types de papilles gustatives y a-t-il ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Quel est le symbole chimique de l'azote ?",a:["Az","At","N","No"],c:2,f:""},
  {q:"Quelle est la durée d'une année lumière ?",a:["Distance, pas durée","10 mois","1 an","365 jours"],c:0,f:""},
  {q:"Combien de segments a une abeille ouvrière ?",a:["3","4","5","6"],c:0,f:""},
  {q:"Quel est le symbole chimique du magnésium ?",a:["Mn","Mg","Ma","Me"],c:1,f:""},
  {q:"Quelle est la formule de l'hydroxyde de sodium (soude caustique) ?",a:["NaCl","NaOH","Na2O","Na2SO4"],c:1,f:""},
  {q:"Combien de vertèbres cervicales a l'être humain ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Quel est le processus par lequel une chenille devient papillon ?",a:["Métamorphose","Hibernation","Mue","Chrysalide"],c:0,f:""},
  {q:"Quelle est la formule chimique de l'ammoniac ?",a:["NH2","NH3","N2H4","N2H2"],c:1,f:""},
  {q:"Combien de litres de sang le rein filtre-t-il par jour ?",a:["50L","100L","150L","200L"],c:2,f:""},
  {q:"Quel est le symbole chimique du chlore ?",a:["Ch","Cr","Cl","Ce"],c:2,f:""},
  {q:"Quelle est la charge électrique d'un proton ?",a:["-1","+1","0","+2"],c:1,f:""},
  {q:"Combien de paires de nerfs crâniens y a-t-il ?",a:["10","12","14","16"],c:1,f:""},
  {q:"Quel est le processus d'absorption des nutriments dans l'intestin grêle ?",a:["Digestion","Absorption","Filtration","Osmose"],c:1,f:""},
  {q:"Quelle est la formule chimique du glucose ?",a:["C5H10O5","C6H12O6","C6H10O5","C12H22O11"],c:1,f:""},
];
