/* ════════════════════════════════════════
   questions/sport.js — Sport — 100 questions
   ════════════════════════════════════════ */
QUESTIONS.sport = [
  {q:"Combien de joueurs y a-t-il sur le terrain par équipe au football ?",a:["9","10","11","12"],c:2,f:""},
  {q:"Dans quel sport joue-t-on le tournoi de Wimbledon ?",a:["Tennis","Badminton","Squash","Ping-pong"],c:0,f:""},
  {q:"Dans quel sport évolue Michael Jordan ?",a:["Baseball","Basket-ball","Football américain","Hockey"],c:1,f:""},
  {q:"Dans quel sport utilise-t-on un ballon ovale ?",a:["Football","Rugby","Handball","Water-polo"],c:1,f:""},
  {q:"Combien de points vaut un panier à trois points au basket-ball ?",a:["1","2","3","4"],c:2,f:""},
  {q:"Combien de joueurs composent une équipe de basket-ball sur le terrain ?",a:["4","5","6","7"],c:1,f:""},
  {q:"Dans quel sport est célèbre Usain Bolt ?",a:["Natation","Athlétisme","Cyclisme","Football"],c:1,f:""},
  {q:"Combien de trous comporte un parcours classique de golf ?",a:["9","12","18","24"],c:2,f:""},
  {q:"Dans quel sport pratique-t-on le Tour de France ?",a:["Marathon","Cyclisme","Triathlon","Ski"],c:1,f:""},
  {q:"Dans quel sport est célèbre Roger Federer ?",a:["Tennis","Golf","Squash","Badminton"],c:0,f:""},
  {q:"Dans quel sport marque-t-on un 'touchdown' ?",a:["Baseball","Football américain","Rugby","Handball"],c:1,f:""},
  {q:"Dans quel sport est célèbre Lionel Messi ?",a:["Rugby","Football","Tennis","Basket"],c:1,f:""},
  {q:"Quel pays a remporté la FIFA World Cup 2018 ?",a:["Allemagne","Brésil","France","Argentine"],c:2,f:""},
  {q:"Dans quel sport joue-t-on la Coupe Stanley ?",a:["Hockey sur glace","Baseball","Basket","Football américain"],c:0,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de rugby à XV sur le terrain ?",a:["13","14","15","16"],c:2,f:""},
  {q:"Dans quel sport est célèbre Michael Phelps ?",a:["Natation","Water-polo","Plongeon","Triathlon"],c:0,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de handball sur le terrain ?",a:["6","7","8","9"],c:1,f:""},
  {q:"Dans quel sport pratique-t-on un 'home run' ?",a:["Cricket","Baseball","Softball","Hockey"],c:1,f:""},
  {q:"Quelle compétition rassemble les meilleurs athlètes du monde tous les 4 ans ?",a:["Jeux Olympiques","Coupe du Monde","Jeux du Commonwealth","Universiades"],c:0,f:""},
  {q:"Dans quel sport joue-t-on la Ryder Cup ?",a:["Golf","Tennis","Cricket","Polo"],c:0,f:""},
  {q:"Dans quel sport utilise-t-on un tatami ?",a:["Judo","Boxe","Escrime","Lutte"],c:0,f:""},
  {q:"Quelle est la durée d'un match de football (hors prolongations) ?",a:["80 minutes","90 minutes","100 minutes","120 minutes"],c:1,f:""},
  {q:"Dans quel sport utilise-t-on une raquette et un volant ?",a:["Tennis","Badminton","Squash","Ping-pong"],c:1,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de volley-ball sur le terrain ?",a:["5","6","7","8"],c:1,f:""},
  {q:"Dans quel sport joue-t-on la Coupe Davis ?",a:["Golf","Tennis","Cricket","Squash"],c:1,f:""},
  {q:"Quel pays a remporté le plus de médailles d'or aux JO d'été historiquement ?",a:["Chine","Russie","États-Unis","Allemagne"],c:2,f:""},
  {q:"Dans quel sport est célèbre Serena Williams ?",a:["Golf","Tennis","Natation","Athlétisme"],c:1,f:""},
  {q:"Combien de sets faut-il gagner pour remporter un match de tennis en Grand Chelem (hommes) ?",a:["2","3","4","5"],c:1,f:""},
  {q:"Dans quel sport est célèbre Cristiano Ronaldo ?",a:["Rugby","Tennis","Football","Natation"],c:2,f:""},
  {q:"Quel pays a inventé le baseball ?",a:["Canada","Royaume-Uni","États-Unis","Cuba"],c:2,f:""},
  {q:"Dans quel sport est célèbre LeBron James ?",a:["Football américain","Baseball","Basket-ball","Hockey"],c:2,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de water-polo sur le terrain ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Dans quel sport est célèbre Novak Djokovic ?",a:["Tennis","Squash","Badminton","Padel"],c:0,f:""},
  {q:"Quel pays a remporté la FIFA World Cup 2022 ?",a:["France","Brésil","Argentine","Croatie"],c:2,f:""},
  {q:"Dans quel sport est célèbre Tiger Woods ?",a:["Golf","Tennis","Baseball","Polo"],c:0,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de hockey sur glace sur la glace ?",a:["4","5","6","7"],c:2,f:""},
  {q:"Dans quel sport est célèbre Rafael Nadal ?",a:["Tennis","Golf","Squash","Badminton"],c:0,f:""},
  {q:"Quel est le record du monde du 100m masculin ?",a:["9.58s","9.69s","9.72s","9.81s"],c:0,f:""},
  {q:"Dans quel sport est célèbre Zinédine Zidane ?",a:["Rugby","Football","Tennis","Cyclisme"],c:1,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de baseball sur le terrain ?",a:["7","8","9","10"],c:2,f:""},
  {q:"Dans quel sport est célèbre Muhammad Ali ?",a:["Lutte","Judo","Boxe","MMA"],c:2,f:""},
  {q:"Quelle ville a accueilli les JO d'été de 2024 ?",a:["Los Angeles","Tokyo","Paris","Londres"],c:2,f:""},
  {q:"Dans quel sport est célèbre Kylian Mbappé ?",a:["Rugby","Tennis","Football","Athlétisme"],c:2,f:""},
  {q:"Combien de points vaut un essai au rugby à XV ?",a:["3","4","5","6"],c:2,f:""},
  {q:"Dans quel sport est célèbre Simone Biles ?",a:["Natation","Athlétisme","Gymnastics","Patinage"],c:2,f:""},
  {q:"Quel pays a remporté la Coupe du Monde de Rugby 2023 ?",a:["Afrique du Sud","Nouvelle-Zélande","France","Angleterre"],c:0,f:""},
  {q:"Dans quel sport est célèbre Lance Armstrong ?",a:["Triathlon","Cyclisme","Natation","Athlétisme"],c:1,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de cricket sur le terrain ?",a:["9","10","11","12"],c:2,f:""},
  {q:"Dans quel sport est célèbre Pelé ?",a:["Rugby","Tennis","Football","Volleyball"],c:2,f:""},
  {q:"Quel club a remporté le plus de Ligues des Champions ?",a:["FC Barcelone","Bayern Munich","Real Madrid","AC Milan"],c:2,f:""},
  {q:"Dans quel sport est célèbre Neymar ?",a:["Rugby","Football","Tennis","Natation"],c:1,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de football américain sur le terrain ?",a:["9","10","11","12"],c:2,f:""},
  {q:"Dans quel sport est célèbre Carl Lewis ?",a:["Natation","Cyclisme","Athlétisme","Haltérophilie"],c:2,f:""},
  {q:"Quel pays a remporté le plus de Coupes du Monde de football ?",a:["Allemagne","Argentine","Brésil","France"],c:2,f:""},
  {q:"Dans quel sport est célèbre Ronnie O'Sullivan ?",a:["Billard","Snooker","Pool","Carambole"],c:1,f:""},
  {q:"Combien de points vaut une transformation au rugby ?",a:["1","2","3","4"],c:1,f:""},
  {q:"Dans quel sport est célèbre Valentino Rossi ?",a:["Formule 1","MotoGP","Rallye","Superbike"],c:1,f:""},
  {q:"Quel club de football a pour surnom 'Les Blaugrana' ?",a:["Real Madrid","Juventus","FC Barcelone","PSG"],c:2,f:""},
  {q:"Dans quel sport est célèbre Floyd Mayweather ?",a:["MMA","Boxe","Kickboxing","Muay Thai"],c:1,f:""},
  {q:"Combien de sets faut-il gagner en tennis pour remporter un match en 5 sets ?",a:["2","3","4","5"],c:1,f:""},
  {q:"Dans quel sport est célèbre Didier Drogba ?",a:["Rugby","Football","Tennis","Natation"],c:1,f:""},
  {q:"Quel pays a remporté la Copa América le plus souvent ?",a:["Brésil","Argentine","Uruguay","Chili"],c:1,f:""},
  {q:"Dans quel sport est célèbre Conor McGregor ?",a:["Boxe","Kickboxing","MMA","Judo"],c:2,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de polo sur le terrain par équipe ?",a:["2","3","4","5"],c:2,f:""},
  {q:"Dans quel sport est célèbre Ayrton Senna ?",a:["MotoGP","Formule 1","Rallye","NASCAR"],c:1,f:""},
  {q:"Quel club a remporté le plus de titres en Premier League anglaise ?",a:["Arsenal","Chelsea","Manchester United","Liverpool"],c:2,f:""},
  {q:"Dans quel sport est célèbre Wilt Chamberlain ?",a:["Football américain","Baseball","Basket-ball","Hockey"],c:2,f:""},
  {q:"Combien de joueurs y a-t-il dans une équipe de rugby à 7 sur le terrain ?",a:["5","6","7","8"],c:2,f:""},
  {q:"Dans quel sport est célèbre Diego Maradona ?",a:["Rugby","Football","Tennis","Boxe"],c:1,f:""},
  {q:"Quel pays a accueilli la première Coupe du Monde de football en 1930 ?",a:["Brésil","Argentine","Uruguay","Chili"],c:2,f:""},
  {q:"Dans quel sport est célèbre Kareem Abdul-Jabbar ?",a:["Baseball","Basket-ball","Football américain","Hockey"],c:1,f:""},
  {q:"Combien de points marque-t-on en frappant la balle de golf dans le trou en un seul coup sous le par ?",a:["Eagle","Birdie","Albatross","Hole-in-one"],c:3,f:""},
  {q:"Dans quel sport est célèbre Ronaldinho ?",a:["Rugby","Football","Tennis","Volley"],c:1,f:""},
  {q:"Quel club de football espagnol est surnommé 'La Casa Blanca' ?",a:["FC Barcelone","Atletico Madrid","Real Madrid","Valencia"],c:2,f:""},
  {q:"Dans quel sport est célèbre Steph Curry ?",a:["Baseball","Basket-ball","Football américain","Hockey"],c:1,f:""},
  {q:"Combien de jours dure le Tour de France en général ?",a:["14","17","21","23"],c:2,f:""},
  {q:"Dans quel sport est célèbre Teddy Riner ?",a:["Lutte","Judo","Sambo","Sumo"],c:1,f:""},
  {q:"Quel pays a accueilli les JO d'été de 2016 ?",a:["Argentine","Chili","Brésil","Mexique"],c:2,f:""},
  {q:"Dans quel sport est célèbre Renaud Lavillenie ?",a:["Lancer du javelot","Saut à la perche","Triple saut","Saut en hauteur"],c:1,f:""},
  {q:"Combien de points vaut une pénalité au rugby à XV ?",a:["1","2","3","4"],c:2,f:""},
  {q:"Dans quel sport est célèbre Kevin Durant ?",a:["Football américain","Basket-ball","Baseball","Hockey"],c:1,f:""},
  {q:"Quel pays a remporté la Coupe du Monde de Rugby le plus souvent ?",a:["Angleterre","Australie","Nouvelle-Zélande","Afrique du Sud"],c:2,f:""},
  {q:"Dans quel sport est célèbre Pierre de Coubertin ?",a:["Escrime","Tennis","Athlétisme","Il a créé les JO modernes"],c:3,f:""},
  {q:"Combien de km fait un marathon ?",a:["40 km","41,195 km","42,195 km","43 km"],c:2,f:""},
  {q:"Dans quel sport est célèbre Thierry Henry ?",a:["Rugby","Football","Tennis","Cyclisme"],c:1,f:""},
  {q:"Quel pays a remporté le plus de médailles aux JO d'hiver ?",a:["Canada","Russie","Norvège","Allemagne"],c:2,f:""},
  {q:"Dans quel sport est célèbre Jean-Pierre Papin ?",a:["Rugby","Football","Tennis","Natation"],c:1,f:""},
];
